Repository helidon-io/helidon, pull requests merged in 2019-04, with the labels that each got.

#563 Finish write-content span before completing delegate
  webserver/webserver/src/main/java/io/helidon/webserver/SendHeadersFirstPublisher.java
Labels: enhancement

#555 Changes required to FT implementation to support new features and TCKs
  microprofile/fault-tolerance/src/main/java/io/helidon/microprofile/faulttolerance/AsynchronousAntn.java
  microprofile/fault-tolerance/src/main/java/io/helidon/microprofile/faulttolerance/CommandFallback.java
  microprofile/fault-tolerance/src/main/java/io/helidon/microprofile/faulttolerance/CommandInterceptor.java
  microprofile/fault-tolerance/src/main/java/io/helidon/microprofile/faulttolerance/CommandRetrier.java
  microprofile/fault-tolerance/src/main/java/io/helidon/microprofile/faulttolerance/CommandScheduler.java
  microprofile/fault-tolerance/src/main/java/io/helidon/microprofile/faulttolerance/FailsafeChainedFuture.java
  microprofile/fault-tolerance/src/main/java/io/helidon/microprofile/faulttolerance/FallbackAntn.java
  microprofile/fault-tolerance/src/main/java/io/helidon/microprofile/faulttolerance/FaultToleranceCommand.java
  microprofile/fault-tolerance/src/main/java/io/helidon/microprofile/faulttolerance/FaultToleranceExtension.java
  microprofile/fault-tolerance/src/main/java/io/helidon/microprofile/faulttolerance/JavaMethodFinder.java
  microprofile/fault-tolerance/src/main/java/io/helidon/microprofile/faulttolerance/MethodIntrospector.java
  microprofile/fault-tolerance/src/test/java/io/helidon/microprofile/faulttolerance/AsynchronousBean.java
  microprofile/fault-tolerance/src/test/java/io/helidon/microprofile/faulttolerance/AsynchronousCallerBean.java
  microprofile/fault-tolerance/src/test/java/io/helidon/microprofile/faulttolerance/AsynchronousTest.java
  microprofile/fault-tolerance/src/test/java/io/helidon/microprofile/faulttolerance/BaseFallbackBean.java
  microprofile/fault-tolerance/src/test/java/io/helidon/microprofile/faulttolerance/BulkheadBean.java
  microprofile/fault-tolerance/src/test/java/io/helidon/microprofile/faulttolerance/BulkheadTest.java
  microprofile/fault-tolerance/src/test/java/io/helidon/microprofile/faulttolerance/CircuitBreakerBean.java
  microprofile/fault-tolerance/src/test/java/io/helidon/microprofile/faulttolerance/CircuitBreakerTest.java
  microprofile/fault-tolerance/src/test/java/io/helidon/microprofile/faulttolerance/FallbackBean.java
  microprofile/fault-tolerance/src/test/java/io/helidon/microprofile/faulttolerance/FallbackTest.java
  microprofile/fault-tolerance/src/test/java/io/helidon/microprofile/faulttolerance/UnitTestException.java
  microprofile/tests/tck/tck-fault-tolerance/src/test/tck-suite.xml
  pom.xml
Labels: enhancement, fault-tolerance

#576 Removed unnecessary synchronization
  media/common/src/main/java/io/helidon/media/common/ContentReaders.java
Labels: enhancement

#608 Fix 606 Webserver documentation does not describe services
  docs/src/main/docs/webserver/03_routing.adoc
  docs/src/main/docs/webserver/05_error-handling.adoc
Labels: docs

#589 Tracing propagation
  docs/src/main/docs/microprofile/07_tracing.adoc
  docs/src/main/docs/tracing/01_tracing.adoc
  docs/src/main/docs/tracing/02_zipkin.adoc
  docs/src/main/docs/tracing/03_jaeger.adoc
  tracing/jaeger/src/main/java/io/helidon/tracing/jaeger/JaegerTracerBuilder.java
Labels: docs, tracing

#609 JSON handling improvements
  media/common/src/main/java/io/helidon/media/common/CharBuffer.java
  media/common/src/main/java/io/helidon/media/common/ContentTypeCharset.java
  media/common/src/main/java/io/helidon/media/common/ContentWriters.java
  media/jackson/common/src/main/java/io/helidon/media/jackson/common/JacksonProcessing.java
  media/jackson/server/pom.xml
  media/jackson/server/src/main/java/io/helidon/media/jackson/server/JacksonSupport.java
  media/jackson/server/src/main/java9/module-info.java
  media/jsonb/common/src/main/java/io/helidon/media/jsonb/common/JsonBinding.java
  media/jsonb/server/src/main/java/io/helidon/media/jsonb/server/JsonBindingSupport.java
  media/jsonp/common/src/main/java/io/helidon/media/jsonp/common/JsonProcessing.java
  media/jsonp/server/src/main/java/io/helidon/media/jsonp/server/JsonSupport.java
Labels: SE

#615 Fixed typo.
  common/configurable/src/main/java/io/helidon/common/configurable/ResourceUtil.java
Labels: SE

#629 Quickstarts: use mavenCentral() in build.gradle instead of url
  examples/quickstarts/helidon-quickstart-mp/build.gradle
  examples/quickstarts/helidon-quickstart-se/build.gradle
Labels: P3
