Repository helidon-io/helidon, pull requests merged in 2019-08, with the labels that each got.

#874 Change Netty workers default to equal available processors.
  docs/src/main/docs/microprofile/02_server-configuration.adoc
  webserver/webserver/src/main/java/io/helidon/webserver/ServerConfiguration.java
Labels: SE

#883 Allow different servers within an app to report different OpenAPI doc…
  openapi/pom.xml
  openapi/src/main/java/io/helidon/openapi/OpenAPISupport.java
  openapi/src/main/java9/module-info.java
  openapi/src/test/java/io/helidon/openapi/ServerTest.java
  openapi/src/test/resources/openapi-greeting.yml
  openapi/src/test/resources/openapi-time-server.yml
  pom.xml
Labels: P1, SE, open-api

#889 Added unit test for UCP integration
  integrations/cdi/datasource-ucp/pom.xml
  integrations/cdi/datasource-ucp/src/test/java/io/helidon/integrations/datasource/ucp/cdi/TestDataSourceAcquisition.java
  integrations/cdi/datasource-ucp/src/test/logging.properties
  integrations/cdi/datasource-ucp/src/test/resources/application.yaml
Labels: MP, P3, task

#895 Added H2-based example for the Hikari connection pool
  examples/integrations/cdi/datasource-hikaricp-h2/README.adoc
  examples/integrations/cdi/datasource-hikaricp-h2/pom.xml
  examples/integrations/cdi/datasource-hikaricp-h2/src/main/java/io/helidon/integrations/examples/datasource/hikaricp/jaxrs/TablesResource.java
  examples/integrations/cdi/datasource-hikaricp-h2/src/main/java/io/helidon/integrations/examples/datasource/hikaricp/jaxrs/package-info.java
  examples/integrations/cdi/datasource-hikaricp-h2/src/main/resources/META-INF/beans.xml
  examples/integrations/cdi/datasource-hikaricp-h2/src/main/resources/META-INF/microprofile-config.properties
  examples/integrations/cdi/datasource-hikaricp-h2/src/main/spotbugs/exclusions.xml
  examples/integrations/cdi/pom.xml
Labels: MP, P5, enhancement, samples

#892 Documentation of admin port configuration in Helidon MP.
  docs/src/main/docs/microprofile/02_server-configuration.adoc
Labels: MP

#901 Zipkin integration no longer fails in MP due to class cast exception.
  tests/integration/pom.xml
  tests/integration/zipkin-mp-2.2/pom.xml
  tests/integration/zipkin-mp-2.2/src/main/java/io/helidon/tests/integration/zipkin/mp22/MpApplication.java
  tests/integration/zipkin-mp-2.2/src/main/java/io/helidon/tests/integration/zipkin/mp22/MpResource.java
  tests/integration/zipkin-mp-2.2/src/main/java/io/helidon/tests/integration/zipkin/mp22/MpResourceImpl.java
  tests/integration/zipkin-mp-2.2/src/main/java/io/helidon/tests/integration/zipkin/mp22/ZipkinMp22Main.java
  tests/integration/zipkin-mp-2.2/src/main/resources/META-INF/beans.xml
  tests/integration/zipkin-mp-2.2/src/main/resources/application.yaml
  tests/integration/zipkin-mp-2.2/src/test/java/io/helidon/tests/integration/zipkin/mp22/ZipkinMp22Test.java
  tests/pom.xml
  tracing/zipkin/src/main/java/io/helidon/tracing/zipkin/ZipkinScopeManager.java
  tracing/zipkin/src/main/java/io/helidon/tracing/zipkin/ZipkinSpan.java
  tracing/zipkin/src/main/java/io/helidon/tracing/zipkin/ZipkinTracer.java
Labels: bug

#886 Audit now logs message even if mismatch of parameter count.
  security/security/src/main/java/io/helidon/security/AuditEvent.java
  security/security/src/main/java/io/helidon/security/AuthorizationClientImpl.java
  security/security/src/main/java/io/helidon/security/DefaultAuditProvider.java
  security/security/src/test/java/io/helidon/security/AuditEventTest.java
  security/security/src/test/java/io/helidon/security/DefaultAuditProviderTest.java
Labels: security

#908 Promoting JPA integration to supported status
  examples/integrations/cdi/jpa/pom.xml
  integrations/cdi/jpa-cdi/src/main/java/io/helidon/integrations/cdi/jpa/JpaExtension.java
  integrations/cdi/jpa-cdi/src/main/resources/io/helidon/integrations/cdi/jpa/Messages.properties
  integrations/cdi/jpa-weld/README.adoc
  integrations/cdi/jpa-weld/pom.xml
  integrations/cdi/jpa-weld/src/main/java/io/helidon/integrations/cdi/jpa/weld/TransactionObserver.java
  integrations/cdi/jpa-weld/src/main/java/io/helidon/integrations/cdi/jpa/weld/WeldJpaInjectionServices.java
  integrations/cdi/jpa-weld/src/main/java/io/helidon/integrations/cdi/jpa/weld/WeldJpaInjectionServicesExtension.java
  integrations/cdi/jpa-weld/src/main/resources/META-INF/beans.xml
  integrations/cdi/jpa-weld/src/main/resources/META-INF/services/javax.enterprise.inject.spi.Extension
  integrations/cdi/jpa-weld/src/main/resources/META-INF/services/org.jboss.weld.bootstrap.api.Service
  integrations/cdi/jpa-weld/src/main/resources/io/helidon/integrations/cdi/jpa/weld/Messages.properties
  integrations/cdi/jpa-weld/src/test/java/io/helidon/integrations/cdi/jpa/weld/TestDeprecation.java
  integrations/cdi/jpa-weld/src/test/java/io/helidon/integrations/cdi/jpa/weld/TestIntegration.java
  integrations/cdi/pom.xml
Labels: MP, P1

#898 Added JTA guide.
  docs/src/main/docs/guides/08_jta.adoc
Labels: MP, P3, docs

#871 Thread pool growth
  common/configurable/pom.xml
  common/configurable/src/main/java/io/helidon/common/configurable/ServerThreadPoolSupplier.java
  common/configurable/src/main/java/io/helidon/common/configurable/ThreadPool.java
  common/configurable/src/main/java/io/helidon/common/configurable/ThreadPoolSupplier.java
  common/configurable/src/main/java9/module-info.java
  common/configurable/src/test/java/io/helidon/common/configurable/ServerThreadPoolSupplierTest.java
  common/configurable/src/test/java/io/helidon/common/configurable/ThreadPoolSupplierTest.java
  common/configurable/src/test/java/io/helidon/common/configurable/ThreadPoolTest.java
  grpc/client/pom.xml
  microprofile/server/src/main/java/io/helidon/microprofile/server/Server.java
  pom.xml
  webserver/test-support/src/test/java/io/helidon/webserver/testsupport/TestClientTest.java
  webserver/webserver/src/main/java/io/helidon/webserver/RequestRouting.java
Labels: MP

#917 Corrects erroneous assert statement in JedisExtension
  integrations/cdi/jedis-cdi/src/main/java/io/helidon/integrations/jedis/cdi/JedisExtension.java
Labels: MP, P1, bug

#914 Adds support for unitName-less PersistenceContext injection points
  integrations/cdi/jpa-cdi/src/main/java/io/helidon/integrations/cdi/jpa/JpaExtension.java
  integrations/cdi/jpa-weld/src/test/java/io/helidon/integrations/cdi/jpa/weld/TestIntegration.java
Labels: MP, P3, enhancement

#934 Update graal docker images
  etc/dockerfiles/Dockerfile.jdk8-graalvm
  etc/dockerfiles/Dockerfile.jdk8-graalvm-maven
  etc/dockerfiles/build.sh
  examples/quickstarts/helidon-quickstart-se/Dockerfile.native
  pom.xml
Labels: graal

#951 Eliminates the last codepath for JNDI to surface in CDISEPlatform.java.
  integrations/cdi/eclipselink-cdi/pom.xml
  integrations/cdi/eclipselink-cdi/src/main/java/io/helidon/integrations/cdi/eclipselink/CDISEPlatform.java
  integrations/cdi/eclipselink-cdi/src/test/java/io/helidon/integrations/cdi/eclipselink/TestManualEntityManagerAcquisition.java
  integrations/cdi/eclipselink-cdi/src/test/resources/META-INF/persistence.xml
Labels: MP, P5, bug

#943 Propagate security automatically
  bom/pom.xml
  examples/grpc/security-outbound/pom.xml
  examples/grpc/security-outbound/src/main/java/io/helidon/grpc/examples/security/outbound/SecureServer.java
  examples/security/jersey/pom.xml
  examples/security/jersey/src/main/java/io/helidon/security/examples/jersey/JerseyResources.java
  examples/security/outbound-override/pom.xml
  examples/security/outbound-override/src/main/java/io/helidon/security/examples/outbound/OutboundOverrideExample.java
  examples/security/outbound-override/src/main/java/io/helidon/security/examples/outbound/OutboundOverrideJwtExample.java
  examples/security/outbound-override/src/main/java/io/helidon/security/examples/outbound/OutboundOverrideUtil.java
  examples/security/outbound-override/src/main/resources/client-service-jwt.yaml
  examples/security/webserver-signatures/pom.xml
  examples/security/webserver-signatures/src/main/java/io/helidon/security/examples/signatures/SignatureExampleUtil.java
  examples/todo-app/demo-backend/cassandra/README.md
  examples/todo-app/demo-frontend/pom.xml
  examples/todo-app/demo-frontend/src/main/java/io/helidon/demo/todos/frontend/BackendServiceClient.java
  examples/todo-app/demo-frontend/src/main/java/io/helidon/demo/todos/frontend/EnvHandler.java
  examples/todo-app/demo-frontend/src/main/java/io/helidon/demo/todos/frontend/Main.java
  examples/todo-app/demo-frontend/src/main/java/io/helidon/demo/todos/frontend/TodosHandler.java
  microprofile/bundles/helidon-microprofile-1.2/pom.xml
  security/integration/grpc/pom.xml
  security/integration/grpc/src/test/java/services/SecuredOutboundEchoService.java
  security/integration/jersey-client/pom.xml
  security/integration/jersey-client/src/main/java/io/helidon/security/integration/jersey/client/ClientSecurity.java
  security/integration/jersey-client/src/main/java/io/helidon/security/integration/jersey/client/ClientSecurityAutoDiscoverable.java
  security/integration/jersey-client/src/main/java/io/helidon/security/integration/jersey/client/ClientSecurityFilter.java
  security/integration/jersey-client/src/main/java/io/helidon/security/integration/jersey/client/package-info.java
  security/integration/jersey-client/src/main/java9/module-info.java
  security/integration/jersey-client/src/main/resources/META-INF/services/org.glassfish.jersey.internal.spi.AutoDiscoverable
  security/integration/jersey-client/src/test/java/io/helidon/security/integration/jersey/client/ClientSecurityAutoDiscoverableTest.java
  security/integration/jersey/src/main/java/io/helidon/security/integration/jersey/ClientSecurityFeature.java
  security/integration/jersey/src/main/java/io/helidon/security/integration/jersey/ClientSecurityFilter.java
  security/integration/jersey/src/main/java/io/helidon/security/integration/jersey/SecureClient.java
  security/integration/pom.xml
  security/providers/http-auth/pom.xml
  security/providers/http-auth/src/test/java/io/helidon/security/providers/httpauth/BasicAuthOutboundOverrideTest.java
  tests/integration/mp-security-client/pom.xml
  tests/integration/mp-security-client/src/main/java/io/helidon/tests/integration/mp/security/client/ClientResource.java
  tests/integration/mp-security-client/src/main/java/io/helidon/tests/integration/mp/security/client/MpSecurityClientMain.java
  tests/integration/mp-security-client/src/main/java/io/helidon/tests/integration/mp/security/client/ServerResource.java
  tests/integration/mp-security-client/src/main/java/io/helidon/tests/integration/mp/security/client/TestApplication.java
  tests/integration/mp-security-client/src/main/resources/META-INF/beans.xml
  tests/integration/mp-security-client/src/main/resources/application.yaml
  tests/integration/mp-security-client/src/test/java/io/helidon/tests/integration/mp/security/client/MpSecurityClientTest.java
  tests/integration/pom.xml
Labels: security

#973 Fix unitTest=no for the new archetypes
  archetypes/mp/src/main/resources/META-INF/archetype-post-generate.groovy
  archetypes/mp/src/test/resources/projects/it4/archetype.properties
  archetypes/mp/src/test/resources/projects/it4/goal.txt
  archetypes/se/src/main/resources/META-INF/archetype-post-generate.groovy
  archetypes/se/src/test/resources/projects/it4/archetype.properties
  archetypes/se/src/test/resources/projects/it4/goal.txt
Labels: samples

#925 SE and MP Health Guides
  docs/src/main/docs/guides/01_overview.adoc
  docs/src/main/docs/guides/07_health_mp_guide.adoc
  docs/src/main/docs/guides/07_health_se_guide.adoc
Labels: docs

#941 MP now returns the original instance of Helidon config.
  config/config/src/main/java/io/helidon/config/internal/UrlConfigSource.java
  examples/microprofile/mp1_1-static-content/src/test/java/io/helidon/microprofile/example/staticc/StaticContentTest.java
  microprofile/config/config/src/main/java/io/helidon/microprofile/config/MpConfig.java
  microprofile/config/config/src/main/java/io/helidon/microprofile/config/MpConfigBuilder.java
Labels: MP, config

#979 Preemptively fixes a couple of default persistence unit edge cases
  integrations/cdi/jpa-cdi/src/main/java/io/helidon/integrations/cdi/jpa/JpaExtension.java
  integrations/cdi/jpa-cdi/src/main/java/io/helidon/integrations/cdi/jpa/PersistenceUnitInfoBean.java
Labels: MP, P2

#980 Cleaned up bom/pom.xml to repair incorrect entries and add missing ones
  bom/pom.xml
Labels: P1, bug, build
