Repository helidon-io/helidon, pull requests merged in 2019-06, with the labels that each got.

#755 Completed support for async bulkheads
  microprofile/fault-tolerance/src/main/java/io/helidon/microprofile/faulttolerance/BulkheadHelper.java
  microprofile/fault-tolerance/src/main/java/io/helidon/microprofile/faulttolerance/CommandRetrier.java
  microprofile/fault-tolerance/src/main/java/io/helidon/microprofile/faulttolerance/CommandScheduler.java
  microprofile/fault-tolerance/src/main/java/io/helidon/microprofile/faulttolerance/FaultToleranceCommand.java
  microprofile/fault-tolerance/src/main/java/io/helidon/microprofile/faulttolerance/FaultToleranceMpService.java
  microprofile/fault-tolerance/src/test/java/io/helidon/microprofile/faulttolerance/BulkheadTest.java
  microprofile/fault-tolerance/src/test/java/io/helidon/microprofile/faulttolerance/SchedulerConfigTest.java
  microprofile/fault-tolerance/src/test/resources/application.yaml
  microprofile/tests/tck/tck-fault-tolerance/pom.xml
Labels: fault-tolerance

#766 Expand openapi mediatypes
  common/http/src/main/java/io/helidon/common/http/MediaType.java
  openapi/src/main/java/io/helidon/openapi/OpenAPISupport.java
Labels: MP, P3, SE, enhancement, open-api

#765 Create Helidon MP 2.2 bundle
  bom/pom.xml
  examples/microprofile/openapi-basic/pom.xml
  microprofile/bundles/helidon-microprofile-2.2/pom.xml
  microprofile/bundles/helidon-microprofile-2.2/src/main/java9/module-info.java
  microprofile/bundles/pom.xml
Labels: MP, P3, enhancement

#774 Fixes #770
  integrations/cdi/jpa-cdi/src/main/java/io/helidon/integrations/cdi/jpa/JpaExtension.java
  microprofile/server/src/main/java/io/helidon/microprofile/server/Main.java
Labels: MP, P1, bug

#758 Fixes support for application calls to flush() when using StreamingOutput
  common/reactive/src/main/java/io/helidon/common/reactive/OutputStreamPublisher.java
  webserver/jersey/src/main/java/io/helidon/webserver/jersey/ResponseWriter.java
  webserver/jersey/src/test/java/io/helidon/webserver/jersey/JerseyExampleResource.java
  webserver/jersey/src/test/java/io/helidon/webserver/jersey/JerseySupportTest.java
Labels: bug

#783 Changes to content length optimization to handle flushes
  common/http/src/main/java/io/helidon/common/http/DataChunk.java
  tests/apps/bookstore/bookstore-mp/src/test/java/io/helidon/tests/apps/bookstore/mp/BookResourceTest.java
  webserver/jersey/src/main/java/io/helidon/webserver/jersey/ResponseWriter.java
  webserver/webserver/src/main/java/io/helidon/webserver/BareResponseImpl.java
Labels: enhancement

#792 Remove unnecessary slf4j dependency
  microprofile/fault-tolerance/pom.xml
Labels: enhancement

#795 Content length enhancement review
  webserver/webserver/src/main/java/io/helidon/webserver/BareResponseImpl.java
Labels: webserver

#796 Return a 400 response for a request with an invalid URL
  webserver/webserver/src/main/java/io/helidon/webserver/BareRequestImpl.java
  webserver/webserver/src/main/java/io/helidon/webserver/ForwardingHandler.java
  webserver/webserver/src/test/java/io/helidon/webserver/PlainTest.java
Labels: webserver

#816 Pass maxContentLength to constructor of HttpServerUpgradeHandler
  tests/apps/bookstore/bookstore-se/src/test/java/io/helidon/tests/apps/bookstore/se/Http2SslTest.java
  webserver/webserver/src/main/java/io/helidon/webserver/HttpInitializer.java
Labels: webserver

#818 Allow posting incomplete books without resulting in an NPE
  tests/apps/bookstore/bookstore-se/src/main/java/io/helidon/tests/apps/bookstore/se/AuthorMapper.java
  tests/apps/bookstore/bookstore-se/src/main/java/io/helidon/tests/apps/bookstore/se/BookMapper.java
  webserver/access-log/src/main/java/io/helidon/webserver/accesslog/AccessLogHandler.java
Labels: enhancement
