Repository helidon-io/helidon, pull requests merged in 2019-07, with the labels that each got.

#823 Enable Netty autoread only after completing a response
  webserver/webserver/src/main/java/io/helidon/webserver/ForwardingHandler.java
Labels: bug

#842 Adds a META-INF/services/javax.enterprise.inject.spi.Extension resource to datasource-ucp
  integrations/cdi/datasource-ucp/src/main/resources/META-INF/services/javax.enterprise.inject.spi.Extension
Labels: P1, bug

#845 Corrects traversal logic for MpConfig when acquiring configuration property names
  microprofile/config/config/src/main/java/io/helidon/microprofile/config/MpConfig.java
Labels: MP, bug

#847 Enables support of application.yaml use case in data source injection extensions
  integrations/cdi/datasource-hikaricp/pom.xml
  integrations/cdi/datasource-hikaricp/src/test/java/io/helidon/integrations/datasource/hikaricp/cdi/TestConfiguration.java
  integrations/cdi/datasource-hikaricp/src/test/logging.properties
  integrations/cdi/datasource-hikaricp/src/test/resources/application.yaml
  integrations/cdi/datasource-ucp/src/main/java/io/helidon/integrations/datasource/ucp/cdi/UCPBackedDataSourceExtension.java
  integrations/cdi/datasource/src/main/java/io/helidon/integrations/datasource/cdi/AbstractDataSourceExtension.java
Labels: MP, P1, bug

#857 Moved --frames option into a profile for JDK 10+
  pom.xml
Labels: P5, bug, docs

#812 Addresses #639
  bom/pom.xml
  etc/copyright-exclude.txt
  integrations/cdi/common-cdi/delegates/pom.xml
  integrations/cdi/common-cdi/delegates/src/main/java/io/helidon/integrations/cdi/delegates/DelegatingInjectionTarget.java
  integrations/cdi/common-cdi/delegates/src/main/java/io/helidon/integrations/cdi/delegates/DelegatingProducer.java
  integrations/cdi/common-cdi/delegates/src/main/java/io/helidon/integrations/cdi/delegates/package-info.java
  integrations/cdi/common-cdi/pom.xml
  integrations/cdi/common-cdi/reference-counted-context/pom.xml
  integrations/cdi/common-cdi/reference-counted-context/src/main/java/io/helidon/integrations/cdi/referencecountedcontext/ReferenceCounted.java
  integrations/cdi/common-cdi/reference-counted-context/src/main/java/io/helidon/integrations/cdi/referencecountedcontext/ReferenceCountedContext.java
  integrations/cdi/common-cdi/reference-counted-context/src/main/java/io/helidon/integrations/cdi/referencecountedcontext/ReferenceCountedExtension.java
  integrations/cdi/common-cdi/reference-counted-context/src/main/java/io/helidon/integrations/cdi/referencecountedcontext/package-info.java
  integrations/cdi/common-cdi/reference-counted-context/src/main/resources/META-INF/services/javax.enterprise.inject.spi.Extension
  integrations/cdi/common-cdi/reference-counted-context/src/test/java/io/helidon/integrations/cdi/referencecountedcontext/TestReferenceCountedContext.java
  integrations/cdi/jpa-cdi/pom.xml
  integrations/cdi/jpa-cdi/src/main/java/io/helidon/integrations/cdi/jpa/BeanManagerBackedDataSourceProvider.java
  integrations/cdi/jpa-cdi/src/main/java/io/helidon/integrations/cdi/jpa/CdiTransactionScoped.java
  integrations/cdi/jpa-cdi/src/main/java/io/helidon/integrations/cdi/jpa/CdiTransactionScopedEntityManager.java
  integrations/cdi/jpa-cdi/src/main/java/io/helidon/integrations/cdi/jpa/ContainerManaged.java
  integrations/cdi/jpa-cdi/src/main/java/io/helidon/integrations/cdi/jpa/DelegatingEntityManager.java
  integrations/cdi/jpa-cdi/src/main/java/io/helidon/integrations/cdi/jpa/EntityManagerFactories.java
  integrations/cdi/jpa-cdi/src/main/java/io/helidon/integrations/cdi/jpa/EntityManagers.java
  integrations/cdi/jpa-cdi/src/main/java/io/helidon/integrations/cdi/jpa/Extended.java
  integrations/cdi/jpa-cdi/src/main/java/io/helidon/integrations/cdi/jpa/ExtendedEntityManager.java
  integrations/cdi/jpa-cdi/src/main/java/io/helidon/integrations/cdi/jpa/JpaCdiQualifiers.java
  integrations/cdi/jpa-cdi/src/main/java/io/helidon/integrations/cdi/jpa/JpaExtension.java
  integrations/cdi/jpa-cdi/src/main/java/io/helidon/integrations/cdi/jpa/JpaTransactionScoped.java
  integrations/cdi/jpa-cdi/src/main/java/io/helidon/integrations/cdi/jpa/JpaTransactionScopedEntityManager.java
  integrations/cdi/jpa-cdi/src/main/java/io/helidon/integrations/cdi/jpa/JtaTransactionSupport.java
  integrations/cdi/jpa-cdi/src/main/java/io/helidon/integrations/cdi/jpa/Messages.java
  integrations/cdi/jpa-cdi/src/main/java/io/helidon/integrations/cdi/jpa/NoTransactionSupport.java
  integrations/cdi/jpa-cdi/src/main/java/io/helidon/integrations/cdi/jpa/NonTransactional.java
  integrations/cdi/jpa-cdi/src/main/java/io/helidon/integrations/cdi/jpa/NonTransactionalEntityManager.java
  integrations/cdi/jpa-cdi/src/main/java/io/helidon/integrations/cdi/jpa/Synchronized.java
  integrations/cdi/jpa-cdi/src/main/java/io/helidon/integrations/cdi/jpa/TransactionSupport.java
  integrations/cdi/jpa-cdi/src/main/java/io/helidon/integrations/cdi/jpa/Unsynchronized.java
  integrations/cdi/jpa-cdi/src/main/javadoc/io/helidon/integrations/cdi/jpa/jaxb/package.html
  integrations/cdi/jpa-cdi/src/main/resources/META-INF/beans.xml
  integrations/cdi/jpa-cdi/src/main/resources/io/helidon/integrations/cdi/jpa/Messages.properties
  integrations/cdi/jpa-cdi/src/test/java/io/helidon/integrations/cdi/jpa/TestAnnotationRewriting.java
  integrations/cdi/jpa-cdi/src/test/java/io/helidon/integrations/cdi/jpa/TestMessages.java
  integrations/cdi/jpa-cdi/src/test/java/io/helidon/integrations/cdi/jpa/chirp/Author.java
  integrations/cdi/jpa-cdi/src/test/java/io/helidon/integrations/cdi/jpa/chirp/Chirp.java
  integrations/cdi/jpa-cdi/src/test/java/io/helidon/integrations/cdi/jpa/chirp/Microblog.java
  integrations/cdi/jpa-cdi/src/test/java/io/helidon/integrations/cdi/jpa/chirp/TestExtendedSynchronizedEntityManager.java
  integrations/cdi/jpa-cdi/src/test/java/io/helidon/integrations/cdi/jpa/chirp/TestExtendedUnsynchronizedEntityManager.java
  integrations/cdi/jpa-cdi/src/test/java/io/helidon/integrations/cdi/jpa/chirp/TestJpaTransactionScopedSynchronizedEntityManager.java
  integrations/cdi/jpa-cdi/src/test/java/io/helidon/integrations/cdi/jpa/chirp/TestJpaTransactionScopedUnsynchronizedEntityManager.java
  integrations/cdi/jpa-cdi/src/test/logging.properties
  integrations/cdi/jpa-cdi/src/test/resources/META-INF/persistence.xml
  integrations/cdi/jpa-cdi/src/test/resources/chirp.ddl
  integrations/cdi/jta-cdi/src/main/java/io/helidon/integrations/jta/cdi/NarayanaExtension.java
  integrations/cdi/jta-cdi/src/main/resources/io/helidon/integrations/jta/cdi/Messages.properties
  integrations/cdi/jta-weld/src/main/java/io/helidon/integrations/jta/weld/NarayanaTransactionServices.java
  integrations/cdi/jta-weld/src/main/resources/io/helidon/integrations/jta/weld/Messages.properties
  integrations/cdi/pom.xml
  javadocs/pom.xml
  pom.xml
Labels: MP, P3, enhancement
