Repository helidon-io/helidon, pull requests merged in 2019-02, with the labels that each got.

#361 Adds sentence with Jersey's property to enable/disable security
  docs/src/main/docs/microprofile/05_security.adoc
Labels: enhancement

#372 Fixes for docs component build warnings
  docs/src/main/docs/config/05_mutability-support.adoc
  docs/src/main/docs/guides/05_Dockerfile.adoc
  docs/src/main/docs/webserver/01_introduction.adoc
Labels: bug

#391 Upgrading to Hystrix 1.5.18
  microprofile/fault-tolerance/src/main/java/io/helidon/microprofile/faulttolerance/CircuitBreakerHelper.java
  microprofile/fault-tolerance/src/main/java/io/helidon/microprofile/faulttolerance/CommandRetrier.java
  microprofile/fault-tolerance/src/main/java/io/helidon/microprofile/faulttolerance/FaultToleranceCommand.java
  microprofile/fault-tolerance/src/main/java/io/helidon/microprofile/faulttolerance/MethodIntrospector.java
  microprofile/fault-tolerance/src/test/java/io/helidon/microprofile/faulttolerance/MetricsTest.java
  pom.xml
Labels: task
