Repository helidon-io/helidon, pull requests merged in 2020-08, with the labels that each got.

#2236 1.4: Upgrade netty to 4.1.51.Final
  dependencies/pom.xml
Labels: 1.x

#2112 Native smoke test for webclient
  tests/integration/native-image/se-1/README.md
  tests/integration/native-image/se-1/pom.xml
  tests/integration/native-image/se-1/src/main/java/io/helidon/tests/integration/nativeimage/se1/Animal.java
  tests/integration/native-image/se-1/src/main/java/io/helidon/tests/integration/nativeimage/se1/MockZipkinService.java
  tests/integration/native-image/se-1/src/main/java/io/helidon/tests/integration/nativeimage/se1/Se1Main.java
  tests/integration/native-image/se-1/src/main/java/io/helidon/tests/integration/nativeimage/se1/WebClientService.java
  tests/integration/native-image/se-1/src/main/resources/application.yaml
Labels: native-image, webclient

#2121 Single add forSingle and exceptionallyAccept
  common/reactive/src/main/java/io/helidon/common/reactive/CompletionAwaitable.java
  common/reactive/src/main/java/io/helidon/common/reactive/Single.java
  common/reactive/src/test/java/io/helidon/common/reactive/SingleTest.java
Labels: reactive

#2237 Health check now non-blocking using fault tolerance async and timeout
  fault-tolerance/src/main/java/module-info.java
  health/health/pom.xml
  health/health/src/main/java/io/helidon/health/HealthSupport.java
  health/health/src/main/java/module-info.java
Labels: bug, health

#2129 Flush streamed datachunk one by one
  media/common/src/main/java/io/helidon/media/common/CharSequenceBodyStreamWriter.java
  media/common/src/main/java/io/helidon/media/common/DefaultMediaSupport.java
  media/common/src/main/java/io/helidon/media/common/MessageBodyContext.java
  media/jsonp/src/main/java/io/helidon/media/jsonp/JsonpBodyStreamWriter.java
  media/jsonp/src/main/java/io/helidon/media/jsonp/JsonpBodyWriter.java
  webserver/webserver/src/main/java/io/helidon/webserver/BareResponseImpl.java
  webserver/webserver/src/main/java/io/helidon/webserver/Response.java
  webserver/webserver/src/test/java/io/helidon/webserver/PlainTest.java
  webserver/webserver/src/test/java/io/helidon/webserver/utils/SocketHttpClient.java
Labels: reactive, webserver

#2242 Kafka connector topic pattern
  messaging/kafka/src/main/java/io/helidon/messaging/connectors/kafka/KafkaConfig.java
  messaging/kafka/src/main/java/io/helidon/messaging/connectors/kafka/KafkaConfigBuilder.java
  messaging/kafka/src/main/java/io/helidon/messaging/connectors/kafka/KafkaPublisher.java
  tests/integration/kafka/src/test/java/io/helidon/messaging/connectors/kafka/KafkaMpTest.java
  tests/integration/kafka/src/test/java/io/helidon/messaging/connectors/kafka/KafkaSeTest.java
Labels: messaging

#2244 Correctly handling invalid requests and custom configuration for HTTP…
  docs/src/main/docs/webserver/02_configuration.adoc
  webserver/webserver/src/main/java/io/helidon/webserver/ForwardingHandler.java
  webserver/webserver/src/main/java/io/helidon/webserver/HttpInitializer.java
  webserver/webserver/src/main/java/io/helidon/webserver/NettyWebServer.java
  webserver/webserver/src/main/java/io/helidon/webserver/ServerBasicConfig.java
  webserver/webserver/src/main/java/io/helidon/webserver/ServerConfiguration.java
  webserver/webserver/src/main/java/io/helidon/webserver/SocketConfiguration.java
  webserver/webserver/src/test/java/io/helidon/webserver/ServerConfigurationTest.java
  webserver/webserver/src/test/java/io/helidon/webserver/TestHttpParsingCustom.java
  webserver/webserver/src/test/java/io/helidon/webserver/TestHttpParsingDefaults.java
Labels: 1.x

#2246 Update CHANGELOG and THIRD_PARTY_LICENSES in prep for 1.4.7 release
  CHANGELOG.md
  THIRD_PARTY_LICENSES.txt
Labels: 1.x

#2254 Upgrade Yasson to 1.0.8
  THIRD_PARTY_LICENSES.txt
  dependencies/pom.xml
Labels: 2.x

#2255 1.4: Update Yasson to 1.0.8
  THIRD_PARTY_LICENSES.txt
  dependencies/pom.xml
Labels: 1.x

#2260 Fix failures caused by memory leak when sending bad requests.
  CHANGELOG.md
  webclient/webclient/src/main/java/io/helidon/webclient/NettyClientInitializer.java
  webserver/webserver/src/main/java/io/helidon/webserver/ForwardingHandler.java
  webserver/webserver/src/main/java/io/helidon/webserver/NettyWebServer.java
  webserver/webserver/src/test/java/io/helidon/webserver/TestHttpParsingDefaults.java
Labels: 2.x

#2261 Fix hangs when bad request was sent.
  webserver/webserver/src/main/java/io/helidon/webserver/ForwardingHandler.java
  webserver/webserver/src/test/java/io/helidon/webserver/TestHttpParsingDefaults.java
Labels: 1.x

#2250 Backpressure counter race condition fix
  messaging/kafka/src/main/java/io/helidon/messaging/connectors/kafka/KafkaSubscriber.java
Labels: messaging

#2265 Update changelog to prepare for 2.0.2 release
  CHANGELOG.md
Labels: 2.x

#2263 Use Session.getDatasourceLogin() instead of Session.getLogin() in CDISEPlatform.java
  integrations/cdi/eclipselink-cdi/src/main/java/io/helidon/integrations/cdi/eclipselink/CDISEPlatform.java
Labels: P4, jpa/jta, task

#2271 1.4: Update third party attribution for eclipselink
  THIRD_PARTY_LICENSES.txt
Labels: 1.x

#2272 2.0: Update third party attribution for eclipselink
  THIRD_PARTY_LICENSES.txt
Labels: 2.x

#2276 Redundant filter execution fix
  webserver/webserver/src/main/java/io/helidon/webserver/Response.java
  webserver/webserver/src/main/java/io/helidon/webserver/ServerResponse.java
  webserver/webserver/src/test/java/io/helidon/webserver/FilterTest.java
Labels: webserver

#1874 Debugging log operator
  common/reactive/src/main/java/io/helidon/common/reactive/Multi.java
  common/reactive/src/main/java/io/helidon/common/reactive/MultiLoggingPublisher.java
  common/reactive/src/test/java/io/helidon/common/reactive/MultiLogTest.java
  common/reactive/src/test/java/io/helidon/common/reactive/MultiTest.java
Labels: enhancement, reactive

#2290 Set junit4 version where used. Fixes #2289
  dependencies/pom.xml
  microprofile/tests/arquillian/pom.xml
Labels: 2.x

#2280 Fix for P-521 curve - wrong id 1.x.
  security/jwt/src/main/java/io/helidon/security/jwt/jwk/JwkEC.java
  security/jwt/src/main/java/io/helidon/security/jwt/jwk/JwkKeys.java
  security/jwt/src/test/resources/jwk_data.json
Labels: 1.x, bug, security

#2281 Fix for P-521 curve - wrong id 2.x
  security/jwt/src/main/java/io/helidon/security/jwt/jwk/JwkEC.java
  security/jwt/src/main/java/io/helidon/security/jwt/jwk/JwkKeys.java
  security/jwt/src/test/resources/jwk_data.json
Labels: 2.x, bug, security

#2287 Weaken test assertion for executions in very slow systems
  fault-tolerance/src/test/java/io/helidon/faulttolerance/RetryTest.java
Labels: build, fault-tolerance

#2298 Security now has higer priority
  microprofile/security/src/main/java/io/helidon/microprofile/security/SecurityMpService.java
  security/providers/abac/src/main/java/io/helidon/security/providers/abac/AbacProvider.java
Labels: 1.x, bug, security

#2305 Added timeouts to client, webserver and tests to identify intermitten…
  webserver/webserver/src/test/java/io/helidon/webserver/TestHttpParsingDefaults.java
Labels: 1.x
