Repository helidon-io/helidon, pull requests merged in 2022-12, with the labels that each got.

#5575 Support for "raw protocol" string
  common/http/src/main/java/io/helidon/common/http/HttpPrologue.java
  common/http/src/test/java/io/helidon/common/http/HttpPrologueTest.java
  nima/http2/webserver/src/main/java/io/helidon/nima/http2/webserver/Http2Connection.java
  nima/http2/webserver/src/main/java/io/helidon/nima/http2/webserver/Http2UpgradeProvider.java
  nima/webserver/access-log/src/test/java/io/helidon/nima/webserver/accesslog/AccessLogFilterTest.java
  nima/webserver/static-content/src/test/java/io/helidon/nima/webserver/staticcontent/CachedHandlerTest.java
  nima/webserver/static-content/src/test/java/io/helidon/nima/webserver/staticcontent/StaticContentHandlerTest.java
  nima/webserver/webserver/src/main/java/io/helidon/nima/webserver/http/RouteCrawler.java
  nima/webserver/webserver/src/main/java/io/helidon/nima/webserver/http/ServerResponseBase.java
  nima/webserver/webserver/src/main/java/io/helidon/nima/webserver/http1/Http1Prologue.java
  nima/webserver/webserver/src/test/java/io/helidon/nima/webserver/http/ErrorHandlersTest.java
Labels: enhancement, Níma, OCA Verified

#5573 [4.x] Jwt scope handling extended over array support
  security/jwt/src/main/java/io/helidon/security/jwt/JwtUtil.java
Labels: OCA Verified

#5566 Remove trailing empty line in copyright comment (part 14)
  messaging/connectors/aq/src/main/java/io/helidon/messaging/connectors/aq/package-info.java
  messaging/connectors/aq/src/test/java/io/helidon/messaging/connectors/aq/ConfigTest.java
  messaging/connectors/jms/src/main/java/io/helidon/messaging/connectors/jms/ConfigHelper.java
  messaging/connectors/jms/src/main/java/io/helidon/messaging/connectors/jms/JmsMessage.java
  messaging/connectors/jms/src/test/java/io/helidon/messaging/connectors/jms/ConfigTest.java
  messaging/kafka/src/main/java/io/helidon/messaging/connectors/kafka/AppInfoParserSubstitution.java
  messaging/kafka/src/main/java/io/helidon/messaging/connectors/kafka/CompressionTypeSubstitution.java
  messaging/kafka/src/main/java/io/helidon/messaging/connectors/kafka/Crc32CSubstitution.java
  messaging/kafka/src/main/java/io/helidon/messaging/connectors/kafka/JmxReporterSubstitution.java
  messaging/kafka/src/main/java/io/helidon/messaging/connectors/kafka/SaslClientCallbackHandlerSubstitution.java
  messaging/kafka/src/main/java/io/helidon/messaging/connectors/kafka/package-info.java
  messaging/messaging/src/main/java/io/helidon/messaging/Channel.java
  messaging/messaging/src/main/java/io/helidon/messaging/ConnectorConfigBuilder.java
  messaging/messaging/src/main/java/io/helidon/messaging/ConnectorConfigHelper.java
  messaging/messaging/src/main/java/io/helidon/messaging/ContextSubscriber.java
  messaging/messaging/src/main/java/io/helidon/messaging/Emitter.java
  messaging/messaging/src/main/java/io/helidon/messaging/MessagingException.java
  messaging/messaging/src/main/java/io/helidon/messaging/MessagingImpl.java
  messaging/messaging/src/main/java/io/helidon/messaging/Stoppable.java
  messaging/messaging/src/main/java/io/helidon/messaging/package-info.java
  messaging/messaging/src/test/java/io/helidon/messaging/ConsumerErrorHandlingTest.java
  messaging/messaging/src/test/java/io/helidon/messaging/EmitterTest.java
  messaging/messaging/src/test/java/io/helidon/messaging/LatchedTestData.java
  messaging/messaging/src/test/java/io/helidon/messaging/MessagingTest.java
  messaging/messaging/src/test/java/io/helidon/messaging/StateTest.java
  messaging/messaging/src/test/java/io/helidon/messaging/TestConfigurableConnector.java
  messaging/messaging/src/test/java/io/helidon/messaging/TestConnector.java
  messaging/messaging/src/test/java/io/helidon/messaging/TestMessages.java
Labels: OCA Verified

#5547 Use Hamcrest assertions instead of JUnit in integrations/db/pgsql - backport 2.x (#1749)
  integrations/db/pgsql/src/test/java/io/helidon/integrations/db/pgsql/TestBaseDataSourceSubstitution.java
Labels: OCA Verified

#5168 2.x: OIDC multi-tenant and lazy loading implementation
  pom.xml
  security/integration/grpc/src/main/java/io/helidon/security/integration/grpc/GrpcClientSecurity.java
  security/integration/jersey-client/src/main/java/io/helidon/security/integration/jersey/client/ClientSecurityFilter.java
  security/integration/jersey-client/src/main/java/module-info.java
  security/integration/jersey/src/main/java/io/helidon/security/integration/jersey/SecurityFilterCommon.java
  security/integration/webserver/src/main/java/io/helidon/security/integration/webserver/SecurityHandler.java
  security/integration/webserver/src/main/java/io/helidon/security/integration/webserver/WebSecurity.java
  security/providers/idcs-mapper/src/main/java/io/helidon/security/providers/idcs/mapper/IdcsRoleMapperRxProviderBase.java
  security/providers/oidc-common/src/main/java/io/helidon/security/providers/oidc/common/BaseBuilder.java
  security/providers/oidc-common/src/main/java/io/helidon/security/providers/oidc/common/OidcConfig.java
  security/providers/oidc-common/src/main/java/io/helidon/security/providers/oidc/common/OidcMetadata.java
  security/providers/oidc-common/src/main/java/io/helidon/security/providers/oidc/common/Tenant.java
  security/providers/oidc-common/src/main/java/io/helidon/security/providers/oidc/common/TenantConfig.java
  security/providers/oidc-common/src/main/java/io/helidon/security/providers/oidc/common/TenantConfigImpl.java
  security/providers/oidc-common/src/main/java/io/helidon/security/providers/oidc/common/spi/TenantConfigFinder.java
  security/providers/oidc-common/src/main/java/io/helidon/security/providers/oidc/common/spi/TenantConfigProvider.java
  security/providers/oidc-common/src/main/java/io/helidon/security/providers/oidc/common/spi/TenantIdFinder.java
  security/providers/oidc-common/src/main/java/io/helidon/security/providers/oidc/common/spi/TenantIdProvider.java
  security/providers/oidc-common/src/main/java/io/helidon/security/providers/oidc/common/spi/package-info.java
  security/providers/oidc-common/src/main/java/module-info.java
  security/providers/oidc-common/src/test/java/io/helidon/security/providers/oidc/common/OidcConfigAbstractTest.java
  security/providers/oidc-common/src/test/java/io/helidon/security/providers/oidc/common/OidcConfigFromBuilderTest.java
  security/providers/oidc/src/main/java/io/helidon/security/providers/oidc/DefaultTenantIdProvider.java
  security/providers/oidc/src/main/java/io/helidon/security/providers/oidc/OidcProvider.java
  security/providers/oidc/src/main/java/io/helidon/security/providers/oidc/OidcSupport.java
  security/providers/oidc/src/main/java/io/helidon/security/providers/oidc/OidcUtil.java
  security/providers/oidc/src/main/java/io/helidon/security/providers/oidc/TenantAuthenticationHandler.java
  security/providers/oidc/src/main/java/module-info.java
  security/security/pom.xml
  security/security/src/main/java/io/helidon/security/SecurityEnvironment.java
  security/security/src/main/java/module-info.java
  tests/integration/oidc/pom.xml
  tests/integration/oidc/src/main/java/io/helidon/tests/integration/oidc/TestResource.java
  tests/integration/oidc/src/test/java/io/helidon/tests/integration/oidc/CommonLoginBase.java
  tests/integration/oidc/src/test/java/io/helidon/tests/integration/oidc/CookieBasedLoginIT.java
  tests/integration/oidc/src/test/java/io/helidon/tests/integration/oidc/QueryBasedLoginIT.java
  tests/integration/oidc/src/test/java/io/helidon/tests/integration/oidc/TenantIdentificationIT.java
  tests/integration/oidc/src/test/resources/application.yaml
  tests/integration/oidc/src/test/resources/test-realm.json
  tests/integration/oidc/src/test/resources/test2-realm.json
  tests/integration/pom.xml
  webclient/security/src/main/java/io/helidon/webclient/security/WebClientSecurity.java
  webclient/webclient/src/main/java/io/helidon/webclient/NettyClientHandler.java
  webclient/webclient/src/main/java/io/helidon/webclient/RedirectInterceptor.java
  webclient/webclient/src/main/java/io/helidon/webclient/WebClient.java
  webclient/webclient/src/main/java/io/helidon/webclient/WebClientConfiguration.java
  webclient/webclient/src/main/java/io/helidon/webclient/WebClientRequestBuilderImpl.java
Labels: OCA Verified

#5587 [4.x] - Add Max Re-Route configurable
  nima/webserver/webserver/src/main/java/io/helidon/nima/webserver/http/HttpRouting.java
Labels: webserver, 4.x, Níma, OCA Verified

#5588 Use Hamcrest assertions instead of JUnit in examples/webserver/threadpool (#1749)
  examples/webserver/threadpool/pom.xml
  examples/webserver/threadpool/src/test/java/io/helidon/examples/webserver/threadpool/MainTest.java
Labels: OCA Verified

#5602 Added method hasEntity to readable entity
  nima/http/media/media/src/main/java/io/helidon/nima/http/media/ReadableEntity.java
  nima/http/media/media/src/main/java/io/helidon/nima/http/media/ReadableEntityBase.java
  nima/http/media/multipart/src/main/java/io/helidon/nima/http/media/multipart/ReadablePartAbstract.java
Labels: 4.x, Níma, OCA Verified

#5599 4.x: MP Opentracing TCK fix
  common/http/src/main/java/io/helidon/common/http/Http.java
  examples/nima/tracing/src/main/java/io/helidon/examples/nima/tracing/TracingMain.java
  microprofile/server/src/main/java/io/helidon/microprofile/server/JaxRsService.java
  microprofile/tests/tck/pom.xml
  microprofile/tests/tck/tck-opentracing/logging.properties
  microprofile/tracing/pom.xml
  microprofile/tracing/src/main/java/io/helidon/microprofile/tracing/MpTracingContextFilter.java
  microprofile/tracing/src/main/java/io/helidon/microprofile/tracing/TracingCdiExtension.java
  microprofile/tracing/src/main/java/module-info.java
  nima/webserver/tracing/pom.xml
  nima/webserver/tracing/src/main/java/io/helidon/nima/webserver/tracing/PathTracingConfig.java
  nima/webserver/tracing/src/main/java/io/helidon/nima/webserver/tracing/TracingFeature.java
  nima/webserver/tracing/src/main/java/io/helidon/nima/webserver/tracing/TracingSupport.java
  nima/webserver/tracing/src/main/java/module-info.java
  nima/webserver/webserver/src/main/java/io/helidon/nima/webserver/http/HttpRouting.java
  nima/webserver/webserver/src/main/java/io/helidon/nima/webserver/http/RouteCrawler.java
  nima/webserver/webserver/src/main/java/io/helidon/nima/webserver/http1/Http1ServerResponse.java
Labels: MP, tracing, 4.x, OCA Verified

#5595 Additional testing for Nima's websocket implementation
  nima/tests/integration/websocket/server/src/main/java/io/helidon/nima/tests/integration/websocket/webserver/WsAction.java
  nima/tests/integration/websocket/server/src/main/java/io/helidon/nima/tests/integration/websocket/webserver/WsConversation.java
  nima/tests/integration/websocket/server/src/main/java/io/helidon/nima/tests/integration/websocket/webserver/WsConversationClient.java
  nima/tests/integration/websocket/server/src/main/java/io/helidon/nima/tests/integration/websocket/webserver/WsConversationService.java
  nima/tests/integration/websocket/server/src/test/java/io/helidon/nima/tests/integration/websocket/webserver/WsConversationTest.java
Labels: websocket, Níma, OCA Verified

#5572 Pass correct config to health providers
  nima/observe/health/src/main/java/io/helidon/nima/observe/health/HealthFeature.java
Labels: OCA Verified

#5593 [4.x] - Add Context to Loom Webserver.
  nima/http2/webserver/src/main/java/io/helidon/nima/http2/webserver/Http2ServerRequest.java
  nima/testing/junit5/webserver/src/main/java/io/helidon/nima/testing/junit5/webserver/DirectClientConnection.java
  nima/webserver/webserver/src/main/java/io/helidon/nima/webserver/ConnectionContext.java
  nima/webserver/webserver/src/main/java/io/helidon/nima/webserver/ConnectionContextImpl.java
  nima/webserver/webserver/src/main/java/io/helidon/nima/webserver/ConnectionHandler.java
  nima/webserver/webserver/src/main/java/io/helidon/nima/webserver/LoomServer.java
  nima/webserver/webserver/src/main/java/io/helidon/nima/webserver/ServerListener.java
  nima/webserver/webserver/src/main/java/io/helidon/nima/webserver/WebServer.java
  nima/webserver/webserver/src/main/java/io/helidon/nima/webserver/http1/Http1ServerRequest.java
Labels: webserver, 4.x, Níma, OCA Verified

#5601 Client tracing interceptor no longer clears exception
  tracing/jersey-client/src/main/java/io/helidon/tracing/jersey/client/ClientTracingInterceptor.java
Labels: OCA Verified

#5607 Wrongly merged files.
  webclient/jaxrs/src/main/resources/META-INF/native-image/io.helidon.webclient/helidon-webclient-jaxrs/native-image.properties
  webclient/jaxrs/src/main/resources/META-INF/native-image/io.helidon.webclient/helidon-webclient-jaxrs/reflect-config.json
Labels: OCA Verified

#5610 Fix handling of entity length in HTTP/2.
  nima/grpc/webserver/src/main/java/io/helidon/nima/grpc/webserver/GrpcProtocolHandler.java
  nima/http2/webserver/src/main/java/io/helidon/nima/http2/webserver/Http2Stream.java
  nima/tests/integration/grpc/server/src/test/java/io/helidon/nima/tests/integration/grpc/webserver/GrpcServerTest.java
  nima/tests/integration/grpc/server/src/test/resources/logging.properties
Labels: grpc, 4.x, Níma, OCA Verified

#5615 Builtin Helidon health features doubling fix
  examples/nima/quickstart-standalone/src/main/java/io/helidon/examples/nima/quickstart/standalone/StandaloneQuickstartMain.java
  examples/nima/quickstart/src/main/java/io/helidon/examples/nima/quickstart/QuickstartMain.java
Labels: 4.x, OCA Verified

#5620 [4.x] Client tracing interceptor no longer clears exception
  tracing/jersey-client/src/main/java/io/helidon/tracing/jersey/client/ClientTracingInterceptor.java
Labels: OCA Verified

#5596 Use Hamcrest assertions instead of JUnit in examples/webserver/threadpool - backport 2.x (#1749)
  examples/webserver/threadpool/pom.xml
  examples/webserver/threadpool/src/test/java/io/helidon/examples/webserver/threadpool/MainTest.java
Labels: OCA Verified

#5622 [3.x] 5496 flatMapCompletionStage javadoc fix
  common/reactive/src/main/java/io/helidon/common/reactive/Multi.java
Labels: OCA Verified

#5624 [4.x] 5618 flatMapCompletionStage javadoc fix
  common/reactive/src/main/java/io/helidon/common/reactive/Multi.java
Labels: OCA Verified

#5628 2.x: Update owasp dependency-check version. Cleanup FP suppressions.
  etc/dependency-check-suppression.xml
  pom.xml
Labels: 2.x, OCA Verified

#5627 4.x: Update owasp dependency-check version. Cleanup FP suppressions.
  etc/dependency-check-suppression.xml
  pom.xml
Labels: 4.x, OCA Verified

#5626 3.x: Update owasp dependency-check version. Cleanup FP suppressions.
  etc/dependency-check-suppression.xml
  pom.xml
Labels: 3.x, OCA Verified

#5623 [2.x] 5617 flatMapCompletionStage javadoc fix
  common/reactive/src/main/java/io/helidon/common/reactive/Multi.java
Labels: OCA Verified

#5576 Archetype Doc
  archetypes/oci-mp/src/main/resources/README.md
  archetypes/oci-mp/src/main/resources/spec/README.md
  docs/about/05_archetype.adoc
Labels: OCA Verified

#5577 Remove trailing empty line in copyright comment (part 15)
  common/reactive/src/test/java/io/helidon/common/reactive/SingleComposeTest.java
  common/reactive/src/test/java/io/helidon/common/reactive/SingleDefaultIfEmptyTest.java
  common/reactive/src/test/java/io/helidon/common/reactive/SingleDeferTest.java
  common/reactive/src/test/java/io/helidon/common/reactive/SingleFlatMapIterableTest.java
  common/reactive/src/test/java/io/helidon/common/reactive/SingleFlatMapMultiTest.java
  common/reactive/src/test/java/io/helidon/common/reactive/SingleFlatMapOptionalTest.java
  common/reactive/src/test/java/io/helidon/common/reactive/SingleFlatMapSingleTest.java
  common/reactive/src/test/java/io/helidon/common/reactive/SingleFromCompletionStageTest.java
  common/reactive/src/test/java/io/helidon/common/reactive/SingleIfEmptyTest.java
  common/reactive/src/test/java/io/helidon/common/reactive/SingleObserveOnTest.java
  common/reactive/src/test/java/io/helidon/common/reactive/SingleOnCompleteResumeWithTest.java
  common/reactive/src/test/java/io/helidon/common/reactive/SingleOnErrorResumeTest.java
  common/reactive/src/test/java/io/helidon/common/reactive/SingleOnErrorResumeWithTest.java
  common/reactive/src/test/java/io/helidon/common/reactive/SingleRetryTest.java
  common/reactive/src/test/java/io/helidon/common/reactive/SingleSwitchIfEmptyTest.java
  common/reactive/src/test/java/io/helidon/common/reactive/SingleTakeUntilPublisherTest.java
  common/reactive/src/test/java/io/helidon/common/reactive/SingleTappedPublisherTest.java
  common/reactive/src/test/java/io/helidon/common/reactive/SingleTimeoutTest.java
  common/reactive/src/test/java/io/helidon/common/reactive/SingleToTest.java
  common/reactive/src/test/java/io/helidon/common/reactive/TerminatedFutureTest.java
Labels: OCA Verified

#5634 Use Hamcrest assertions instead of JUnit in tests/functional/jax-rs-multiple-apps (#1749)
  tests/functional/jax-rs-multiple-apps/src/test/java/io/helidon/tests/functional/multipleapps/MainTest.java
Labels: OCA Verified

#5632 WebServer.Builder media support methods with Supplier variants
  media/common/src/main/java/io/helidon/media/common/MediaContextBuilder.java
  media/common/src/main/java/io/helidon/media/common/ParentingMediaContextBuilder.java
Labels: OCA Verified

#5641 4.x: Fix inconsistent status name.
  common/http/src/main/java/io/helidon/common/http/Http.java
Labels: 4.x, OCA Verified

#5640 WebServer.Builder media support methods with Supplier variants
  media/common/src/main/java/io/helidon/media/common/MediaContextBuilder.java
  media/common/src/main/java/io/helidon/media/common/ParentingMediaContextBuilder.java
Labels: OCA Verified

#5590 Add doc describing use of OpenAPI code generator to 2.x
  docs/mp/openapi/02_openapi-generator.adoc
  docs/se/openapi/02_openapi-generator.adoc
  docs/shared/openapi/openapi-generator.adoc
Labels: OCA Verified

#5621 [3.x] Various metrics test improvements to avoid intermittent failures
  config/testing/src/main/java/io/helidon/config/testing/MatcherWithRetry.java
  integrations/micrometer/cdi/pom.xml
  integrations/micrometer/cdi/src/test/java/io/helidon/integrations/micrometer/cdi/HelloWorldTest.java
  integrations/micrometer/cdi/src/test/java/io/helidon/integrations/micrometer/cdi/MeteredBeanTest.java
  metrics/metrics/src/test/java/io/helidon/metrics/TestPeriodicExecutor.java
  microprofile/metrics/src/test/java/io/helidon/microprofile/metrics/HelloWorldAsyncResponseTest.java
  microprofile/metrics/src/test/java/io/helidon/microprofile/metrics/HelloWorldAsyncResponseWithRestRequestTest.java
  microprofile/metrics/src/test/java/io/helidon/microprofile/metrics/HelloWorldRestEndpointSimpleTimerDisabledTest.java
  microprofile/metrics/src/test/java/io/helidon/microprofile/metrics/HelloWorldTest.java
Labels: 3.x, OCA Verified

#5652 Adding feature file for MP native image.
  integrations/graal/mp-native-image-extension/src/main/resources/META-INF/native-image/io.helidon.integrations.graal/helidon-mp-graal-native-image-extension/native-image.properties
Labels: native-image, OCA Verified

#5635 Use Hamcrest assertions instead of JUnit in tests/functional/jax-rs-multiple-apps - backport 2.x (#1749)
  tests/functional/jax-rs-multiple-apps/src/test/java/io/helidon/tests/functional/multipleapps/MainTest.java
Labels: OCA Verified

#5642 3.x: Fix inconsistent status name
  common/http/src/main/java/io/helidon/common/http/Http.java
Labels: 3.x, OCA Verified

#5631 Fix problems causing MP metrics TCK failures
  metrics/service-api/src/main/java/io/helidon/metrics/serviceapi/JsonFormat.java
  microprofile/tests/tck/pom.xml
  nima/observe/metrics/src/main/java/io/helidon/nima/observe/metrics/MetricsFeature.java
  reactive/metrics/src/main/java/io/helidon/reactive/metrics/MetricsSupport.java
Labels: OCA Verified

#5651 5650 openapi examples issues
  examples/openapi-tools/quickstart-mp/README.md
  examples/openapi-tools/quickstart-mp/mp-server/src/main/java/org/openapitools/server/api/MessageServiceImpl.java
Labels: OCA Verified

#5646 set transfer encoding as response header
  nima/webserver/webserver/src/main/java/io/helidon/nima/webserver/http1/Http1ServerResponse.java
Labels: OCA Verified

#5644 Handle exception on inTransaction apply
  dbclient/jdbc/src/main/java/io/helidon/dbclient/jdbc/JdbcDbClient.java
  dbclient/jdbc/src/test/java/io/helidon/dbclient/jdbc/JdbcClientTest.java
Labels: OCA Verified

#5678 Multitenant lazy loading implementation improved
  security/providers/oidc-common/src/main/java/io/helidon/security/providers/oidc/common/BaseBuilder.java
  security/providers/oidc-common/src/main/java/io/helidon/security/providers/oidc/common/OidcConfig.java
  security/providers/oidc-common/src/main/java/io/helidon/security/providers/oidc/common/Tenant.java
  security/providers/oidc-common/src/main/java/io/helidon/security/providers/oidc/common/TenantConfig.java
  security/providers/oidc-common/src/main/java/io/helidon/security/providers/oidc/common/TenantConfigImpl.java
  security/providers/oidc/src/main/java/io/helidon/security/providers/oidc/OidcProvider.java
  security/providers/oidc/src/main/java/io/helidon/security/providers/oidc/OidcSupport.java
  security/providers/oidc/src/main/java/io/helidon/security/providers/oidc/TenantAuthenticationHandler.java
Labels: OCA Verified

#5667 Declare `h1-prefix` as early as possible so it is used for the title prefix
  docs/mp/metrics/metrics-capable-components.adoc
Labels: OCA Verified

#5670 [4.x] - [Features] - Nima Tracing
  nima/webserver/tracing/pom.xml
  nima/webserver/tracing/src/main/java/module-info.java
Labels: 4.x, OCA Verified

#5671 [4.x] - [Features] - Nima Access Log
  nima/webserver/access-log/pom.xml
  nima/webserver/access-log/src/main/java/module-info.java
Labels: 4.x, OCA Verified

#5672 [4.x] - [Features] - Nima CORS
  nima/webserver/cors/pom.xml
  nima/webserver/cors/src/main/java/module-info.java
Labels: 4.x, OCA Verified

#5673 [4.x] - [Features] - Nima Static Content
  nima/webserver/static-content/pom.xml
  nima/webserver/static-content/src/main/java/module-info.java
Labels: 4.x, OCA Verified

#5674 [4.x] - [Features] - Nima WebClient
  nima/webclient/webclient/pom.xml
  nima/webclient/webclient/src/main/java/module-info.java
Labels: 4.x, OCA Verified

#5675 [4.x] - [Features] - Nima OpenAPI
  nima/openapi/pom.xml
  nima/openapi/src/main/java/module-info.java
Labels: 4.x, OCA Verified

#5676 [4.x] - [Features] - Nima Fault Tolerance
  reactive/fault-tolerance/pom.xml
  reactive/fault-tolerance/src/main/java/module-info.java
Labels: 4.x, OCA Verified

#5684 [4.x] - [Features] - Nima Http Deflate Encoding
  nima/http/encoding/deflate/pom.xml
  nima/http/encoding/deflate/src/main/java/module-info.java
Labels: 4.x, OCA Verified

#5686 [4.x] - [Features] - Nima Http Encoding
  nima/http/encoding/encoding/pom.xml
  nima/http/encoding/encoding/src/main/java/module-info.java
Labels: 4.x, OCA Verified

#5689 [4.x] - [Features] - Nima Http Media JSON-P
  nima/http/media/jsonp/pom.xml
  nima/http/media/jsonp/src/main/java/module-info.java
Labels: 4.x, OCA Verified

#5688 [4.x] - [Features] - Nima Http Media JSON-B
  nima/http/media/jsonb/pom.xml
  nima/http/media/jsonb/src/main/java/module-info.java
Labels: 4.x, OCA Verified

#5687 [4.x] - [Features] - Nima Http Encoding GZip
  nima/http/encoding/gzip/pom.xml
  nima/http/encoding/gzip/src/main/java/module-info.java
Labels: 4.x, OCA Verified

#5677 [4.x] - [Features] - Nima GraphQL
  nima/graphql/server/pom.xml
  nima/graphql/server/src/main/java/module-info.java
Labels: 4.x, OCA Verified

#5696 [4.x] - [Features] - Nima WebSocket
  nima/websocket/websocket/pom.xml
  nima/websocket/websocket/src/main/java/module-info.java
Labels: 4.x, OCA Verified

#5699 Handle exception on inTransaction apply
  dbclient/jdbc/src/main/java/io/helidon/dbclient/jdbc/JdbcDbClient.java
  dbclient/jdbc/src/test/java/io/helidon/dbclient/jdbc/JdbcClientTest.java
Labels: OCA Verified

#5691 [4.x] - [Features] - Nima Http Media Multipart
  nima/http/media/multipart/pom.xml
  nima/http/media/multipart/src/main/java/module-info.java
Labels: 4.x, OCA Verified

#5700 Handle exception on inTransaction apply
  reactive/dbclient/jdbc/src/main/java/io/helidon/reactive/dbclient/jdbc/JdbcDbClient.java
  reactive/dbclient/jdbc/src/test/java/io/helidon/reactive/dbclient/jdbc/JdbcClientTest.java
Labels: OCA Verified

#5705 2.x: Upgrade build-tools to 2.3.7
  applications/parent/pom.xml
  examples/quickstarts/helidon-standalone-quickstart-mp/pom.xml
  examples/quickstarts/helidon-standalone-quickstart-se/pom.xml
  pom.xml
Labels: 2.x, OCA Verified

#5619 [3.x] OIDC multi-tenant and lazy loading implementation
  docs/config/config_reference.adoc
  docs/config/io_helidon_security_providers_oidc_common_BaseBuilder.adoc
  docs/config/io_helidon_security_providers_oidc_common_OidcConfig.adoc
  docs/config/io_helidon_security_providers_oidc_common_TenantConfig.adoc
  pom.xml
  security/integration/grpc/src/main/java/io/helidon/security/integration/grpc/GrpcClientSecurity.java
  security/integration/jersey-client/src/main/java/io/helidon/security/integration/jersey/client/ClientSecurityFilter.java
  security/integration/jersey-client/src/main/java/module-info.java
  security/integration/jersey/src/main/java/io/helidon/security/integration/jersey/SecurityFilterCommon.java
  security/integration/webserver/src/main/java/io/helidon/security/integration/webserver/SecurityHandler.java
  security/integration/webserver/src/main/java/io/helidon/security/integration/webserver/WebSecurity.java
  security/providers/idcs-mapper/src/main/java/io/helidon/security/providers/idcs/mapper/IdcsRoleMapperRxProviderBase.java
  security/providers/oidc-common/src/main/java/io/helidon/security/providers/oidc/common/BaseBuilder.java
  security/providers/oidc-common/src/main/java/io/helidon/security/providers/oidc/common/OidcConfig.java
  security/providers/oidc-common/src/main/java/io/helidon/security/providers/oidc/common/OidcMetadata.java
  security/providers/oidc-common/src/main/java/io/helidon/security/providers/oidc/common/Tenant.java
  security/providers/oidc-common/src/main/java/io/helidon/security/providers/oidc/common/TenantConfig.java
  security/providers/oidc-common/src/main/java/io/helidon/security/providers/oidc/common/TenantConfigImpl.java
  security/providers/oidc-common/src/main/java/io/helidon/security/providers/oidc/common/spi/TenantConfigFinder.java
  security/providers/oidc-common/src/main/java/io/helidon/security/providers/oidc/common/spi/TenantConfigProvider.java
  security/providers/oidc-common/src/main/java/io/helidon/security/providers/oidc/common/spi/TenantIdFinder.java
  security/providers/oidc-common/src/main/java/io/helidon/security/providers/oidc/common/spi/TenantIdProvider.java
  security/providers/oidc-common/src/main/java/io/helidon/security/providers/oidc/common/spi/package-info.java
  security/providers/oidc-common/src/main/java/module-info.java
  security/providers/oidc-common/src/test/java/io/helidon/security/providers/oidc/common/OidcConfigAbstractTest.java
  security/providers/oidc-common/src/test/java/io/helidon/security/providers/oidc/common/OidcConfigFromBuilderTest.java
  security/providers/oidc/src/main/java/io/helidon/security/providers/oidc/DefaultTenantIdProvider.java
  security/providers/oidc/src/main/java/io/helidon/security/providers/oidc/OidcProvider.java
  security/providers/oidc/src/main/java/io/helidon/security/providers/oidc/OidcSupport.java
  security/providers/oidc/src/main/java/io/helidon/security/providers/oidc/OidcUtil.java
  security/providers/oidc/src/main/java/io/helidon/security/providers/oidc/TenantAuthenticationHandler.java
  security/providers/oidc/src/main/java/module-info.java
  security/security/pom.xml
  security/security/src/main/java/io/helidon/security/SecurityEnvironment.java
  security/security/src/main/java/module-info.java
  tests/integration/oidc/pom.xml
  tests/integration/oidc/src/main/java/io/helidon/tests/integration/oidc/TestResource.java
  tests/integration/oidc/src/test/java/io/helidon/tests/integration/oidc/CommonLoginBase.java
  tests/integration/oidc/src/test/java/io/helidon/tests/integration/oidc/CookieBasedLoginIT.java
  tests/integration/oidc/src/test/java/io/helidon/tests/integration/oidc/QueryBasedLoginIT.java
  tests/integration/oidc/src/test/java/io/helidon/tests/integration/oidc/TenantIdentificationIT.java
  tests/integration/oidc/src/test/resources/application.yaml
  tests/integration/oidc/src/test/resources/test-realm.json
  tests/integration/oidc/src/test/resources/test2-realm.json
  tests/integration/pom.xml
  webclient/security/src/main/java/io/helidon/webclient/security/WebClientSecurity.java
  webclient/webclient/src/main/java/io/helidon/webclient/NettyClientHandler.java
  webclient/webclient/src/main/java/io/helidon/webclient/RedirectInterceptor.java
  webclient/webclient/src/main/java/io/helidon/webclient/WebClient.java
  webclient/webclient/src/main/java/io/helidon/webclient/WebClientConfiguration.java
  webclient/webclient/src/main/java/io/helidon/webclient/WebClientRequestBuilderImpl.java
Labels: OCA Verified

#5704 Replace OCI Java SDK shaded jar with v3 for OCI integration
  dependencies/pom.xml
  docs/includes/oci.adoc
  docs/mp/integrations/oci.adoc
  docs/se/integrations/oci.adoc
  examples/integrations/oci/README.md
  examples/integrations/oci/atp-cdi/pom.xml
  examples/integrations/oci/atp-cdi/src/main/java/io/helidon/examples/integrations/oci/atp/cdi/AtpResource.java
  examples/integrations/oci/atp-reactive/pom.xml
  examples/integrations/oci/metrics-reactive/pom.xml
  examples/integrations/oci/objectstorage-cdi/pom.xml
  examples/integrations/oci/objectstorage-reactive/pom.xml
  examples/integrations/oci/vault-cdi/pom.xml
  examples/integrations/oci/vault-reactive/pom.xml
  integrations/oci/sdk/cdi/pom.xml
  integrations/oci/sdk/cdi/src/main/java/io/helidon/integrations/oci/sdk/cdi/OciExtension.java
  integrations/oci/sdk/cdi/src/main/java/module-info.java
  integrations/oci/sdk/cdi/src/test/java/io/helidon/integrations/oci/sdk/cdi/TestSpike.java
Labels: 3.x, OCA Verified

#5648 [3.x] Jwt now support multiple issuers and multi issuer validation
  security/jwt/src/main/java/io/helidon/security/jwt/Jwt.java
  security/jwt/src/test/java/io/helidon/security/jwt/JwtTest.java
Labels: OCA Verified

#5715 Fix user log entry of access log.
  nima/webserver/access-log/src/main/java/io/helidon/nima/webserver/accesslog/AccessLogFeature.java
  nima/webserver/access-log/src/main/java/io/helidon/nima/webserver/accesslog/UserLogEntry.java
  nima/webserver/access-log/src/main/java/module-info.java
  nima/webserver/access-log/src/test/java/io/helidon/nima/webserver/accesslog/AccessLogFeatureTest.java
Labels: 4.x, Níma, OCA Verified

#5703 3.x: Upgrade Netty to 4.1.86.Final
  dependencies/pom.xml
  pom.xml
  webserver/webserver/src/test/java/io/helidon/webserver/TestNettyRejectRequest.java
Labels: 3.x, OCA Verified

#5725 2.x: Upgrade Netty to 4.1.86.Final
  dependencies/pom.xml
  pom.xml
  webserver/webserver/src/test/java/io/helidon/webserver/TestNettyRejectRequest.java
Labels: 2.x, dependencies, OCA Verified

#5735 4.x: Upgrade build-tools to 3.0.3, fix hbs template file copyright
  applications/pom.xml
  etc/copyright-exclude.txt
  examples/quickstarts/helidon-standalone-quickstart-mp/pom.xml
  examples/quickstarts/helidon-standalone-quickstart-se/pom.xml
  pico/tools/src/main/resources/templates/pico/default/module-info.hbs
  pom.xml
Labels: 4.x, OCA Verified

#5730 4.x: Upgrade owasp dependency check to 7.4.1
  pom.xml
Labels: 4.x, OCA Verified

#5729 3.x: Upgrade owasp dependency check to 7.4.1
  pom.xml
Labels: 3.x, OCA Verified

#5728 2.x: Upgrade owasp dependency check to 7.4.1
  pom.xml
Labels: 2.x, OCA Verified

#5726 3.x: Upgrade build-tools to 3.0.3
  applications/pom.xml
  examples/quickstarts/helidon-standalone-quickstart-mp/pom.xml
  examples/quickstarts/helidon-standalone-quickstart-se/pom.xml
  pom.xml
Labels: 3.x, OCA Verified

#5736 3.x: Fix parent poms in example
  examples/openapi-tools/quickstart-mp/mp-client/pom.xml
  examples/openapi-tools/quickstart-mp/mp-server/pom.xml
  examples/openapi-tools/quickstart-se/se-client/pom.xml
  examples/openapi-tools/quickstart-se/se-server/pom.xml
Labels: 3.x, OCA Verified

#5708 Cannot debug in Eclipse IDE Version: 2022-09 (4.25.0) #5706
  .gitignore
  config/metadata-processor/src/main/java/io/helidon/config/metadata/processor/ConfigMetadataHandler.java
Labels: OCA Verified

#5739 #5737 - Nima: Add WebServer.Builder configuration option to support not registering JVM shutdown hook
  lra/coordinator/server/src/test/java/io/helidon/lra/coordinator/CoordinatorTest.java
  nima/testing/junit5/webserver/src/main/java/io/helidon/nima/testing/junit5/webserver/HelidonServerJunitExtension.java
  nima/webserver/webserver/src/main/java/io/helidon/nima/webserver/LoomServer.java
  nima/webserver/webserver/src/main/java/io/helidon/nima/webserver/WebServer.java
Labels: OCA Verified

#5692 [4.x] - [Features] - Nima Http2 WebServer
  nima/http2/webserver/pom.xml
  nima/http2/webserver/src/main/java/module-info.java
Labels: 4.x, OCA Verified

#5734 4.x: Upgrade netty to 4.1.86.Final and use netty bom
  dependencies/pom.xml
  pom.xml
  reactive/webserver/webserver/src/test/java/io/helidon/reactive/webserver/TestNettyRejectRequest.java
Labels: 4.x, OCA Verified

#5690 [4.x] - [Features] - Nima Http Media
  nima/http/media/media/pom.xml
  nima/http/media/media/src/main/java/module-info.java
Labels: 4.x, OCA Verified

#5753 [2.x] - Neo4j Driver update
  dependencies/pom.xml
Labels: 2.x, OCA Verified

#5751 [4.x] - Neo4j driver update
  dependencies/pom.xml
Labels: 4.x, OCA Verified

#5695 [4.x] - [Features] - Nima WebSocket WebServer
  nima/websocket/webserver/pom.xml
  nima/websocket/webserver/src/main/java/module-info.java
Labels: 4.x, OCA Verified

#5732 Add built-in support for converting config strings to enum values
  config/config/src/main/java/io/helidon/config/BuilderImpl.java
  config/config/src/main/java/io/helidon/config/ConfigMapperManager.java
  config/config/src/main/java/io/helidon/config/EnumMapperProvider.java
  config/config/src/test/java/io/helidon/config/ConfigMappersTest.java
  docs/se/config/property-mapping.adoc
  tests/integration/native-image/se-1/README.md
  tests/integration/native-image/se-1/src/main/java/io/helidon/tests/integration/nativeimage/se1/ColorService.java
  tests/integration/native-image/se-1/src/main/java/io/helidon/tests/integration/nativeimage/se1/Se1Main.java
  tests/integration/native-image/se-1/src/main/resources/application.yaml
  tests/integration/native-image/se-1/src/test/java/io/helidon/tests/integration/nativeimage/se1/Se1MainTest.java
Labels: OCA Verified

#5752 [3.x] - Neo4j Driver update
  dependencies/pom.xml
Labels: OCA Verified

#5744 3.x: Update smoketest for 3.x archetype endpoints
  etc/scripts/smoketest.sh
Labels: 3.x, OCA Verified

#5747 Fixed race condition on bulkhead.
  nima/fault-tolerance/src/main/java/io/helidon/nima/faulttolerance/AsyncImpl.java
  nima/fault-tolerance/src/main/java/io/helidon/nima/faulttolerance/BulkheadImpl.java
  nima/fault-tolerance/src/test/java/io/helidon/nima/faulttolerance/AsyncTest.java
  nima/fault-tolerance/src/test/java/io/helidon/nima/faulttolerance/BulkheadTest.java
  tests/integration/webclient/src/test/java/io/helidon/tests/integration/webclient/TracingPropagationTest.java
Labels: bug, 4.x, OCA Verified

#5761 Fix incorrectly reverted icons
  docs/sitegen.yaml
Labels: OCA Verified

#5709 5409 duration timeout
  common/reactive/src/main/java/io/helidon/common/reactive/Awaitable.java
  common/reactive/src/main/java/io/helidon/common/reactive/IoMulti.java
  config/config/src/main/java/io/helidon/config/FileSystemWatcher.java
  integrations/microstream/health/src/main/java/io/helidon/integrations/microstream/health/MicrostreamHealthCheck.java
  lra/coordinator/client/narayana-client/src/main/java/io/helidon/lra/coordinator/client/narayana/NarayanaClient.java
  lra/coordinator/client/spi/src/main/java/io/helidon/lra/coordinator/client/CoordinatorClient.java
  reactive/dbclient/health/src/main/java/io/helidon/reactive/dbclient/health/DbClientHealthCheck.java
  reactive/health/src/main/java/io/helidon/reactive/health/HealthSupport.java
  reactive/webclient/webclient/src/main/java/io/helidon/reactive/webclient/WebClient.java
  reactive/webclient/webclient/src/main/java/io/helidon/reactive/webclient/WebClientRequestBuilder.java
  reactive/webclient/webclient/src/main/java/io/helidon/reactive/webclient/WebClientRequestBuilderImpl.java
Labels: OCA Verified

#5755 4.x: Intermittent failure (WebClient tracing test)
  tests/integration/webclient/pom.xml
  tests/integration/webclient/src/test/java/io/helidon/tests/integration/webclient/TracingPropagationTest.java
  tests/integration/webclient/src/test/java/io/helidon/tests/integration/webclient/TracingTest.java
Labels: webclient, intermittent, 4.x, OCA Verified

#5765 [4.x] - Features formatting
  config/config/src/main/java/module-info.java
  config/encryption/src/main/java/module-info.java
  docs-internal/feature-catalog.md
  grpc/client/src/main/java/module-info.java
  grpc/metrics/src/main/java/module-info.java
  integrations/cdi/hibernate-cdi/src/main/java/module-info.java
  integrations/cdi/jta-cdi/src/main/java/module-info.java
  integrations/micrometer/micrometer/src/main/java/module-info.java
  messaging/messaging/src/main/java/module-info.java
  nima/graphql/server/src/main/java/module-info.java
  nima/grpc/webserver/src/main/java/module-info.java
  nima/http/encoding/deflate/src/main/java/module-info.java
  nima/http/encoding/encoding/src/main/java/module-info.java
  nima/http/encoding/gzip/src/main/java/module-info.java
  nima/http/media/jsonb/src/main/java/module-info.java
  nima/http/media/jsonp/src/main/java/module-info.java
  nima/http/media/media/src/main/java/module-info.java
  nima/http/media/multipart/src/main/java/module-info.java
  nima/http2/webserver/src/main/java/module-info.java
  nima/webserver/access-log/src/main/java/module-info.java
  nima/webserver/cors/src/main/java/module-info.java
  nima/webserver/tracing/src/main/java/module-info.java
  nima/webserver/webserver/src/main/java/module-info.java
  nima/websocket/webserver/src/main/java/module-info.java
  nima/websocket/websocket/src/main/java/module-info.java
  openapi/src/main/java/module-info.java
  reactive/graphql/server/src/main/java/module-info.java
  reactive/health/src/main/java/module-info.java
  reactive/media/jackson/src/main/java/module-info.java
  reactive/media/jsonb/src/main/java/module-info.java
  reactive/media/jsonp/src/main/java/module-info.java
  reactive/media/multipart/src/main/java/module-info.java
  reactive/webserver/access-log/src/main/java/module-info.java
  reactive/webserver/cors/src/main/java/module-info.java
  reactive/webserver/jersey/src/main/java/module-info.java
  reactive/webserver/webserver/src/main/java/module-info.java
  reactive/webserver/websocket/src/main/java/module-info.java
  scheduling/src/main/java/module-info.java
  security/security/src/main/java/module-info.java
  tracing/tracing/src/main/java/module-info.java
Labels: 4.x, OCA Verified

#5614 Doc fixes for Issue 4673
  docs/includes/cors.adoc
  docs/includes/mp.adoc
  docs/includes/openapi/openapi-generator.adoc
  docs/includes/se.adoc
  docs/includes/security/helidon-endpoints.adoc
  docs/includes/security/providers/oidc.adoc
  docs/mp/aot.adoc
  docs/mp/cors/cors.adoc
  docs/mp/cors/why-options.adoc
  docs/mp/guides/config.adoc
  docs/mp/guides/security-oidc.adoc
  docs/mp/guides/tracing.adoc
  docs/mp/introduction.adoc
  docs/mp/jaxrs/jaxrs-applications.adoc
  docs/mp/jwt.adoc
  docs/mp/lra.adoc
  docs/mp/metrics/metrics.adoc
  docs/mp/openapi.adoc
  docs/mp/openapi/openapi-generator.adoc
  docs/mp/openapi/openapi-ui.adoc
  docs/mp/openapi/openapi.adoc
  docs/mp/reactivemessaging/aq.adoc
  docs/mp/reactivemessaging/introduction.adoc
  docs/mp/reactivemessaging/jms.adoc
  docs/mp/reactivemessaging/kafka.adoc
  docs/mp/reactivemessaging/mock.adoc
  docs/mp/reactivemessaging/weblogic.adoc
  docs/mp/security/configuration-secrets.adoc
  docs/mp/security/security.adoc
  docs/mp/testing-ng.adoc
  docs/mp/testing.adoc
  docs/se/aot.adoc
  docs/se/cors.adoc
  docs/se/fault-tolerance.adoc
  docs/se/guides/config.adoc
  docs/se/guides/migration_3x.adoc
  docs/se/guides/tracing.adoc
  docs/se/introduction.adoc
  docs/se/openapi/openapi-generator.adoc
  docs/se/openapi/openapi-ui.adoc
  docs/se/openapi/openapi.adoc
  docs/se/reactive-messaging.adoc
  docs/se/scheduling.adoc
  docs/se/security/introduction.adoc
Labels: OCA Verified

#5733 Introduces LocalXAResource and a few support classes in jta/jdbc
  integrations/jta/jdbc/src/main/java/io/helidon/integrations/jta/jdbc/ExceptionConverter.java
  integrations/jta/jdbc/src/main/java/io/helidon/integrations/jta/jdbc/LocalXAResource.java
  integrations/jta/jdbc/src/main/java/io/helidon/integrations/jta/jdbc/TransactionSupplier.java
  integrations/jta/jdbc/src/main/java/io/helidon/integrations/jta/jdbc/UncheckedXAException.java
Labels: jpa/jta, 3.x, OCA Verified
