Repository helidon-io/helidon, pull requests merged in 2022-11, with the labels that each got.

#5292 [4.x] - AllowThreadLocals configurable
  nima/webserver/webserver/src/main/java/io/helidon/nima/webserver/LoomServer.java
Labels: config, 4.x, Níma, OCA Verified

#5294 [Archetypes] database choices should be before packaging (backport)
  archetypes/helidon/src/main/archetype/common/docker.xml
  archetypes/helidon/src/main/archetype/common/observability.xml
  archetypes/helidon/src/main/archetype/mp/custom/custom-mp.xml
  archetypes/helidon/src/main/archetype/mp/custom/database.xml
  archetypes/helidon/src/main/archetype/se/custom/custom-se.xml
  archetypes/helidon/src/main/archetype/se/custom/database.xml
Labels: 3.x, archetypes, backport, OCA Verified

#5295 Log an entry in warning level for a 400 or 413 response
  webserver/webserver/src/main/java/io/helidon/webserver/ForwardingHandler.java
Labels: enhancement, webserver, logging, OCA Verified

#5286 Use Hamcrest assertions instead of JUnit in openapi - backport 2.x (#1749)
  openapi/src/test/java/io/helidon/openapi/ServerModelReaderTest.java
  openapi/src/test/java/io/helidon/openapi/ServerTest.java
  openapi/src/test/java/io/helidon/openapi/TestCors.java
  openapi/src/test/java/io/helidon/openapi/TestUtil.java
Labels: OCA Verified

#5285 Use Hamcrest assertions instead of JUnit in openapi (#1749)
  openapi/src/test/java/io/helidon/openapi/ServerModelReaderTest.java
  openapi/src/test/java/io/helidon/openapi/ServerTest.java
  openapi/src/test/java/io/helidon/openapi/TestCors.java
  openapi/src/test/java/io/helidon/openapi/TestUtil.java
Labels: OCA Verified

#5241 [4.x] Added author for Neo4j
  etc/checkstyle.xml
  etc/copyright-exclude.txt
  examples/integrations/neo4j/neo4j-mp/src/main/java/io/helidon/examples/integrations/neo4j/mp/domain/Actor.java
  examples/integrations/neo4j/neo4j-mp/src/main/java/io/helidon/examples/integrations/neo4j/mp/domain/Movie.java
  examples/integrations/neo4j/neo4j-mp/src/main/java/io/helidon/examples/integrations/neo4j/mp/domain/MovieRepository.java
  examples/integrations/neo4j/neo4j-mp/src/main/java/io/helidon/examples/integrations/neo4j/mp/domain/Person.java
  examples/integrations/neo4j/neo4j-se/src/main/java/io/helidon/examples/integrations/neo4j/se/domain/Actor.java
  examples/integrations/neo4j/neo4j-se/src/main/java/io/helidon/examples/integrations/neo4j/se/domain/Movie.java
  examples/integrations/neo4j/neo4j-se/src/main/java/io/helidon/examples/integrations/neo4j/se/domain/MovieRepository.java
  examples/integrations/neo4j/neo4j-se/src/main/java/io/helidon/examples/integrations/neo4j/se/domain/Person.java
Labels: docs, testing, 4.x, OCA Verified

#5269 [3.x] - Simplify named socket WebTarget injection in Tests
  microprofile/tests/junit5-tests/src/test/java/io/helidon/microprofile/tests/junit5/TestNamedWebTarget.java
  microprofile/tests/junit5/src/main/java/io/helidon/microprofile/tests/junit5/HelidonJunitExtension.java
  microprofile/tests/junit5/src/main/java/io/helidon/microprofile/tests/junit5/Socket.java
Labels: 3.x, testing, OCA Verified, junit

#5243 [2.x] Added author for Neo4j
  etc/checkstyle.xml
  etc/copyright-exclude.txt
  examples/integrations/neo4j/neo4j-mp/src/main/java/io/helidon/examples/integrations/neo4j/mp/domain/Actor.java
  examples/integrations/neo4j/neo4j-mp/src/main/java/io/helidon/examples/integrations/neo4j/mp/domain/Movie.java
  examples/integrations/neo4j/neo4j-mp/src/main/java/io/helidon/examples/integrations/neo4j/mp/domain/MovieRepository.java
  examples/integrations/neo4j/neo4j-mp/src/main/java/io/helidon/examples/integrations/neo4j/mp/domain/Person.java
  examples/integrations/neo4j/neo4j-se/src/main/java/io/helidon/examples/integrations/neo4j/se/domain/Actor.java
  examples/integrations/neo4j/neo4j-se/src/main/java/io/helidon/examples/integrations/neo4j/se/domain/Movie.java
  examples/integrations/neo4j/neo4j-se/src/main/java/io/helidon/examples/integrations/neo4j/se/domain/MovieRepository.java
  examples/integrations/neo4j/neo4j-se/src/main/java/io/helidon/examples/integrations/neo4j/se/domain/Person.java
Labels: docs, 2.x, testing, OCA Verified

#5242 [3.x] Added author for Neo4j
  etc/checkstyle.xml
  etc/copyright-exclude.txt
  examples/integrations/neo4j/neo4j-mp/src/main/java/io/helidon/examples/integrations/neo4j/mp/domain/Actor.java
  examples/integrations/neo4j/neo4j-mp/src/main/java/io/helidon/examples/integrations/neo4j/mp/domain/Movie.java
  examples/integrations/neo4j/neo4j-mp/src/main/java/io/helidon/examples/integrations/neo4j/mp/domain/MovieRepository.java
  examples/integrations/neo4j/neo4j-mp/src/main/java/io/helidon/examples/integrations/neo4j/mp/domain/Person.java
  examples/integrations/neo4j/neo4j-se/src/main/java/io/helidon/examples/integrations/neo4j/se/domain/Actor.java
  examples/integrations/neo4j/neo4j-se/src/main/java/io/helidon/examples/integrations/neo4j/se/domain/Movie.java
  examples/integrations/neo4j/neo4j-se/src/main/java/io/helidon/examples/integrations/neo4j/se/domain/MovieRepository.java
  examples/integrations/neo4j/neo4j-se/src/main/java/io/helidon/examples/integrations/neo4j/se/domain/Person.java
Labels: docs, 3.x, testing, OCA Verified

#5267 Add relativeUris flag in OidcConfig to allow Oidc webclient to use relative path on the request URI
  docs/shared/security/providers/oidc.adoc
  security/providers/oidc-common/src/main/java/io/helidon/security/providers/oidc/common/OidcConfig.java
  security/providers/oidc-common/src/main/java/io/helidon/security/providers/oidc/common/OidcUtil.java
  security/providers/oidc-common/src/test/java/io/helidon/security/providers/oidc/common/OidcConfigAbstractTest.java
  security/providers/oidc-common/src/test/java/io/helidon/security/providers/oidc/common/OidcConfigFromBuilderTest.java
  security/providers/oidc-common/src/test/resources/application.yaml
  webclient/webclient/src/main/java/io/helidon/webclient/WebClient.java
  webclient/webclient/src/test/java/io/helidon/webclient/ProxyTest.java
Labels: OCA Verified

#5289 Fix error in OpenAPI handling of `default` values' types
  openapi/pom.xml
  openapi/src/main/java/io/helidon/openapi/ExpandedTypeDescription.java
  openapi/src/main/java/io/helidon/openapi/OpenAPISupport.java
  openapi/src/test/java/io/helidon/openapi/ParserTest.java
  openapi/src/test/resources/petstore-with-fake-endpoints-models-for-testing.yaml
Labels: OCA Verified

#5304 4.x: Upgrade to jackson-databind-2.13.4.2 via bom 2.13.4.20221013
  dependencies/pom.xml
  etc/HELIDON_THIRD_PARTY_LICENSES.xml
Labels: dependencies, 4.x, OCA Verified

#5314 [4.x] - Simplify named socket WebTarget injection in Tests
  microprofile/tests/junit5-tests/src/test/java/io/helidon/microprofile/tests/junit5/TestNamedWebTarget.java
  microprofile/tests/junit5/src/main/java/io/helidon/microprofile/tests/junit5/HelidonJunitExtension.java
  microprofile/tests/junit5/src/main/java/io/helidon/microprofile/tests/junit5/Socket.java
Labels: testing, 4.x, OCA Verified, junit

#5315 [2.x] - Simplify named socket WebTarget injection in Tests
  microprofile/tests/junit5-tests/src/test/java/io/helidon/microprofile/tests/junit5/TestNamedWebTarget.java
  microprofile/tests/junit5/src/main/java/io/helidon/microprofile/tests/junit5/HelidonJunitExtension.java
  microprofile/tests/junit5/src/main/java/io/helidon/microprofile/tests/junit5/Socket.java
  microprofile/tests/junit5/src/main/java/module-info.java
Labels: 2.x, testing, OCA Verified, junit

#5263 Openapi generator doc 3.x
  docs/includes/attributes.adoc
  docs/includes/openapi/openapi-generator.adoc
  docs/includes/openapi/openapi.adoc
  docs/includes/pages.adoc
  docs/mp/introduction.adoc
  docs/mp/openapi/openapi-generator.adoc
  docs/mp/openapi/openapi.adoc
  docs/se/health.adoc
  docs/se/introduction.adoc
  docs/se/openapi/openapi-generator.adoc
  docs/se/openapi/openapi.adoc
  docs/se/tracing.adoc
  docs/sitegen.yaml
Labels: OCA Verified

#5311 Fix problem when double quotes exist in the subject title during Create backport issues action
  etc/scripts/actions/create-backport-issues.sh
Labels: OCA Verified

#5303 2.x: Upgrade to jackson-databind-2.13.4.2 via bom 2.13.4.20221013
  dependencies/pom.xml
  etc/HELIDON_THIRD_PARTY_LICENSES.xml
Labels: 2.x, dependencies, OCA Verified

#5302 3.x: Upgrade to jackson-databind-2.13.4.2 via bom 2.13.4.20221013
  dependencies/pom.xml
  etc/HELIDON_THIRD_PARTY_LICENSES.xml
Labels: dependencies, 3.x, OCA Verified

#5334 Fix inadvertent changes in attributes.adoc
  docs/includes/attributes.adoc
Labels: OCA Verified

#5312 Use property to skip execution of eclipselink weave
  archetypes/helidon/src/main/archetype/mp/custom/database.xml
Labels: archetypes, 4.x, OCA Verified

#5313 Use property to skip execution of eclipselink weave
  archetypes/helidon/src/main/archetype/mp/custom/database.xml
Labels: 3.x, archetypes, backport, OCA Verified

#5322 Remove benchmark modules from Helidon repository.
  .gitignore
  nima/tests/benchmark/h2/h2load.md
  nima/tests/benchmark/h2/pom.xml
  nima/tests/benchmark/h2/src/main/java/io/helidon/nima/tests/benchmark/h2/Client.java
  nima/tests/benchmark/h2/src/main/java/io/helidon/nima/tests/benchmark/h2/Main.java
  nima/tests/benchmark/h2/src/main/resources/certificate.p12
  nima/tests/benchmark/h2/src/main/resources/logging.properties
  nima/tests/benchmark/pom.xml
  nima/tests/benchmark/techempower/benchmark.sh
  nima/tests/benchmark/techempower/pipeline.lua
  nima/tests/benchmark/techempower/pom.xml
  nima/tests/benchmark/techempower/src/main/java/io/helidon/nima/tests/benchmark/techempower/TechEmpowerMain.java
  nima/tests/benchmark/techempower/src/main/resources/META-INF/native-image/io.helidon.nima.tests.benchmark/helidon-nima-tests-benchmark-techempower/native-image.properties
  nima/tests/benchmark/techempower/src/main/resources/application.yaml
  nima/tests/benchmark/techempower/src/main/resources/config-profile.yaml
  nima/tests/benchmark/techempower/src/main/resources/logging.properties
  nima/tests/benchmark/techempower/src/test/java/io/helidon/nima/tests/benchmark/techempower/BenchmarkIT.java
  nima/tests/benchmark/techempower/src/test/java/io/helidon/nima/tests/benchmark/techempower/BenchmarkTest.java
  nima/tests/benchmark/techempower/src/test/java/io/helidon/nima/tests/benchmark/techempower/BenchmarkTestBase.java
  nima/tests/benchmark/techempower/wrk.md
  reactive/pom.xml
  reactive/tests/benchmark/pom.xml
  reactive/tests/benchmark/techempower/pom.xml
  reactive/tests/benchmark/techempower/src/main/java/io/helidon/reactive/tests/benchmark/techempower/TechEmpowerMain.java
  reactive/tests/benchmark/techempower/src/main/resources/META-INF/native-image/io.helidon.reactive.tests.benchmark/helidon-nima-reactive-benchmark-techempower/native-image.properties
  reactive/tests/benchmark/techempower/src/main/resources/application.yaml
  reactive/tests/benchmark/techempower/src/main/resources/config-profile.yaml
  reactive/tests/benchmark/techempower/src/main/resources/logging.properties
  reactive/tests/pom.xml
  tests/integration/native-image/mp-1/src/main/java/io/helidon/tests/integration/nativeimage/mp1/TestBean.java
Labels: 4.x, OCA Verified

#5342 Remove trailing empty line in copyright comment (part 4)
  openapi/src/test/java/io/helidon/openapi/OpenAPIConfigTest.java
  openapi/src/test/java/io/helidon/openapi/ParserTest.java
  openapi/src/test/java/io/helidon/openapi/SerializerTest.java
  openapi/src/test/java/io/helidon/openapi/ServerModelReaderTest.java
  openapi/src/test/java/io/helidon/openapi/ServerTest.java
  openapi/src/test/java/io/helidon/openapi/TestCors.java
  openapi/src/test/java/io/helidon/openapi/TestUtil.java
  openapi/src/test/java/io/helidon/openapi/test/MyModelReader.java
  openapi/src/test/java/io/helidon/openapi/test/MySimpleFilter.java
  scheduling/src/main/java/io/helidon/scheduling/CronInvocation.java
  scheduling/src/main/java/io/helidon/scheduling/CronTask.java
  scheduling/src/main/java/io/helidon/scheduling/FixedRateTask.java
  scheduling/src/main/java/io/helidon/scheduling/ScheduledConsumer.java
  scheduling/src/main/java/io/helidon/scheduling/Scheduling.java
  scheduling/src/main/java/io/helidon/scheduling/SchedulingException.java
  scheduling/src/main/java/io/helidon/scheduling/Task.java
  scheduling/src/test/java/io/helidon/scheduling/CronSchedulingTest.java
  scheduling/src/test/java/io/helidon/scheduling/FixedRateSchedulingTest.java
  scheduling/src/test/java/io/helidon/scheduling/IntervalMeter.java
Labels: OCA Verified

#5340 Remove trailing empty line in copyright comment (part 3)
  tests/tck/tck-reactive-streams/src/test/java/io/helidon/common/reactive/BufferedEmittingPublisherTckTest.java
  tests/tck/tck-reactive-streams/src/test/java/io/helidon/common/reactive/ConcatPublisher2TckTest.java
  tests/tck/tck-reactive-streams/src/test/java/io/helidon/common/reactive/ConcatPublisherTckTest.java
  tests/tck/tck-reactive-streams/src/test/java/io/helidon/common/reactive/EmittingPublisherTckTest.java
  tests/tck/tck-reactive-streams/src/test/java/io/helidon/common/reactive/MultiCollectTckTest.java
  tests/tck/tck-reactive-streams/src/test/java/io/helidon/common/reactive/MultiCollectorTckTest.java
  tests/tck/tck-reactive-streams/src/test/java/io/helidon/common/reactive/MultiConcatArrayTck1Test.java
  tests/tck/tck-reactive-streams/src/test/java/io/helidon/common/reactive/MultiConcatArrayTck2Test.java
  tests/tck/tck-reactive-streams/src/test/java/io/helidon/common/reactive/MultiDeferTckTest.java
  tests/tck/tck-reactive-streams/src/test/java/io/helidon/common/reactive/MultiDistinctPublisherModuloTckTest.java
  tests/tck/tck-reactive-streams/src/test/java/io/helidon/common/reactive/MultiDistinctPublisherTckTest.java
  tests/tck/tck-reactive-streams/src/test/java/io/helidon/common/reactive/MultiDropWhileTckTest.java
  tests/tck/tck-reactive-streams/src/test/java/io/helidon/common/reactive/MultiFilterPublisherTckTest.java
  tests/tck/tck-reactive-streams/src/test/java/io/helidon/common/reactive/MultiFirstPublisherTckTest.java
  tests/tck/tck-reactive-streams/src/test/java/io/helidon/common/reactive/MultiFlatMapCompletionStageTckTest.java
  tests/tck/tck-reactive-streams/src/test/java/io/helidon/common/reactive/MultiFlatMapIterableManyToManyTckTest.java
  tests/tck/tck-reactive-streams/src/test/java/io/helidon/common/reactive/MultiFlatMapIterableManyToOneTckTest.java
  tests/tck/tck-reactive-streams/src/test/java/io/helidon/common/reactive/MultiFlatMapIterableOneToManyTckTest.java
  tests/tck/tck-reactive-streams/src/test/java/io/helidon/common/reactive/MultiFlatMapPublisherManyToOneTckTest.java
  tests/tck/tck-reactive-streams/src/test/java/io/helidon/common/reactive/MultiFlatMapPublisherOneToManyTckTest.java
  tests/tck/tck-reactive-streams/src/test/java/io/helidon/common/reactive/MultiFromArrayTckTest.java
  tests/tck/tck-reactive-streams/src/test/java/io/helidon/common/reactive/MultiFromIterableTckTest.java
  tests/tck/tck-reactive-streams/src/test/java/io/helidon/common/reactive/MultiFromNotTrustedInputStreamTckTest.java
  tests/tck/tck-reactive-streams/src/test/java/io/helidon/common/reactive/MultiFromStreamTckTest.java
  tests/tck/tck-reactive-streams/src/test/java/io/helidon/common/reactive/MultiFromTrustedInputStreamTckTest.java
  tests/tck/tck-reactive-streams/src/test/java/io/helidon/common/reactive/MultiIntervalTckTest.java
  tests/tck/tck-reactive-streams/src/test/java/io/helidon/common/reactive/MultiLimitPublisherMoreTckTest.java
  tests/tck/tck-reactive-streams/src/test/java/io/helidon/common/reactive/MultiLimitPublisherTckTest.java
  tests/tck/tck-reactive-streams/src/test/java/io/helidon/common/reactive/MultiLimitPublisherZeroTckTest.java
  tests/tck/tck-reactive-streams/src/test/java/io/helidon/common/reactive/MultiOnCompleteResumeWithTckTest.java
  tests/tck/tck-reactive-streams/src/test/java/io/helidon/common/reactive/MultiOnCompleteTckTest.java
  tests/tck/tck-reactive-streams/src/test/java/io/helidon/common/reactive/MultiOnErrorResumeFailureTckTest.java
  tests/tck/tck-reactive-streams/src/test/java/io/helidon/common/reactive/MultiOnErrorResumeSuccessTckTest.java
  tests/tck/tck-reactive-streams/src/test/java/io/helidon/common/reactive/MultiOnErrorResumeWithFailureTckTest.java
  tests/tck/tck-reactive-streams/src/test/java/io/helidon/common/reactive/MultiOnErrorResumeWithSuccessTckTest.java
  tests/tck/tck-reactive-streams/src/test/java/io/helidon/common/reactive/MultiOnErrorTckTest.java
Labels: 2.x, OCA Verified

#5331 Remove trailing empty line in copyright comment (part 2)
  tests/integration/jms/src/test/java/io/helidon/messaging/connectors/jms/AbstractMPTest.java
  tests/integration/jms/src/test/java/io/helidon/messaging/connectors/jms/AckMpTest.java
  tests/integration/jms/src/test/java/io/helidon/messaging/connectors/jms/JmsMpTest.java
  webserver/cors/src/main/java/io/helidon/webserver/cors/Aggregator.java
  webserver/cors/src/main/java/io/helidon/webserver/cors/CorsEnabledServiceHelper.java
  webserver/cors/src/main/java/io/helidon/webserver/cors/CorsSetter.java
  webserver/cors/src/main/java/io/helidon/webserver/cors/CorsSupportBase.java
  webserver/cors/src/main/java/io/helidon/webserver/cors/Loader.java
  webserver/cors/src/main/java/io/helidon/webserver/cors/LogHelper.java
  webserver/cors/src/main/java/io/helidon/webserver/cors/RequestAdapterSe.java
  webserver/cors/src/main/java/io/helidon/webserver/cors/ResponseAdapterSe.java
  webserver/cors/src/main/java/io/helidon/webserver/cors/package-info.java
  webserver/cors/src/main/java/module-info.java
  webserver/cors/src/test/java/io/helidon/webserver/cors/AbstractCorsTest.java
  webserver/cors/src/test/java/io/helidon/webserver/cors/AbstractCorsTestService.java
  webserver/cors/src/test/java/io/helidon/webserver/cors/CompareOriginsTest.java
  webserver/cors/src/test/java/io/helidon/webserver/cors/CorsTest.java
  webserver/cors/src/test/java/io/helidon/webserver/cors/CorsTestServices.java
  webserver/cors/src/test/java/io/helidon/webserver/cors/CustomMatchers.java
  webserver/cors/src/test/java/io/helidon/webserver/cors/GreetService.java
  webserver/cors/src/test/java/io/helidon/webserver/cors/MissingConfigTest.java
  webserver/cors/src/test/java/io/helidon/webserver/cors/TestDefaultCorsSupport.java
  webserver/cors/src/test/java/io/helidon/webserver/cors/TestHandlerRegistration.java
  webserver/cors/src/test/java/io/helidon/webserver/cors/TestOrdering.java
  webserver/cors/src/test/java/io/helidon/webserver/cors/TestTwoCorsConfigs.java
  webserver/cors/src/test/java/io/helidon/webserver/cors/TestUtil.java
  webserver/cors/src/test/java/io/helidon/webserver/cors/TestUtilityMethods.java
Labels: 2.x, OCA Verified

#5335 Add relativeUris flag in OidcConfig to allow Oidc webclient to use relative path on the request URI
  docs/config/io_helidon_security_providers_oidc_OidcProvider.adoc
  docs/config/io_helidon_security_providers_oidc_common_OidcConfig.adoc
  security/providers/oidc-common/src/main/java/io/helidon/security/providers/oidc/common/OidcConfig.java
  security/providers/oidc-common/src/main/java/io/helidon/security/providers/oidc/common/OidcUtil.java
  security/providers/oidc-common/src/test/java/io/helidon/security/providers/oidc/common/OidcConfigAbstractTest.java
  security/providers/oidc-common/src/test/java/io/helidon/security/providers/oidc/common/OidcConfigFromBuilderTest.java
  security/providers/oidc-common/src/test/resources/application.yaml
  webclient/webclient/src/main/java/io/helidon/webclient/WebClient.java
  webclient/webclient/src/test/java/io/helidon/webclient/ProxyTest.java
Labels: 3.x, OCA Verified

#5317 New FT Nima executors and larger multiplier for TCK timeouts in pipeline
  microprofile/fault-tolerance/src/main/java/io/helidon/microprofile/faulttolerance/FaultToleranceExtension.java
  microprofile/fault-tolerance/src/test/java/io/helidon/microprofile/faulttolerance/ThreadPoolConfigTest.java
  microprofile/tests/tck/tck-fault-tolerance/pom.xml
  nima/fault-tolerance/src/main/java/io/helidon/nima/faulttolerance/Async.java
  nima/fault-tolerance/src/main/java/io/helidon/nima/faulttolerance/AsyncImpl.java
  nima/fault-tolerance/src/main/java/io/helidon/nima/faulttolerance/BulkheadImpl.java
  nima/fault-tolerance/src/main/java/io/helidon/nima/faulttolerance/CircuitBreaker.java
  nima/fault-tolerance/src/main/java/io/helidon/nima/faulttolerance/CircuitBreakerImpl.java
  nima/fault-tolerance/src/main/java/io/helidon/nima/faulttolerance/FaultTolerance.java
  nima/fault-tolerance/src/main/java/io/helidon/nima/faulttolerance/Timeout.java
  nima/fault-tolerance/src/main/java/io/helidon/nima/faulttolerance/TimeoutImpl.java
  nima/fault-tolerance/src/test/java/io/helidon/nima/faulttolerance/AsyncTest.java
  nima/fault-tolerance/src/test/java/io/helidon/nima/faulttolerance/BulkheadTest.java
  nima/fault-tolerance/src/test/java/io/helidon/nima/faulttolerance/CircuitBreakerTest.java
Labels: enhancement, testing, OCA Verified

#5347 Remove trailing empty line in copyright comment (part 6)
  metrics/jaeger/src/main/java/module-info.java
  metrics/metrics/src/main/java/io/helidon/metrics/DisplayableLabeledSnapshot.java
  metrics/metrics/src/main/java/io/helidon/metrics/ExemplarService.java
  metrics/metrics/src/main/java/io/helidon/metrics/ExemplarServiceManager.java
  metrics/metrics/src/main/java/io/helidon/metrics/HelidonSimpleTimer.java
  metrics/metrics/src/main/java/io/helidon/metrics/PrometheusName.java
  metrics/metrics/src/main/java/io/helidon/metrics/Sample.java
  metrics/metrics/src/main/java/io/helidon/metrics/WrappedSnapshot.java
  metrics/metrics/src/test/java/io/helidon/metrics/GreetService.java
  metrics/metrics/src/test/java/io/helidon/metrics/HelidonMetricsMatcher.java
  metrics/metrics/src/test/java/io/helidon/metrics/HelidonSimpleTimerTest.java
  metrics/metrics/src/test/java/io/helidon/metrics/OutputUnitConversionTest.java
  metrics/metrics/src/test/java/io/helidon/metrics/TestNearestValueSearch.java
  metrics/metrics/src/test/java/io/helidon/metrics/TestServer.java
  metrics/metrics/src/test/java/io/helidon/metrics/TestSetup.java
  metrics/metrics/src/test/java/io/helidon/metrics/TestStorageUnitsScaling.java
  metrics/service-api/src/main/java/module-info.java
  metrics/trace-exemplar/src/main/java/io/helidon/metrics/exemplartrace/package-info.java
  metrics/trace-exemplar/src/main/java/module-info.java
Labels: OCA Verified

#5339 Fix problem when double quotes exist in the subject title during Create backport issues action
  etc/scripts/actions/create-backport-issues.sh
Labels: 4.x, OCA Verified

#5336 Add relativeUris flag in OidcConfig to allow Oidc webclient to use relative path on the request URI
  docs/config/io_helidon_security_providers_oidc_OidcProvider.adoc
  docs/config/io_helidon_security_providers_oidc_common_OidcConfig.adoc
  reactive/webclient/webclient/src/main/java/io/helidon/reactive/webclient/WebClient.java
  reactive/webclient/webclient/src/test/java/io/helidon/reactive/webclient/ProxyTest.java
  security/providers/oidc-common/pom.xml
  security/providers/oidc-common/src/main/java/io/helidon/security/providers/oidc/common/OidcConfig.java
  security/providers/oidc-common/src/main/java/io/helidon/security/providers/oidc/common/OidcUtil.java
  security/providers/oidc-common/src/test/java/io/helidon/security/providers/oidc/common/OidcConfigAbstractTest.java
  security/providers/oidc-common/src/test/java/io/helidon/security/providers/oidc/common/OidcConfigFromBuilderTest.java
  security/providers/oidc-common/src/test/resources/application.yaml
Labels: OCA Verified

#5346 Remove trailing empty line in copyright comment (part 5)
  common/reactive/src/main/java/io/helidon/common/reactive/EmittingPublisher.java
  dbclient/jdbc/src/test/java/io/helidon/dbclient/jdbc/JdbcClientMultipleDMLOperationTest.java
  dbclient/jdbc/src/test/java/io/helidon/dbclient/jdbc/JdbcClientTest.java
  examples/integrations/neo4j/neo4j-se/src/main/java/io/helidon/examples/integrations/neo4j/se/domain/Actor.java
  examples/integrations/neo4j/neo4j-se/src/main/java/io/helidon/examples/integrations/neo4j/se/domain/Movie.java
  examples/integrations/neo4j/neo4j-se/src/main/java/io/helidon/examples/integrations/neo4j/se/domain/MovieRepository.java
  examples/integrations/neo4j/neo4j-se/src/main/java/io/helidon/examples/integrations/neo4j/se/domain/Person.java
  examples/metrics/filtering/mp/src/main/java/io/helidon/examples/metrics/filtering/mp/package-info.java
  integrations/jdbc/jdbc/src/main/java/io/helidon/integrations/jdbc/package-info.java
  integrations/jdbc/jdbc/src/main/java/module-info.java
  integrations/neo4j/neo4j/src/main/java/io/helidon/integrations/neo4j/Neo4j.java
  integrations/neo4j/neo4j/src/main/java/io/helidon/integrations/neo4j/Neo4jCdiExtension.java
  lra/coordinator/client/narayana-client/src/main/java/io/helidon/lra/coordinator/client/narayana/LraStatusReader.java
  lra/coordinator/client/narayana-client/src/main/java/io/helidon/lra/coordinator/client/narayana/package-info.java
  lra/coordinator/client/narayana-client/src/main/java/module-info.java
  messaging/connectors/aq/src/main/java/io/helidon/messaging/connectors/aq/AqConnectorImpl.java
  messaging/connectors/jms/src/main/java/io/helidon/messaging/connectors/jms/ConnectionContext.java
  messaging/connectors/jms/src/main/java/io/helidon/messaging/connectors/jms/JmsConnector.java
  messaging/connectors/jms/src/main/java/io/helidon/messaging/connectors/jms/package-info.java
  tests/tck/tck-reactive-streams/src/test/java/io/helidon/common/reactive/SingleOnErrorResumeWithFailureTckTest.java
  webclient/webclient/src/main/java/io/helidon/webclient/NettyChannel.java
  webclient/webclient/src/test/java/io/helidon/webclient/OrderOfWritesTest.java
Labels: OCA Verified

#5330 Support for requested URI for web server requests.
  common/http/src/main/java/io/helidon/common/http/Forwarded.java
  common/http/src/main/java/io/helidon/common/http/Http.java
  common/http/src/main/java/io/helidon/common/http/UriInfo.java
  common/http/src/test/java/io/helidon/common/http/ForwardedTest.java
  webserver/jersey/src/main/java/io/helidon/webserver/jersey/JerseySupport.java
  webserver/test-support/src/main/java/io/helidon/webserver/testsupport/TestClient.java
  webserver/webserver/pom.xml
  webserver/webserver/src/main/java/io/helidon/webserver/BareRequest.java
  webserver/webserver/src/main/java/io/helidon/webserver/BareRequestImpl.java
  webserver/webserver/src/main/java/io/helidon/webserver/ForwardingHandler.java
  webserver/webserver/src/main/java/io/helidon/webserver/Request.java
  webserver/webserver/src/main/java/io/helidon/webserver/ServerBasicConfig.java
  webserver/webserver/src/main/java/io/helidon/webserver/ServerConfiguration.java
  webserver/webserver/src/main/java/io/helidon/webserver/ServerRequest.java
  webserver/webserver/src/main/java/io/helidon/webserver/SocketConfiguration.java
  webserver/webserver/src/main/java/io/helidon/webserver/WebServer.java
  webserver/webserver/src/test/java/io/helidon/webserver/RequestedUriTest.java
Labels: webserver, 3.x, OCA Verified

#5355 Log simple message for a 400 or a 413 and more under FINE
  webserver/webserver/src/main/java/io/helidon/webserver/ForwardingHandler.java
Labels: enhancement, logging, OCA Verified

#5298 Log an entry in warning level for a 400 or 413 response
  webserver/webserver/src/main/java/io/helidon/webserver/ForwardingHandler.java
Labels: webserver, 2.x, logging, OCA Verified

#5225 JAXRS doc updates for 3611
  docs/mp/jaxrs/jaxrs-applications.adoc
Labels: docs, OCA Verified

#5363 Add null check to MP Server.Builder.config()
  config/config-mp/src/main/java/io/helidon/config/mp/MpConfigSources.java
  config/config-mp/src/test/java/io/helidon/config/mp/MpConfigSourcesTest.java
  microprofile/server/src/main/java/io/helidon/microprofile/server/Server.java
  microprofile/server/src/test/java/io/helidon/microprofile/server/ServerImplTest.java
Labels: 2.x, OCA Verified

#5360 2.x: Upgrade grpc-java to 1.49.2
  THIRD_PARTY_LICENSES.txt
  dependencies/pom.xml
  etc/HELIDON_THIRD_PARTY_LICENSES.xml
  grpc/io.grpc/src/main/java/module-info.java
Labels: grpc, 2.x, dependencies, OCA Verified

#5361 4.x: Upgrade grpc-java to 1.49.2
  dependencies/pom.xml
  etc/HELIDON_THIRD_PARTY_LICENSES.xml
  grpc/io.grpc/src/main/java/module-info.java
  nima/tests/integration/grpc/server/src/test/java/io/helidon/nima/tests/integration/grpc/webserver/GrpcServerTest.java
Labels: grpc, dependencies, 4.x, OCA Verified

#5348 3.x: Upgrade grpc-java to 1.49.2
  dependencies/pom.xml
  etc/HELIDON_THIRD_PARTY_LICENSES.xml
  grpc/io.grpc/src/main/java/module-info.java
Labels: grpc, dependencies, 3.x, OCA Verified

#5368 2.x Add info to Charbuf exceptions
  media/common/src/main/java/io/helidon/media/common/CharBuffer.java
Labels: 2.x, media-support, OCA Verified

#5372 Add null check to MP Server.Builder.config() (#5363)
  config/config-mp/src/main/java/io/helidon/config/mp/MpConfigSources.java
  config/config-mp/src/test/java/io/helidon/config/mp/MpConfigSourcesTest.java
  microprofile/server/src/main/java/io/helidon/microprofile/server/Server.java
  microprofile/server/src/test/java/io/helidon/microprofile/server/ServerImplTest.java
Labels: OCA Verified

#5374 Add null check to MP Server.Builder.config() (#5363)
  config/config-mp/src/main/java/io/helidon/config/mp/MpConfigSources.java
  config/config-mp/src/test/java/io/helidon/config/mp/MpConfigSourcesTest.java
  microprofile/server/src/main/java/io/helidon/microprofile/server/Server.java
  microprofile/server/src/test/java/io/helidon/microprofile/server/ServerTest.java
Labels: OCA Verified

#5357 Remove trailing empty line in copyright comment (part 7)
  common/reactive/src/main/java/io/helidon/common/reactive/ByteChannelSubscriber.java
  common/reactive/src/main/java/io/helidon/common/reactive/CompletionSingle.java
  common/reactive/src/main/java/io/helidon/common/reactive/ConcatPublisher.java
  common/reactive/src/main/java/io/helidon/common/reactive/ConsumerChain.java
  common/reactive/src/main/java/io/helidon/common/reactive/DeferredSubscription.java
  common/reactive/src/main/java/io/helidon/common/reactive/HalfSerializer.java
  common/reactive/src/main/java/io/helidon/common/reactive/MultiConcatArray.java
  common/reactive/src/main/java/io/helidon/common/reactive/MultiDefaultIfEmpty.java
  common/reactive/src/main/java/io/helidon/common/reactive/MultiDefer.java
  common/reactive/src/main/java/io/helidon/common/reactive/MultiDeferredDefaultIfEmpty.java
  common/reactive/src/main/java/io/helidon/common/reactive/MultiDistinctPublisher.java
  common/reactive/src/main/java/io/helidon/common/reactive/MultiDropWhilePublisher.java
  common/reactive/src/main/java/io/helidon/common/reactive/MultiFilterPublisher.java
  common/reactive/src/main/java/io/helidon/common/reactive/MultiFlatMapIterable.java
  common/reactive/src/main/java/io/helidon/common/reactive/MultiFlatMapPublisher.java
  common/reactive/src/main/java/io/helidon/common/reactive/MultiFromIterable.java
  common/reactive/src/main/java/io/helidon/common/reactive/MultiFromStream.java
  common/reactive/src/main/java/io/helidon/common/reactive/MultiIfEmptyPublisher.java
  common/reactive/src/main/java/io/helidon/common/reactive/MultiLimitPublisher.java
  common/reactive/src/main/java/io/helidon/common/reactive/MultiObserveOn.java
  common/reactive/src/main/java/io/helidon/common/reactive/MultiOnCompleteResumeWith.java
  common/reactive/src/main/java/io/helidon/common/reactive/MultiOnErrorResumeWith.java
  common/reactive/src/main/java/io/helidon/common/reactive/MultiRangeLongPublisher.java
  common/reactive/src/main/java/io/helidon/common/reactive/MultiRangePublisher.java
Labels: OCA Verified

#5349 [4.x] - [Features Migration] gRPC Client
  docs-internal/feature-catalog.md
  grpc/client/pom.xml
  grpc/client/src/main/java/module-info.java
Labels: docs, 4.x, OCA Verified

#5376 4.x Add info to CharBuf exceptions
  reactive/media/common/src/main/java/io/helidon/reactive/media/common/CharBuffer.java
Labels: media-support, 4.x, OCA Verified

#4876 4.x - Custom DNS resolvers for Nima
  nima/http2/webclient/src/main/java/io/helidon/nima/http2/webclient/ClientRequestImpl.java
  nima/http2/webclient/src/main/java/io/helidon/nima/http2/webclient/Http2ClientConnection.java
  nima/http2/webclient/src/main/java/io/helidon/nima/http2/webclient/Http2ClientConnectionHandler.java
  nima/webclient/webclient/src/main/java/io/helidon/nima/webclient/ConnectionKey.java
  nima/webclient/webclient/src/main/java/io/helidon/nima/webclient/DefaultDnsAddressLookupFinder.java
  nima/webclient/webclient/src/main/java/io/helidon/nima/webclient/DefaultDnsResolver.java
  nima/webclient/webclient/src/main/java/io/helidon/nima/webclient/DefaultDnsResolverProvider.java
  nima/webclient/webclient/src/main/java/io/helidon/nima/webclient/DnsAddressLookup.java
  nima/webclient/webclient/src/main/java/io/helidon/nima/webclient/LoomClient.java
  nima/webclient/webclient/src/main/java/io/helidon/nima/webclient/NoDnsResolver.java
  nima/webclient/webclient/src/main/java/io/helidon/nima/webclient/NoDnsResolverProvider.java
  nima/webclient/webclient/src/main/java/io/helidon/nima/webclient/RoundRobinDnsResolver.java
  nima/webclient/webclient/src/main/java/io/helidon/nima/webclient/RoundRobinDnsResolverProvider.java
  nima/webclient/webclient/src/main/java/io/helidon/nima/webclient/RuntimeUnknownHostException.java
  nima/webclient/webclient/src/main/java/io/helidon/nima/webclient/WebClient.java
  nima/webclient/webclient/src/main/java/io/helidon/nima/webclient/http1/ClientRequestImpl.java
  nima/webclient/webclient/src/main/java/io/helidon/nima/webclient/http1/Http1ClientConnection.java
  nima/webclient/webclient/src/main/java/io/helidon/nima/webclient/spi/DnsResolver.java
  nima/webclient/webclient/src/main/java/io/helidon/nima/webclient/spi/DnsResolverProvider.java
  nima/webclient/webclient/src/main/java/module-info.java
Labels: OCA Verified

#5375 3.x Add info to CharBuf exceptions
  media/common/src/main/java/io/helidon/media/common/CharBuffer.java
Labels: media-support, 3.x, OCA Verified

#5381 Remove dependency on yaml config from nima module.
  nima/nima/pom.xml
  nima/nima/src/main/java/module-info.java
Labels: 4.x, OCA Verified

#5397 Name all threads.
  common/socket/src/main/java/io/helidon/common/socket/SocketWriterAsync.java
  nima/fault-tolerance/src/main/java/io/helidon/nima/faulttolerance/AsyncImpl.java
  nima/fault-tolerance/src/main/java/io/helidon/nima/faulttolerance/FaultTolerance.java
  nima/fault-tolerance/src/test/java/io/helidon/nima/faulttolerance/AsyncTest.java
  nima/tests/integration/webserver/webserver/src/test/java/io/helidon/nima/tests/integration/server/ThreadNameTest.java
  nima/tests/integration/websocket/server/src/test/java/io/helidon/nima/tests/integration/websocket/webserver/WebSocketTest.java
  nima/webserver/webserver/src/main/java/io/helidon/nima/webserver/ConnectionHandler.java
  nima/webserver/webserver/src/main/java/io/helidon/nima/webserver/LoomServer.java
  nima/webserver/webserver/src/main/java/io/helidon/nima/webserver/ServerListener.java
Labels: 4.x, OCA Verified

#5401 [4.x] - [features migration] - Messaging
  docs-internal/feature-catalog.md
  messaging/messaging/pom.xml
  messaging/messaging/src/main/java/module-info.java
Labels: docs, 4.x, OCA Verified

#5432 [4.x] - [features migration] - Webserver-Jersey
  reactive/webserver/jersey/pom.xml
  reactive/webserver/jersey/src/main/java/module-info.java
Labels: docs, 4.x, OCA Verified

#5419 [4.x] - [features migration] - Webserver-Accesslog.
  docs-internal/feature-catalog.md
  reactive/webserver/access-log/pom.xml
  reactive/webserver/access-log/src/main/java/module-info.java
Labels: docs, 4.x, OCA Verified

#5438 [4.x] - [features migration] - EclipseLink
  integrations/cdi/eclipselink-cdi/pom.xml
  integrations/cdi/eclipselink-cdi/src/main/java/module-info.java
Labels: docs, 4.x, OCA Verified

#5435 [4.x] - [features migration] - Micrometer
  integrations/micrometer/micrometer/pom.xml
  integrations/micrometer/micrometer/src/main/java/module-info.java
Labels: docs, 4.x, OCA Verified

#5450 4.x: Suppress false positives
  etc/dependency-check-suppression.xml
Labels: OCA Verified

#5449 3.x: Suppress false positives
  etc/dependency-check-suppression.xml
Labels: OCA Verified

#5441 Fix handling of optional whitespace at the beginning of headers.
  common/buffers/src/main/java/io/helidon/common/buffers/Bytes.java
  common/buffers/src/main/java/io/helidon/common/buffers/LazyString.java
  common/buffers/src/test/java/io/helidon/common/buffers/LazyStringTest.java
  common/http/src/main/java/io/helidon/common/http/HeaderValueLazy.java
  common/http/src/main/java/io/helidon/common/http/Http1HeadersParser.java
Labels: Níma, OCA Verified

#5470 NullPointerException when there is an illegal character in the request
  webserver/webserver/src/main/java/io/helidon/webserver/ForwardingHandler.java
Labels: OCA Verified

#5471 NullPointerException when there is an illegal character in the request
  webserver/webserver/src/main/java/io/helidon/webserver/ForwardingHandler.java
Labels: OCA Verified

#5472 NullPointerException when there is an illegal character in the request (#5470)
  reactive/webserver/webserver/src/main/java/io/helidon/reactive/webserver/ForwardingHandler.java
Labels: OCA Verified

#5436 Error handling support in HTTP for Nima WebServer.
  nima/tests/integration/webserver/webserver/src/test/java/io/helidon/nima/tests/integration/server/ErrorHandlingTest.java
  nima/webserver/webserver/pom.xml
  nima/webserver/webserver/src/main/java/io/helidon/nima/webserver/http/ErrorHandler.java
  nima/webserver/webserver/src/main/java/io/helidon/nima/webserver/http/ErrorHandlers.java
  nima/webserver/webserver/src/main/java/io/helidon/nima/webserver/http/Filters.java
  nima/webserver/webserver/src/main/java/io/helidon/nima/webserver/http/HttpRouting.java
  nima/webserver/webserver/src/test/java/io/helidon/nima/webserver/http/ErrorHandlersTest.java
Labels: webserver, 4.x, Níma, OCA Verified

#5491 [4.x] - [features migration] - RestClient MP
  microprofile/rest-client/pom.xml
  microprofile/rest-client/src/main/java/module-info.java
Labels: docs, 4.x, OCA Verified

#5448 Move bean utils from spi to processor
  pico/builder/builder/pom.xml
  pico/builder/builder/src/main/java/io/helidon/pico/builder/spi/package-info.java
  pico/builder/builder/src/main/java/module-info.java
  pico/builder/builder/src/test/java/io/helidon/pico/builder/spi/BeanUtilsTest.java
  pico/builder/processor-tools/pom.xml
  pico/builder/processor-tools/src/main/java/io/helidon/pico/builder/processor/tools/BeanUtils.java
  pico/builder/processor-tools/src/main/java/io/helidon/pico/builder/processor/tools/BodyContext.java
  pico/builder/processor-tools/src/main/java/io/helidon/pico/builder/processor/tools/DefaultBuilderCreator.java
  pico/builder/processor-tools/src/test/java/io/helidon/pico/builder/processor/tools/BeanUtilsTest.java
Labels: 4.x, pico, OCA Verified

#5442 [4.x] - [features migration] - Hibernate
  integrations/cdi/hibernate-cdi/pom.xml
  integrations/cdi/hibernate-cdi/src/main/java/module-info.java
Labels: docs, 4.x, OCA Verified

#5444 [4.x] - [features migration] - JPA
  integrations/cdi/jpa-cdi/pom.xml
  integrations/cdi/jpa-cdi/src/main/java/module-info.java
Labels: docs, 4.x, OCA Verified

#5445 [4.x] - [features migration] - JTA
  integrations/cdi/jta-cdi/pom.xml
  integrations/cdi/jta-cdi/src/main/java/module-info.java
Labels: docs, 4.x, OCA Verified

#5451 [4.x] - [features migration] - AccessLog MP
  microprofile/access-log/pom.xml
  microprofile/access-log/src/main/java/module-info.java
Labels: docs, 4.x, OCA Verified

#5453 [4.x] - [features migration] - Config MP
  microprofile/config/pom.xml
  microprofile/config/src/main/java/module-info.java
Labels: docs, 4.x, OCA Verified

#5454 [4.x] - [features migration] - CORS MP
  microprofile/cors/pom.xml
  microprofile/cors/src/main/java/module-info.java
Labels: docs, 4.x, OCA Verified

#5455 [4.x] - [features migration] - Fault Tolerance MP
  microprofile/fault-tolerance/pom.xml
  microprofile/fault-tolerance/src/main/java/module-info.java
Labels: docs, 4.x, OCA Verified

#5456 [4.x] - [features migration] - GraphQL Server MP
  microprofile/graphql/server/pom.xml
  microprofile/graphql/server/src/main/java/module-info.java
Labels: docs, 4.x, OCA Verified

#5457 [4.x] - [features migration] - gRPC Server MP
  microprofile/grpc/server/pom.xml
  microprofile/grpc/server/src/main/java/module-info.java
Labels: docs, 4.x, OCA Verified

#5458 [4.x] - [features migration] - gRPC Client MP
  microprofile/grpc/client/pom.xml
  microprofile/grpc/client/src/main/java/module-info.java
Labels: docs, 4.x, OCA Verified

#5459 [4.x] - [features migration] - gRPC Metrics MP
  microprofile/grpc/metrics/pom.xml
  microprofile/grpc/metrics/src/main/java/module-info.java
Labels: docs, 4.x, OCA Verified

#5460 [4.x] - [features migration] - Metrics MP
  microprofile/metrics/pom.xml
  microprofile/metrics/src/main/java/module-info.java
Labels: docs, 4.x, OCA Verified

#5461 [4.x] - [features migration] - Health MP
  microprofile/health/pom.xml
  microprofile/health/src/main/java/module-info.java
Labels: docs, 4.x, OCA Verified

#5462 [4.x] - [features migration] - JWT-Auth MP
  microprofile/jwt-auth/pom.xml
  microprofile/jwt-auth/src/main/java/module-info.java
Labels: docs, 4.x, OCA Verified

#5463 [4.x] - [features migration] - Messaging MP
  microprofile/messaging/core/pom.xml
  microprofile/messaging/core/src/main/java/module-info.java
Labels: docs, 4.x, OCA Verified

#5465 [4.x] - [features migration] - Reactive Streams MP
  microprofile/reactive-streams/pom.xml
  microprofile/reactive-streams/src/main/java/module-info.java
Labels: docs, 4.x, OCA Verified

#5466 [4.x] - [features migration] - OpenApi MP
  microprofile/openapi/pom.xml
  microprofile/openapi/src/main/java/module-info.java
Labels: docs, 4.x, OCA Verified

#5467 [4.x] - [features migration] - Security MP
  microprofile/security/pom.xml
  microprofile/security/src/main/java/module-info.java
Labels: docs, 4.x, OCA Verified

#5475 [4.x] - [features migration] - Server MP
  microprofile/server/pom.xml
  microprofile/server/src/main/java/module-info.java
Labels: docs, 4.x, OCA Verified

#5476 [4.x] - [features migration] - Tracing MP
  microprofile/tracing/pom.xml
  microprofile/tracing/src/main/java/module-info.java
Labels: docs, 4.x, OCA Verified

#5492 [4.x] - [features migration] - Micronaut Data, Micronaut CDI, LRA, Scheduling MP
  integrations/micrometer/cdi/pom.xml
  integrations/micrometer/cdi/src/main/java/module-info.java
  integrations/micronaut/data/pom.xml
  integrations/micronaut/data/src/main/java/module-info.java
  integrations/microstream/cdi/pom.xml
  integrations/microstream/cdi/src/main/java/module-info.java
  microprofile/lra/jax-rs/pom.xml
  microprofile/lra/jax-rs/src/main/java/module-info.java
  microprofile/scheduling/pom.xml
  microprofile/scheduling/src/main/java/module-info.java
Labels: docs, 4.x, OCA Verified

#5452 [4.x] - [features migration] - CDI MP
  microprofile/cdi/pom.xml
  microprofile/cdi/src/main/java/module-info.java
Labels: docs, 4.x, OCA Verified

#5477 [4.x] - [features migration] - WebSocket MP
  microprofile/websocket/pom.xml
  microprofile/websocket/src/main/java/module-info.java
Labels: docs, 4.x, OCA Verified

#5446 Fix Guava version to match that required by the grpc-java libraries
  dependencies/pom.xml
  integrations/oci/sdk/cdi/src/main/java/io/helidon/integrations/oci/sdk/cdi/AdpSelectionStrategy.java
Labels: 2.x, OCA Verified

#5486 remove -Ddocker.build=true
  archetypes/quickstart-mp/src/main/resources/Dockerfile.jlink.mustache
  archetypes/quickstart-se/src/main/resources/Dockerfile.jlink.mustache
  examples/integrations/neo4j/neo4j-mp/Dockerfile.jlink
  examples/integrations/neo4j/neo4j-se/Dockerfile.jlink
  examples/quickstarts/helidon-quickstart-mp/Dockerfile.jlink
  examples/quickstarts/helidon-quickstart-se/Dockerfile.jlink
  examples/quickstarts/helidon-standalone-quickstart-mp/Dockerfile.jlink
  examples/quickstarts/helidon-standalone-quickstart-se/Dockerfile.jlink
Labels: 2.x, OCA Verified

#5484 remove -Ddocker.build=true
  archetypes/helidon/src/main/archetype/common/files/Dockerfile.jlink.mustache
  examples/integrations/neo4j/neo4j-mp/Dockerfile.jlink
  examples/integrations/neo4j/neo4j-se/Dockerfile.jlink
  examples/quickstarts/helidon-quickstart-mp/Dockerfile.jlink
  examples/quickstarts/helidon-quickstart-se/Dockerfile.jlink
  examples/quickstarts/helidon-standalone-quickstart-mp/Dockerfile.jlink
  examples/quickstarts/helidon-standalone-quickstart-se/Dockerfile.jlink
Labels: 3.x, OCA Verified

#5479 Remove trailing empty line in copyright comment (part 9)
  lra/coordinator/client/spi/src/main/java/io/helidon/lra/coordinator/client/CoordinatorClient.java
  lra/coordinator/client/spi/src/main/java/io/helidon/lra/coordinator/client/CoordinatorConnectionException.java
  lra/coordinator/client/spi/src/main/java/io/helidon/lra/coordinator/client/Headers.java
  lra/coordinator/client/spi/src/main/java/io/helidon/lra/coordinator/client/Participant.java
  lra/coordinator/client/spi/src/main/java/io/helidon/lra/coordinator/client/PropagatedHeaders.java
  lra/coordinator/client/spi/src/main/java/io/helidon/lra/coordinator/client/package-info.java
  lra/coordinator/client/spi/src/main/java/module-info.java
  lra/coordinator/server/src/main/java/io/helidon/lra/coordinator/CoordinatorService.java
  lra/coordinator/server/src/main/java/io/helidon/lra/coordinator/Link.java
  lra/coordinator/server/src/main/java/io/helidon/lra/coordinator/Lra.java
  lra/coordinator/server/src/main/java/io/helidon/lra/coordinator/LraDatabasePersistentRegistry.java
  lra/coordinator/server/src/main/java/io/helidon/lra/coordinator/LraPersistentRegistry.java
  lra/coordinator/server/src/main/java/io/helidon/lra/coordinator/Main.java
  lra/coordinator/server/src/main/java/io/helidon/lra/coordinator/Participant.java
  lra/coordinator/server/src/main/java/io/helidon/lra/coordinator/package-info.java
  lra/coordinator/server/src/main/java/module-info.java
  openapi/src/main/java/io/helidon/openapi/CustomConstructor.java
  openapi/src/main/java/io/helidon/openapi/ExpandedTypeDescription.java
  openapi/src/main/java/io/helidon/openapi/ImplTypeDescription.java
  openapi/src/main/java/io/helidon/openapi/OpenAPIParser.java
  openapi/src/main/java/io/helidon/openapi/OpenAPISupport.java
  openapi/src/main/java/io/helidon/openapi/SEOpenAPISupport.java
  openapi/src/main/java/io/helidon/openapi/SEOpenAPISupportBuilder.java
  openapi/src/main/java/io/helidon/openapi/Serializer.java
  openapi/src/main/java/io/helidon/openapi/internal/OpenAPIConfigImpl.java
  openapi/src/main/java/io/helidon/openapi/internal/package-info.java
  openapi/src/main/java/io/helidon/openapi/package-info.java
Labels: OCA Verified

#5493 Remove trailing empty line in copyright comment (part 10)
  integrations/micrometer/cdi/src/main/java/io/helidon/integrations/micrometer/cdi/InterceptorCounted.java
  integrations/micrometer/cdi/src/main/java/io/helidon/integrations/micrometer/cdi/InterceptorTimed.java
  integrations/micrometer/cdi/src/main/java/io/helidon/integrations/micrometer/cdi/MeterProducer.java
  integrations/micrometer/cdi/src/main/java/io/helidon/integrations/micrometer/cdi/MeterRegistryProducer.java
  integrations/micrometer/cdi/src/main/java/io/helidon/integrations/micrometer/cdi/MicrometerCdiExtension.java
  integrations/micrometer/cdi/src/main/java/io/helidon/integrations/micrometer/cdi/MicrometerInterceptorBase.java
  integrations/micrometer/cdi/src/main/java/io/helidon/integrations/micrometer/cdi/package-info.java
  integrations/micrometer/cdi/src/main/java/module-info.java
  integrations/micrometer/cdi/src/test/java/io/helidon/integrations/micrometer/cdi/MeteredBean.java
  integrations/micrometer/cdi/src/test/java/io/helidon/integrations/micrometer/cdi/MeteredBeanTest.java
  integrations/micrometer/micrometer/src/main/java/io/helidon/integrations/micrometer/MeterRegistryFactory.java
  integrations/micrometer/micrometer/src/main/java/io/helidon/integrations/micrometer/MicrometerBuiltInRegistrySupport.java
  integrations/micrometer/micrometer/src/main/java/io/helidon/integrations/micrometer/MicrometerPrometheusRegistrySupport.java
  integrations/micrometer/micrometer/src/main/java/io/helidon/integrations/micrometer/MicrometerSupport.java
  integrations/micrometer/micrometer/src/main/java/io/helidon/integrations/micrometer/package-info.java
  integrations/micrometer/micrometer/src/main/java/module-info.java
  integrations/micrometer/micrometer/src/test/java/io/helidon/integrations/micrometer/MicrometerEndpointTests.java
  integrations/micrometer/micrometer/src/test/java/io/helidon/integrations/micrometer/MicrometerSimplePrometheusTest.java
  integrations/micrometer/micrometer/src/test/java/io/helidon/integrations/micrometer/MicrometerSupportBuilderTest.java
  integrations/micrometer/micrometer/src/test/java/io/helidon/integrations/micrometer/MicrometerTestAddingMeters.java
  integrations/micrometer/micrometer/src/test/java/io/helidon/integrations/micrometer/MicrometerTestUtil.java
  integrations/neo4j/health/src/main/java/io/helidon/integrations/neo4j/health/Neo4jHealthCheck.java
  integrations/neo4j/metrics/src/main/java/io/helidon/integrations/neo4j/metrics/Neo4jMetricsCdiExtension.java
  integrations/neo4j/metrics/src/main/java/io/helidon/integrations/neo4j/metrics/Neo4jMetricsSupport.java
Labels: OCA Verified

#5380 Remove trailing empty line in copyright comment (part 8)
  tests/tck/tck-reactive-streams/src/test/java/io/helidon/common/reactive/MultiOnTerminateTckTest.java
  tests/tck/tck-reactive-streams/src/test/java/io/helidon/common/reactive/MultiPeekTckTest.java
  tests/tck/tck-reactive-streams/src/test/java/io/helidon/common/reactive/MultiPeekTwiceTckTest.java
  tests/tck/tck-reactive-streams/src/test/java/io/helidon/common/reactive/MultiRangeLongTckTest.java
  tests/tck/tck-reactive-streams/src/test/java/io/helidon/common/reactive/MultiRangeTckTest.java
  tests/tck/tck-reactive-streams/src/test/java/io/helidon/common/reactive/MultiReduceFullTckTest.java
  tests/tck/tck-reactive-streams/src/test/java/io/helidon/common/reactive/MultiReduceTckTest.java
  tests/tck/tck-reactive-streams/src/test/java/io/helidon/common/reactive/MultiSkipPublisherNoSkipTckTest.java
  tests/tck/tck-reactive-streams/src/test/java/io/helidon/common/reactive/MultiSkipPublisherTckTest.java
  tests/tck/tck-reactive-streams/src/test/java/io/helidon/common/reactive/MultiTakeUntilPublisherTckTest.java
  tests/tck/tck-reactive-streams/src/test/java/io/helidon/common/reactive/MultiTakeWhilePublisherTckTest.java
  tests/tck/tck-reactive-streams/src/test/java/io/helidon/common/reactive/SingleDeferTckTest.java
  tests/tck/tck-reactive-streams/src/test/java/io/helidon/common/reactive/SingleFlatMapIterableTckTest.java
  tests/tck/tck-reactive-streams/src/test/java/io/helidon/common/reactive/SingleFlatMapMultiTckTest.java
  tests/tck/tck-reactive-streams/src/test/java/io/helidon/common/reactive/SingleFlatMapSingleTckTest.java
  tests/tck/tck-reactive-streams/src/test/java/io/helidon/common/reactive/SingleOnCompleteResumeWithSingleCompletedTckTest.java
  tests/tck/tck-reactive-streams/src/test/java/io/helidon/common/reactive/SingleOnCompleteResumeWithSingleTckTest.java
  tests/tck/tck-reactive-streams/src/test/java/io/helidon/common/reactive/SingleOnErrorResumeFailureTckTest.java
  tests/tck/tck-reactive-streams/src/test/java/io/helidon/common/reactive/SingleOnErrorResumeSuccessTckTest.java
  tests/tck/tck-reactive-streams/src/test/java/io/helidon/common/reactive/SingleOnErrorResumeWithSuccessTckTest.java
  tests/tck/tck-reactive-streams/src/test/java/io/helidon/common/reactive/SinglePeekTckTest.java
  tests/tck/tck-reactive-streams/src/test/java/io/helidon/common/reactive/SinglePeekTwiceTckTest.java
  tests/tck/tck-reactive-streams/src/test/java/io/helidon/common/reactive/SingleTakeUntilPublisherTckTest.java
  tests/tck/tck-reactive-streams/src/test/java/io/helidon/common/reactive/TidyTestExecutor.java
Labels: 2.x, OCA Verified

#5497 3.x: Suppress false positive
  etc/dependency-check-suppression.xml
Labels: 3.x, OCA Verified

#5500 [4.x] - [features migration] - DBClient, Health, Metrics, MongoDB, Tracing
  reactive/dbclient/dbclient/pom.xml
  reactive/dbclient/dbclient/src/main/java/module-info.java
  reactive/dbclient/health/pom.xml
  reactive/dbclient/health/src/main/java/module-info.java
  reactive/dbclient/metrics/pom.xml
  reactive/dbclient/metrics/src/main/java/module-info.java
  reactive/dbclient/mongodb/pom.xml
  reactive/dbclient/mongodb/src/main/java/module-info.java
  reactive/dbclient/tracing/pom.xml
  reactive/dbclient/tracing/src/main/java/module-info.java
Labels: docs, 4.x, OCA Verified

#5503 3.x Fix Guava version to match that required by the grpc-java libraries
  dependencies/pom.xml
Labels: 3.x, OCA Verified

#5502 [4.x] - [features migration] - Role, Scope, Time, grpc, Jersey, Webserver
  security/abac/role/pom.xml
  security/abac/role/src/main/java/module-info.java
  security/abac/scope/pom.xml
  security/abac/scope/src/main/java/module-info.java
  security/abac/time/pom.xml
  security/abac/time/src/main/java/module-info.java
  security/integration/grpc/pom.xml
  security/integration/grpc/src/main/java/module-info.java
  security/integration/jersey/pom.xml
  security/integration/jersey/src/main/java/module-info.java
  security/integration/webserver/pom.xml
  security/integration/webserver/src/main/java/module-info.java
Labels: docs, 4.x, OCA Verified

#5511 [4.x] - [features migration] - Security Providers
  security/providers/abac/pom.xml
  security/providers/abac/src/main/java/module-info.java
  security/providers/config-vault/pom.xml
  security/providers/config-vault/src/main/java/module-info.java
  security/providers/google-login/pom.xml
  security/providers/google-login/src/main/java/module-info.java
  security/providers/header/pom.xml
  security/providers/header/src/main/java/module-info.java
  security/providers/http-auth/pom.xml
  security/providers/http-auth/src/main/java/module-info.java
  security/providers/http-sign/pom.xml
  security/providers/http-sign/src/main/java/module-info.java
  security/providers/idcs-mapper/pom.xml
  security/providers/idcs-mapper/src/main/java/module-info.java
  security/providers/jwt/pom.xml
  security/providers/jwt/src/main/java/module-info.java
  security/providers/oidc/pom.xml
  security/providers/oidc/src/main/java/module-info.java
Labels: docs, 4.x, OCA Verified

#5512 [4.x] - [features migration] - Tracing
  tracing/jaeger/pom.xml
  tracing/jaeger/src/main/java/module-info.java
  tracing/jersey-client/pom.xml
  tracing/jersey-client/src/main/java/module-info.java
  tracing/jersey/pom.xml
  tracing/jersey/src/main/java/module-info.java
  tracing/zipkin/pom.xml
  tracing/zipkin/src/main/java/module-info.java
Labels: docs, 4.x, OCA Verified

#5517 [4.x] - [features migration] - Neo4j, WebClient, Static Content
  integrations/neo4j/health/pom.xml
  integrations/neo4j/health/src/main/java/module-info.java
  integrations/neo4j/metrics/pom.xml
  integrations/neo4j/metrics/src/main/java/module-info.java
  integrations/neo4j/neo4j/pom.xml
  integrations/neo4j/neo4j/src/main/java/module-info.java
  logging/log4j/pom.xml
  logging/log4j/src/main/java/module-info.java
  reactive/webclient/metrics/pom.xml
  reactive/webclient/metrics/src/main/java/module-info.java
  reactive/webclient/security/pom.xml
  reactive/webclient/security/src/main/java/module-info.java
  reactive/webclient/tracing/pom.xml
  reactive/webclient/tracing/src/main/java/module-info.java
  reactive/webclient/webclient/pom.xml
  reactive/webclient/webclient/src/main/java/module-info.java
  reactive/webserver/static-content/pom.xml
  reactive/webserver/static-content/src/main/java/module-info.java
Labels: docs, 4.x, OCA Verified

#5506 Remove trailing empty line in copyright comment (part 11)
  common/reactive/src/main/java/io/helidon/common/reactive/MultiReduce.java
  common/reactive/src/main/java/io/helidon/common/reactive/MultiReduceFull.java
  common/reactive/src/main/java/io/helidon/common/reactive/MultiRetry.java
  common/reactive/src/main/java/io/helidon/common/reactive/MultiSkipPublisher.java
  common/reactive/src/main/java/io/helidon/common/reactive/MultiSwitchIfEmpty.java
  common/reactive/src/main/java/io/helidon/common/reactive/MultiTakeUntilPublisher.java
  common/reactive/src/main/java/io/helidon/common/reactive/MultiTakeWhilePublisher.java
  common/reactive/src/main/java/io/helidon/common/reactive/MultiTappedPublisher.java
  common/reactive/src/main/java/io/helidon/common/reactive/MultiTimeout.java
  common/reactive/src/main/java/io/helidon/common/reactive/MultiTimer.java
  common/reactive/src/main/java/io/helidon/common/reactive/NamedOperator.java
  common/reactive/src/main/java/io/helidon/common/reactive/SequentialSubscriber.java
  common/reactive/src/main/java/io/helidon/common/reactive/SingleDefaultIfEmpty.java
  common/reactive/src/main/java/io/helidon/common/reactive/SingleDefer.java
  common/reactive/src/main/java/io/helidon/common/reactive/SingleDeferredDefaultIfEmpty.java
  common/reactive/src/main/java/io/helidon/common/reactive/SingleFlatMapMulti.java
  common/reactive/src/main/java/io/helidon/common/reactive/SingleFlatMapSingle.java
  common/reactive/src/main/java/io/helidon/common/reactive/SingleIfEmptyPublisher.java
  common/reactive/src/main/java/io/helidon/common/reactive/SingleRetry.java
  common/reactive/src/main/java/io/helidon/common/reactive/SingleSwitchIfEmpty.java
  common/reactive/src/main/java/io/helidon/common/reactive/SingleTakeUntilPublisher.java
  common/reactive/src/main/java/io/helidon/common/reactive/SingleTappedPublisher.java
  common/reactive/src/main/java/io/helidon/common/reactive/SingleTimeout.java
  common/reactive/src/main/java/io/helidon/common/reactive/SingleTimer.java
  common/reactive/src/main/java/io/helidon/common/reactive/StreamValidationUtils.java
  common/reactive/src/main/java/io/helidon/common/reactive/SubscriptionArbiter.java
  common/reactive/src/main/java/io/helidon/common/reactive/SubscriptionHelper.java
  common/reactive/src/main/java/io/helidon/common/reactive/TerminatedFuture.java
Labels: OCA Verified

#5508 5379 TempDir support for tests
  common/testing/junit5/src/main/java/io/helidon/common/testing/junit5/TemporaryFolderExt.java
  config/config/src/test/java/io/helidon/config/ConfigSourceMetaConfigTest.java
  config/config/src/test/java/io/helidon/config/DirectoryConfigSourceTest.java
  config/config/src/test/java/io/helidon/config/FileConfigSourceTest.java
  config/config/src/test/java/io/helidon/config/FileOverrideSourceTest.java
  config/config/src/test/java/io/helidon/config/FileSourceHelperTest.java
  config/git/src/test/java/io/helidon/config/git/GitConfigSourceBuilderTest.java
  examples/microprofile/multipart/src/test/java/io/helidon/examples/microprofile/multipart/FileServiceTest.java
  reactive/webserver/static-content/src/test/java/io/helidon/reactive/webserver/staticcontent/FileSystemContentHandlerTest.java
  reactive/webserver/test-support/src/main/java/io/helidon/reactive/webserver/testsupport/TemporaryFolder.java
  reactive/webserver/test-support/src/main/java/io/helidon/reactive/webserver/testsupport/TemporaryFolderExtension.java
Labels: 4.x, OCA Verified

#5531 [4.x] 5510 kafka prod nack 4x
  messaging/connectors/kafka/src/main/java/io/helidon/messaging/connectors/kafka/KafkaSubscriber.java
  tests/integration/kafka/src/test/java/io/helidon/messaging/connectors/kafka/AbstractSampleBean.java
  tests/integration/kafka/src/test/java/io/helidon/messaging/connectors/kafka/KafkaMpTest.java
Labels: 4.x, OCA Verified

#5527 [3.x] Multi.forEachCS
  common/reactive/src/main/java/io/helidon/common/reactive/Multi.java
  common/reactive/src/test/java/io/helidon/common/reactive/MultiTest.java
  docs/includes/reactivestreams/engine.adoc
Labels: reactive, OCA Verified

#5520 [2.x] Jwt scope handling extended over array support
  security/jwt/src/main/java/io/helidon/security/jwt/JwtUtil.java
Labels: OCA Verified

#5521 [3.x] Jwt scope handling extended over array support
  security/jwt/src/main/java/io/helidon/security/jwt/JwtUtil.java
Labels: OCA Verified

#5464 Tyrus integration into Nima
  examples/messaging/pom.xml
  examples/microprofile/pom.xml
  microprofile/pom.xml
  microprofile/websocket/pom.xml
  microprofile/websocket/src/main/java/io/helidon/microprofile/tyrus/HelidonComponentProvider.java
  microprofile/websocket/src/main/java/io/helidon/microprofile/tyrus/TyrusApplication.java
  microprofile/websocket/src/main/java/io/helidon/microprofile/tyrus/TyrusCdiExtension.java
  microprofile/websocket/src/main/java/io/helidon/microprofile/tyrus/TyrusConnection.java
  microprofile/websocket/src/main/java/io/helidon/microprofile/tyrus/TyrusRoute.java
  microprofile/websocket/src/main/java/io/helidon/microprofile/tyrus/TyrusRouting.java
  microprofile/websocket/src/main/java/io/helidon/microprofile/tyrus/TyrusUpgradeProvider.java
  microprofile/websocket/src/main/java/module-info.java
  microprofile/websocket/src/test/java/io/helidon/microprofile/tyrus/EchoClient.java
  microprofile/websocket/src/test/java/io/helidon/microprofile/tyrus/EchoEndpoint.java
  microprofile/websocket/src/test/java/io/helidon/microprofile/tyrus/EchoEndpointBaseTest.java
  microprofile/websocket/src/test/java/io/helidon/microprofile/tyrus/EchoEndpointProg.java
  microprofile/websocket/src/test/java/io/helidon/microprofile/tyrus/EchoEndpointProgTest.java
  microprofile/websocket/src/test/java/io/helidon/microprofile/tyrus/EchoEndpointRestTest.java
  microprofile/websocket/src/test/java/io/helidon/microprofile/tyrus/EchoEndpointTest.java
  microprofile/websocket/src/test/java/io/helidon/microprofile/tyrus/EchoListener.java
  microprofile/websocket/src/test/java/io/helidon/microprofile/tyrus/ExtensionEndpointTest.java
  microprofile/websocket/src/test/java/io/helidon/microprofile/tyrus/WebSocketBaseTest.java
  microprofile/websocket/src/test/java/io/helidon/microprofile/tyrus/WebSocketEndpointTest.java
  nima/webserver/webserver/src/main/java/io/helidon/nima/webserver/http1/Http1ConnectionProvider.java
  nima/websocket/webserver/src/main/java/io/helidon/nima/websocket/webserver/WsUpgradeProvider.java
Labels: websocket, 4.x, OCA Verified

#5526 [4.x] Bump-up reactive messaging/ops to 3.0
  dependencies/pom.xml
Labels: dependencies, 4.x, OCA Verified

#5532 [4.x] Multi.forEachCS
  common/reactive/src/main/java/io/helidon/common/reactive/Multi.java
  common/reactive/src/test/java/io/helidon/common/reactive/MultiTest.java
  docs/includes/reactivestreams/engine.adoc
Labels: backport, OCA Verified

#5542 [4.x] - Fix Intermittent TestJBatchEndpoint.runJob
  examples/jbatch/src/test/java/io/helidon/examples/jbatch/TestJBatchEndpoint.java
Labels: testing, 4.x, OCA Verified, jbatch

#5538 Remove trailing empty line in copyright comment (part 13)
  service-common/rest-cdi/src/main/java/io/helidon/servicecommon/restcdi/HelidonInterceptor.java
  service-common/rest-cdi/src/main/java/io/helidon/servicecommon/restcdi/HelidonRestCdiExtension.java
  service-common/rest-cdi/src/main/java/io/helidon/servicecommon/restcdi/InterceptionRunner.java
  service-common/rest-cdi/src/main/java/io/helidon/servicecommon/restcdi/InterceptionRunnerImpl.java
  service-common/rest-cdi/src/main/java/io/helidon/servicecommon/restcdi/package-info.java
  service-common/rest-cdi/src/main/java/module-info.java
  service-common/rest/src/main/java/io/helidon/servicecommon/rest/HelidonRestServiceSupport.java
  service-common/rest/src/main/java/io/helidon/servicecommon/rest/package-info.java
  service-common/rest/src/main/java/module-info.java
  tests/integration/mp-bean-validation/src/test/java/io/helidon/tests/integration/bean/validation/TestValidationEndpoint.java
  tests/integration/native-image/se-1/src/main/java/io/helidon/tests/integration/nativeimage/se1/Animal.java
  tests/integration/native-image/se-1/src/main/java/io/helidon/tests/integration/nativeimage/se1/MockZipkinService.java
  tests/integration/native-image/se-1/src/main/java/io/helidon/tests/integration/nativeimage/se1/WebClientService.java
  tests/integration/native-image/se-1/src/main/java/io/helidon/tests/integration/nativeimage/se1/WebSocketEndpoint.java
  tests/integration/tools/client/src/main/java/io/helidon/tests/integration/tools/client/HelidonProcessRunner.java
  webserver/webserver/src/main/java/io/helidon/webserver/InboundHttp2ToHttpAdapterWrapper.java
  webserver/webserver/src/main/java/io/helidon/webserver/NettyChannel.java
  webserver/webserver/src/test/java/io/helidon/webserver/CacheHeadersTest.java
  webserver/webserver/src/test/java/io/helidon/webserver/FilterTest.java
  webserver/webserver/src/test/java/io/helidon/webserver/Http2Test.java
  webserver/webserver/src/test/java/io/helidon/webserver/KeepAliveTest.java
  webserver/webserver/src/test/java/io/helidon/webserver/OrderOfWritesTest.java
  webserver/webserver/src/test/java/io/helidon/webserver/PrematureConnectionCutTest.java
  webserver/webserver/src/test/java/io/helidon/webserver/ReqEntityAnalyzedTest.java
  webserver/webserver/src/test/java/io/helidon/webserver/TestNettyRejectRequest.java
Labels: OCA Verified

#5540 Use Hamcrest assertions instead of JUnit in integrations/db/pgsql (#1749)
  integrations/db/pgsql/src/test/java/io/helidon/integrations/db/pgsql/TestBaseDataSourceSubstitution.java
Labels: OCA Verified

#5505 5377 custom exception for CharBuffer
  reactive/media/common/src/main/java/io/helidon/reactive/media/common/CharBuffer.java
  reactive/media/common/src/main/java/io/helidon/reactive/media/common/OutOfCapacityException.java
Labels: 4.x, OCA Verified

#5544 Fix incorrect tags comparison when trying to match metric IDs
  metrics/api/src/main/java/io/helidon/metrics/api/MetricStore.java
  metrics/api/src/test/java/io/helidon/metrics/api/MetricStoreTests.java
Labels: OCA Verified

#5525 [3.x] Bump-up reactive messaging/ops to 3.0
  dependencies/pom.xml
Labels: dependencies, 3.x, OCA Verified

#5550 [4.x] Fix incorrect tags comparison when trying to match metric IDs
  metrics/api/src/main/java/io/helidon/metrics/api/MetricStore.java
  metrics/api/src/test/java/io/helidon/metrics/api/MetricStoreTests.java
Labels: OCA Verified

#5562 Updated bulkhead test to properly wait until Task 1 is enqueued
  nima/fault-tolerance/src/main/java/io/helidon/nima/faulttolerance/Async.java
  nima/fault-tolerance/src/main/java/io/helidon/nima/faulttolerance/AsyncImpl.java
  nima/fault-tolerance/src/test/java/io/helidon/nima/faulttolerance/BulkheadTest.java
Labels: testing, 4.x, OCA Verified

#5555 [3.x] LRA false warning
  microprofile/lra/jax-rs/src/main/java/io/helidon/microprofile/lra/InspectionService.java
Labels: lra, OCA Verified

#5556 [4.x] LRA false warning
  microprofile/lra/jax-rs/src/main/java/io/helidon/microprofile/lra/InspectionService.java
Labels: lra, OCA Verified

#5561 [4.x] Upgrade PostgreSQL JDBC driver dependency to 42.4.3
  dependencies/pom.xml
Labels: dependencies, OCA Verified

#5560 [3.x] Upgrade PostgreSQL JDBC driver dependency to 42.4.3
  dependencies/pom.xml
Labels: dependencies, OCA Verified

#5563 [2.x] Upgrade PostgreSQL JDBC driver dependency to 42.4.3
  dependencies/pom.xml
Labels: dependencies, OCA Verified

#5551 [4.x] - Named port Nima ServerTest and RoutingTest
  nima/testing/junit5/webserver/src/main/java/io/helidon/nima/testing/junit5/webserver/HelidonRoutingJunitExtension.java
  nima/testing/junit5/webserver/src/main/java/io/helidon/nima/testing/junit5/webserver/HelidonServerJunitExtension.java
  nima/testing/junit5/webserver/src/main/java/io/helidon/nima/testing/junit5/webserver/Socket.java
  nima/testing/junit5/webserver/src/test/java/io/helidon/nima/testing/junit5/webserver/TestRoutingTest.java
  nima/testing/junit5/webserver/src/test/java/io/helidon/nima/testing/junit5/webserver/TestServerTest.java
Labels: testing, 4.x, Níma, OCA Verified

#5557 [3.x] - Fix Intermittent TestJBatchEndpoint.runJob
  examples/jbatch/pom.xml
  examples/jbatch/src/test/java/io/helidon/examples/jbatch/TestJBatchEndpoint.java
Labels: 3.x, testing, OCA Verified, jbatch

#5567 [4.x] - Fix Intermittent TestJBatchEndpoint.runJob
  examples/jbatch/pom.xml
  examples/jbatch/src/test/java/io/helidon/examples/jbatch/TestJBatchEndpoint.java
Labels: testing, 4.x, OCA Verified, jbatch

#5558 [2.x] - Fix Intermittent TestJBatchEndpoint.runJob
  examples/jbatch/pom.xml
  examples/jbatch/src/test/java/io/helidon/examples/jbatch/TestJBatchEndpoint.java
Labels: 2.x, testing, OCA Verified, jbatch

#5523 [2.x] Message body operator matching with parameters
  common/http/src/main/java/io/helidon/common/http/MediaType.java
  media/common/src/main/java/io/helidon/media/common/FormParamsBodyReader.java
  media/common/src/main/java/io/helidon/media/common/FormParamsBodyWriter.java
  media/jackson/src/main/java/io/helidon/media/jackson/JacksonEsBodyStreamWriter.java
  media/jackson/src/main/java/io/helidon/media/jackson/JacksonNdBodyStreamWriter.java
  media/jsonb/src/main/java/io/helidon/media/jsonb/JsonbEsBodyStreamWriter.java
  media/jsonb/src/main/java/io/helidon/media/jsonb/JsonbNdBodyStreamWriter.java
  media/jsonp/src/main/java/io/helidon/media/jsonp/JsonpEsBodyStreamWriter.java
  media/jsonp/src/main/java/io/helidon/media/jsonp/JsonpNdBodyStreamWriter.java
  media/multipart/src/main/java/io/helidon/media/multipart/MultiPartBodyWriter.java
Labels: OCA Verified

#5529 Remove trailing empty line in copyright comment (part 12)
  common/reactive/src/test/java/io/helidon/common/reactive/AwaitTest.java
  common/reactive/src/test/java/io/helidon/common/reactive/ByteChannelSubscriberTest.java
  common/reactive/src/test/java/io/helidon/common/reactive/IgnoreElementsTest.java
  common/reactive/src/test/java/io/helidon/common/reactive/MultiComposeTest.java
  common/reactive/src/test/java/io/helidon/common/reactive/MultiDefaultIfEmptyTest.java
  common/reactive/src/test/java/io/helidon/common/reactive/MultiDeferTest.java
  common/reactive/src/test/java/io/helidon/common/reactive/MultiDropWhileTest.java
  common/reactive/src/test/java/io/helidon/common/reactive/MultiFilterPublisherTest.java
  common/reactive/src/test/java/io/helidon/common/reactive/MultiFirstPublisherTest.java
  common/reactive/src/test/java/io/helidon/common/reactive/MultiFlatMapIterableTest.java
  common/reactive/src/test/java/io/helidon/common/reactive/MultiFlatMapOptionalTest.java
  common/reactive/src/test/java/io/helidon/common/reactive/MultiFlatMapPublisherTest.java
  common/reactive/src/test/java/io/helidon/common/reactive/MultiFromArrayTest.java
  common/reactive/src/test/java/io/helidon/common/reactive/MultiFromCompletionStageTest.java
  common/reactive/src/test/java/io/helidon/common/reactive/MultiFromIterableTest.java
  common/reactive/src/test/java/io/helidon/common/reactive/MultiFromNotTrustedInputStreamTest.java
  common/reactive/src/test/java/io/helidon/common/reactive/MultiFromStreamTest.java
  common/reactive/src/test/java/io/helidon/common/reactive/MultiIfEmptyTest.java
  common/reactive/src/test/java/io/helidon/common/reactive/MultiIntervalTest.java
  common/reactive/src/test/java/io/helidon/common/reactive/MultiObserveOnTest.java
  common/reactive/src/test/java/io/helidon/common/reactive/MultiOnCompleteResumeWithTest.java
  common/reactive/src/test/java/io/helidon/common/reactive/MultiOnErrorResumeTest.java
  common/reactive/src/test/java/io/helidon/common/reactive/MultiOnErrorResumeWithTest.java
  common/reactive/src/test/java/io/helidon/common/reactive/MultiRangeLongTest.java
  common/reactive/src/test/java/io/helidon/common/reactive/MultiRangeTest.java
  common/reactive/src/test/java/io/helidon/common/reactive/MultiReduceFullTest.java
  common/reactive/src/test/java/io/helidon/common/reactive/MultiReduceTest.java
  common/reactive/src/test/java/io/helidon/common/reactive/MultiRetryTest.java
  common/reactive/src/test/java/io/helidon/common/reactive/MultiSkipPublisherTest.java
  common/reactive/src/test/java/io/helidon/common/reactive/MultiSwitchIfEmptyTest.java
  common/reactive/src/test/java/io/helidon/common/reactive/MultiTakeUntilPublisherTest.java
  common/reactive/src/test/java/io/helidon/common/reactive/MultiTakeWhilePublisherTest.java
  common/reactive/src/test/java/io/helidon/common/reactive/MultiTappedPublisherTest.java
  common/reactive/src/test/java/io/helidon/common/reactive/MultiTimeoutTest.java
  common/reactive/src/test/java/io/helidon/common/reactive/MultiToTest.java
  common/reactive/src/test/java/io/helidon/common/reactive/SequentialSubscriberTest.java
Labels: OCA Verified

#5539 Remove experimental flag from Vault docs (#5431)
  docs/mp/vault/01_vault.adoc
  docs/se/vault/01_vault.adoc
Labels: OCA Verified
