Repository helidon-io/helidon, pull requests merged in 2022-10, with the labels that each got.

#5037 2.x upgrade hibernate validator to 6.2.5
  dependencies/pom.xml
Labels: 2.x, dependencies

#5026 Vault tests
  .github/workflows/validate.yml
  etc/scripts/github-compile.sh
  etc/scripts/test-integ-vault.sh
  etc/scripts/test-packaging-jar.sh
  etc/scripts/test-packaging-jlink.sh
  reactive/webclient/webclient/src/main/java/io/helidon/reactive/webclient/WebClient.java
  tests/integration/native-image/mp-1/src/main/java/io/helidon/tests/integration/nativeimage/mp1/Mp1Main.java
  tests/integration/native-image/mp-1/test-runtime.sh
  tests/integration/native-image/mp-3/test-runtime.sh
  tests/integration/pom.xml
  tests/integration/vault/mp/README.md
  tests/integration/vault/mp/pom.xml
  tests/integration/vault/mp/src/main/resources/META-INF/beans.xml
  tests/integration/vault/mp/src/test/java/io/helidon/tests/integration/vault/mp/TestDbSecrets.java
  tests/integration/vault/mp/src/test/java/io/helidon/tests/integration/vault/mp/TestKubernetesAuth.java
  tests/integration/vault/mp/src/test/resources/vault-application.yaml
  tests/integration/vault/pom.xml
  tests/integration/vault/se/README.md
  tests/integration/vault/se/pom.xml
  tests/integration/vault/se/src/main/java/io/helidon/examples/integrations/vault/hcp/reactive/AppRoleExample.java
  tests/integration/vault/se/src/main/java/io/helidon/examples/integrations/vault/hcp/reactive/CubbyholeService.java
  tests/integration/vault/se/src/main/java/io/helidon/examples/integrations/vault/hcp/reactive/K8sExample.java
  tests/integration/vault/se/src/main/java/io/helidon/examples/integrations/vault/hcp/reactive/Kv1Service.java
  tests/integration/vault/se/src/main/java/io/helidon/examples/integrations/vault/hcp/reactive/Kv2Service.java
  tests/integration/vault/se/src/main/java/io/helidon/examples/integrations/vault/hcp/reactive/ReactiveVaultMain.java
  tests/integration/vault/se/src/main/java/io/helidon/examples/integrations/vault/hcp/reactive/TransitService.java
  tests/integration/vault/se/src/main/java/io/helidon/examples/integrations/vault/hcp/reactive/VaultPolicy.java
  tests/integration/vault/se/src/main/resources/application.yaml
  tests/integration/vault/src/test/java/io/helidon/examples/integrations/vault/hcp/reactive/VaultPolicy.java
  tests/integration/vault/src/test/java/io/helidon/examples/integrations/vault/hcp/reactive/VaultTest.java
  tests/integration/vault/src/test/resources/logging.properties
Labels: dependencies, 4.x

#5046 4.x: Upgrade reactive streams to 1.0.4
  dependencies/pom.xml
Labels: dependencies, 4.x

#5045 3.x: Upgrade reactive-streams to 1.0.4
  dependencies/pom.xml
Labels: dependencies, 3.x

#5044 2.x Upgrade reactive-sreams to 1.0.4
  dependencies/pom.xml
Labels: 2.x, dependencies

#5051 4.x [Doc] Preamble fix
  docs/se/aot.adoc
Labels: docs

#5019 WebClient dependency in generated Helidon SE Quickstart should be in test scope
  archetypes/helidon/src/main/archetype/se/common/common-se.xml
Labels: archetypes

#5033 Updated intermittently failing CircuitBreakerTest
  nima/fault-tolerance/src/main/java/io/helidon/nima/faulttolerance/CircuitBreakerImpl.java
  nima/fault-tolerance/src/test/java/io/helidon/nima/faulttolerance/CircuitBreakerTest.java
Labels: fault-tolerance, 4.x

#4959 fix for issue in handling ConfigProperties using List
  config/config-mp/src/test/java/io/helidon/config/mp/MpConfigTest.java
  microprofile/config/pom.xml
  microprofile/config/src/main/java/io/helidon/microprofile/config/FieldSetter.java
  microprofile/config/src/test/java/io/helidon/microprofile/config/ConfigBeanDescriptorTest.java
  microprofile/config/src/test/java/io/helidon/microprofile/config/EnvironmentVariableTest.java
  microprofile/config/src/test/java/io/helidon/microprofile/config/testsubjects/TestConfiguredBean.java
Labels: MP, config

#5054 Ported Access Log documentation to 4.x
  docs/includes/server/access-log-config-common.adoc
  docs/mp/server.adoc
  docs/se/webserver.adoc
Labels: docs, 4.x

#4724 Watermarked response backpressure 3x
  docs/config/io_helidon_webserver_WebServer.adoc
  microprofile/server/src/test/java/io/helidon/microprofile/server/StreamingOutputLeakTest.java
  webserver/test-support/src/main/java/io/helidon/webserver/testsupport/TestClient.java
  webserver/webserver/pom.xml
  webserver/webserver/src/main/java/io/helidon/webserver/BackpressureStrategy.java
  webserver/webserver/src/main/java/io/helidon/webserver/BareResponse.java
  webserver/webserver/src/main/java/io/helidon/webserver/BareResponseImpl.java
  webserver/webserver/src/main/java/io/helidon/webserver/ForwardingHandler.java
  webserver/webserver/src/main/java/io/helidon/webserver/HttpInitializer.java
  webserver/webserver/src/main/java/io/helidon/webserver/Response.java
  webserver/webserver/src/main/java/io/helidon/webserver/ServerBasicConfig.java
  webserver/webserver/src/main/java/io/helidon/webserver/ServerConfiguration.java
  webserver/webserver/src/main/java/io/helidon/webserver/ServerResponseSubscription.java
  webserver/webserver/src/main/java/io/helidon/webserver/SocketConfiguration.java
  webserver/webserver/src/main/java/io/helidon/webserver/WebServer.java
  webserver/webserver/src/test/java/io/helidon/webserver/BackpressureTest.java
  webserver/webserver/src/test/java/io/helidon/webserver/BareResponseSubscriberTckTest.java
  webserver/webserver/src/test/java/io/helidon/webserver/ResponseTest.java
  webserver/webserver/src/test/java/io/helidon/webserver/WaterMarkedBackpressureIT.java
Labels: 3.x

#4750 Upgrades OCI to 2.40.0
  dependencies/pom.xml
Labels: P4, dependencies, 3.x, OCI

#5034 Sec provider 4810
  docs/mp/security/02_providers.adoc
  docs/shared/security/providers/http-basic-auth.adoc
  docs/shared/security/providers/http-digest-auth.adoc
  docs/shared/security/providers/http-signatures.adoc
  docs/shared/security/providers/oidc.adoc
Labels: docs

#3597 MultiFromBlockingInputStream RC fix 3x
  common/reactive/src/main/java/io/helidon/common/reactive/MultiFromBlockingInputStream.java
  tests/tck/tck-reactive-streams/src/test/java/io/helidon/common/reactive/MultiFromNotTrustedInputStreamTckTest.java
  tests/tck/tck-reactive-streams/src/test/java/io/helidon/common/reactive/MultiFromTrustedInputStreamTckTest.java
Labels: reactive

#4827 Upgrades OCI to 2.45.0 on helidon-3.x
  dependencies/pom.xml
Labels: P3, 3.x, OCI

#4772 [2.x] Issue #4719 - Helidon DBClient does not trigger an Exception when no sane DB connection can be obtained
  dbclient/jdbc/src/main/java/io/helidon/dbclient/jdbc/JdbcStatementDml.java
Labels: bug, 2.x, DB client, backport

#5065 2.x: Update third party attributions
  THIRD_PARTY_LICENSES.txt
  etc/HELIDON_THIRD_PARTY_LICENSES.xml
Labels: 2.x

#5059 Register a low-priority exception mapper to log internal errors
  webserver/jersey/src/main/java/io/helidon/webserver/jersey/JerseySupport.java
  webserver/jersey/src/main/java/module-info.java
  webserver/jersey/src/test/java/io/helidon/webserver/jersey/JerseySupportTest.java
Labels: webserver, jax-rs, 2.x

#5027 Issue 4740 - JPA integration tests should run on every build
  tests/integration/jpa/appl/pom.xml
  tests/integration/jpa/appl/src/main/java/io/helidon/tests/integration/jpa/appl/JdbcApiIT.java
  tests/integration/jpa/appl/src/main/java/io/helidon/tests/integration/jpa/appl/UpdateIT.java
  tests/integration/jpa/appl/src/main/resources/hibernate.properties
  tests/integration/jpa/appl/src/test/java/io/helidon/tests/integration/jpa/appl/test/LifeCycleExtension.java
  tests/integration/jpa/model/src/main/java/io/helidon/tests/integration/jpa/model/Pokemon.java
  tests/integration/jpa/model/src/main/java/io/helidon/tests/integration/jpa/model/Settlement.java
  tests/integration/jpa/model/src/main/java/io/helidon/tests/integration/jpa/model/Stadium.java
  tests/integration/jpa/model/src/main/java/io/helidon/tests/integration/jpa/model/Trainer.java
  tests/integration/jpa/simple/pom.xml
  tests/integration/jpa/simple/src/test/java/io/helidon/tests/integration/jpa/simple/init/InitIT.java
  tests/integration/jpa/simple/src/test/java/io/helidon/tests/integration/jpa/simple/test/DeleteIT.java
  tests/integration/jpa/simple/src/test/java/io/helidon/tests/integration/jpa/simple/test/InsertIT.java
  tests/integration/jpa/simple/src/test/java/io/helidon/tests/integration/jpa/simple/test/QueryIT.java
  tests/integration/jpa/simple/src/test/java/io/helidon/tests/integration/jpa/simple/test/UpdateIT.java
  tests/integration/pom.xml
Labels: jpa/jta, 3.x, testing, integration

#5073 [3.x] Register a low-priority exception mapper to log internal errors
  webserver/jersey/src/main/java/io/helidon/webserver/jersey/JerseySupport.java
  webserver/jersey/src/main/java/module-info.java
  webserver/jersey/src/test/java/io/helidon/webserver/jersey/JerseySupportTest.java
Labels: webserver, jax-rs, 3.x

#5052 Ported TestInstance.Lifecycle.PER_CLASS fix to 4.x
  microprofile/tests/junit5/src/main/java/io/helidon/microprofile/tests/junit5/HelidonJunitExtension.java
Labels: bug, P3, testing

#5018 Default header size increased to 16K Helidon Server and docs - Helidon 2.x
  docs/se/webserver/02_configuration.adoc
  webserver/webserver/src/main/java/io/helidon/webserver/SocketConfiguration.java
  webserver/webserver/src/test/java/io/helidon/webserver/TestHttpParseFineTuning.java
  webserver/webserver/src/test/java/io/helidon/webserver/TestHttpParsingDefaults.java
Labels: 2.x, server

#5053 Ported TestInstance.Lifecycle.PER_CLASS fix to 2.x
  microprofile/tests/junit5/src/main/java/io/helidon/microprofile/tests/junit5/HelidonJunitExtension.java
Labels: bug, 2.x, testing

#5082 [4.x] Register a low-priority exception mapper to log internal errors
  reactive/webserver/jersey/src/main/java/io/helidon/reactive/webserver/jersey/JerseySupport.java
  reactive/webserver/jersey/src/main/java/module-info.java
  reactive/webserver/jersey/src/test/java/io/helidon/reactive/webserver/jersey/JerseySupportTest.java
Labels: webserver, jax-rs, 4.x

#5099 2.x: Upgrade build-tools to 2.3.6
  applications/pom.xml
  examples/quickstarts/helidon-standalone-quickstart-mp/pom.xml
  examples/quickstarts/helidon-standalone-quickstart-se/pom.xml
  pom.xml
Labels: 2.x

#5100 3.x: Upgrade Hibernate to 6.1.4.Final, EclipseLink to 3.0.3
  applications/mp/pom.xml
  dependencies/pom.xml
  examples/integrations/cdi/pokemons/pom.xml
  pom.xml
Labels: jpa/jta, dependencies, 3.x

#5101 4.x: Upgrade EclipseLink to 3.0.3 and Hibernate to 6.1.4.Final
  applications/mp/pom.xml
  dependencies/pom.xml
  examples/integrations/cdi/pokemons/pom.xml
  pom.xml
Labels: jpa/jta, dependencies, 4.x

#5106 Use lazy values to initialized HealthSupport FT handlers
  fault-tolerance/src/main/java/io/helidon/faulttolerance/FaultTolerance.java
  health/health/src/main/java/io/helidon/health/HealthSupport.java
  health/health/src/test/java/io/helidon/health/HealthSupportTest.java
Labels: health, fault-tolerance, 2.x

#5118 Set default write queue length to 0 and display version on startup.
  nima/tests/integration/webserver/access-log/src/test/java/io/helidon/nima/tests/integration/server/accesslog/AccessLogTest.java
  nima/webserver/webserver/src/main/java/io/helidon/nima/webserver/ListenerConfiguration.java
  nima/webserver/webserver/src/main/java/io/helidon/nima/webserver/LoomServer.java
Labels: 4.x

#5001 Tracing config updates in archetype
  archetypes/helidon/src/main/archetype/common/files/README.jaeger.md
  archetypes/helidon/src/main/archetype/common/files/README.zipkin.md
  archetypes/helidon/src/main/archetype/common/observability.xml
  archetypes/helidon/src/main/archetype/mp/common/files/src/main/resources/META-INF/microprofile-config.properties.mustache
  archetypes/helidon/src/main/archetype/mp/custom/custom-mp.xml
  archetypes/helidon/src/main/archetype/mp/custom/observability.xml
  archetypes/helidon/src/main/archetype/se/common/files/src/main/resources/application.yaml.mustache
  archetypes/helidon/src/main/archetype/se/custom/custom-se.xml
  archetypes/helidon/src/main/archetype/se/custom/database.xml
  archetypes/helidon/src/main/archetype/se/custom/observability.xml
Labels: tracing, archetypes

#5132 2.x: Upgrade protobuf-java.
  dependencies/pom.xml
Labels: 2.x, dependencies

#5133 3.x: Upgrade protobuf-java
  dependencies/pom.xml
Labels: dependencies, 3.x

#5134 4.x: Upgrade protobuf-java
  dependencies/pom.xml
Labels: dependencies, 4.x

#5112 [3.x] Do not use retry to fix the test; stats are approximate; just check for existence, not values
  metrics/metrics/pom.xml
  metrics/metrics/src/test/java/io/helidon/metrics/TestServer.java
Labels: 3.x

#5137 Tracing config updates in archetype
  archetypes/helidon/src/main/archetype/common/files/README.jaeger.md
  archetypes/helidon/src/main/archetype/common/files/README.zipkin.md
  archetypes/helidon/src/main/archetype/common/observability.xml
  archetypes/helidon/src/main/archetype/mp/common/files/src/main/resources/META-INF/microprofile-config.properties.mustache
  archetypes/helidon/src/main/archetype/mp/custom/custom-mp.xml
  archetypes/helidon/src/main/archetype/mp/custom/observability.xml
  archetypes/helidon/src/main/archetype/se/common/files/src/main/resources/application.yaml.mustache
  archetypes/helidon/src/main/archetype/se/custom/custom-se.xml
  archetypes/helidon/src/main/archetype/se/custom/database.xml
  archetypes/helidon/src/main/archetype/se/custom/observability.xml
Labels: tracing, 3.x, archetypes

#5146 Use lazy values to initialized HealthSupport FT handlers
  fault-tolerance/src/main/java/io/helidon/faulttolerance/FaultTolerance.java
  health/health/pom.xml
  health/health/src/main/java/io/helidon/health/HealthSupport.java
  health/health/src/test/java/io/helidon/health/HealthSupportInitTest.java
  health/health/src/test/java/io/helidon/health/HealthSupportTest.java
Labels: health, fault-tolerance, 3.x

#5147 Use lazy values to initialized HealthSupport FT handlers
  reactive/fault-tolerance/src/main/java/io/helidon/reactive/faulttolerance/FaultTolerance.java
  reactive/health/pom.xml
  reactive/health/src/main/java/io/helidon/reactive/health/HealthSupport.java
  reactive/health/src/test/java/io/helidon/reactive/health/HealthSupportInitTest.java
Labels: health, fault-tolerance, 4.x

#5155 [4.x] Close client after each test to avoid intermittent failures on MacOS
  reactive/webserver/webserver/src/test/java/io/helidon/reactive/webserver/XssServerTest.java
Labels: webserver, testing, 4.x

#5158 3.x: Do not generate CDS archive when using Dockerfile.jlink
  archetypes/helidon/src/main/archetype/common/files/Dockerfile.jlink.mustache
  examples/integrations/neo4j/neo4j-mp/Dockerfile.jlink
  examples/integrations/neo4j/neo4j-se/Dockerfile.jlink
  examples/quickstarts/helidon-quickstart-mp/Dockerfile.jlink
  examples/quickstarts/helidon-quickstart-se/Dockerfile.jlink
  examples/quickstarts/helidon-standalone-quickstart-mp/Dockerfile.jlink
  examples/quickstarts/helidon-standalone-quickstart-se/Dockerfile.jlink
Labels: 3.x

#5161 3.x Update CHANGELOG for 3.0.1 and 3.0.2
  CHANGELOG.md
Labels: 3.x

#5164 Make Github pipeline more robust by increasing HTTP ttl and adding a retry
  .github/workflows/validate.yml
  etc/scripts/includes/pipeline-env.sh
Labels: build, 4.x

#5141 Introduce Helidon Pico
  .gitignore
  bom/pom.xml
  pico/api/pom.xml
  pico/api/src/main/java/io/helidon/pico/api/Contract.java
  pico/api/src/main/java/io/helidon/pico/api/ExternalContracts.java
  pico/api/src/main/java/io/helidon/pico/api/RunLevel.java
  pico/api/src/main/java/io/helidon/pico/api/package-info.java
  pico/api/src/main/java/module-info.java
  pico/pom.xml
  pico/types/pom.xml
  pico/types/src/main/java/io/helidon/pico/types/AnnotationAndValue.java
  pico/types/src/main/java/io/helidon/pico/types/TypeName.java
  pico/types/src/main/java/io/helidon/pico/types/package-info.java
  pico/types/src/main/java/module-info.java
  pom.xml
Labels: 4.x, pico

#5175 3.x: Manage protobuf using BOM
  dependencies/pom.xml
Labels: dependencies, 3.x

#5177 2.x: Manage protobuf version using BOM
  dependencies/pom.xml
Labels: 2.x, dependencies

#5178 4.x: Manage protobuf version using BOM
  dependencies/pom.xml
Labels: dependencies, 4.x

#5203 3.x: Suppress false positive on helidon-webserver-access-log
  etc/dependency-check-suppression.xml
Labels: 3.x

#5207 Make JSON-B a default option for Helidon MP projects
  archetypes/helidon/src/main/archetype/common/media.xml
Labels: archetypes, 4.x

#5208 Make JSON-B a default option for Helidon MP projects (backport)
  archetypes/helidon/src/main/archetype/common/media.xml
Labels: 3.x, archetypes

#5214 4.x: various fixes for validate workflow
  .github/workflows/validate.yml
  pom.xml
Labels: build, 4.x

#5211 4.x: Update CHANGELOG after ALPHA1 and ALPHA2 releases
  CHANGELOG.md
Labels: 4.x

#5217 Use Hamcrest assertions instead of JUnit in examples/quickstarts/helidon-standalone-quickstart-se (#1749)
  examples/quickstarts/helidon-standalone-quickstart-se/pom.xml
  examples/quickstarts/helidon-standalone-quickstart-se/src/test/java/io/helidon/examples/quickstart/se/MainTest.java
Labels: OCA Verified

#5218 Use Hamcrest assertions instead of JUnit in examples/quickstarts/helidon-standalone-quickstart-se - backport 2.x (#1749)
  examples/quickstarts/helidon-standalone-quickstart-se/pom.xml
  examples/quickstarts/helidon-standalone-quickstart-se/src/test/java/io/helidon/examples/quickstart/se/MainTest.java
Labels: OCA Verified

#5226 Use Hamcrest assertions instead of JUnit in tests/apps/bookstore/bookstore-se - backport 2.x (#1749)
  tests/apps/bookstore/bookstore-se/pom.xml
  tests/apps/bookstore/bookstore-se/src/test/java/io/helidon/tests/apps/bookstore/se/Http2SslTest.java
  tests/apps/bookstore/bookstore-se/src/test/java/io/helidon/tests/apps/bookstore/se/MainTest.java
  tests/apps/bookstore/bookstore-se/src/test/java/io/helidon/tests/apps/bookstore/se/SslTest.java
Labels: OCA Verified

#5222 Use Hamcrest assertions instead of JUnit in tests/apps/bookstore/bookstore-se (#1749)
  tests/apps/bookstore/bookstore-se/pom.xml
  tests/apps/bookstore/bookstore-se/src/test/java/io/helidon/tests/apps/bookstore/se/Http2SslTest.java
  tests/apps/bookstore/bookstore-se/src/test/java/io/helidon/tests/apps/bookstore/se/MainTest.java
  tests/apps/bookstore/bookstore-se/src/test/java/io/helidon/tests/apps/bookstore/se/SslTest.java
Labels: OCA Verified

#5188 (3.x) Document config.require-encryption
  docs/includes/security/providers/http-basic-auth.adoc
  docs/includes/security/providers/http-digest-auth.adoc
  docs/includes/security/providers/http-signatures.adoc
  docs/includes/security/providers/oidc.adoc
  docs/mp/security/providers.adoc
Labels: OCA Verified

#5200 4.x: Support for optional entity in Níma.
  nima/tests/integration/webserver/webserver/src/test/java/io/helidon/nima/tests/integration/server/GetTest.java
  nima/webserver/webserver/src/main/java/io/helidon/nima/webserver/http/ServerResponse.java
Labels: webserver, 4.x, Níma, OCA Verified

#5230 [2.x] - Additional @Retry strategies
  fault-tolerance/etc/spotbugs/exclude.xml
  fault-tolerance/src/main/java/io/helidon/faulttolerance/Retry.java
  fault-tolerance/src/test/java/io/helidon/faulttolerance/RetryTest.java
  microprofile/fault-tolerance/src/main/java/io/helidon/microprofile/faulttolerance/MethodIntrospector.java
  microprofile/fault-tolerance/src/main/java/io/helidon/microprofile/faulttolerance/MethodInvoker.java
  microprofile/fault-tolerance/src/main/java/io/helidon/microprofile/faulttolerance/RetryExponentialBackoff.java
  microprofile/fault-tolerance/src/main/java/io/helidon/microprofile/faulttolerance/RetryFibonacciBackoff.java
  microprofile/fault-tolerance/src/test/java/io/helidon/microprofile/faulttolerance/RetryBean.java
  microprofile/fault-tolerance/src/test/java/io/helidon/microprofile/faulttolerance/RetryTest.java
Labels: OCA Verified

#5165 [3.x] - Additional @Retry strategies
  fault-tolerance/etc/spotbugs/exclude.xml
  fault-tolerance/src/main/java/io/helidon/faulttolerance/Retry.java
  fault-tolerance/src/test/java/io/helidon/faulttolerance/RetryTest.java
  microprofile/fault-tolerance/src/main/java/io/helidon/microprofile/faulttolerance/MethodIntrospector.java
  microprofile/fault-tolerance/src/main/java/io/helidon/microprofile/faulttolerance/MethodInvoker.java
  microprofile/fault-tolerance/src/main/java/io/helidon/microprofile/faulttolerance/RetryExponentialBackoff.java
  microprofile/fault-tolerance/src/main/java/io/helidon/microprofile/faulttolerance/RetryFibonacciBackoff.java
  microprofile/fault-tolerance/src/test/java/io/helidon/microprofile/faulttolerance/RetryBean.java
  microprofile/fault-tolerance/src/test/java/io/helidon/microprofile/faulttolerance/RetryTest.java
Labels: enhancement, 3.x, OCA Verified

#5232 Use Hamcrest assertions instead of JUnit in tests/integration/native-image/se-1 (#1749)
  tests/integration/native-image/se-1/pom.xml
  tests/integration/native-image/se-1/src/test/java/io/helidon/tests/integration/nativeimage/se1/Se1MainTest.java
Labels: OCA Verified

#5233 Use Hamcrest assertions instead of JUnit in tests/integration/native-image/se-1 - backport 2.x (#1749)
  tests/integration/native-image/se-1/pom.xml
  tests/integration/native-image/se-1/src/test/java/io/helidon/tests/integration/nativeimage/se1/Se1MainTest.java
Labels: OCA Verified

#5234 2.x: License attribution fixes
  THIRD_PARTY_LICENSES.txt
  etc/HELIDON_THIRD_PARTY_LICENSES.xml
Labels: 2.x, OCA Verified

#5150 2.x: Issue 4567 - Grpc component Does not handle "package" directive in proto files.
  grpc/server/src/main/java/io/helidon/grpc/server/BindableServiceImpl.java
  grpc/server/src/main/java/io/helidon/grpc/server/ServiceDescriptor.java
  grpc/server/src/test/java/io/helidon/grpc/server/GrpcProtoPackageNoJavaPackageTest.java
  grpc/server/src/test/java/io/helidon/grpc/server/GrpcProtoPackageTest.java
  grpc/server/src/test/java/io/helidon/grpc/server/ServiceDescriptorTest.java
  grpc/server/src/test/proto/echopackage.proto
  grpc/server/src/test/proto/echopackagenojavapackage.proto
Labels: OCA Verified

#5244 3.x: Remove license report from maven lifecycle
  applications/pom.xml
  archetypes/helidon/src/main/archetype/common/files/pom.xml.mustache
  examples/grpc/microprofile/basic-client/pom.xml
  examples/grpc/microprofile/basic-server-implicit/pom.xml
  examples/grpc/microprofile/metrics/pom.xml
  examples/jbatch/pom.xml
  examples/metrics/http-status-count-se/pom.xml
  examples/microprofile/http-status-count-mp/pom.xml
  tests/functional/config-profiles/pom.xml
Labels: 3.x, OCA Verified

#5246 4.x: Remove license-report from maven lifecycle
  applications/pom.xml
  archetypes/helidon/src/main/archetype/common/files/pom.xml.mustache
  examples/grpc/microprofile/basic-client/pom.xml
  examples/grpc/microprofile/basic-server-implicit/pom.xml
  examples/grpc/microprofile/metrics/pom.xml
  examples/jbatch/pom.xml
  examples/metrics/http-status-count-se/pom.xml
  examples/microprofile/http-status-count-mp/pom.xml
  tests/functional/config-profiles/pom.xml
Labels: 4.x, OCA Verified

#5245 2.x: Remove license-report from maven lifecycle
  applications/pom.xml
  archetypes/bare-mp/src/main/resources/pom.xml.mustache
  archetypes/bare-se/src/main/resources/pom.xml.mustache
  archetypes/database-mp/src/main/resources/pom.xml.mustache
  archetypes/database-se/src/main/resources/pom.xml.mustache
  archetypes/quickstart-mp/src/main/resources/pom.xml.mustache
  archetypes/quickstart-se/src/main/resources/pom.xml.mustache
  examples/grpc/microprofile/basic-client/pom.xml
  examples/grpc/microprofile/basic-server-implicit/pom.xml
  examples/grpc/microprofile/metrics/pom.xml
  examples/istio/helidon-jpa/pom.xml
  examples/jbatch/pom.xml
  examples/metrics/http-status-count-se/pom.xml
  examples/microprofile/http-status-count-mp/pom.xml
  tests/functional/config-profiles/pom.xml
Labels: 2.x, OCA Verified

#5236 Use Hamcrest assertions instead of JUnit in tests/integration/kafka - backport 2.x (#1749)
  tests/integration/kafka/src/test/java/io/helidon/messaging/connectors/kafka/AbstractKafkaTest.java
  tests/integration/kafka/src/test/java/io/helidon/messaging/connectors/kafka/EmittingPublisherTest.java
  tests/integration/kafka/src/test/java/io/helidon/messaging/connectors/kafka/KafkaMpTest.java
  tests/integration/kafka/src/test/java/io/helidon/messaging/connectors/kafka/KafkaSeTest.java
Labels: OCA Verified

#5235 Use Hamcrest assertions instead of JUnit in tests/integration/kafka (#1749)
  tests/integration/kafka/src/test/java/io/helidon/messaging/connectors/kafka/AbstractKafkaTest.java
  tests/integration/kafka/src/test/java/io/helidon/messaging/connectors/kafka/EmittingPublisherTest.java
  tests/integration/kafka/src/test/java/io/helidon/messaging/connectors/kafka/KafkaMpTest.java
  tests/integration/kafka/src/test/java/io/helidon/messaging/connectors/kafka/KafkaSeTest.java
Labels: OCA Verified

#5240 Use only public APIs to read PKCS#1 keys
  common/key-util/pom.xml
  common/key-util/src/main/java/io/helidon/common/pki/DerUtils.java
  common/key-util/src/main/java/io/helidon/common/pki/PemReader.java
  common/key-util/src/main/java/io/helidon/common/pki/Pkcs1Util.java
  common/key-util/src/test/java/io/helidon/common/pki/KeyConfigTest.java
  common/key-util/src/test/resources/keystore/pkcs1-1024.pem
  common/key-util/src/test/resources/keystore/pkcs1-2048.pem
  common/key-util/src/test/resources/keystore/pkcs1-512.pem
  pom.xml
Labels: 4.x, OCA Verified

#5258 Use only public APIs to read PKCS#1 keys (#5240)
  common/key-util/pom.xml
  common/key-util/src/main/java/io/helidon/common/pki/DerUtils.java
  common/key-util/src/main/java/io/helidon/common/pki/PemReader.java
  common/key-util/src/main/java/io/helidon/common/pki/Pkcs1Util.java
  common/key-util/src/test/java/io/helidon/common/pki/KeyConfigTest.java
  common/key-util/src/test/resources/keystore/pkcs1-1024.pem
  common/key-util/src/test/resources/keystore/pkcs1-2048.pem
  common/key-util/src/test/resources/keystore/pkcs1-512.pem
  pom.xml
Labels: 3.x, backport, OCA Verified

#5259 Use only public APIs to read PKCS#1 keys (#5240)
  common/key-util/pom.xml
  common/key-util/src/main/java/io/helidon/common/pki/DerUtils.java
  common/key-util/src/main/java/io/helidon/common/pki/PemReader.java
  common/key-util/src/main/java/io/helidon/common/pki/Pkcs1Util.java
  common/key-util/src/test/java/io/helidon/common/pki/KeyConfigTest.java
  common/key-util/src/test/resources/keystore/pkcs1-1024.pem
  common/key-util/src/test/resources/keystore/pkcs1-2048.pem
  common/key-util/src/test/resources/keystore/pkcs1-512.pem
  pom.xml
Labels: 2.x, backport, OCA Verified

#5251 Use Hamcrest assertions instead of JUnit in integrations/cdi/jpa-cdi (#1749)
  integrations/cdi/jpa-cdi/src/test/java/io/helidon/integrations/cdi/jpa/TestAnnotationRewriting.java
  integrations/cdi/jpa-cdi/src/test/java/io/helidon/integrations/cdi/jpa/TestMessages.java
  integrations/cdi/jpa-cdi/src/test/java/io/helidon/integrations/cdi/jpa/TestMultiplePersistenceUnits.java
  integrations/cdi/jpa-cdi/src/test/java/io/helidon/integrations/cdi/jpa/chirp/TestCascadePersist.java
  integrations/cdi/jpa-cdi/src/test/java/io/helidon/integrations/cdi/jpa/chirp/TestExtendedSynchronizedEntityManager.java
  integrations/cdi/jpa-cdi/src/test/java/io/helidon/integrations/cdi/jpa/chirp/TestExtendedUnsynchronizedEntityManager.java
  integrations/cdi/jpa-cdi/src/test/java/io/helidon/integrations/cdi/jpa/chirp/TestJpaTransactionScopedSynchronizedEntityManager.java
  integrations/cdi/jpa-cdi/src/test/java/io/helidon/integrations/cdi/jpa/chirp/TestJpaTransactionScopedUnsynchronizedEntityManager.java
  integrations/cdi/jpa-cdi/src/test/java/io/helidon/integrations/cdi/jpa/chirp/TestRollbackScenarios.java
  integrations/cdi/jpa-cdi/src/test/java/io/helidon/integrations/cdi/jpa/chirp/TestWithTransactionalInterceptors.java
Labels: OCA Verified

#5249 [4.x] - Fix intermittent jBatch test
  examples/jbatch/src/test/java/io/helidon/examples/jbatch/TestJBatchEndpoint.java
Labels: testing, intermittent, 4.x, OCA Verified

#5248 [2.x] - Fix intermittent jBatch test
  examples/jbatch/src/test/java/io/helidon/examples/jbatch/TestJBatchEndpoint.java
Labels: 2.x, testing, intermittent, OCA Verified

#5247 [3.x] - Fix intermittent jBatch test
  examples/jbatch/src/test/java/io/helidon/examples/jbatch/TestJBatchEndpoint.java
Labels: 3.x, testing, intermittent, OCA Verified

#5262 2.x attribution cleanup
  THIRD_PARTY_LICENSES.txt
  applications/pom.xml
  etc/HELIDON_THIRD_PARTY_LICENSES.xml
Labels: 2.x, OCA Verified

#5265 2.x: Add GPLv2-CPE
  THIRD_PARTY_LICENSES.txt
  etc/HELIDON_THIRD_PARTY_LICENSES.xml
Labels: 2.x, OCA Verified

#5264 3.x: Better handle EPL-2.0-plus-GPLv2-CPE
  THIRD_PARTY_LICENSES.txt
  etc/HELIDON_THIRD_PARTY_LICENSES.xml
Labels: 3.x, OCA Verified

#5276 3.x: Add back helidon-licensing dependency to application pom
  applications/pom.xml
Labels: 3.x, OCA Verified

#5274 Use Hamcrest assertions instead of JUnit in config/encryption (#1749)
  config/encryption/src/test/java/io/helidon/config/encryption/EncryptionUtilTest.java
  config/encryption/src/test/java/io/helidon/config/encryption/MainTest.java
Labels: OCA Verified

#5275 Use Hamcrest assertions instead of JUnit in config/encryption - backport 2.x (#1749)
  config/encryption/src/test/java/io/helidon/config/encryption/EncryptionUtilTest.java
  config/encryption/src/test/java/io/helidon/config/encryption/MainTest.java
Labels: OCA Verified

#5282 4.x license cleanup
  THIRD_PARTY_LICENSES.txt
  applications/pom.xml
  etc/HELIDON_THIRD_PARTY_LICENSES.xml
Labels: 4.x, OCA Verified

#5287 fix builder build for mvn -T 4, forcing test-builder to depend on bui…
  pico/builder/test-builder/pom.xml
Labels: pico, OCA Verified

#5221 Broad changes to handle case properly in headers and parameters
  common/http/pom.xml
  common/http/src/main/java/io/helidon/common/http/HashHeaders.java
  common/http/src/main/java/io/helidon/common/http/HashParameters.java
  common/http/src/main/java/io/helidon/common/http/Parameters.java
  common/http/src/main/java/io/helidon/common/http/ReadOnlyHeaders.java
  common/http/src/main/java/io/helidon/common/http/ReadOnlyParameters.java
  common/http/src/main/java/io/helidon/common/http/UnmodifiableParameters.java
  common/http/src/test/java/io/helidon/common/http/CaseSensitivityTest.java
  config/testing/src/main/java/io/helidon/config/testing/CaseSensitivityTester.java
  grpc/server/src/main/java/io/helidon/grpc/server/GrpcTracing.java
  jersey/connector/pom.xml
  jersey/connector/src/main/java/io/helidon/jersey/connector/HelidonStructures.java
  jersey/connector/src/test/java/io/helidon/jersey/connector/CaseSensitivityTest.java
  media/common/src/main/java/io/helidon/media/common/MessageBodyReaderContext.java
  media/common/src/main/java/io/helidon/media/common/MessageBodyWriterContext.java
  media/multipart/pom.xml
  media/multipart/src/main/java/io/helidon/media/multipart/ReadableBodyPartHeaders.java
  media/multipart/src/main/java/io/helidon/media/multipart/WriteableBodyPartHeaders.java
  media/multipart/src/test/java/io/helidon/media/multipart/CaseSensitivityTest.java
  tracing/jaeger/pom.xml
  tracing/jaeger/src/test/java/io/helidon/tracing/jaeger/B3HeadersPropagationCaseTest.java
  tracing/jersey-client/src/main/java/io/helidon/tracing/jersey/client/ClientTracingFilter.java
  tracing/tracing/src/main/java/io/helidon/tracing/MapHeaderConsumer.java
  tracing/zipkin/pom.xml
  webclient/webclient/pom.xml
  webclient/webclient/src/main/java/io/helidon/webclient/WebClientQueryParams.java
  webclient/webclient/src/main/java/io/helidon/webclient/WebClientRequestHeadersImpl.java
  webclient/webclient/src/main/java/io/helidon/webclient/WebClientResponseHeadersImpl.java
  webclient/webclient/src/test/java/io/helidon/webclient/CaseSensitivityTest.java
  webserver/webserver/src/main/java/io/helidon/webserver/HashRequestHeaders.java
  webserver/webserver/src/main/java/io/helidon/webserver/HashResponseHeaders.java
  webserver/webserver/src/test/java/io/helidon/webserver/CaseSensitivityTest.java
Labels: 3.x, OCA Verified

#5284 Issue 4567 - Grpc component Does not handle "package" directive in proto files.
  grpc/server/src/main/java/io/helidon/grpc/server/BindableServiceImpl.java
  grpc/server/src/main/java/io/helidon/grpc/server/ServiceDescriptor.java
  grpc/server/src/test/java/io/helidon/grpc/server/GrpcProtoPackageNoJavaPackageTest.java
  grpc/server/src/test/java/io/helidon/grpc/server/GrpcProtoPackageTest.java
  grpc/server/src/test/java/io/helidon/grpc/server/ServiceDescriptorTest.java
  grpc/server/src/test/proto/echopackage.proto
  grpc/server/src/test/proto/echopackagenojavapackage.proto
Labels: OCA Verified

#5283 Issue 4567 - Grpc component Does not handle package directive in proto files.
  grpc/server/src/main/java/io/helidon/grpc/server/BindableServiceImpl.java
  grpc/server/src/main/java/io/helidon/grpc/server/ServiceDescriptor.java
  grpc/server/src/test/java/io/helidon/grpc/server/GrpcProtoPackageNoJavaPackageTest.java
  grpc/server/src/test/java/io/helidon/grpc/server/GrpcProtoPackageTest.java
  grpc/server/src/test/java/io/helidon/grpc/server/ServiceDescriptorTest.java
  grpc/server/src/test/proto/echopackage.proto
  grpc/server/src/test/proto/echopackagenojavapackage.proto
Labels: OCA Verified
