Repository helidon-io/helidon, pull requests merged in 2022-04, with the labels that each got.

#4088 Update quickstart docker images
  examples/quickstarts/helidon-quickstart-mp/Dockerfile
  examples/quickstarts/helidon-quickstart-mp/Dockerfile.jlink
  examples/quickstarts/helidon-quickstart-mp/README.md
  examples/quickstarts/helidon-quickstart-mp/build.gradle
  examples/quickstarts/helidon-quickstart-se/Dockerfile
  examples/quickstarts/helidon-quickstart-se/Dockerfile.jlink
  examples/quickstarts/helidon-quickstart-se/README.md
  examples/quickstarts/helidon-quickstart-se/build.gradle
  examples/quickstarts/helidon-standalone-quickstart-mp/Dockerfile
  examples/quickstarts/helidon-standalone-quickstart-mp/Dockerfile.jlink
  examples/quickstarts/helidon-standalone-quickstart-mp/README.md
  examples/quickstarts/helidon-standalone-quickstart-se/Dockerfile
  examples/quickstarts/helidon-standalone-quickstart-se/Dockerfile.jlink
  examples/quickstarts/helidon-standalone-quickstart-se/README.md
Labels: docs, dependencies, 3.x

#4093 New security response mapper mechanism (master)
  security/integration/jersey/src/main/java/io/helidon/security/integration/jersey/SecurityFilterCommon.java
  security/integration/jersey/src/main/java/io/helidon/security/integration/jersey/SecurityResponseMapper.java
  security/integration/jersey/src/main/java/module-info.java
  tests/integration/security/pom.xml
  tests/integration/security/security-response-mapper/pom.xml
  tests/integration/security/security-response-mapper/src/main/java/io/helidon/tests/integration/security/mapper/MySecurityResponseMapper.java
  tests/integration/security/security-response-mapper/src/main/java/io/helidon/tests/integration/security/mapper/Restricted.java
  tests/integration/security/security-response-mapper/src/main/java/io/helidon/tests/integration/security/mapper/RestrictedProvider.java
  tests/integration/security/security-response-mapper/src/main/java/io/helidon/tests/integration/security/mapper/RestrictedProviderService.java
  tests/integration/security/security-response-mapper/src/main/java/io/helidon/tests/integration/security/mapper/RestrictedResource.java
  tests/integration/security/security-response-mapper/src/main/resources/META-INF/services/io.helidon.security.integration.jersey.SecurityResponseMapper
  tests/integration/security/security-response-mapper/src/main/resources/META-INF/services/io.helidon.security.spi.SecurityProviderService
  tests/integration/security/security-response-mapper/src/main/resources/application.yaml
  tests/integration/security/security-response-mapper/src/main/resources/logging.properties
  tests/integration/security/security-response-mapper/src/test/java/io/helidon/tests/integration/security/mapper/RestrictedResourceTest.java
Labels: MP, security, 3.x

#4087 3984 Describe more Scheduled properties for 2.x
  docs/mp/scheduling/01_introduction.adoc
Labels: docs, 2.x

#4096 Deprecate SE MultiPart buffered mode.
  media/multipart/src/main/java/io/helidon/media/multipart/MultiPart.java
  media/multipart/src/main/java/io/helidon/media/multipart/MultiPartBodyReader.java
  media/multipart/src/main/java/io/helidon/media/multipart/ReadableMultiPart.java
Labels: api-change

#4014 Quickstart cleanup, using @HelidonTest in MP. (#4011)
  examples/quickstarts/helidon-quickstart-mp/pom.xml
  examples/quickstarts/helidon-quickstart-mp/src/main/java/io/helidon/examples/quickstart/mp/GreetResource.java
  examples/quickstarts/helidon-quickstart-mp/src/main/java/io/helidon/examples/quickstart/mp/ReactiveService.java
  examples/quickstarts/helidon-quickstart-mp/src/test/java/io/helidon/examples/quickstart/mp/MainTest.java
  examples/quickstarts/helidon-quickstart-se/src/test/java/io/helidon/examples/quickstart/se/MainTest.java
  examples/quickstarts/helidon-quickstart-se/src/test/resources/config-profile.yaml
  examples/quickstarts/helidon-standalone-quickstart-mp/pom.xml
  examples/quickstarts/helidon-standalone-quickstart-mp/src/test/java/io/helidon/examples/quickstart/mp/MainTest.java
  examples/quickstarts/helidon-standalone-quickstart-se/src/test/java/io/helidon/examples/quickstart/se/MainTest.java
  examples/quickstarts/helidon-standalone-quickstart-se/src/test/resources/config-profile.yaml
  examples/quickstarts/pom.xml
Labels: 3.x

#4103 Remove buffered multipart
  examples/media/multipart/src/main/java/io/helidon/examples/media/multipart/FileService.java
  examples/media/multipart/src/main/resources/WEB/index.html
  media/multipart/src/main/java/io/helidon/media/multipart/MultiPart.java
  media/multipart/src/main/java/io/helidon/media/multipart/MultiPartBodyReader.java
  media/multipart/src/main/java/io/helidon/media/multipart/MultiPartSupport.java
  media/multipart/src/main/java/io/helidon/media/multipart/ReadableMultiPart.java
  media/multipart/src/main/java/io/helidon/media/multipart/WriteableMultiPart.java
Labels: api-change

#4107 2.x: Upgrade directory-maven-plugin
  pom.xml
Labels: build, 2.x

#4106 3.x: Upgrade directory-maven-plugin to 1.0
  pom.xml
Labels: build, 3.x

#4115 Fix retention of @Configured 3.x
  config/metadata/src/main/java/io/helidon/config/metadata/Configured.java
Labels: 3.x

#4113 Fix retention of @Configured 2.x
  config/metadata/src/main/java/io/helidon/config/metadata/Configured.java
Labels: 2.x

#4099 Fixed dbclient integration tests build issue.
  tests/integration/dbclient/common/pom.xml
Labels: 2.x

#4100 Fixed dbclient integration tests build issues.
  tests/integration/dbclient/appl/src/main/java/io/helidon/tests/integration/dbclient/appl/InitService.java
  tests/integration/dbclient/appl/src/main/java/io/helidon/tests/integration/dbclient/appl/health/HealthCheckService.java
  tests/integration/dbclient/appl/src/test/java/io/helidon/tests/integration/dbclient/appl/it/health/HealthCheckIT.java
  tests/integration/dbclient/common/pom.xml
  tests/integration/dbclient/common/src/main/java/io/helidon/tests/integration/dbclient/common/tests/health/HealthCheckIT.java
Labels: 3.x

#4117 Native image configuration reflection update for Jaeger 3.x
  tracing/jaeger/src/main/resources/META-INF/native-image/io.helidon.tracing/helidon-tracing-jaeger/reflect-config.json
Labels: 3.x

#4118 Native image configuration reflection update for Jaeger 2.x
  tracing/jaeger/src/main/resources/META-INF/native-image/io.helidon.tracing/helidon-tracing-jaeger/reflect-config.json
Labels: 2.x

#3885 Support of Bean Validation in Helidon MP #721 for Helidon 2.x
  bom/pom.xml
  dependencies/pom.xml
  docs/mp/beanvalidation/02_general_beanvalidation.adoc
  examples/microprofile/bean-validation/README.md
  examples/microprofile/bean-validation/pom.xml
  examples/microprofile/bean-validation/src/main/java/io/helidon/examples/microprofile/bean/validation/ValidEmailResource.java
  examples/microprofile/bean-validation/src/main/java/io/helidon/examples/microprofile/bean/validation/package-info.java
  examples/microprofile/bean-validation/src/main/resources/META-INF/beans.xml
  examples/microprofile/bean-validation/src/main/resources/META-INF/microprofile-config.properties
  examples/microprofile/bean-validation/src/main/resources/logging.properties
  examples/microprofile/bean-validation/src/test/java/io/helidon/tests/integration/bean/validation/TestValidationEndpoint.java
  examples/microprofile/pom.xml
  examples/todo-app/frontend/package-lock.json
  microprofile/bean-validation/pom.xml
  microprofile/bean-validation/src/main/java/io/helidon/microprofile/bean/validation/HelidonConstraintViolationExceptionMapper.java
  microprofile/bean-validation/src/main/java/io/helidon/microprofile/bean/validation/package-info.java
  microprofile/bean-validation/src/main/java/module-info.java
  microprofile/bean-validation/src/main/resources/META-INF/beans.xml
  microprofile/bean-validation/src/main/resources/META-INF/helidon/native-image/weld-proxies.json
  microprofile/bean-validation/src/main/resources/META-INF/native-image/io.helidon.microprofile.bean-validation/helidon-microprofile-bean-validation/native-image.properties
  microprofile/bean-validation/src/main/resources/META-INF/native-image/io.helidon.microprofile.bean-validation/helidon-microprofile-bean-validation/reflect-config.json
  microprofile/pom.xml
  tests/integration/mp-bean-validation/pom.xml
  tests/integration/mp-bean-validation/src/main/java/io/helidon/examples/microprofile/bean/validation/ValidEmailResource.java
  tests/integration/mp-bean-validation/src/main/java/io/helidon/examples/microprofile/bean/validation/package-info.java
  tests/integration/mp-bean-validation/src/main/resources/META-INF/beans.xml
  tests/integration/mp-bean-validation/src/main/resources/META-INF/microprofile-config.properties
  tests/integration/mp-bean-validation/src/main/resources/logging.properties
  tests/integration/mp-bean-validation/src/test/java/io/helidon/tests/integration/bean/validation/TestValidationEndpoint.java
  tests/integration/pom.xml
Labels: dependencies

#4121 Upgrade Netty to 4.1.76.Final
  dependencies/pom.xml
  pom.xml
Labels: dependencies, 3.x

#3780 Support of Bean Validation in Helidon MP #721
  bom/pom.xml
  dependencies/pom.xml
  docs/mp/beanvalidation/02_general_beanvalidation.adoc
  examples/microprofile/bean-validation/README.md
  examples/microprofile/bean-validation/pom.xml
  examples/microprofile/bean-validation/src/main/java/io/helidon/examples/microprofile/bean/validation/ValidEmailResource.java
  examples/microprofile/bean-validation/src/main/java/io/helidon/examples/microprofile/bean/validation/package-info.java
  examples/microprofile/bean-validation/src/main/resources/META-INF/beans.xml
  examples/microprofile/bean-validation/src/main/resources/META-INF/microprofile-config.properties
  examples/microprofile/bean-validation/src/main/resources/logging.properties
  examples/microprofile/bean-validation/src/test/java/io/helidon/tests/integration/bean/validation/TestValidationEndpoint.java
  examples/microprofile/pom.xml
  microprofile/bean-validation/pom.xml
  microprofile/bean-validation/src/main/java/io/helidon/microprofile/bean/validation/HelidonConstraintViolationExceptionMapper.java
  microprofile/bean-validation/src/main/java/io/helidon/microprofile/bean/validation/package-info.java
  microprofile/bean-validation/src/main/java/module-info.java
  microprofile/bean-validation/src/main/resources/META-INF/beans.xml
  microprofile/bean-validation/src/main/resources/META-INF/helidon/native-image/weld-proxies.json
  microprofile/bean-validation/src/main/resources/META-INF/native-image/io.helidon.microprofile.bean-validation/helidon-microprofile-bean-validation/native-image.properties
  microprofile/bean-validation/src/main/resources/META-INF/native-image/io.helidon.microprofile.bean-validation/helidon-microprofile-bean-validation/reflect-config.json
  microprofile/pom.xml
  tests/integration/mp-bean-validation/pom.xml
  tests/integration/mp-bean-validation/src/main/java/io/helidon/examples/microprofile/bean/validation/ValidEmailResource.java
  tests/integration/mp-bean-validation/src/main/java/io/helidon/examples/microprofile/bean/validation/package-info.java
  tests/integration/mp-bean-validation/src/main/resources/META-INF/beans.xml
  tests/integration/mp-bean-validation/src/main/resources/META-INF/microprofile-config.properties
  tests/integration/mp-bean-validation/src/main/resources/logging.properties
  tests/integration/mp-bean-validation/src/test/java/io/helidon/tests/integration/bean/validation/TestValidationEndpoint.java
  tests/integration/pom.xml
Labels: dependencies

#4131 Upgrades Eclipselink to 2.7.10
  applications/mp/pom.xml
  dependencies/pom.xml
  pom.xml
Labels: MP, P3, jpa/jta, 2.x, dependencies

#4132 3.x Fix deps in jpa examples and do other cleanup
  etc/copyright-exclude.txt
  examples/integrations/cdi/jpa/pom.xml
  examples/integrations/cdi/jpa/src/main/resources/META-INF/persistence.xml
  examples/integrations/cdi/pokemons/README.md
  examples/integrations/cdi/pokemons/pom.xml
  examples/integrations/cdi/pokemons/src/main/resources/META-INF/init_script.sql
  examples/integrations/cdi/pokemons/src/main/resources/META-INF/persistence.xml
Labels: examples, jpa/jta, 3.x

#4133 Fix guide broken links and typos 4119 for 3.x
  docs/common/guides/maven_build.adoc
Labels: docs, 3.x

#4134 Fix guide broken links and typos 4119 for 2.x
  docs/common/guides/maven_build.adoc
Labels: docs, 2.x

#4135 Abstract decorator class now gets correct proxy name in Weld
  microprofile/weld/weld-core-impl/src/main/java/org/jboss/weld/bean/proxy/ProxyFactory.java
  tests/integration/mp-gh-4123/pom.xml
  tests/integration/mp-gh-4123/src/main/java/io/helidon/tests/integration/gh4123/ContractBean.java
  tests/integration/mp-gh-4123/src/main/java/io/helidon/tests/integration/gh4123/ContractDecorator.java
  tests/integration/mp-gh-4123/src/main/java/io/helidon/tests/integration/gh4123/SomeContract.java
  tests/integration/mp-gh-4123/src/main/java/io/helidon/tests/integration/gh4123/UsingBean.java
  tests/integration/mp-gh-4123/src/main/resources/META-INF/beans.xml
  tests/integration/mp-gh-4123/src/test/java/io/helidon/tests/integration/gh4123/Gh4123Test.java
  tests/integration/pom.xml
Labels: 2.x

#4139 2.x: possible fix for HttpPipelineTest hang
  webserver/webserver/src/test/java/io/helidon/webserver/utils/SocketHttpClient.java
Labels: 2.x

#4143 3.x - possible fix for HttpPipelineTest hang
  webserver/webserver/src/test/java/io/helidon/webserver/utils/SocketHttpClient.java
Labels: 3.x, testing

#4138 2.x: Upgrade Netty to 4.1.76.Final
  dependencies/pom.xml
  pom.xml
Labels: 2.x, dependencies

#4148 Abstract decorator class now gets correct proxy name in Weld (3.x)
  microprofile/weld/weld-core-impl/src/main/java/org/jboss/weld/bean/proxy/ProxyFactory.java
  tests/integration/mp-gh-4123/pom.xml
  tests/integration/mp-gh-4123/src/main/java/io/helidon/tests/integration/gh4123/ContractBean.java
  tests/integration/mp-gh-4123/src/main/java/io/helidon/tests/integration/gh4123/ContractDecorator.java
  tests/integration/mp-gh-4123/src/main/java/io/helidon/tests/integration/gh4123/SomeContract.java
  tests/integration/mp-gh-4123/src/main/java/io/helidon/tests/integration/gh4123/UsingBean.java
  tests/integration/mp-gh-4123/src/main/resources/META-INF/beans.xml
  tests/integration/mp-gh-4123/src/test/java/io/helidon/tests/integration/gh4123/Gh4123Test.java
  tests/integration/pom.xml
Labels: 3.x

#4146 2.x: Uppgrade grpc-java to 1.45.1
  dependencies/pom.xml
Labels: 2.x, dependencies

#4147 Enable mp-graphql tck with 2.0-RC3 of Microprofile GraphQL Spec
  dependencies/pom.xml
  microprofile/tests/arquillian/src/main/java/io/helidon/microprofile/arquillian/HelidonContainerExtension.java
  microprofile/tests/tck/tck-graphql/pom.xml
Labels: graphql

#4150 3.x: Upgrade grpc-java to 1.45.1
  dependencies/pom.xml
Labels: dependencies, 3.x

#4165 2.x: Improve threadNamePrefix defaulting to be more informative
  common/configurable/src/main/java/io/helidon/common/configurable/ThreadPoolSupplier.java
  common/configurable/src/test/java/io/helidon/common/configurable/ThreadPoolSupplierTest.java
Labels: 2.x
