Repository helidon-io/helidon, pull requests merged in 2023-09, with the labels that each got.

#7486 3.x: Create constants for outbound id and secret
  docs/config/io_helidon_security_providers_jwt_JwtProvider.adoc
  docs/includes/security/providers/http-basic-auth.adoc
  docs/se/grpc/server.adoc
  examples/grpc/security-outbound/src/main/java/io/helidon/grpc/examples/security/outbound/SecureGreetClient.java
  examples/grpc/security-outbound/src/main/java/io/helidon/grpc/examples/security/outbound/SecureServer.java
  examples/grpc/security/src/main/java/io/helidon/grpc/examples/security/SecureGreetClient.java
  examples/grpc/security/src/main/java/io/helidon/grpc/examples/security/SecureStringClient.java
  examples/security/basic-auth-with-static-content/src/test/java/io/helidon/security/examples/webserver/basic/BasicExampleTest.java
  examples/security/outbound-override/src/main/java/io/helidon/security/examples/outbound/OutboundOverrideExample.java
  examples/security/outbound-override/src/main/java/io/helidon/security/examples/outbound/OutboundOverrideJwtExample.java
  examples/security/outbound-override/src/test/java/io/helidon/security/examples/outbound/OutboundOverrideExampleTest.java
  examples/security/outbound-override/src/test/java/io/helidon/security/examples/outbound/OutboundOverrideJwtExampleTest.java
  examples/security/webserver-signatures/src/test/java/io/helidon/security/examples/signatures/SignatureExampleTest.java
  microprofile/jwt-auth/src/main/java/io/helidon/microprofile/jwt/auth/JwtAuthProvider.java
  security/integration/grpc/src/test/java/io/helidon/security/integration/grpc/OutboundSecurityIT.java
  security/integration/webserver/src/test/java/io/helidon/security/integration/webserver/WebSecurityBuilderGateDefaultsTest.java
  security/integration/webserver/src/test/java/io/helidon/security/integration/webserver/WebSecurityTests.java
  security/providers/http-auth/src/main/java/io/helidon/security/providers/httpauth/HttpBasicAuthProvider.java
  security/providers/http-auth/src/test/java/io/helidon/security/providers/httpauth/BasicAuthOutboundOverrideTest.java
  security/providers/jwt/src/main/java/io/helidon/security/providers/jwt/JwtProvider.java
  security/security/src/main/java/io/helidon/security/EndpointConfig.java
  tests/integration/webclient/src/test/java/io/helidon/tests/integration/webclient/ContextCheckTest.java
  tests/integration/webclient/src/test/java/io/helidon/tests/integration/webclient/SecurityTest.java
Labels: 3.x, backport, OCA Verified

#7501 4.x: Docs: Remove description of Config.changes() API and other cleanup
  docs/mp/config/advanced-configuration.adoc
  docs/mp/config/introduction.adoc
  docs/se/config/advanced-configuration.adoc
  docs/se/config/config-profiles.adoc
  docs/se/config/extensions.adoc
  docs/se/config/hierarchical-features.adoc
  docs/se/config/introduction.adoc
  docs/se/config/mutability-support.adoc
  docs/se/config/property-mapping.adoc
Labels: docs, config, 4.x, OCA Verified

#7511 2.x: Security context not overridden
  security/integration/jersey/src/main/java/io/helidon/security/integration/jersey/SecurityPreMatchingFilter.java
  tests/integration/security/pom.xml
  tests/integration/security/security-context-not-overridden/pom.xml
  tests/integration/security/security-context-not-overridden/src/main/java/io/helidon/tests/integration/context/TestEndpointResource.java
  tests/integration/security/security-context-not-overridden/src/main/java/io/helidon/tests/integration/context/TestProvider.java
  tests/integration/security/security-context-not-overridden/src/main/java/io/helidon/tests/integration/context/TestProviderService.java
  tests/integration/security/security-context-not-overridden/src/main/resources/META-INF/services/io.helidon.security.spi.SecurityProviderService
  tests/integration/security/security-context-not-overridden/src/main/resources/application.yaml
  tests/integration/security/security-context-not-overridden/src/main/resources/logging.properties
  tests/integration/security/security-context-not-overridden/src/test/java/io/helidon/tests/integration/context/SecurityTest.java
Labels: OCA Verified

#7512 3.x: Security context not overridden
  security/integration/jersey/src/main/java/io/helidon/security/integration/jersey/SecurityPreMatchingFilter.java
  tests/integration/security/pom.xml
  tests/integration/security/security-context-not-overridden/pom.xml
  tests/integration/security/security-context-not-overridden/src/main/java/io/helidon/tests/integration/context/TestEndpointResource.java
  tests/integration/security/security-context-not-overridden/src/main/java/io/helidon/tests/integration/context/TestProvider.java
  tests/integration/security/security-context-not-overridden/src/main/java/io/helidon/tests/integration/context/TestProviderService.java
  tests/integration/security/security-context-not-overridden/src/main/resources/META-INF/services/io.helidon.security.spi.SecurityProviderService
  tests/integration/security/security-context-not-overridden/src/main/resources/application.yaml
  tests/integration/security/security-context-not-overridden/src/main/resources/logging.properties
  tests/integration/security/security-context-not-overridden/src/test/java/io/helidon/tests/integration/context/SecurityTest.java
Labels: OCA Verified

#7475 Client URL scheme validation #6547
  webclient/api/src/main/java/io/helidon/webclient/api/ClientRequestBase.java
  webclient/tests/http1/src/test/java/io/helidon/webclient/http1/Http1ClientTest.java
  webclient/tests/http2/src/test/java/io/helidon/webclient/tests/http2/Http2ClientTest.java
  webclient/websocket/src/main/java/io/helidon/webclient/websocket/WsClientImpl.java
  webclient/websocket/src/test/java/io/helidon/webclient/websocket/WsClientTest.java
  webserver/testing/junit5/junit5/src/main/java/io/helidon/webserver/testing/junit5/DirectClient.java
  webserver/testing/junit5/junit5/src/main/java/io/helidon/webserver/testing/junit5/DirectWebClient.java
  webserver/testing/junit5/websocket/src/test/resources/logging.properties
Labels: OCA Verified

#7521 4.x: Fix source and javadoc jars required for oss staging
  metrics/metrics/pom.xml
  metrics/provider-tests/pom.xml
  webclient/webclient/pom.xml
Labels: build, 4.x, OCA Verified

#7533 [4.x] Try to fix occasional test failures in pipeline
  metrics/provider-tests/src/main/java/io/helidon/metrics/provider/tests/TestGlobalTags.java
  metrics/providers/micrometer/src/test/java/io/helidon/metrics/providers/micrometer/TestCounter.java
  metrics/providers/micrometer/src/test/java/io/helidon/metrics/providers/micrometer/TestGauge.java
  metrics/providers/micrometer/src/test/java/io/helidon/metrics/providers/micrometer/TestTimer.java
Labels: OCA Verified

#7528 4.x: Use JSON-B instead of JSON-P in MP quickstarts
  examples/integrations/micrometer/mp/pom.xml
  examples/integrations/micrometer/mp/src/main/java/io/helidon/examples/integrations/micrometer/mp/GreetResource.java
  examples/integrations/micrometer/mp/src/main/java/io/helidon/examples/integrations/micrometer/mp/GreetingMessage.java
  examples/integrations/micrometer/mp/src/test/java/io/helidon/examples/integrations/micrometer/mp/TestEndpoint.java
  examples/integrations/microstream/greetings-mp/src/main/java/io/helidon/examples/integrations/microstream/greetings/mp/GreetResource.java
  examples/integrations/microstream/greetings-mp/src/main/java/io/helidon/examples/integrations/microstream/greetings/mp/GreetingMessage.java
  examples/integrations/microstream/greetings-mp/src/test/java/io/helidon/examples/integrations/microstream/greetings/mp/MicrostreamExampleGreetingsMpTest.java
  examples/metrics/filtering/mp/pom.xml
  examples/metrics/filtering/mp/src/main/java/io/helidon/examples/metrics/filtering/mp/GreetResource.java
  examples/metrics/filtering/mp/src/main/java/io/helidon/examples/metrics/filtering/mp/GreetingMessage.java
  examples/microprofile/cors/src/main/java/io/helidon/microprofile/examples/cors/GreetResource.java
  examples/microprofile/cors/src/main/java/io/helidon/microprofile/examples/cors/GreetingMessage.java
  examples/microprofile/cors/src/test/java/io/helidon/microprofile/examples/cors/TestCORS.java
  examples/microprofile/http-status-count-mp/pom.xml
  examples/microprofile/http-status-count-mp/src/main/java/io/helidon/examples/mp/httpstatuscount/GreetResource.java
  examples/microprofile/http-status-count-mp/src/main/java/io/helidon/examples/mp/httpstatuscount/GreetingMessage.java
  examples/microprofile/http-status-count-mp/src/main/java/io/helidon/examples/mp/httpstatuscount/SimpleGreetResource.java
  examples/microprofile/http-status-count-mp/src/test/java/io/helidon/examples/mp/httpstatuscount/MainTest.java
  examples/microprofile/openapi-basic/src/main/java/io/helidon/microprofile/examples/openapi/basic/GreetResource.java
  examples/microprofile/openapi-basic/src/main/java/io/helidon/microprofile/examples/openapi/basic/GreetingMessage.java
  examples/microprofile/openapi-basic/src/test/java/io/helidon/microprofile/examples/openapi/basic/MainTest.java
  examples/microprofile/telemetry/greeting/src/main/java/io/helidon/examples/microprofile/telemetry/GreetResource.java
  examples/microprofile/telemetry/greeting/src/main/java/io/helidon/examples/microprofile/telemetry/GreetingMessage.java
  examples/microprofile/telemetry/secondary/src/main/java/io/helidon/examples/microprofile/telemetry/SecondaryResource.java
  examples/microprofile/tls/src/main/java/io/helidon/microprofile/example/tls/GreetResource.java
  examples/quickstarts/helidon-quickstart-mp/src/main/java/io/helidon/examples/quickstart/mp/GreetResource.java
  examples/quickstarts/helidon-quickstart-mp/src/main/java/io/helidon/examples/quickstart/mp/GreetingMessage.java
  examples/quickstarts/helidon-quickstart-mp/src/test/java/io/helidon/examples/quickstart/mp/MainTest.java
  examples/quickstarts/helidon-standalone-quickstart-mp/src/main/java/io/helidon/examples/quickstart/mp/GreetResource.java
  examples/quickstarts/helidon-standalone-quickstart-mp/src/main/java/io/helidon/examples/quickstart/mp/GreetingMessage.java
  examples/quickstarts/helidon-standalone-quickstart-mp/src/test/java/io/helidon/examples/quickstart/mp/MainTest.java
Labels: MP, examples, 4.x, OCA Verified

#7523 2.x: Use JSON-B instead of JSON-P in MP quickstarts
  examples/integrations/micrometer/mp/pom.xml
  examples/integrations/micrometer/mp/src/main/java/io/helidon/examples/integrations/micrometer/mp/GreetResource.java
  examples/integrations/micrometer/mp/src/main/java/io/helidon/examples/integrations/micrometer/mp/GreetingMessage.java
  examples/integrations/micrometer/mp/src/test/java/io/helidon/examples/integrations/micrometer/mp/TestEndpoint.java
  examples/integrations/microstream/greetings-mp/src/main/java/io/helidon/examples/integrations/microstream/greetings/mp/GreetResource.java
  examples/integrations/microstream/greetings-mp/src/main/java/io/helidon/examples/integrations/microstream/greetings/mp/GreetingMessage.java
  examples/integrations/microstream/greetings-mp/src/test/java/io/helidon/examples/integrations/microstream/greetings/mp/MicrostreamExampleGreetingsMpTest.java
  examples/istio/helidon-config/src/main/java/io/helidon/examples/config/GreetResource.java
  examples/istio/helidon-jpa/src/main/java/io/helidon/examples/istio/GreetResource.java
  examples/istio/helidon-jpa/src/main/java/io/helidon/examples/istio/GreetingMessage.java
  examples/metrics/filtering/mp/src/main/java/io/helidon/examples/metrics/filtering/mp/GreetResource.java
  examples/metrics/filtering/mp/src/main/java/io/helidon/examples/metrics/filtering/mp/GreetingMessage.java
  examples/metrics/filtering/mp/src/test/java/io/helidon/examples/metrics/filtering/mp/MainTest.java
  examples/microprofile/cors/pom.xml
  examples/microprofile/cors/src/main/java/io/helidon/microprofile/examples/cors/GreetResource.java
  examples/microprofile/cors/src/main/java/io/helidon/microprofile/examples/cors/GreetingMessage.java
  examples/microprofile/cors/src/test/java/io/helidon/microprofile/examples/cors/TestCORS.java
  examples/microprofile/openapi-basic/src/main/java/io/helidon/microprofile/examples/openapi/basic/GreetResource.java
  examples/microprofile/openapi-basic/src/main/java/io/helidon/microprofile/examples/openapi/basic/GreetingMessage.java
  examples/microprofile/openapi-basic/src/test/java/io/helidon/microprofile/examples/openapi/basic/MainTest.java
  examples/microprofile/tls/src/main/java/io/helidon/microprofile/example/tls/GreetResource.java
  examples/quickstarts/helidon-quickstart-mp/src/main/java/io/helidon/examples/quickstart/mp/GreetResource.java
  examples/quickstarts/helidon-quickstart-mp/src/main/java/io/helidon/examples/quickstart/mp/GreetingMessage.java
  examples/quickstarts/helidon-quickstart-mp/src/test/java/io/helidon/examples/quickstart/mp/MainTest.java
  examples/quickstarts/helidon-standalone-quickstart-mp/src/main/java/io/helidon/examples/quickstart/mp/GreetResource.java
  examples/quickstarts/helidon-standalone-quickstart-mp/src/main/java/io/helidon/examples/quickstart/mp/GreetingMessage.java
  examples/quickstarts/helidon-standalone-quickstart-mp/src/test/java/io/helidon/examples/quickstart/mp/MainTest.java
Labels: MP, examples, 2.x, OCA Verified

#7522 Add missing permutations in archetype integration tests
  archetypes/helidon/filters.properties
Labels: archetypes, testing, 4.x, OCA Verified

#7539 4.x: Update to lifecycle tests to include various webserver components.
  microprofile/tests/server/src/test/java/io/helidon/microprofile/tests/server/WebServerLifecycleAnnotationTest.java
  microprofile/tests/server/src/test/java/io/helidon/microprofile/tests/server/WebServerLifecycleTest.java
  webserver/tests/webserver/src/test/java/io/helidon/webserver/tests/LifecycleMethodAnnotatedTest.java
  webserver/tests/webserver/src/test/java/io/helidon/webserver/tests/LifecycleMethodTest.java
Labels: webserver, testing, 4.x, OCA Verified

#7526 2.x: Doc issues
  docs/common/guides/metrics.adoc
  docs/mp/guides/07_datasource.adoc
Labels: docs, OCA Verified

#7540 Add SE legacy archetypes
  archetypes/legacy/bare-se/pom.xml
  archetypes/legacy/database-se/pom.xml
  archetypes/legacy/pom.xml
  archetypes/legacy/quickstart-se/pom.xml
Labels: archetypes, 4.x, OCA Verified

#7550 Integrate build-tools 4.0.0-M2
  applications/parent/pom.xml
  examples/quickstarts/helidon-standalone-quickstart-mp/pom.xml
  examples/quickstarts/helidon-standalone-quickstart-se/pom.xml
  pom.xml
Labels: OCA Verified

#7520 4.x: Introduces OciSecretsMpMetaConfigProvider, which adapts OciSecretsConfigSourceProvider to the MpMetaConfigProvider contract
  bom/pom.xml
  integrations/oci/oci-secrets-mp-config-source/pom.xml
  integrations/oci/oci-secrets-mp-config-source/src/main/java/io/helidon/integrations/oci/secrets/mp/configsource/OciSecretsMpMetaConfigProvider.java
  integrations/oci/oci-secrets-mp-config-source/src/main/java/io/helidon/integrations/oci/secrets/mp/configsource/package-info.java
  integrations/oci/oci-secrets-mp-config-source/src/main/java/module-info.java
  integrations/oci/oci-secrets-mp-config-source/src/test/java/io/helidon/integrations/oci/secrets/mp/configsource/UsageTest.java
  integrations/oci/oci-secrets-mp-config-source/src/test/java/logging.properties
  integrations/oci/oci-secrets-mp-config-source/src/test/resources/mp-meta-config.yaml
  integrations/oci/pom.xml
Labels: MP, config, P2, OCI, java, 4.x, OCA Verified

#7559 2.x: Adds zero-argument non-private constructors to NonTransactionalEntityManager and ExtendedEntityManager
  integrations/cdi/jpa-cdi/src/main/java/io/helidon/integrations/cdi/jpa/ExtendedEntityManager.java
  integrations/cdi/jpa-cdi/src/main/java/io/helidon/integrations/cdi/jpa/NonTransactionalEntityManager.java
Labels: bug, P1, cdi, jpa/jta, 2.x, must-have, OCA Verified

#7560 3.x: Adds zero-argument non-private constructors to NonTransactionalEntityManager and ExtendedEntityManager
  integrations/cdi/jpa-cdi/src/main/java/io/helidon/integrations/cdi/jpa/ExtendedEntityManager.java
  integrations/cdi/jpa-cdi/src/main/java/io/helidon/integrations/cdi/jpa/NonTransactionalEntityManager.java
Labels: bug, P1, cdi, jpa/jta, 3.x, must-have, backport, OCA Verified

#7561 4.x: Adds zero-argument non-private constructors to NonTransactionalEntityManager and ExtendedEntityManager
  integrations/cdi/jpa-cdi/src/main/java/io/helidon/integrations/cdi/jpa/ExtendedEntityManager.java
  integrations/cdi/jpa-cdi/src/main/java/io/helidon/integrations/cdi/jpa/NonTransactionalEntityManager.java
Labels: bug, P1, cdi, jpa/jta, must-have, backport, 4.x, OCA Verified

#7556 4.x Refactor archetype metrics
  archetypes/helidon/src/main/archetype/common/extra.xml
  archetypes/helidon/src/main/archetype/common/observability.xml
  archetypes/helidon/src/main/archetype/mp/oci/oci-mp.xml
  archetypes/helidon/src/main/archetype/se/custom/observability.xml
Labels: archetypes, 4.x, OCA Verified

#7535 [3.x] Fix bug with empty Accept header
  openapi/src/main/java/io/helidon/openapi/OpenAPISupport.java
  openapi/src/test/java/io/helidon/openapi/ServerTest.java
Labels: 3.x, OCA Verified

#7551 4.x: Remove Helidon declarative annotation processors and example
  examples/fault-tolerance/pom.xml
  examples/fault-tolerance/src/main/java/io/helidon/examples/faulttolerance/AdminEndpoint.java
  examples/fault-tolerance/src/main/java/io/helidon/examples/faulttolerance/GreetEndpoint.java
  examples/fault-tolerance/src/main/java/io/helidon/examples/faulttolerance/PlatformExecutorProvider.java
  examples/fault-tolerance/src/main/java/io/helidon/examples/faulttolerance/package-info.java
  examples/fault-tolerance/src/main/resources/application.yaml
  examples/fault-tolerance/src/main/resources/logging.properties
  examples/fault-tolerance/src/test/java/io/helidon/examples/faulttolerance/FaultToleranceTest.java
  examples/pom.xml
  fault-tolerance/fault-tolerance/src/main/java/io/helidon/faulttolerance/AsyncInterceptor.java
  fault-tolerance/fault-tolerance/src/main/java/io/helidon/faulttolerance/BulkheadInterceptor.java
  fault-tolerance/fault-tolerance/src/main/java/io/helidon/faulttolerance/CircuitBreakerInterceptor.java
  fault-tolerance/fault-tolerance/src/main/java/io/helidon/faulttolerance/CircuitBreakerMethod.java
  fault-tolerance/fault-tolerance/src/main/java/io/helidon/faulttolerance/FallbackInterceptor.java
  fault-tolerance/fault-tolerance/src/main/java/io/helidon/faulttolerance/FallbackMethod.java
  fault-tolerance/fault-tolerance/src/main/java/io/helidon/faulttolerance/FaultTolerance.java
  fault-tolerance/fault-tolerance/src/main/java/io/helidon/faulttolerance/FtMethod.java
  fault-tolerance/fault-tolerance/src/main/java/io/helidon/faulttolerance/InterceptorBase.java
  fault-tolerance/fault-tolerance/src/main/java/io/helidon/faulttolerance/RetryInterceptor.java
  fault-tolerance/fault-tolerance/src/main/java/io/helidon/faulttolerance/RetryMethod.java
  fault-tolerance/fault-tolerance/src/main/java/io/helidon/faulttolerance/TimeoutInterceptor.java
  fault-tolerance/pom.xml
  fault-tolerance/processor/pom.xml
  fault-tolerance/processor/src/main/java/io/helidon/faulttolerance/processor/CircuitBreakerMethodCreator.java
  fault-tolerance/processor/src/main/java/io/helidon/faulttolerance/processor/FallbackMethodCreator.java
  fault-tolerance/processor/src/main/java/io/helidon/faulttolerance/processor/FtMethodCreatorBase.java
  fault-tolerance/processor/src/main/java/io/helidon/faulttolerance/processor/RetryMethodCreator.java
  fault-tolerance/processor/src/main/java/io/helidon/faulttolerance/processor/Templates.java
  fault-tolerance/processor/src/main/java/io/helidon/faulttolerance/processor/package-info.java
  fault-tolerance/processor/src/main/java/module-info.java
  fault-tolerance/processor/src/main/resources/templates/inject/circuit-breaker-method.java.hbs
  fault-tolerance/processor/src/main/resources/templates/inject/fallback-method.java.hbs
  fault-tolerance/processor/src/main/resources/templates/inject/retry-method.java.hbs
  http/http/src/main/java/io/helidon/http/Endpoint.java
  http/pom.xml
  http/processor/pom.xml
  http/processor/src/main/java/io/helidon/http/processor/HttpCreatorBase.java
  http/processor/src/main/java/io/helidon/http/processor/HttpEndpointCreator.java
  http/processor/src/main/java/io/helidon/http/processor/HttpMethodCreator.java
  http/processor/src/main/java/io/helidon/http/processor/Templates.java
  http/processor/src/main/java/io/helidon/http/processor/package-info.java
  http/processor/src/main/java/module-info.java
  http/processor/src/main/resources/templates/inject/helidon/http-endpoint.java.hbs
  http/processor/src/main/resources/templates/inject/helidon/http-method.java.hbs
  inject/api/src/main/java/io/helidon/inject/api/Helidon.java
  inject/configdriven/runtime/pom.xml
  inject/configdriven/runtime/src/main/java/module-info.java
Labels: 4.x, pico, OCA Verified

#7569 4.x: release workflow
  .github/workflows/release.yaml
  .github/workflows/snapshotrelease.yaml
  Jenkinsfile
  etc/scripts/includes/pipeline-env.sh
  etc/scripts/release.sh
Labels: build, 4.x, OCA Verified

#7563 [4.x] OciExtension refinements
  integrations/oci/sdk/runtime/etc/spotbugs/exclude.xml
  integrations/oci/sdk/runtime/src/main/java/io/helidon/integrations/oci/sdk/runtime/OciAuthenticationDetailsProvider.java
  integrations/oci/sdk/runtime/src/main/java/io/helidon/integrations/oci/sdk/runtime/OciExtension.java
  integrations/oci/sdk/runtime/src/test/java/io/helidon/integrations/oci/sdk/runtime/OciExtensionTest.java
Labels: 4.x, OCA Verified

#7575 1.x: Upgrade dependency-check-maven plugin and add suppression
  etc/dependency-check-suppression.xml
  pom.xml
Labels: 1.x, OCA Verified

#7574 2.x: Upgrade dependency-check-maven plugin and add suppression
  etc/dependency-check-suppression.xml
  pom.xml
Labels: 2.x, OCA Verified

#7573 3.x: Upgrade dependency-check-maven plugin and add suppression
  etc/dependency-check-suppression.xml
  pom.xml
Labels: 3.x, OCA Verified

#7376 2.x Replace try/catch in tests on assertThrows
  common/reactive/src/test/java/io/helidon/common/reactive/SingleTest.java
  config/config-mp/src/test/java/io/helidon/config/mp/MpMetaConfigTest.java
  config/hocon-mp/src/test/java/io/helidon/config/hocon/mp/HoconJsonMpMetaConfigTest.java
  config/yaml-mp/src/test/java/io/helidon/config/yaml/mp/YamlMpMetaConfigTest.java
  security/jwt/src/test/java/io/helidon/security/jwt/SignedJwtTest.java
Labels: OCA Verified

#7344 3.x Replace try/catch in tests on assertThrows
  common/reactive/src/test/java/io/helidon/common/reactive/SingleTest.java
  config/config-mp/src/test/java/io/helidon/config/mp/MpMetaConfigTest.java
  config/hocon-mp/src/test/java/io/helidon/config/hocon/mp/HoconJsonMpMetaConfigTest.java
  config/yaml-mp/src/test/java/io/helidon/config/yaml/mp/YamlMpMetaConfigTest.java
  security/jwt/src/test/java/io/helidon/security/jwt/SignedJwtTest.java
Labels: OCA Verified

#7576 [3.x] backport of OciExtension Refinements
  integrations/oci/sdk/runtime/etc/spotbugs/exclude.xml
  integrations/oci/sdk/runtime/src/main/java/io/helidon/integrations/oci/sdk/runtime/OciAuthenticationDetailsProvider.java
  integrations/oci/sdk/runtime/src/main/java/io/helidon/integrations/oci/sdk/runtime/OciExtension.java
  integrations/oci/sdk/runtime/src/test/java/io/helidon/integrations/oci/sdk/runtime/OciExtensionTest.java
Labels: 3.x, backport, OCA Verified

#7579 Restore test of model reader and filter
  microprofile/openapi/src/test/java/io/helidon/microprofile/openapi/TestFilterAndModelReader.java
Labels: OCA Verified

#7373 4.x: Adjusts CDI OciExtension to use runtime OciExtension for certain authentication tasks
  integrations/oci/sdk/cdi/pom.xml
  integrations/oci/sdk/cdi/src/main/java/io/helidon/integrations/oci/sdk/cdi/AdpSelectionStrategy.java
  integrations/oci/sdk/cdi/src/main/java/io/helidon/integrations/oci/sdk/cdi/OciExtension.java
  integrations/oci/sdk/cdi/src/main/java/module-info.java
  integrations/oci/sdk/cdi/src/test/java/io/helidon/integrations/oci/sdk/cdi/TestOciSdkRuntimeOciExtension.java
Labels: MP, P4, cdi, OCI, 4.x, OCA Verified, microprofile

#7555 3.x: Introduces OciSecretsMpMetaConfigProvider, which adapts OciSecretsConfigSourceProvider to the MpMetaConfigProvider contract
  bom/pom.xml
  integrations/oci/oci-secrets-mp-config-source/pom.xml
  integrations/oci/oci-secrets-mp-config-source/src/main/java/io/helidon/integrations/oci/secrets/mp/configsource/OciSecretsMpMetaConfigProvider.java
  integrations/oci/oci-secrets-mp-config-source/src/main/java/io/helidon/integrations/oci/secrets/mp/configsource/package-info.java
  integrations/oci/oci-secrets-mp-config-source/src/main/java/module-info.java
  integrations/oci/oci-secrets-mp-config-source/src/test/java/io/helidon/integrations/oci/oci-secrets-mp-config-source/src/test/java/UsageTest.java
  integrations/oci/oci-secrets-mp-config-source/src/test/java/logging.properties
  integrations/oci/oci-secrets-mp-config-source/src/test/resources/mp-meta-config.yaml
  integrations/oci/pom.xml
Labels: MP, config, P2, 3.x, OCI, backport, OCA Verified

#7587 4.x: Allowed cipher suite test added
  webserver/testing/junit5/junit5/src/main/java/io/helidon/webserver/testing/junit5/HelidonServerJunitExtension.java
  webserver/tests/webserver/src/test/java/io/helidon/webserver/tests/CipherSuiteTest.java
  webserver/tests/webserver/src/test/resources/certificate.p12
  webserver/tests/webserver/src/test/resources/cipherSuiteConfig.yaml
Labels: OCA Verified

#7585 Use requested URI info in CORS decision-making
  cors/src/main/java/io/helidon/cors/CorsRequestAdapter.java
  cors/src/main/java/io/helidon/cors/CorsSupportHelper.java
  cors/src/main/java/io/helidon/cors/LogHelper.java
  docs/includes/cors.adoc
  docs/mp/cors/cors.adoc
  docs/se/cors.adoc
  microprofile/cors/src/main/java/io/helidon/microprofile/cors/CorsSupportMp.java
  microprofile/server/src/main/java/io/helidon/microprofile/server/JaxRsService.java
  webserver/cors/src/main/java/io/helidon/webserver/cors/CorsServerRequestAdapter.java
Labels: OCA Verified

#7594 1.x: Upgrade jgit to 6.7.0
  config/git/pom.xml
  config/git/src/test/java/io/helidon/config/git/GitConfigSourceBuilderTest.java
  pom.xml
Labels: 1.x, dependencies, OCA Verified

#7592 3.x: Upgrade jgit to 6.7.0
  config/git/src/test/java/io/helidon/config/git/GitConfigSourceBuilderTest.java
  dependencies/pom.xml
Labels: dependencies, 3.x, OCA Verified

#7593 2.x: Upgrade jgit to 6.7.0
  config/git/src/test/java/io/helidon/config/git/GitConfigSourceBuilderTest.java
  dependencies/pom.xml
Labels: 2.x, dependencies, OCA Verified

#7588 4.x: Checkstyle suppression in code
  DEV-GUIDELINES.md
  config/config/src/main/java/io/helidon/config/ClasspathConfigSource.java
  etc/checkstyle-suppressions.xml
  etc/checkstyle.xml
  microprofile/lra/jax-rs/src/main/java/io/helidon/microprofile/lra/NonJaxRsResource.java
  microprofile/reactive-streams/src/main/java/io/helidon/microprofile/reactive/HelidonReactiveStreamsEngine.java
  webserver/http2/src/main/java/io/helidon/webserver/http2/spi/Http2SubProtocolSelector.java
  webserver/webserver/src/main/java/io/helidon/webserver/http1/Http1ServerRequest.java
Labels: build, 4.x, OCA Verified

#7590 4.x: Mark inject processor as preview (warning when executed).
  config/config/pom.xml
  config/tests/service-registry/pom.xml
  examples/inject/basics/pom.xml
  examples/inject/interceptors/pom.xml
  examples/inject/providers/pom.xml
  inject/processor/src/main/java/io/helidon/inject/processor/BaseAnnotationProcessor.java
  inject/tests/interception/pom.xml
  inject/tests/resources-inject/pom.xml
  inject/tools/src/main/java/io/helidon/inject/tools/Options.java
Labels: 4.x, OCA Verified

#7607 4.x: Intermittent OciCertificatesTlsManagerTest fix
  integrations/oci/tls-certificates/src/test/java/io/helidon/integrations/oci/tls/certificates/OciCertificatesTlsManagerTest.java
  integrations/oci/tls-certificates/src/test/resources/application.yaml
Labels: OCA Verified

#7608 4.x: Introducing request and response stream filters to server.
  http/encoding/deflate/src/main/java/io/helidon/http/encoding/deflate/DeflateEncoding.java
  http/encoding/encoding/src/main/java/io/helidon/http/encoding/ContentDecoder.java
  http/encoding/encoding/src/main/java/io/helidon/http/encoding/ContentEncoder.java
  http/encoding/gzip/src/main/java/io/helidon/http/encoding/gzip/GzipEncoding.java
  tracing/tests/it-tracing-client-zipkin/src/test/java/io/helidon/tracing/tests/it1/OpenTraceableClientE2ETest.java
  tracing/tests/it-tracing-client-zipkin/src/test/resources/logging.properties
  webclient/tests/webclient/src/test/java/io/helidon/webclient/tests/TracingPropagationTest.java
  webserver/http2/src/main/java/io/helidon/webserver/http2/Http2ServerRequest.java
  webserver/http2/src/main/java/io/helidon/webserver/http2/Http2ServerRequestEntity.java
  webserver/http2/src/main/java/io/helidon/webserver/http2/Http2ServerResponse.java
  webserver/tracing/src/main/java/io/helidon/webserver/tracing/TracingFeature.java
  webserver/webserver/src/main/java/io/helidon/webserver/http/ServerRequest.java
  webserver/webserver/src/main/java/io/helidon/webserver/http/ServerRequestEntity.java
  webserver/webserver/src/main/java/io/helidon/webserver/http/ServerResponse.java
  webserver/webserver/src/main/java/io/helidon/webserver/http/ServerResponseBase.java
  webserver/webserver/src/main/java/io/helidon/webserver/http1/Http1ServerRequestNoEntity.java
  webserver/webserver/src/main/java/io/helidon/webserver/http1/Http1ServerRequestWithEntity.java
  webserver/webserver/src/main/java/io/helidon/webserver/http1/Http1ServerResponse.java
Labels: tracing, webserver, 4.x, OCA Verified

#7595 4.x: Upgrade jboss logging to 3.5.3.Final
  dependencies/pom.xml
  microprofile/cdi/src/main/java/module-info.java
Labels: dependencies, 4.x, OCA Verified

#7596 3.x: Upgrade jboss logging to 3.5.3.Final
  dependencies/pom.xml
  microprofile/cdi/src/main/java/module-info.java
Labels: dependencies, 3.x, OCA Verified

#7597 2.x: Upgrade jboss logging to 3.5.3.Final
  dependencies/pom.xml
  microprofile/cdi/src/main/java/module-info.java
Labels: 2.x, dependencies, OCA Verified

#7622 4.x: Fix MutualTlsTest and related issues
  common/tls/src/main/java/io/helidon/common/tls/Tls.java
  webclient/tests/webclient/src/test/java/io/helidon/webclient/tests/MutualTlsTest.java
  webserver/webserver/src/main/java/io/helidon/webserver/ServerListener.java
Labels: webserver, P1, 4.x, OCA Verified

#7621 4.x: Upgrade zipkin-sender-urlconnection to 2.16.4
  dependencies/pom.xml
Labels: dependencies, 4.x, OCA Verified

#7623 4.x: Deprecate support for etcd v2
  config/etcd/src/main/java/io/helidon/config/etcd/EtcdConfigSourceBuilder.java
  config/etcd/src/main/java/io/helidon/config/etcd/internal/client/v2/EtcdV2Client.java
  docs/se/config/supported-formats.adoc
Labels: config, 4.x, OCA Verified

#7624 4.x: Upgrade io.dropwizard.metrics:metrics-core to 4.1.36
  dependencies/pom.xml
Labels: dependencies, 4.x, OCA Verified

#7626 4.x: Re-enables microprofile/server/ServerSseTest.java
  microprofile/server/src/test/java/io/helidon/microprofile/server/ServerSseTest.java
Labels: jax-rs, P2, testing, java, 4.x, Níma, OCA Verified

#7616 [3.x] Fix parent for TestNG project
  microprofile/tests/testng/pom.xml
  microprofile/tests/testng/src/main/java/io/helidon/microprofile/tests/testng/Configuration.java
Labels: bug, P2, 3.x, OCA Verified

#7633 4.x: HTTP/2 server 100-continue
  http/http2/src/main/java/io/helidon/http/http2/Http2Stream.java
  pom.xml
  webclient/http2/src/main/java/io/helidon/webclient/http2/Http2CallOutputStreamChain.java
  webclient/http2/src/main/java/io/helidon/webclient/http2/Http2ClientStream.java
  webclient/tests/http2/src/test/java/io/helidon/webclient/tests/http2/HeadersTest.java
  webserver/http2/src/main/java/io/helidon/webserver/http2/Http2ServerStream.java
  webserver/tests/http2/pom.xml
  webserver/tests/http2/src/test/java/io/helidon/webserver/tests/http2/Continue100Test.java
Labels: OCA Verified

#7635 [3.x] - Upgrade Neo4j to v.5
  dependencies/pom.xml
  examples/integrations/neo4j/neo4j-mp/pom.xml
  examples/integrations/neo4j/neo4j-se/pom.xml
  examples/integrations/neo4j/neo4j-se/src/test/java/io/helidon/examples/quickstart/se/MainTest.java
  integrations/neo4j/health/pom.xml
  integrations/neo4j/health/src/main/java/io/helidon/integrations/neo4j/health/Neo4jHealthCheck.java
  integrations/neo4j/metrics/pom.xml
  integrations/neo4j/neo4j/pom.xml
Labels: 3.x, integration, OCA Verified

#7636 [4.x] - Upgrade Neo4j to v.5
  dependencies/pom.xml
  examples/integrations/neo4j/pom.xml
  integrations/neo4j/health/pom.xml
  integrations/neo4j/health/src/main/java/io/helidon/integrations/neo4j/health/Neo4jHealthCheck.java
  integrations/neo4j/metrics/pom.xml
  integrations/neo4j/neo4j/pom.xml
Labels: integration, 4.x, OCA Verified

#7582 [4.x] Modifies Helidon Connector to use WebClient and also support HTTP/2
  jersey/connector/pom.xml
  jersey/connector/src/main/java/io/helidon/jersey/connector/HelidonConnector.java
  jersey/connector/src/main/java/io/helidon/jersey/connector/HelidonConnectorProvider.java
  jersey/connector/src/main/java/io/helidon/jersey/connector/HelidonProperties.java
  jersey/connector/src/main/java/module-info.java
  jersey/connector/src/test/java/io/helidon/jersey/connector/ConfigTest.java
  jersey/tests/connector/pom.xml
  jersey/tests/connector/src/test/java/io/helidon/jersey/connector/ConnectorBase.java
  jersey/tests/connector/src/test/java/io/helidon/jersey/connector/ConnectorHttp1Test.java
  jersey/tests/connector/src/test/java/io/helidon/jersey/connector/ConnectorHttp2AlpnTest.java
  jersey/tests/connector/src/test/java/io/helidon/jersey/connector/ConnectorHttp2PriorTest.java
  jersey/tests/connector/src/test/java/io/helidon/jersey/connector/ConnectorHttp2UpgradeTest.java
  jersey/tests/connector/src/test/resources/certificate.p12
  webclient/http2/src/main/java/module-info.java
Labels: integration, 4.x, OCA Verified

#7638 [3.x] archetypes does not offer a metrics provider choice for custom/se
  archetypes/helidon/filters.properties
  archetypes/helidon/pom.xml
  archetypes/helidon/src/main/archetype/common/observability.xml
  archetypes/helidon/src/main/cli/versions.xml.mustache
Labels: 3.x, archetypes, OCA Verified

#7645 3.x: Suppress jgit false positive
  etc/dependency-check-suppression.xml
Labels: 3.x, OCA Verified

#7571 DOCS: 4x overview and general intro doc updates
  docs/about/archetype.adoc
  docs/about/benefits.adoc
  docs/about/doc_overview.adoc
  docs/about/intro.adoc
  docs/about/introduction.adoc
  docs/mp/testing-ng.adoc
  docs/mp/testing.adoc
  docs/se/introduction.adoc
  docs/se/sse/sse.adoc
  docs/sitegen.yaml
Labels: docs, 4.x, OCA Verified

#7654 Removes Jedis integration to reduce technical debt
  bom/pom.xml
  dependencies/pom.xml
  docs/includes/attributes.adoc
  docs/mp/integrations/jedis.adoc
  docs/sitegen.yaml
  etc/HELIDON_THIRD_PARTY_LICENSES.xml
  examples/integrations/cdi/datasource-hikaricp/pom.xml
  examples/integrations/cdi/jedis/.dockerignore
  examples/integrations/cdi/jedis/Dockerfile
  examples/integrations/cdi/jedis/README.md
  examples/integrations/cdi/jedis/app.yaml
  examples/integrations/cdi/jedis/pom.xml
  examples/integrations/cdi/jedis/redis.yaml
  examples/integrations/cdi/jedis/src/main/java/io/helidon/examples/integrations/jedis/jaxrs/RedisClientResource.java
  examples/integrations/cdi/jedis/src/main/java/io/helidon/examples/integrations/jedis/jaxrs/package-info.java
  examples/integrations/cdi/jedis/src/main/resources/META-INF/beans.xml
  examples/integrations/cdi/jedis/src/main/resources/META-INF/microprofile-config.properties
  examples/integrations/cdi/pom.xml
  integrations/cdi/README.md
  integrations/cdi/jedis-cdi/README.md
  integrations/cdi/jedis-cdi/pom.xml
  integrations/cdi/jedis-cdi/src/main/java/io/helidon/integrations/jedis/cdi/JedisExtension.java
  integrations/cdi/jedis-cdi/src/main/java/io/helidon/integrations/jedis/cdi/package-info.java
  integrations/cdi/jedis-cdi/src/main/java/module-info.java
  integrations/cdi/jedis-cdi/src/main/resources/META-INF/beans.xml
  integrations/cdi/jedis-cdi/src/test/java/io/helidon/integrations/jedis/cdi/TestExtension.java
  integrations/cdi/jedis-cdi/src/test/resources/META-INF/beans.xml
  integrations/cdi/jedis-cdi/src/test/resources/META-INF/microprofile-config.properties
  integrations/cdi/pom.xml
Labels: MP, docs, P2, cdi, dependencies, integration, 4.x, OCA Verified

#7653 4.x: Update workflows to Oracle JDK 21 LTS
  .github/workflows/release.yaml
  .github/workflows/snapshotrelease.yaml
  .github/workflows/validate.yml
Labels: build, 4.x, OCA Verified

#7651 4.x: Upgrade mongodb driver to 4.10.2
  dependencies/pom.xml
Labels: dependencies, 4.x, OCA Verified

#7655 4.x: Update examples to use Config.global(config)
  examples/cors/src/main/java/io/helidon/examples/cors/GreetService.java
  examples/cors/src/main/java/io/helidon/examples/cors/Main.java
  examples/cors/src/test/java/io/helidon/examples/cors/MainTest.java
  examples/integrations/micrometer/se/src/main/java/io/helidon/examples/integrations/micrometer/se/GreetService.java
  examples/integrations/micrometer/se/src/main/java/io/helidon/examples/integrations/micrometer/se/Main.java
  examples/integrations/micrometer/se/src/test/java/io/helidon/examples/integrations/micrometer/se/MainTest.java
  examples/metrics/exemplar/src/main/java/io/helidon/examples/metrics/exemplar/GreetService.java
  examples/metrics/exemplar/src/main/java/io/helidon/examples/metrics/exemplar/Main.java
  examples/metrics/exemplar/src/test/java/io/helidon/examples/metrics/exemplar/MainTest.java
  examples/metrics/filtering/se/src/main/java/io/helidon/examples/metrics/filtering/se/GreetService.java
  examples/metrics/filtering/se/src/main/java/io/helidon/examples/metrics/filtering/se/Main.java
  examples/metrics/filtering/se/src/test/java/io/helidon/examples/metrics/filtering/se/MainTest.java
  examples/metrics/http-status-count-se/src/main/java/io/helidon/examples/se/httpstatuscount/GreetService.java
  examples/metrics/http-status-count-se/src/main/java/io/helidon/examples/se/httpstatuscount/Main.java
  examples/metrics/http-status-count-se/src/main/java/io/helidon/examples/se/httpstatuscount/SimpleGreetService.java
  examples/metrics/http-status-count-se/src/test/java/io/helidon/examples/se/httpstatuscount/StatusTest.java
  examples/metrics/kpi/src/main/java/io/helidon/examples/metrics/kpi/GreetService.java
  examples/metrics/kpi/src/main/java/io/helidon/examples/metrics/kpi/Main.java
  examples/openapi/src/main/java/io/helidon/examples/openapi/GreetService.java
  examples/openapi/src/main/java/io/helidon/examples/openapi/Main.java
  examples/quickstarts/helidon-quickstart-se/src/main/java/io/helidon/examples/quickstart/se/GreetService.java
  examples/quickstarts/helidon-quickstart-se/src/main/java/io/helidon/examples/quickstart/se/Main.java
  examples/quickstarts/helidon-standalone-quickstart-se/pom.xml
  examples/quickstarts/helidon-standalone-quickstart-se/src/main/java/io/helidon/examples/quickstart/se/GreetService.java
  examples/quickstarts/helidon-standalone-quickstart-se/src/main/java/io/helidon/examples/quickstart/se/Main.java
  examples/webclient/standalone/src/main/java/io/helidon/examples/webclient/standalone/GreetService.java
  examples/webclient/standalone/src/main/java/io/helidon/examples/webclient/standalone/ServerMain.java
  examples/webclient/standalone/src/test/java/io/helidon/examples/webclient/standalone/ClientMainTest.java
  examples/webserver/imperative/src/main/java/io/helidon/examples/webserver/imperative/ImperativeMain.java
  examples/webserver/multiport/src/main/java/io/helidon/webserver/examples/multiport/Main.java
  examples/webserver/multiport/src/test/java/io/helidon/webserver/examples/multiport/MainTest.java
Labels: examples, 4.x, OCA Verified

#7649 4.x: Server side trailers #7647
  http/http/src/main/java/io/helidon/http/ServerResponseTrailers.java
  http/http/src/main/java/io/helidon/http/ServerResponseTrailersImpl.java
  webclient/http2/src/main/java/io/helidon/webclient/http2/Http2CallEntityChain.java
  webclient/http2/src/main/java/io/helidon/webclient/http2/Http2CallOutputStreamChain.java
  webclient/http2/src/main/java/io/helidon/webclient/http2/Http2ClientStream.java
  webclient/tests/http1/src/test/java/io/helidon/webclient/tests/HeadersClientTest.java
  webclient/tests/http2/src/test/java/io/helidon/webclient/tests/http2/HeadersClientTest.java
  webserver/http2/src/main/java/io/helidon/webserver/http2/Http2ServerResponse.java
  webserver/http2/src/main/java/io/helidon/webserver/http2/Http2ServerStream.java
  webserver/tests/http2/src/test/java/io/helidon/webserver/tests/http2/Continue100Test.java
  webserver/tests/http2/src/test/java/io/helidon/webserver/tests/http2/HeadersServerTest.java
  webserver/tests/webserver/src/test/java/io/helidon/webserver/tests/HeadersServerTest.java
  webserver/webserver/src/main/java/io/helidon/webserver/http/ServerResponse.java
  webserver/webserver/src/main/java/io/helidon/webserver/http/ServerResponseBase.java
  webserver/webserver/src/main/java/io/helidon/webserver/http1/Http1ServerResponse.java
Labels: OCA Verified

#7657 4.x: double-slash URI issue #7474
  common/uri/src/main/java/io/helidon/common/uri/UriPathNoParam.java
  common/uri/src/test/java/io/helidon/common/uri/UriPathTest.java
  webclient/tests/webclient/src/test/java/io/helidon/webclient/tests/TracingPropagationTest.java
Labels: OCA Verified

#7662 4.x: Upgrades Narayana to version 7.0.0.Final
  dependencies/pom.xml
  integrations/cdi/jta-cdi/pom.xml
  integrations/cdi/jta-cdi/src/main/java/module-info.java
  integrations/cdi/jta-weld/pom.xml
  integrations/cdi/jta-weld/src/main/java/module-info.java
  integrations/jta/jdbc/pom.xml
  integrations/jta/jdbc/src/main/java/io/helidon/integrations/jta/jdbc/JtaConnection.java
  tests/integration/jpa/appl/pom.xml
Labels: MP, P2, jpa/jta, dependencies, java, 4.x, OCA Verified

#7664 4.x: demonstrate proper use of GlobalConfig in archetypes
  archetypes/helidon/src/main/archetype/common/observability.xml
  archetypes/helidon/src/main/archetype/mp/custom/files/src/test/java/__pkg__/TestCORS.java.mustache
  archetypes/helidon/src/main/archetype/mp/oci/files/server/src/test/java/__pkg__/server/GreetResourceConfigFileTest.java.mustache
  archetypes/helidon/src/main/archetype/se/common/common-se.xml
  archetypes/helidon/src/main/archetype/se/common/files/src/main/java/__pkg__/Main.java.mustache
  archetypes/helidon/src/main/archetype/se/common/files/src/test/java/__pkg__/AbstractMainTest.java.mustache
  archetypes/helidon/src/main/archetype/se/custom/files/src/main/java/__pkg__/GreetService.java.json.mustache
  archetypes/helidon/src/main/archetype/se/custom/files/src/main/java/__pkg__/GreetService.java.jsonp.mustache
  archetypes/helidon/src/main/archetype/se/custom/files/src/main/java/__pkg__/GreetService.java.mustache
  archetypes/helidon/src/main/archetype/se/custom/files/src/main/java/__pkg__/MetricsService.java.mustache
  archetypes/helidon/src/main/archetype/se/custom/files/src/main/java/__pkg__/WebClientMain.java.mustache
  archetypes/helidon/src/main/archetype/se/quickstart/files/src/main/java/__pkg__/GreetClientHttp.java.mustache
Labels: archetypes, 4.x, OCA Verified

#7670 4.x: fix archetypes code formatting
  archetypes/helidon/src/main/archetype/common/observability.xml
  archetypes/helidon/src/main/archetype/se/common/files/src/main/java/__pkg__/Main.java.mustache
  archetypes/helidon/src/main/archetype/se/custom/observability.xml
Labels: archetypes, 4.x, OCA Verified

#7666 Make SE metrics default scope application instead of nothing
  archetypes/helidon/src/main/archetype/common/observability.xml
  examples/metrics/exemplar/src/test/java/io/helidon/examples/metrics/exemplar/MainTest.java
  examples/metrics/filtering/se/src/main/java/io/helidon/examples/metrics/filtering/se/GreetService.java
  examples/metrics/filtering/se/src/main/java/io/helidon/examples/metrics/filtering/se/Main.java
  examples/metrics/filtering/se/src/test/java/io/helidon/examples/metrics/filtering/se/MainTest.java
  examples/metrics/http-status-count-se/src/main/java/io/helidon/examples/se/httpstatuscount/HttpStatusMetricService.java
  examples/metrics/http-status-count-se/src/main/java/io/helidon/examples/se/httpstatuscount/Main.java
  examples/metrics/http-status-count-se/src/test/java/io/helidon/examples/se/httpstatuscount/MainTest.java
  examples/metrics/http-status-count-se/src/test/java/io/helidon/examples/se/httpstatuscount/StatusTest.java
  examples/metrics/kpi/src/test/java/io/helidon/examples/metrics/kpi/MainTest.java
  metrics/api/src/main/java/io/helidon/metrics/api/NoOpMeter.java
  metrics/api/src/main/java/io/helidon/metrics/api/ScopingConfigBlueprint.java
  metrics/provider-tests/src/main/java/io/helidon/metrics/provider/tests/TestScopeManagement.java
  metrics/providers/micrometer/src/main/java/io/helidon/metrics/providers/micrometer/MMeterRegistry.java
Labels: metrics, 4.x, OCA Verified

#7639 Fixed DbClient H2 tests.
  dbclient/dbclient/src/main/java/io/helidon/dbclient/DbClientBuilderBase.java
  dbclient/jdbc/src/main/java/io/helidon/dbclient/jdbc/JdbcStatement.java
  dbclient/jdbc/src/main/java/io/helidon/dbclient/jdbc/JdbcTransactionStatement.java
  tests/integration/dbclient/app/src/main/resources/logging.properties
  tests/integration/dbclient/app/src/test/resources/logging.properties
  tests/integration/dbclient/common/pom.xml
  tests/integration/dbclient/common/src/main/java/io/helidon/tests/integration/dbclient/common/spi/SetupProvider.java
  tests/integration/dbclient/common/src/main/java/io/helidon/tests/integration/dbclient/common/tests/DbClientParameterResolver.java
  tests/integration/dbclient/common/src/main/java/io/helidon/tests/integration/dbclient/common/tests/ExceptionalStmtIT.java
  tests/integration/dbclient/common/src/main/java/io/helidon/tests/integration/dbclient/common/tests/FlowControlIT.java
  tests/integration/dbclient/common/src/main/java/io/helidon/tests/integration/dbclient/common/tests/GetStatementIT.java
  tests/integration/dbclient/common/src/main/java/io/helidon/tests/integration/dbclient/common/tests/HealthCheckIT.java
  tests/integration/dbclient/common/src/main/java/io/helidon/tests/integration/dbclient/common/tests/InterceptorIT.java
  tests/integration/dbclient/common/src/main/java/io/helidon/tests/integration/dbclient/common/tests/MapperIT.java
  tests/integration/dbclient/common/src/main/java/io/helidon/tests/integration/dbclient/common/tests/QueryStatementIT.java
  tests/integration/dbclient/common/src/main/java/io/helidon/tests/integration/dbclient/common/tests/ServerHealthCheckIT.java
  tests/integration/dbclient/common/src/main/java/io/helidon/tests/integration/dbclient/common/tests/ServerMetricsCheckIT.java
  tests/integration/dbclient/common/src/main/java/io/helidon/tests/integration/dbclient/common/tests/SimpleDeleteIT.java
  tests/integration/dbclient/common/src/main/java/io/helidon/tests/integration/dbclient/common/tests/SimpleDmlIT.java
  tests/integration/dbclient/common/src/main/java/io/helidon/tests/integration/dbclient/common/tests/SimpleGetIT.java
  tests/integration/dbclient/common/src/main/java/io/helidon/tests/integration/dbclient/common/tests/SimpleInsertIT.java
  tests/integration/dbclient/common/src/main/java/io/helidon/tests/integration/dbclient/common/tests/SimpleQueriesIT.java
  tests/integration/dbclient/common/src/main/java/io/helidon/tests/integration/dbclient/common/tests/SimpleUpdateIT.java
  tests/integration/dbclient/common/src/main/java/io/helidon/tests/integration/dbclient/common/tests/StatementDmlIT.java
  tests/integration/dbclient/common/src/main/java/io/helidon/tests/integration/dbclient/common/tests/TransactionDeleteIT.java
  tests/integration/dbclient/common/src/main/java/io/helidon/tests/integration/dbclient/common/tests/TransactionExceptionalStmtIT.java
  tests/integration/dbclient/common/src/main/java/io/helidon/tests/integration/dbclient/common/tests/TransactionGetIT.java
  tests/integration/dbclient/common/src/main/java/io/helidon/tests/integration/dbclient/common/tests/TransactionInsertIT.java
  tests/integration/dbclient/common/src/main/java/io/helidon/tests/integration/dbclient/common/tests/TransactionQueriesIT.java
  tests/integration/dbclient/common/src/main/java/io/helidon/tests/integration/dbclient/common/tests/TransactionUpdateIT.java
  tests/integration/dbclient/common/src/main/java/io/helidon/tests/integration/dbclient/common/utils/MapperProvider.java
  tests/integration/dbclient/common/src/main/java/io/helidon/tests/integration/dbclient/common/utils/TestConfig.java
  tests/integration/dbclient/common/src/main/java/module-info.java
  tests/integration/dbclient/common/src/main/resources/META-INF/services/io.helidon.dbclient.spi.DbMapperProvider
  tests/integration/dbclient/h2/pom.xml
  tests/integration/dbclient/h2/src/main/java/io/helidon/tests/integration/dbclient/jdbc/H2SetupProvider.java
  tests/integration/dbclient/h2/src/main/java/module-info.java
  tests/integration/dbclient/h2/src/test/java/io/helidon/tests/integration/dbclient/jdbc/H2SuiteIT.java
  tests/integration/dbclient/h2/src/test/resources/h2.yaml
  tests/integration/dbclient/pom.xml
  tests/integration/harness/src/main/java/io/helidon/tests/integration/harness/SuiteLifeCycle.java
  tests/integration/harness/src/main/java/module-info.java
Labels: OCA Verified

#7602 3.x: TargetKeys Map changed to ConcurrentHashMap
  security/providers/http-sign/src/main/java/io/helidon/security/providers/httpsign/HttpSignProvider.java
Labels: OCA Verified

#7601 2.x: TargetKeys Map changed to ConcurrentHashMap
  security/providers/http-sign/src/main/java/io/helidon/security/providers/httpsign/HttpSignProvider.java
Labels: OCA Verified

#7603 4.x: TargetKeys Map changed to ConcurrentHashMap
  security/providers/http-sign/src/main/java/io/helidon/security/providers/httpsign/HttpSignProvider.java
Labels: OCA Verified

#7676 4.x: Remove prefetch #7663
  webclient/http2/src/main/java/io/helidon/webclient/http2/Http2ClientConnection.java
  webclient/http2/src/main/java/io/helidon/webclient/http2/Http2ClientProtocolConfigBlueprint.java
  webclient/tests/http2/src/test/java/io/helidon/webclient/tests/http2/ClientFlowControlTest.java
Labels: OCA Verified

#7650 [3x] TlsManager backport
  bom/pom.xml
  common/key-util/src/main/java/io/helidon/common/pki/PemReader.java
  integrations/oci/pom.xml
  integrations/oci/tls-certificates/README.md
  integrations/oci/tls-certificates/etc/spotbugs/exclude.xml
  integrations/oci/tls-certificates/pom.xml
  integrations/oci/tls-certificates/src/main/java/io/helidon/integrations/oci/tls/certificates/DefaultOciCertificatesDownloader.java
  integrations/oci/tls-certificates/src/main/java/io/helidon/integrations/oci/tls/certificates/DefaultOciCertificatesTlsManager.java
  integrations/oci/tls-certificates/src/main/java/io/helidon/integrations/oci/tls/certificates/DefaultOciCertificatesTlsManagerProvider.java
  integrations/oci/tls-certificates/src/main/java/io/helidon/integrations/oci/tls/certificates/DefaultOciPrivateKeyDownloader.java
  integrations/oci/tls-certificates/src/main/java/io/helidon/integrations/oci/tls/certificates/InjectionServices.java
  integrations/oci/tls-certificates/src/main/java/io/helidon/integrations/oci/tls/certificates/LifecycleHook.java
  integrations/oci/tls-certificates/src/main/java/io/helidon/integrations/oci/tls/certificates/OciCertificatesTlsManager.java
  integrations/oci/tls-certificates/src/main/java/io/helidon/integrations/oci/tls/certificates/OciCertificatesTlsManagerConfig.java
  integrations/oci/tls-certificates/src/main/java/io/helidon/integrations/oci/tls/certificates/OciCertificatesTlsManagerConfigBlueprint.java
  integrations/oci/tls-certificates/src/main/java/io/helidon/integrations/oci/tls/certificates/package-info.java
  integrations/oci/tls-certificates/src/main/java/io/helidon/integrations/oci/tls/certificates/spi/OciCertificatesDownloader.java
  integrations/oci/tls-certificates/src/main/java/io/helidon/integrations/oci/tls/certificates/spi/OciPrivateKeyDownloader.java
  integrations/oci/tls-certificates/src/main/java/io/helidon/integrations/oci/tls/certificates/spi/package-info.java
  integrations/oci/tls-certificates/src/main/java/module-info.java
  integrations/oci/tls-certificates/src/test/java/io/helidon/integrations/oci/tls/certificates/OciCertificatesTlsManagerTest.java
  integrations/oci/tls-certificates/src/test/java/io/helidon/integrations/oci/tls/certificates/OciTestUtils.java
  integrations/oci/tls-certificates/src/test/java/io/helidon/integrations/oci/tls/certificates/TestOciCertificatesDownloader.java
  integrations/oci/tls-certificates/src/test/java/io/helidon/integrations/oci/tls/certificates/TestOciPrivateKeyDownloader.java
  integrations/oci/tls-certificates/src/test/java/io/helidon/integrations/oci/tls/certificates/TestingCdiExtension.java
  integrations/oci/tls-certificates/src/test/java/io/helidon/integrations/oci/tls/certificates/TestingConfigSource.java
  integrations/oci/tls-certificates/src/test/resources/META-INF/beans.xml
  integrations/oci/tls-certificates/src/test/resources/META-INF/services/io.helidon.integrations.oci.tls.certificates.LifecycleHook
  integrations/oci/tls-certificates/src/test/resources/META-INF/services/io.helidon.integrations.oci.tls.certificates.spi.OciCertificatesDownloader
  integrations/oci/tls-certificates/src/test/resources/META-INF/services/io.helidon.integrations.oci.tls.certificates.spi.OciPrivateKeyDownloader
  integrations/oci/tls-certificates/src/test/resources/META-INF/services/jakarta.enterprise.inject.spi.Extension
  integrations/oci/tls-certificates/src/test/resources/application.yaml
  integrations/oci/tls-certificates/src/test/resources/logging.properties
  integrations/oci/tls-certificates/src/test/resources/oci.yaml
  integrations/oci/tls-certificates/src/test/resources/test-keys/ca.pem
  integrations/oci/tls-certificates/src/test/resources/test-keys/keystore-chain.p12
  integrations/oci/tls-certificates/src/test/resources/test-keys/serverCert.pem
  integrations/oci/tls-certificates/src/test/resources/test-keys/serverKey.pem
  webserver/webserver/etc/spotbugs/exclude.xml
  webserver/webserver/src/main/java/io/helidon/webserver/ConfiguredTlsManager.java
  webserver/webserver/src/main/java/io/helidon/webserver/NettyWebServer.java
  webserver/webserver/src/main/java/io/helidon/webserver/TlsManager.java
  webserver/webserver/src/main/java/io/helidon/webserver/TrustAllManagerFactory.java
  webserver/webserver/src/main/java/io/helidon/webserver/WebServerTls.java
  webserver/webserver/src/main/java/io/helidon/webserver/spi/TlsManagerProvider.java
  webserver/webserver/src/main/java/module-info.java
  webserver/webserver/src/test/java/io/helidon/webserver/NettyWebServerTest.java
  webserver/webserver/src/test/java/io/helidon/webserver/ServerConfigurationTest.java
  webserver/webserver/src/test/java/io/helidon/webserver/WebServerTlsTest.java
  webserver/webserver/src/test/java/io/helidon/webserver/spi/FakeReloadableTlsManager.java
  webserver/webserver/src/test/java/io/helidon/webserver/spi/FakeTlsManagerProvider.java
  webserver/webserver/src/test/java/io/helidon/webserver/spi/TlsManagerProviderTest.java
  webserver/webserver/src/test/resources/META-INF/services/io.helidon.webserver.spi.TlsManagerProvider
  webserver/webserver/src/test/resources/config-with-ssl-and-tls-manager.conf
Labels: 3.x, OCA Verified

#7678 [4.x] - Move Opentracing to Helidon Tracing API
  integrations/common/rest/pom.xml
  integrations/common/rest/src/main/java/io/helidon/integrations/common/rest/RestApiBase.java
  integrations/common/rest/src/main/java/module-info.java
Labels: tracing, 4.x, OCA Verified

#7679 [3.x] - Move Opentracing to Helidon Tracing API
  integrations/common/rest/pom.xml
  integrations/common/rest/src/main/java/io/helidon/integrations/common/rest/RestApiBase.java
  integrations/common/rest/src/main/java/module-info.java
Labels: tracing, 3.x, OCA Verified

#7612 4.x: Move archetype metrics under `GreetService`
  archetypes/helidon/src/main/archetype/common/observability.xml
  archetypes/helidon/src/main/archetype/se/custom/files/src/main/java/__pkg__/MetricsService.java.mustache
  archetypes/helidon/src/main/archetype/se/custom/observability.xml
Labels: metrics, archetypes, 4.x, OCA Verified

#7572 4.x: metrics and openapi endpoints should be authorized by default
  metrics/api/src/main/java/io/helidon/metrics/api/MetricsConfigBlueprint.java
  microprofile/security/src/main/java/io/helidon/microprofile/security/SecurityPreMatchingFilter.java
  openapi/openapi/src/main/java/io/helidon/openapi/OpenApiFeature.java
  openapi/openapi/src/main/java/io/helidon/openapi/OpenApiFeatureConfigBlueprint.java
  webserver/observe/metrics/src/main/java/io/helidon/webserver/observe/metrics/MetricsFeature.java
  webserver/tests/observe/pom.xml
  webserver/tests/observe/security/pom.xml
  webserver/tests/observe/security/src/test/java/io/helidon/webserver/tests/observe/metrics/ObserveSecurityTest.java
  webserver/tests/observe/security/src/test/resources/META-INF/openapi.yml
  webserver/webserver/src/main/java/io/helidon/webserver/http/SecureHandler.java
Labels: enhancement, metrics, security, open-api, 4.x, OCA Verified

#7682 4.x release updates
  .github/workflows/release.yaml
  .github/workflows/validate.yml
  CHANGELOG.md
Labels: build, 4.x, OCA Verified

#7677 4.x: Upgrade ASM version used by plugins to 9.5
  pom.xml
Labels: build, 4.x, OCA Verified

#7685 3.x: Force upgrade snappy-java to 1.1.10.5
  dependencies/pom.xml
Labels: dependencies, 3.x, OCA Verified

#7684 Fix occurences of reactive in the docs
  docs/about/intro.adoc
  docs/includes/attributes.adoc
  docs/includes/cors.adoc
  docs/includes/security/helidon-endpoints.adoc
  docs/mp/cors/cors.adoc
  docs/mp/guides/mp-tutorial.adoc
  docs/mp/guides/se-services.adoc
  docs/mp/integrations/hcv.adoc
  docs/mp/jaxrs/jaxrs-applications.adoc
  docs/mp/server.adoc
  docs/se/dbclient.adoc
  docs/se/guides/dbclient.adoc
  docs/se/guides/metrics.adoc
  docs/se/guides/migration.adoc
  docs/se/guides/migration_3x.adoc
  docs/se/guides/overview.adoc
  docs/se/guides/security-oidc.adoc
  docs/se/guides/tracing.adoc
  docs/se/guides/webclient.adoc
  docs/se/health.adoc
  docs/se/inject/injection_intro.adoc
  docs/se/integrations/hcv.adoc
  docs/se/integrations/neo4j.adoc
  docs/se/introduction.adoc
  docs/se/metrics/metrics.adoc
  docs/se/metrics/micrometer.adoc
  docs/se/openapi/openapi-generator.adoc
  docs/se/security/containers-integration.adoc
  docs/se/tracing.adoc
  docs/se/webclient.adoc
  docs/se/webserver.adoc
  docs/se/websocket.adoc
  docs/sitegen.yaml
Labels: docs, 4.x, OCA Verified

#7687 Update HttpRules API to not have varargs with generics
  microprofile/server/src/main/java/io/helidon/microprofile/server/RoutingPath.java
  webserver/security/src/main/java/io/helidon/webserver/security/SecurityFeature.java
  webserver/static-content/src/main/java/io/helidon/webserver/staticcontent/StaticContentService.java
  webserver/tracing/src/main/java/io/helidon/webserver/tracing/TracingFeature.java
  webserver/webserver/src/main/java/io/helidon/webserver/http/HttpRouting.java
  webserver/webserver/src/main/java/io/helidon/webserver/http/HttpRoutingFeature.java
  webserver/webserver/src/main/java/io/helidon/webserver/http/HttpRules.java
  webserver/webserver/src/main/java/io/helidon/webserver/http/HttpService.java
  webserver/webserver/src/main/java/io/helidon/webserver/http/ServiceRules.java
  webserver/webserver/src/test/java/io/helidon/webserver/http/HttpRoutingTest.java
  webserver/webserver/src/test/java/io/helidon/webserver/http/HttpRulesTest.java
Labels: OCA Verified

#7691 4.x: Upgrade parsson to 1.1.3
  dependencies/pom.xml
Labels: dependencies, 4.x, OCA Verified
