Repository helidon-io/helidon, pull requests merged in 2023-11, with the labels that each got.

#7924 [4.x] Corrects a case typo in the custom MP archetype that results in an invalid property being installed on UCP
  archetypes/helidon/src/main/archetype/mp/common/files/src/main/resources/META-INF/microprofile-config.properties.mustache
Labels: bug, MP, P1, jpa/jta, archetypes, 4.x, OCA Verified

#7927 [4.x] Adds a DialectFactory implementation to permit Hibernate to introspect database metadata properly when supporting container-mode JPA
  dependencies/pom.xml
  etc/javadoc/hibernate/element-list
  integrations/cdi/hibernate-cdi/etc/spotbugs/exclude.xml
  integrations/cdi/hibernate-cdi/pom.xml
  integrations/cdi/hibernate-cdi/src/main/java/io/helidon/integrations/cdi/hibernate/CDISEJtaPlatformProvider.java
  integrations/cdi/hibernate-cdi/src/main/java/io/helidon/integrations/cdi/hibernate/DataSourceBackedDialectFactory.java
  integrations/cdi/hibernate-cdi/src/main/java/module-info.java
  integrations/cdi/hibernate-cdi/src/test/java/io/helidon/integrations/cdi/hibernate/TestDialectDetection.java
  pom.xml
Labels: enhancement, MP, P3, jpa/jta, java, 4.x, OCA Verified

#7928 3.x: Update supression for netty
  etc/dependency-check-suppression.xml
Labels: 3.x, OCA Verified

#7929 Upgrades to Tyrus 2.1.4.
  dependencies/pom.xml
Labels: websocket, 4.x, OCA Verified

#7933 [3.x] Corrects a case typo in the custom MP archetype that results in an invalid property being installed on UCP
  archetypes/helidon/src/main/archetype/mp/common/files/src/main/resources/META-INF/microprofile-config.properties.mustache
Labels: bug, MP, P1, jpa/jta, 3.x, archetypes, backport, OCA Verified

#7934 [3.x] Adds a DialectFactory implementation to permit Hibernate to introspect database metadata properly when supporting container-mode JPA
  dependencies/pom.xml
  etc/javadoc/hibernate/element-list
  integrations/cdi/hibernate-cdi/etc/spotbugs/exclude.xml
  integrations/cdi/hibernate-cdi/pom.xml
  integrations/cdi/hibernate-cdi/src/main/java/io/helidon/integrations/cdi/hibernate/CDISEJtaPlatformProvider.java
  integrations/cdi/hibernate-cdi/src/main/java/io/helidon/integrations/cdi/hibernate/DataSourceBackedDialectFactory.java
  integrations/cdi/hibernate-cdi/src/main/java/module-info.java
  integrations/cdi/hibernate-cdi/src/test/java/io/helidon/integrations/cdi/hibernate/TestDialectDetection.java
  pom.xml
Labels: bug, MP, P1, jpa/jta, 3.x, backport, java, OCA Verified

#7936 [3.x] Backports database-related information present on 4.x to 3.x archetypes
  archetypes/helidon/src/main/archetype/mp/custom/database.xml
Labels: 3.x, archetypes, OCA Verified

#7940 1.x: Add release workflow
  .github/workflows/release.yaml
  etc/scripts/pipeline-env.sh
  etc/scripts/release.sh
Labels: build, OCA Verified

#7942 4.x: Archetype - Generated projects does not contains empty application.yaml
  archetypes/helidon/src/main/archetype/common/security.xml
  archetypes/helidon/src/main/archetype/mp/custom/custom-mp.xml
  archetypes/helidon/src/main/archetype/mp/custom/files/src/main/resources/application.yaml.mustache
  archetypes/helidon/src/main/archetype/mp/oci/oci-mp.xml
Labels: MP, archetypes, 4.x, OCA Verified

#7944 Upgrades to Tyrus 2.1.4
  dependencies/pom.xml
Labels: 3.x, websocket, OCA Verified

#7960 3.x: Upgrade parsson to 1.0.5
  dependencies/pom.xml
Labels: dependencies, 3.x, OCA Verified

#7958 4.x: Upgrade parsson to 1.1.5
  dependencies/pom.xml
Labels: dependencies, 4.x, OCA Verified

#7949 4.x Enable tests that were disabled during renaming to `jakarta` packages work
  examples/integrations/micronaut/data/src/main/java/io/helidon/examples/integrations/micronaut/data/BeanValidationExceptionMapper.java
  examples/integrations/micronaut/data/src/main/java/io/helidon/examples/integrations/micronaut/data/PetResource.java
  examples/integrations/micronaut/data/src/test/java/io/helidon/examples/integrations/micronaut/data/MicronautExampleTest.java
  examples/microprofile/cors/pom.xml
  examples/microprofile/cors/src/main/java/io/helidon/microprofile/examples/cors/GreetResource.java
  examples/microprofile/cors/src/test/java/io/helidon/microprofile/examples/cors/TestCORS.java
Labels: testing, 4.x, OCA Verified

#7952 Properly removes a channel from the cache
  webclient/webclient/src/main/java/io/helidon/webclient/WebClientRequestBuilderImpl.java
  webclient/webclient/src/test/java/io/helidon/webclient/WebClientRequestBuilderImplTest.java
Labels: webclient, 3.x, OCA Verified

#7969 Correct errors in how OpenAPI generator config settings are set
  docs/includes/openapi/openapi-generator.adoc
Labels: OCA Verified

#7970 Correct errors in how OpenAPI generator config settings are set
  docs/includes/openapi/openapi-generator.adoc
Labels: OCA Verified

#7971 2.x Correct errors in how OpenAPI generator config settings are set
  docs/shared/openapi/openapi-generator.adoc
Labels: OCA Verified

#7972 4.x: backport native-image fixes + support -Dnative.image.skip and -Dnative.image.buildStatic
  applications/mp/pom.xml
  applications/parent/pom.xml
  applications/se/pom.xml
  examples/quickstarts/helidon-quickstart-se/Dockerfile.native
Labels: native-image, backport, 4.x, OCA Verified

#7877 4.x: Use H2 in-memory in SE archetype
  archetypes/helidon/src/main/archetype/se/custom/database-output.xml
Labels: bug, archetypes, 4.x, OCA Verified

#7909 Fix dockerFiles in examples
  archetypes/helidon/src/main/archetype/common/docker.xml
  archetypes/helidon/src/main/archetype/common/files/Dockerfile.jlink.mustache
  archetypes/helidon/src/main/archetype/common/files/Dockerfile.mustache
  archetypes/helidon/src/main/archetype/common/files/pom.xml.mustache
  archetypes/helidon/src/main/archetype/mp/oci/oci-mp.xml
  docs/mp/guides/mp-tutorial.adoc
  examples/employee-app/Dockerfile
  examples/integrations/cdi/datasource-hikaricp/Dockerfile
  examples/quickstarts/helidon-quickstart-mp/Dockerfile
  examples/quickstarts/helidon-quickstart-mp/Dockerfile.jlink
  examples/quickstarts/helidon-quickstart-se/Dockerfile.jlink
  examples/quickstarts/helidon-standalone-quickstart-mp/Dockerfile
  examples/quickstarts/helidon-standalone-quickstart-mp/Dockerfile.jlink
  examples/quickstarts/helidon-standalone-quickstart-mp/README.md
  examples/quickstarts/helidon-standalone-quickstart-se/Dockerfile
  examples/quickstarts/helidon-standalone-quickstart-se/Dockerfile.jlink
  examples/quickstarts/helidon-standalone-quickstart-se/README.md
  examples/translator-app/README.md
  examples/translator-app/backend/Dockerfile
  examples/translator-app/backend/pom.xml
  examples/translator-app/frontend/Dockerfile
  examples/translator-app/frontend/pom.xml
  examples/webserver/opentracing/Dockerfile
Labels: docs, 4.x, OCA Verified

#7977 4.x: GZIP encoder - properly trigger chunked enc
  http/tests/encoding/gzip/pom.xml
  http/tests/encoding/gzip/src/test/java/io/helidon/http/tests/integration/encoding/gzip/GzipEncodingStaticContentTest.java
  http/tests/encoding/gzip/src/test/resources/WEB/index.html
  webserver/webserver/src/main/java/io/helidon/webserver/http1/Http1ServerResponse.java
Labels: OCA Verified

#7982 Keep EOF at end of OpenMetrics output
  metrics/providers/micrometer/src/main/java/io/helidon/metrics/providers/micrometer/MicrometerPrometheusFormatter.java
  metrics/providers/micrometer/src/test/java/io/helidon/metrics/providers/micrometer/TestPrometheusFormatting.java
Labels: OCA Verified

#7989 4.x: Re-enable TCP auto-tuning
  common/socket/src/main/java/io/helidon/common/socket/SocketOptionsBlueprint.java
Labels: OCA Verified

#7988 [4.x] Upgrade to mysql-connector-j 8.2.0
  archetypes/helidon/src/main/archetype/mp/custom/database-outputs.xml
  archetypes/helidon/src/main/archetype/se/custom/database-output.xml
  dependencies/pom.xml
  examples/dbclient/jdbc/pom.xml
  examples/dbclient/pokemons/pom.xml
  examples/integrations/cdi/datasource-hikaricp-mysql/pom.xml
  integrations/db/mysql/pom.xml
  tests/integration/dbclient/app/pom.xml
  tests/integration/jpa/appl/pom.xml
  tests/integration/vault/pom.xml
Labels: OCA Verified

#7992 Fix 7951. Adds Testing section back to the menu and fix maven coordinates
  docs/se/testing.adoc
  docs/sitegen.yaml
Labels: docs, 4.x, OCA Verified

#7987 4.x: Docs - fix Security http basic authentication property
  docs/includes/security/providers/http-basic-auth.adoc
  docs/includes/security/providers/http-digest-auth.adoc
Labels: docs, 4.x, OCA Verified

#7962 [4.x][Doc] - Fix tracing documentation
  docs/se/guides/tracing.adoc
  docs/se/tracing.adoc
Labels: docs, 4.x, OCA Verified

#7994 4.x Add a new `addCheck` variant allowing the caller to set the health check name; add tests; revise doc
  docs/se/health.adoc
  webserver/observe/health/src/main/java/io/helidon/webserver/observe/health/HealthObserverSupport.java
  webserver/observe/health/src/test/java/io/helidon/webserver/observe/health/TestNamedResponseSupplier.java
Labels: OCA Verified

#8000 Updates header type hierarchy to make HeaderValueCached not writeable
  http/http/src/main/java/io/helidon/http/HeaderValueArray.java
  http/http/src/main/java/io/helidon/http/HeaderValueBase.java
  http/http/src/main/java/io/helidon/http/HeaderValueCached.java
  http/http/src/main/java/io/helidon/http/HeaderValueCopy.java
  http/http/src/main/java/io/helidon/http/HeaderValueLazy.java
  http/http/src/main/java/io/helidon/http/HeaderValueList.java
  http/http/src/main/java/io/helidon/http/HeaderValueSingle.java
  http/http/src/main/java/io/helidon/http/HeaderWritableValueBase.java
Labels: OCA Verified

#7947 4.x: archetype fix MP security
  archetypes/helidon/src/main/archetype/common/files/application.abac.yaml
  archetypes/helidon/src/main/archetype/common/files/application.oidc.yaml
  archetypes/helidon/src/main/archetype/common/security.xml
  archetypes/helidon/src/main/archetype/mp/custom/custom-mp.xml
  archetypes/helidon/src/main/archetype/mp/custom/files/application.abac.yaml
  archetypes/helidon/src/main/archetype/mp/custom/files/application.google.yaml
  archetypes/helidon/src/main/archetype/mp/custom/files/application.http-signature.yaml
  archetypes/helidon/src/main/archetype/mp/custom/files/application.oidc.yaml
  archetypes/helidon/src/main/archetype/mp/custom/files/src/main/java/__pkg__/JwtApplication.java.mustache
  archetypes/helidon/src/main/archetype/mp/custom/files/src/main/java/__pkg__/JwtResource.java.mustache
  archetypes/helidon/src/main/archetype/mp/custom/files/src/main/java/__pkg__/OidcResource.java.mustache
  archetypes/helidon/src/main/archetype/mp/custom/security-outputs.xml
  archetypes/helidon/src/main/archetype/se/common/common-se.xml
  archetypes/helidon/src/main/archetype/se/common/files/src/main/resources/application.yaml.mustache
  archetypes/helidon/src/main/archetype/se/custom/custom-se.xml
  archetypes/helidon/src/main/archetype/se/custom/files/application.jwt.yaml
  archetypes/helidon/src/main/archetype/se/custom/files/src/main/java/__pkg__/GoogleMain.java.mustache
  archetypes/helidon/src/main/archetype/se/custom/files/src/main/java/__pkg__/JwtOverrideService.java.mustache
  archetypes/helidon/src/main/archetype/se/custom/files/src/main/java/__pkg__/OutboundOverrideJwt.java.mustache
  archetypes/helidon/src/main/archetype/se/custom/files/src/main/java/__pkg__/SignatureMain.java.mustache
  archetypes/helidon/src/main/archetype/se/custom/files/src/main/resources/WEB/google-login.html
  archetypes/helidon/src/main/archetype/se/custom/files/src/main/resources/signing-jwk.json
  archetypes/helidon/src/main/archetype/se/custom/files/src/main/resources/verifying-jwk.json
  archetypes/helidon/src/main/archetype/se/custom/files/src/test/java/__pkg__/GoogleMainTest.java.mustache
  archetypes/helidon/src/main/archetype/se/custom/files/src/test/java/__pkg__/OutboundOverrideJwtTest.java.mustache
  archetypes/helidon/src/main/archetype/se/custom/files/src/test/java/__pkg__/SignatureMainTest.java.mustache
  archetypes/helidon/src/main/archetype/se/custom/security-outputs.xml
  archetypes/helidon/src/main/archetype/se/custom/security.xml
Labels: MP, security, archetypes, 4.x, OCA Verified

#7993 4.x: Use MP OpenTelemetry instead of OpenTracing in archetypes
  archetypes/helidon/src/main/archetype/common/files/README.jaeger.md
  archetypes/helidon/src/main/archetype/common/observability.xml
  archetypes/helidon/src/main/archetype/mp/custom/files/src/main/java/__pkg__/TracedResource.java.mustache
  archetypes/helidon/src/main/archetype/mp/custom/observability.xml
  archetypes/helidon/src/main/archetype/mp/custom/tracing-outputs.xml
  archetypes/helidon/src/main/archetype/se/custom/observability.xml
  archetypes/helidon/src/main/archetype/se/custom/tracing-outputs.xml
Labels: MP, tracing, archetypes, 4.x

#7997 [4.x] - Update Neo4j module to generated config
  docs/config/io_helidon_integrations_neo4j.adoc
  docs/config/io_helidon_integrations_neo4j_Neo4j.adoc
  docs/mp/integrations/neo4j.adoc
  docs/se/integrations/neo4j.adoc
  integrations/neo4j/neo4j/pom.xml
  integrations/neo4j/neo4j/src/main/java/io/helidon/integrations/neo4j/Neo4j.java
  integrations/neo4j/neo4j/src/main/java/module-info.java
  integrations/vault/auths/approle/pom.xml
Labels: docs, 4.x, OCA Verified

#8006 [4.x] Adds support for Provider-specializing injection points in OciExtension
  integrations/oci/sdk/cdi/etc/spotbugs/exclude.xml
  integrations/oci/sdk/cdi/src/main/java/io/helidon/integrations/oci/sdk/cdi/OciExtension.java
  integrations/oci/sdk/cdi/src/test/java/io/helidon/integrations/oci/sdk/cdi/TestProcessProviderInjectionPoint.java
Labels: MP, P2, cdi, OCI, java, 4.x, OCA Verified

#8007 New section describing support for the Proxy Protocol
  docs/se/webserver.adoc
Labels: docs, webserver, 4.x, OCA Verified

#8017 [2.x] Upgrade to mysql-connector-j 8.2.0
  dependencies/pom.xml
  examples/dbclient/jdbc/pom.xml
  examples/dbclient/pokemons/pom.xml
  examples/integrations/cdi/datasource-hikaricp-mysql/pom.xml
  examples/istio/helidon-jpa/pom.xml
  integrations/db/mysql/pom.xml
  tests/integration/dbclient/appl/pom.xml
  tests/integration/dbclient/jdbc/pom.xml
  tests/integration/jpa/appl/pom.xml
  tests/integration/tools/example/pom.xml
  tests/integration/vault/mp/pom.xml
Labels: OCA Verified

#8016 [3.x] Upgrade to mysql-connector-j 8.2.0
  archetypes/helidon/src/main/archetype/mp/custom/database.xml
  archetypes/helidon/src/main/archetype/se/custom/database.xml
  dependencies/pom.xml
  examples/dbclient/jdbc/pom.xml
  examples/dbclient/pokemons/pom.xml
  examples/integrations/cdi/datasource-hikaricp-mysql/pom.xml
  integrations/db/mysql/pom.xml
  tests/integration/dbclient/appl/pom.xml
  tests/integration/dbclient/jdbc/pom.xml
  tests/integration/jpa/appl/pom.xml
  tests/integration/tools/example/pom.xml
  tests/integration/vault/mp/pom.xml
Labels: OCA Verified

#8020 4.x: Archetype - Fix the wrong metrics endpoint for Helidon SE
  archetypes/helidon/src/main/archetype/common/observability.xml
Labels: archetypes, 4.x, OCA Verified

#8010 4.x Fix nested config prefix for observer settings
  microprofile/health/src/main/java/io/helidon/microprofile/health/HealthCdiExtension.java
  microprofile/health/src/test/java/io/helidon/microprofile/health/NestedConfigTest.java
  microprofile/metrics/src/main/java/io/helidon/microprofile/metrics/MetricsCdiExtension.java
  microprofile/service-common/src/main/java/io/helidon/microprofile/servicecommon/HelidonRestCdiExtension.java
Labels: OCA Verified

#8008 Use correct config nodes for metrics settings; when using global meter registry set metrics config correctly
  metrics/api/src/main/java/io/helidon/metrics/api/MetricsFactoryManager.java
  microprofile/metrics/src/main/java/io/helidon/microprofile/metrics/MetricsCdiExtension.java
  microprofile/metrics/src/main/java/io/helidon/microprofile/metrics/RegistryFactory.java
  webserver/observe/metrics/pom.xml
  webserver/observe/metrics/src/main/java/io/helidon/webserver/observe/metrics/MetricsFeature.java
  webserver/observe/metrics/src/main/java/io/helidon/webserver/observe/metrics/MetricsObserver.java
  webserver/observe/metrics/src/test/java/io/helidon/webserver/observe/metrics/TestMetricsConfigPropagation.java
  webserver/observe/metrics/src/test/resources/application.yaml
Labels: OCA Verified

#8027 [3.x] Adds support for Provider-specializing injection points in OciExtension
  integrations/oci/sdk/cdi/etc/spotbugs/exclude.xml
  integrations/oci/sdk/cdi/src/main/java/io/helidon/integrations/oci/sdk/cdi/OciExtension.java
  integrations/oci/sdk/cdi/src/test/java/io/helidon/integrations/oci/sdk/cdi/TestProcessProviderInjectionPoint.java
Labels: MP, P2, cdi, 3.x, OCI, backport, java, OCA Verified

#8028 [2.x] Adds support for Provider-specializing injection points in OciExtension
  integrations/oci/sdk/cdi/etc/spotbugs/exclude.xml
  integrations/oci/sdk/cdi/src/main/java/io/helidon/integrations/oci/sdk/cdi/OciExtension.java
  integrations/oci/sdk/cdi/src/test/java/io/helidon/integrations/oci/sdk/cdi/TestProcessProviderInjectionPoint.java
Labels: MP, P2, cdi, 2.x, OCI, backport, java, OCA Verified

#8038 Change CorsConfig.enabled to optional and add logic to infer it
  webserver/cors/src/main/java/io/helidon/webserver/cors/CorsConfigBlueprint.java
  webserver/cors/src/main/java/io/helidon/webserver/cors/CorsConfigSupport.java
Labels: OCA Verified

#8025 Support for longer WebSocket frames
  webserver/tests/websocket/src/test/java/io/helidon/webserver/tests/websocket/WebSocketTest.java
  webserver/tests/websocket/src/test/resources/application.yaml
  webserver/websocket/src/main/java/io/helidon/webserver/websocket/WsConfigBlueprint.java
  webserver/websocket/src/main/java/io/helidon/webserver/websocket/WsConnection.java
  webserver/websocket/src/main/java/io/helidon/webserver/websocket/WsUpgradeProvider.java
  websocket/src/main/java/io/helidon/websocket/AbstractWsFrame.java
Labels: webserver, websocket, 4.x, OCA Verified

#7829 4.x: Initial support for proxy protocol V1 and V2
  common/testing/http-junit5/src/main/java/io/helidon/common/testing/http/junit5/SocketHttpClient.java
  webserver/http2/src/main/java/io/helidon/webserver/http2/Http2Connection.java
  webserver/http2/src/main/java/io/helidon/webserver/http2/Http2ServerRequest.java
  webserver/tests/webserver/src/test/java/io/helidon/webserver/tests/ProxyProtocolTest.java
  webserver/webserver/src/main/java/io/helidon/webserver/ConnectionContext.java
  webserver/webserver/src/main/java/io/helidon/webserver/ConnectionHandler.java
  webserver/webserver/src/main/java/io/helidon/webserver/ListenerConfigBlueprint.java
  webserver/webserver/src/main/java/io/helidon/webserver/ProxyProtocolData.java
  webserver/webserver/src/main/java/io/helidon/webserver/ProxyProtocolHandler.java
  webserver/webserver/src/main/java/io/helidon/webserver/http/ServerRequest.java
  webserver/webserver/src/main/java/io/helidon/webserver/http1/Http1Connection.java
  webserver/webserver/src/main/java/io/helidon/webserver/http1/Http1ServerRequest.java
  webserver/webserver/src/test/java/io/helidon/webserver/ProxyProtocolHandlerTest.java
Labels: OCA Verified

#8002 Optimize single provider case
  webserver/webserver/src/main/java/io/helidon/webserver/ConnectionHandler.java
Labels: webserver, performance, 4.x

#8041 Fix for access-log feature.
  examples/todo-app/frontend/src/main/resources/application.yaml
  webserver/access-log/src/main/java/io/helidon/webserver/accesslog/AccessLogFeatureProvider.java
  webserver/access-log/src/main/java/module-info.java
Labels: 4.x, OCA Verified

#8037 1.x: upgrade owasp depenency check to 8.4.3
  etc/dependency-check-suppression.xml
  pom.xml
Labels: 1.x, dependencies, OCA Verified

#8043 4.x: Fix broken link and explicitly state MP uses Helidon WebServer
  docs/about/doc_overview.adoc
  docs/about/introduction.adoc
  docs/mp/introduction.adoc
Labels: docs, 4.x, OCA Verified

#8036 2.x: upgrade owasp depenency check to 8.4.3
  etc/dependency-check-suppression.xml
  pom.xml
Labels: 2.x, dependencies, OCA Verified

#8035 4.x: upgrade owasp depenency check to 8.4.3
  etc/dependency-check-suppression.xml
  pom.xml
Labels: dependencies, 4.x, OCA Verified

#8034 3.x: Upgrade owasp dependency check to 8.4.3
  pom.xml
Labels: dependencies, 3.x, OCA Verified

#8014 [4.x][Doc] - Fix telemetry docs
  docs/images/telemetry/telemetry-custom-jaeger.png
  docs/images/telemetry/telemetry-general.png
  docs/images/telemetry/telemetry-greeting-jaeger.png
  docs/images/telemetry/telemetry-outbound-jaeger.png
  docs/mp/telemetry.adoc
  examples/microprofile/telemetry/README.md
  microprofile/telemetry/src/main/java/io/helidon/microprofile/telemetry/OpenTelemetryProducer.java
  microprofile/telemetry/src/main/java/io/helidon/microprofile/telemetry/WithSpanInterceptor.java
Labels: docs, 4.x, OCA Verified

#8044 4.x: JSON-P native image
  http/media/jsonp/src/main/resources/META-INF/native-image/io.helidon.http.media/helidon-http-media-jsonp/native-image.properties
  integrations/graal/native-image-extension/src/main/resources/META-INF/native-image/io.helidon.integrations.graal/helidon-graal-native-image-extension/native-image.properties
Labels: bug, native-image, 4.x, OCA Verified

#8042 Headers on server cannot be set after entity was sent
  webserver/http2/src/main/java/io/helidon/webserver/http2/Http2ServerResponse.java
  webserver/tests/webserver/src/test/java/io/helidon/webserver/tests/OutputStreamAndContentLengthTest.java
  webserver/webserver/src/main/java/io/helidon/webserver/http/ServerResponse.java
  webserver/webserver/src/main/java/io/helidon/webserver/http1/Http1ServerResponse.java
Labels: bug, 4.x, OCA Verified

#7995 Fix repeated pseudo-header field `:status`
  webserver/grpc/src/main/java/io/helidon/webserver/grpc/GrpcProtocolHandler.java
Labels: OCA Verified

#8053 4.x - WebServer fix req.next typo
  docs/se/webserver.adoc
Labels: SE, docs, webserver, 4.x, OCA Verified

#8056 4.x: Update JaxRsService to reset status to 200 when nexting.
  microprofile/server/src/main/java/io/helidon/microprofile/server/JaxRsService.java
Labels: MP, 4.x, OCA Verified

#8046 4.x: Change "Java for cloud" to "Helidon"
  security/providers/common/src/main/java/module-info.java
  security/security/src/main/java/module-info.java
Labels: docs, 4.x, OCA Verified

#8057 Add meter type to JSON metrics metadata output
  docs/includes/guides/metrics.adoc
  metrics/api/src/main/java/io/helidon/metrics/api/Meter.java
  webserver/observe/metrics/src/main/java/io/helidon/webserver/observe/metrics/JsonFormatter.java
Labels: OCA Verified

#8051 4.x: Graceful client connection close
  webclient/api/src/main/java/io/helidon/webclient/api/HttpClient.java
  webclient/api/src/main/java/io/helidon/webclient/api/LoomClient.java
  webclient/api/src/main/java/io/helidon/webclient/spi/ClientConnectionCache.java
  webclient/api/src/main/java/io/helidon/webclient/spi/HttpClientSpi.java
  webclient/http1/src/main/java/io/helidon/webclient/http1/Http1ClientImpl.java
  webclient/http1/src/main/java/io/helidon/webclient/http1/Http1ConnectionCache.java
  webclient/http2/src/main/java/io/helidon/webclient/http2/Http2ClientConnection.java
  webclient/http2/src/main/java/io/helidon/webclient/http2/Http2ClientConnectionHandler.java
  webclient/http2/src/main/java/io/helidon/webclient/http2/Http2ClientImpl.java
  webclient/http2/src/main/java/io/helidon/webclient/http2/Http2ConnectionCache.java
  webclient/tests/http1/src/test/java/io/helidon/webclient/tests/SharedCacheTest.java
  webclient/tests/http2/pom.xml
  webclient/tests/http2/src/test/java/io/helidon/webclient/tests/http2/MockHttp2Server.java
  webclient/tests/http2/src/test/java/io/helidon/webclient/tests/http2/ShutDownTest.java
  webserver/http2/src/main/java/io/helidon/webserver/http2/Http2ConfigBlueprint.java
  webserver/http2/src/main/java/io/helidon/webserver/http2/Http2Connection.java
  webserver/testing/junit5/junit5/src/main/java/io/helidon/webserver/testing/junit5/DirectClient.java
  webserver/testing/junit5/junit5/src/main/java/io/helidon/webserver/testing/junit5/DirectWebClient.java
  webserver/tests/http2/src/test/java/io/helidon/webserver/tests/http2/EmptyFrameCntTest.java
Labels: OCA Verified

#8065 4.x jvm uptime units
  docs/includes/guides/metrics.adoc
  docs/mp/guides/metrics.adoc
  metrics/system-meters/src/main/java/io/helidon/metrics/systemmeters/SystemMetersProvider.java
Labels: OCA Verified

#8081 4.x: Incorporate release branch name in artifact bundle name
  .github/workflows/release.yaml
Labels: build, 4.x, OCA Verified

#8080 3.x: Incorporate release branch name in artifact bundle name
  .github/workflows/release.yaml
Labels: build, 3.x, OCA Verified

#8086 3.x: Upgrade OCI SDK to 3.29.0
  dependencies/pom.xml
Labels: dependencies, 3.x, OCA Verified
