Repository helidon-io/helidon, pull requests merged in 2023-05, with the labels that each got.

#6734 [4.x] - Fix LRA Logging
  lra/coordinator/client/narayana-client/src/main/java/io/helidon/lra/coordinator/client/narayana/NarayanaClient.java
Labels: lra, 4.x, OCA Verified

#6746 [2.x] - Fix LRA logging
  lra/coordinator/client/narayana-client/src/main/java/io/helidon/lra/coordinator/client/narayana/NarayanaClient.java
Labels: 2.x, lra, OCA Verified

#6733 [3.x] - Fix LRA Logging
  lra/coordinator/client/narayana-client/src/main/java/io/helidon/lra/coordinator/client/narayana/NarayanaClient.java
Labels: 3.x, lra, OCA Verified

#6736 Documentation enhancements for WebClient
  docs/config/io_helidon_webclient_WebClientConfiguration.adoc
  webclient/webclient/src/main/java/io/helidon/webclient/WebClientConfiguration.java
Labels: docs, OCA Verified

#6770 Updates to (standalone) Quickstart SE to use Nima and @ServerTest
  examples/quickstarts/helidon-standalone-quickstart-se/Dockerfile
  examples/quickstarts/helidon-standalone-quickstart-se/Dockerfile.jlink
  examples/quickstarts/helidon-standalone-quickstart-se/pom.xml
  examples/quickstarts/helidon-standalone-quickstart-se/src/main/java/io/helidon/examples/quickstart/se/GreetService.java
  examples/quickstarts/helidon-standalone-quickstart-se/src/main/java/io/helidon/examples/quickstart/se/Main.java
  examples/quickstarts/helidon-standalone-quickstart-se/src/main/java/io/helidon/examples/quickstart/se/package-info.java
  examples/quickstarts/helidon-standalone-quickstart-se/src/main/resources/application.yaml
  examples/quickstarts/helidon-standalone-quickstart-se/src/main/resources/logging.properties
  examples/quickstarts/helidon-standalone-quickstart-se/src/test/java/io/helidon/examples/quickstart/se/MainTest.java
Labels: examples, 4.x, OCA Verified

#6766 Updates to Quickstart SE to use Nima and @ServerTest
  examples/quickstarts/helidon-quickstart-se/Dockerfile
  examples/quickstarts/helidon-quickstart-se/Dockerfile.jlink
  examples/quickstarts/helidon-quickstart-se/README.md
  examples/quickstarts/helidon-quickstart-se/build.gradle
  examples/quickstarts/helidon-quickstart-se/pom.xml
  examples/quickstarts/helidon-quickstart-se/src/main/java/io/helidon/examples/quickstart/se/GreetService.java
  examples/quickstarts/helidon-quickstart-se/src/main/java/io/helidon/examples/quickstart/se/Main.java
  examples/quickstarts/helidon-quickstart-se/src/main/resources/application.yaml
  examples/quickstarts/helidon-quickstart-se/src/main/resources/logging.properties
  examples/quickstarts/helidon-quickstart-se/src/test/java/io/helidon/examples/quickstart/se/MainTest.java
Labels: examples, 4.x, OCA Verified

#6239 Support for unordered scope closings in JaegerScopeManager
  tracing/jaeger/src/main/java/io/helidon/tracing/jaeger/JaegerScopeManager.java
  tracing/jaeger/src/test/java/io/helidon/tracing/jaeger/JaegerScopeManagerTest.java
Labels: bug, tracing, OCA Verified

#6781 4.x: Truncate example token in README so it is not valid
  integrations/vault/README.md
Labels: 4.x, OCA Verified

#6780 2.x Truncate example token in README so it is not valid
  integrations/vault/README.md
Labels: 2.x, OCA Verified

#6777 2.x: Update jaeger-client to 1.8.1
  dependencies/pom.xml
Labels: tracing, 2.x, dependencies, OCA Verified

#6782 [3.x]: Fix params of @ExampleObject annotations in examples (#6040)
  docs/mp/openapi.adoc
  docs/mp/openapi/openapi.adoc
  examples/microprofile/openapi-basic/src/main/java/io/helidon/microprofile/examples/openapi/basic/GreetResource.java
Labels: OCA Verified

#6778 Port of static content example to Nima webserver
  examples/webserver/static-content/README.md
  examples/webserver/static-content/pom.xml
  examples/webserver/static-content/src/main/java/io/helidon/reactive/webserver/examples/staticcontent/Main.java
  examples/webserver/static-content/src/main/java/io/helidon/webserver/examples/staticcontent/CounterService.java
  examples/webserver/static-content/src/main/java/io/helidon/webserver/examples/staticcontent/Main.java
  examples/webserver/static-content/src/main/java/io/helidon/webserver/examples/staticcontent/package-info.java
  examples/webserver/static-content/src/test/java/io/helidon/webserver/examples/staticcontent/MainTest.java
Labels: examples, 4.x, OCA Verified

#6786 [2.x]: Fix params of @ExampleObject annotations in examples (#6785)
  examples/cors/src/main/resources/META-INF/openapi.yml
  examples/microprofile/openapi-basic/src/main/java/io/helidon/microprofile/examples/openapi/basic/GreetResource.java
  examples/openapi/src/main/resources/META-INF/openapi.yml
Labels: OCA Verified

#6705 Pico anno processor rewrite
  builder/processor-tools/src/main/java/io/helidon/builder/processor/tools/BuilderTypeTools.java
  common/types/src/main/java/io/helidon/common/types/TypedElementNameDefault.java
  pico/api/src/main/java/io/helidon/pico/api/QualifierAndValueDefault.java
  pico/api/src/main/java/io/helidon/pico/api/RunLevel.java
  pico/configdriven/processor/pom.xml
  pico/configdriven/processor/src/main/java/io/helidon/pico/configdriven/processor/ConfiguredByAnnotationProcessor.java
  pico/configdriven/processor/src/main/java/io/helidon/pico/configdriven/processor/ConfiguredByProcessor.java
  pico/configdriven/processor/src/main/java/io/helidon/pico/configdriven/processor/ConfiguredByProcessorUtils.java
  pico/configdriven/processor/src/main/java/module-info.java
  pico/configdriven/runtime/src/main/java/io/helidon/pico/configdriven/runtime/AbstractConfiguredServiceProvider.java
  pico/configdriven/tests/configuredby-application/pom.xml
  pico/configdriven/tests/configuredby-application/src/test/java/io/helidon/pico/configdriven/configuredby/test/ApplicationConfiguredByTest.java
  pico/configdriven/tests/configuredby/pom.xml
  pico/maven-plugin/src/main/java/io/helidon/pico/maven/plugin/AbstractApplicationCreatorMojo.java
  pico/processor/etc/spotbugs/exclude.xml
  pico/processor/src/main/java/io/helidon/pico/processor/ActiveProcessorUtils.java
  pico/processor/src/main/java/io/helidon/pico/processor/BaseAnnotationProcessor.java
  pico/processor/src/main/java/io/helidon/pico/processor/ContractAnnotationProcessor.java
  pico/processor/src/main/java/io/helidon/pico/processor/CreatorHandler.java
  pico/processor/src/main/java/io/helidon/pico/processor/CustomAnnotationProcessor.java
  pico/processor/src/main/java/io/helidon/pico/processor/GeneralProcessorUtils.java
  pico/processor/src/main/java/io/helidon/pico/processor/GenericTemplateCreatorDefault.java
  pico/processor/src/main/java/io/helidon/pico/processor/InjectAnnotationProcessor.java
  pico/processor/src/main/java/io/helidon/pico/processor/PicoAnnotationProcessor.java
  pico/processor/src/main/java/io/helidon/pico/processor/PostConstructPreDestroyAnnotationProcessor.java
  pico/processor/src/main/java/io/helidon/pico/processor/ProcessorUtils.java
  pico/processor/src/main/java/io/helidon/pico/processor/ServiceAnnotationProcessor.java
  pico/processor/src/main/java/module-info.java
  pico/processor/src/test/java/io/helidon/pico/processor/CustomAnnotationProcessorTest.java
  pico/processor/src/test/java/io/helidon/pico/processor/ExtensibleGetTemplateProducer.java
  pico/tests/resources-pico/src/main/java/io/helidon/pico/tests/pico/tbox/AbstractSaw.java
  pico/tests/resources-pico/src/main/java/io/helidon/pico/tests/pico/tbox/impl/MainToolBox.java
  pico/tests/resources-pico/src/test/java/io/helidon/pico/tests/pico/tbox/ToolBoxTest.java
  pico/tests/resources-pico/src/test/resources/expected/tests-module-info.java._pico_
  pico/tools/src/main/java/io/helidon/pico/tools/AbstractFilerMessager.java
  pico/tools/src/main/java/io/helidon/pico/tools/ActivatorCreatorDefault.java
  pico/tools/src/main/java/io/helidon/pico/tools/ApplicationCreatorDefault.java
  pico/tools/src/main/java/io/helidon/pico/tools/CodeGenFiler.java
  pico/tools/src/main/java/io/helidon/pico/tools/CodeGenInterceptorRequest.java
  pico/tools/src/main/java/io/helidon/pico/tools/CodeGenUtils.java
  pico/tools/src/main/java/io/helidon/pico/tools/ExternalModuleCreatorDefault.java
  pico/tools/src/main/java/io/helidon/pico/tools/GeneralCreatorRequest.java
  pico/tools/src/main/java/io/helidon/pico/tools/InterceptorCreatorDefault.java
  pico/tools/src/main/java/io/helidon/pico/tools/ModuleUtils.java
  pico/tools/src/main/java/io/helidon/pico/tools/ServicesToProcess.java
  pico/tools/src/main/java/io/helidon/pico/tools/TypeNames.java
  pico/tools/src/main/java/io/helidon/pico/tools/TypeTools.java
  pico/tools/src/main/java/io/helidon/pico/tools/spi/ActivatorCreator.java
  pico/tools/src/main/java/io/helidon/pico/tools/spi/InterceptorCreator.java
  pico/tools/src/test/java/io/helidon/pico/tools/ApplicationCreatorDefaultTest.java
Labels: pico, OCA Verified

#6793 3.x: Fix attributions for jsr305
  THIRD_PARTY_LICENSES.txt
  etc/HELIDON_THIRD_PARTY_LICENSES.xml
Labels: OCA Verified

#6795 Update GraphQLServiceTest to use @ServerTest and Http1Client
  nima/graphql/server/pom.xml
  nima/graphql/server/src/test/java/io/helidon/nima/graphql/server/GraphQlServiceTest.java
Labels: OCA Verified

#6798 [3.x] Support for injection of ServerRequest and ServerResponse also via CDI
  microprofile/server/src/main/java/io/helidon/microprofile/server/ServerCdiExtension.java
  tests/functional/pom.xml
  tests/functional/request-scope-injection/pom.xml
  tests/functional/request-scope-injection/src/main/java/io/helidon/tests/functional/context/injection/CheckInjectionResource.java
  tests/functional/request-scope-injection/src/main/java/io/helidon/tests/functional/context/injection/package-info.java
  tests/functional/request-scope-injection/src/main/resources/META-INF/beans.xml
  tests/functional/request-scope-injection/src/test/java/io/helidon/tests/functional/context/injection/CheckInjectionTest.java
  tests/functional/request-scope-injection/src/test/resources/logging.properties
  webserver/jersey/src/main/java/io/helidon/webserver/jersey/JerseySupport.java
Labels: webserver, cdi, 3.x, OCA Verified

#6790 Removed old bookstore-se app and renamed bookstore-nima to bookstore-se
  tests/apps/bookstore/bookstore-nima/README.md
  tests/apps/bookstore/bookstore-nima/pom.xml
  tests/apps/bookstore/bookstore-nima/src/main/java/io/helidon/tests/apps/bookstore/nima/BookService.java
  tests/apps/bookstore/bookstore-nima/src/main/java/io/helidon/tests/apps/bookstore/nima/Main.java
  tests/apps/bookstore/bookstore-nima/src/main/java/io/helidon/tests/apps/bookstore/nima/package-info.java
  tests/apps/bookstore/bookstore-nima/src/main/java/module-info.java
  tests/apps/bookstore/bookstore-nima/src/main/resources/application.yaml
  tests/apps/bookstore/bookstore-nima/src/main/resources/certificate.p12
  tests/apps/bookstore/bookstore-nima/src/main/resources/logging.properties
  tests/apps/bookstore/bookstore-nima/src/test/java/io/helidon/tests/apps/bookstore/nima/Http2SslTest.java
  tests/apps/bookstore/bookstore-nima/src/test/java/io/helidon/tests/apps/bookstore/nima/MainTest.java
  tests/apps/bookstore/bookstore-nima/src/test/java/io/helidon/tests/apps/bookstore/nima/SslTest.java
  tests/apps/bookstore/bookstore-nima/src/test/java/io/helidon/tests/apps/bookstore/nima/TestServer.java
  tests/apps/bookstore/bookstore-nima/src/test/resources/book.json
  tests/apps/bookstore/bookstore-se/README.md
  tests/apps/bookstore/bookstore-se/pom.xml
  tests/apps/bookstore/bookstore-se/src/main/java/io/helidon/tests/apps/bookstore/se/BookService.java
  tests/apps/bookstore/bookstore-se/src/main/java/io/helidon/tests/apps/bookstore/se/Main.java
  tests/apps/bookstore/bookstore-se/src/main/java/io/helidon/tests/apps/bookstore/se/package-info.java
  tests/apps/bookstore/bookstore-se/src/main/java/module-info.java
  tests/apps/bookstore/bookstore-se/src/main/resources/application.yaml
  tests/apps/bookstore/bookstore-se/src/main/resources/logging.properties
  tests/apps/bookstore/bookstore-se/src/test/java/io/helidon/tests/apps/bookstore/se/Http2SslTest.java
  tests/apps/bookstore/bookstore-se/src/test/java/io/helidon/tests/apps/bookstore/se/MainTest.java
  tests/apps/bookstore/bookstore-se/src/test/java/io/helidon/tests/apps/bookstore/se/SslTest.java
  tests/apps/bookstore/bookstore-se/src/test/java/io/helidon/tests/apps/bookstore/se/TestServer.java
  tests/apps/bookstore/pom.xml
  tests/functional/bookstore/pom.xml
  tests/functional/bookstore/src/test/java/io/helidon/tests/bookstore/MainTest.java
Labels: testing, 4.x, OCA Verified

#6784 Support for injection of ServerRequest and ServerResponse also via CDI
  microprofile/server/src/main/java/io/helidon/microprofile/server/JaxRsService.java
  microprofile/server/src/main/java/io/helidon/microprofile/server/ServerCdiExtension.java
  tests/functional/pom.xml
  tests/functional/request-scope-injection/pom.xml
  tests/functional/request-scope-injection/src/main/java/io/helidon/tests/functional/context/injection/CheckInjectionResource.java
  tests/functional/request-scope-injection/src/main/java/io/helidon/tests/functional/context/injection/package-info.java
  tests/functional/request-scope-injection/src/main/resources/META-INF/beans.xml
  tests/functional/request-scope-injection/src/test/java/io/helidon/tests/functional/context/injection/CheckInjectionTest.java
  tests/functional/request-scope-injection/src/test/resources/logging.properties
Labels: webserver, cdi, 4.x, Níma, OCA Verified

#6493 [4.x] - MicroProfile Telemetry Support
  bom/pom.xml
  dependencies/pom.xml
  microprofile/pom.xml
  microprofile/telemetry/pom.xml
  microprofile/telemetry/src/main/java/io/helidon/microprofile/telemetry/HelidonTelemetryClientFilter.java
  microprofile/telemetry/src/main/java/io/helidon/microprofile/telemetry/HelidonTelemetryConstants.java
  microprofile/telemetry/src/main/java/io/helidon/microprofile/telemetry/HelidonTelemetryContainerFilter.java
  microprofile/telemetry/src/main/java/io/helidon/microprofile/telemetry/HelidonWithSpan.java
  microprofile/telemetry/src/main/java/io/helidon/microprofile/telemetry/OpenTelemetryProducer.java
  microprofile/telemetry/src/main/java/io/helidon/microprofile/telemetry/TelemetryAutoDiscoverable.java
  microprofile/telemetry/src/main/java/io/helidon/microprofile/telemetry/TelemetryCdiExtension.java
  microprofile/telemetry/src/main/java/io/helidon/microprofile/telemetry/WithSpanInterceptor.java
  microprofile/telemetry/src/main/java/io/helidon/microprofile/telemetry/package-info.java
  microprofile/telemetry/src/main/java/module-info.java
  microprofile/tests/arquillian/src/main/java/io/helidon/microprofile/arquillian/HelidonMethodExecutor.java
  microprofile/tests/tck/pom.xml
  microprofile/tests/tck/tck-telemetry/pom.xml
  microprofile/tests/tck/tck-telemetry/src/test/java/io/helidon/microprofile/telemetry/tck/TelemetryExtension.java
  microprofile/tests/tck/tck-telemetry/src/test/java/io/helidon/microprofile/telemetry/tck/UrlResourceProvider.java
  microprofile/tests/tck/tck-telemetry/src/test/resources/META-INF/services/org.jboss.arquillian.core.spi.LoadableExtension
  microprofile/tests/tck/tck-telemetry/src/test/resources/arquillian.xml
  microprofile/tests/tck/tck-telemetry/src/test/resources/logging.properties
  microprofile/tests/tck/tck-telemetry/src/test/tck-suite.xml
  tracing/opentelemetry/pom.xml
  tracing/opentelemetry/src/main/java/io/helidon/tracing/opentelemetry/HelidonOpenTelemetry.java
  tracing/opentelemetry/src/main/java/io/helidon/tracing/opentelemetry/OpenTelemetryTracerProvider.java
  tracing/opentelemetry/src/main/java/module-info.java
  tracing/opentelemetry/src/test/java/io/helidon/tracing/opentelemetry/AgentDetectorTest.java
Labels: MP, 4.x, OCA Verified, TCK

#6796 Default prefixed builder types renamed to be suffixed
  builder/processor-spi/src/main/java/io/helidon/builder/processor/spi/TypeAndBodyDefault.java
  builder/processor-tools/src/main/java/io/helidon/builder/processor/tools/DefaultBuilderCreatorProvider.java
  pico/api/src/test/java/io/helidon/pico/api/PicoConfigDefaultTest.java
  pico/api/src/test/java/io/helidon/pico/api/QualifierAndValueDefaultTest.java
  pico/maven-plugin/src/main/java/io/helidon/pico/maven/plugin/AbstractApplicationCreatorMojo.java
  pico/runtime/src/main/java/io/helidon/pico/runtime/DefaultInjectionPlanBinder.java
  pico/runtime/src/main/java/io/helidon/pico/runtime/DefaultInjectionPlans.java
  pico/runtime/src/main/java/io/helidon/pico/runtime/DefaultServices.java
  pico/runtime/src/main/java/io/helidon/pico/runtime/ServiceBinderDefault.java
  pico/testing/src/main/java/io/helidon/pico/testing/PicoTestingSupport.java
  pico/tools/src/main/java/io/helidon/pico/tools/AbstractCreator.java
  pico/tools/src/main/java/io/helidon/pico/tools/ApplicationCreatorDefault.java
  tests/functional/request-scope-injection/src/test/java/io/helidon/tests/functional/context/injection/CheckInjectionTest.java
Labels: 4.x, OCA Verified

#6792 [4.x]: Fix params of @ExampleObject annotations in examples (#6791)
  docs/mp/openapi.adoc
  docs/mp/openapi/openapi.adoc
  examples/microprofile/openapi-basic/src/main/java/io/helidon/microprofile/examples/openapi/basic/GreetResource.java
Labels: OCA Verified

#6815 [4.x] - Clean MP Telemetry dependencies
  dependencies/pom.xml
  microprofile/telemetry/pom.xml
  microprofile/tests/tck/tck-telemetry/pom.xml
Labels: 4.x, OCA Verified, telemetry

#6812 Refactor examples/nima/media into examples/media/multipart
  examples/media/multipart/README.md
  examples/media/multipart/pom.xml
  examples/media/multipart/src/main/java/io/helidon/examples/media/multipart/FileService.java
  examples/media/multipart/src/main/java/io/helidon/examples/media/multipart/FileStorage.java
  examples/media/multipart/src/main/java/io/helidon/examples/media/multipart/Main.java
  examples/media/multipart/src/main/resources/WEB/index.html
  examples/media/multipart/src/main/resources/logging.properties
  examples/media/multipart/src/test/java/io/helidon/examples/media/multipart/FileServiceTest.java
Labels: OCA Verified

#6794 3.x upgrade Weld
  .gitignore
  dependencies/pom.xml
Labels: OCA Verified

#6816 Module helidon-reactive-webclient-jaxrs is no longer needed
  bom/pom.xml
  examples/translator-app/frontend/pom.xml
  reactive/webclient/jaxrs/pom.xml
  reactive/webclient/jaxrs/src/main/java/io/helidon/reactive/webclient/jaxrs/JaxRsClient.java
  reactive/webclient/jaxrs/src/main/java/io/helidon/reactive/webclient/jaxrs/JerseyClientAutoDiscoverable.java
  reactive/webclient/jaxrs/src/main/java/io/helidon/reactive/webclient/jaxrs/package-info.java
  reactive/webclient/jaxrs/src/main/java/module-info.java
  reactive/webclient/pom.xml
  security/integration/jersey-client/pom.xml
  security/integration/jersey-client/src/main/java/module-info.java
  security/integration/jersey/pom.xml
  security/integration/jersey/src/main/java/module-info.java
  security/providers/oidc-common/pom.xml
  security/providers/oidc-common/src/main/java/module-info.java
  tracing/jersey-client/pom.xml
  tracing/jersey-client/src/main/java/module-info.java
Labels: jax-rs, 4.x, OCA Verified, jersey

#6833 Convenient method status(int) in ServerResponse.
  nima/tests/integration/webserver/webserver/src/test/java/io/helidon/nima/tests/integration/server/StatusCodeTest.java
  nima/webserver/webserver/src/main/java/io/helidon/nima/webserver/http/ServerResponse.java
Labels: webserver, Níma, OCA Verified

#6835 [3.x] 6524 Intermittent watermark test fix
  webserver/webserver/src/test/java/io/helidon/webserver/WaterMarkedBackpressureIT.java
Labels: OCA Verified

#6814 Update MessagingHealthTest to use Nima WebClient instead of Reactive WebClient
  microprofile/messaging/health/pom.xml
  microprofile/messaging/health/src/test/java/io/helidon/microprofile/messaging/health/MessagingHealthTest.java
Labels: OCA Verified

#6836 [2.x] 6524 Intermittent watermark test fix
  webserver/webserver/src/test/java/io/helidon/webserver/WaterMarkedBackpressureIT.java
Labels: OCA Verified

#6842 Improved performance of metric lookups in MetricProducer
  microprofile/metrics/pom.xml
  microprofile/metrics/src/main/java/io/helidon/microprofile/metrics/MetricProducer.java
  microprofile/metrics/src/test/java/io/helidon/microprofile/metrics/MetricLookupTest.java
Labels: performance, OCA Verified

#6844 support lowercase for modifiers names
  builder/processor-tools/src/main/java/io/helidon/builder/processor/tools/BeanUtils.java
  builder/processor-tools/src/main/java/io/helidon/builder/processor/tools/BodyContext.java
  builder/processor-tools/src/main/java/io/helidon/builder/processor/tools/BuilderTypeTools.java
  common/types/src/main/java/io/helidon/common/types/TypeInfo.java
  pico/processor/src/main/java/io/helidon/pico/processor/PicoAnnotationProcessor.java
  pico/tools/src/main/java/io/helidon/pico/tools/TypeTools.java
Labels: OCA Verified

#6841 TypeInfo and TypedElementName API name tuning
  builder/builder-config-processor/src/main/java/io/helidon/builder/config/processor/ConfigBeanBuilderCreator.java
  builder/builder-config-processor/src/test/java/io/helidon/builder/config/processor/ConfigBeanBuilderCreatorTest.java
  builder/processor-spi/src/main/java/io/helidon/builder/processor/spi/TypeInfoCreatorProvider.java
  builder/processor-tools/src/main/java/io/helidon/builder/processor/tools/BodyContext.java
  builder/processor-tools/src/main/java/io/helidon/builder/processor/tools/BuilderTypeTools.java
  builder/processor-tools/src/main/java/io/helidon/builder/processor/tools/DefaultBuilderCreatorProvider.java
  builder/processor-tools/src/main/java/io/helidon/builder/processor/tools/GenerateJavadoc.java
  builder/processor-tools/src/main/java/io/helidon/builder/processor/tools/GenerateMethod.java
  common/types/src/main/java/io/helidon/common/types/AnnotationAndValueDefault.java
  common/types/src/main/java/io/helidon/common/types/TypeInfo.java
  common/types/src/main/java/io/helidon/common/types/TypeInfoDefault.java
  common/types/src/main/java/io/helidon/common/types/TypedElementInfo.java
  common/types/src/main/java/io/helidon/common/types/TypedElementInfoDefault.java
  common/types/src/test/java/io/helidon/common/types/TypedElementInfoDefaultTest.java
  nima/http/processor/src/main/java/io/helidon/nima/http/processor/HttpMethodCreator.java
  pico/api/src/main/java/io/helidon/pico/api/InvocationContext.java
  pico/configdriven/processor/src/main/java/io/helidon/pico/configdriven/processor/ConfiguredByAnnotationProcessor.java
  pico/processor/src/main/java/io/helidon/pico/processor/ActiveProcessorUtils.java
  pico/processor/src/main/java/io/helidon/pico/processor/CustomAnnotationProcessor.java
  pico/processor/src/main/java/io/helidon/pico/processor/GeneralProcessorUtils.java
  pico/processor/src/main/java/io/helidon/pico/processor/PicoAnnotationProcessor.java
  pico/processor/src/test/java/io/helidon/pico/processor/CustomAnnotationProcessorTest.java
  pico/runtime/src/main/java/io/helidon/pico/runtime/InterceptedMethod.java
  pico/runtime/src/test/java/io/helidon/pico/runtime/InvocationTest.java
  pico/tests/resources-pico/src/test/resources/expected/ximpl-interceptor._java_
  pico/tests/resources-pico/src/test/resources/expected/yimpl-interceptor._java_
  pico/tests/resources-plain/src/main/java/io/helidon/pico/tests/plain/interceptor/TestNamedInterceptor.java
  pico/tools/src/main/java/io/helidon/pico/tools/CustomAnnotationTemplateRequest.java
  pico/tools/src/main/java/io/helidon/pico/tools/CustomAnnotationTemplateResponse.java
  pico/tools/src/main/java/io/helidon/pico/tools/InterceptorCreatorDefault.java
  pico/tools/src/main/resources/templates/pico/default/interface-based-interceptor.hbs
  pico/tools/src/main/resources/templates/pico/default/no-arg-based-interceptor.hbs
Labels: OCA Verified

#6805 2.x Upgrade Weld #6575
  .gitignore
  dependencies/pom.xml
  integrations/graal/mp-native-image-extension/src/main/java/io/helidon/integrations/graal/mp/nativeimage/extension/WeldSubstitutions.java
  microprofile/weld/weld-core-impl/src/main/java/org/jboss/weld/bean/proxy/ProxyFactory.java
Labels: OCA Verified

#6851 Avoid calling MimeParser.offer with empty buffers
  media/multipart/src/main/java/io/helidon/media/multipart/MimeParser.java
  media/multipart/src/main/java/io/helidon/media/multipart/MultiPartDecoder.java
  media/multipart/src/test/java/io/helidon/media/multipart/MultiPartDecoderTest.java
Labels: 2.x, media-support, OCA Verified

#6839 Porting of example to Nima and removal of reactive dependencies
  examples/health/basics/pom.xml
  examples/health/basics/src/main/java/io/helidon/examples/health/basics/Main.java
Labels: 4.x, OCA Verified

#6868 Add option to disable DNS Resolver for WebClient.
  webclient/webclient/pom.xml
  webclient/webclient/src/main/java/io/helidon/webclient/DnsResolverType.java
  webclient/webclient/src/main/java/io/helidon/webclient/WebClientRequestBuilderImpl.java
  webclient/webclient/src/test/java/io/helidon/webclient/DnsResolverTest.java
Labels: 2.x, OCA Verified

#6861 Update examples/logging/log4j to use Nima
  examples/logging/log4j/README.md
  examples/logging/log4j/pom.xml
  examples/logging/log4j/src/main/java/io/helidon/examples/logging/log4j/Main.java
Labels: OCA Verified

#6862 Update examples/logging/slf4j to use Nima
  examples/logging/slf4j/README.md
  examples/logging/slf4j/pom.xml
  examples/logging/slf4j/src/main/java/io/helidon/examples/logging/slf4j/Main.java
Labels: OCA Verified

#6865 Update examples/logging/jul to use Nima
  examples/logging/jul/README.md
  examples/logging/jul/pom.xml
  examples/logging/jul/src/main/java/io/helidon/examples/logging/jul/Main.java
Labels: OCA Verified

#6800 Creates a clean set of Pico examples
  examples/pico/README.md
  examples/pico/application/README.md
  examples/pico/application/pom.xml
  examples/pico/application/src/main/java/io/helidon/examples/pico/application/Main.java
  examples/pico/application/src/main/java/io/helidon/examples/pico/application/package-info.java
  examples/pico/application/src/main/resources/logging.properties
  examples/pico/application/src/test/java/io/helidon/examples/pico/application/PicoApplicationTest.java
  examples/pico/basics/README.md
  examples/pico/basics/pom.xml
  examples/pico/basics/src/main/java/io/helidon/examples/pico/basics/Big.java
  examples/pico/basics/src/main/java/io/helidon/examples/pico/basics/BigHammer.java
  examples/pico/basics/src/main/java/io/helidon/examples/pico/basics/Hammer.java
  examples/pico/basics/src/main/java/io/helidon/examples/pico/basics/Little.java
  examples/pico/basics/src/main/java/io/helidon/examples/pico/basics/LittleHammer.java
  examples/pico/basics/src/main/java/io/helidon/examples/pico/basics/Main.java
  examples/pico/basics/src/main/java/io/helidon/examples/pico/basics/Tool.java
  examples/pico/basics/src/main/java/io/helidon/examples/pico/basics/ToolBox.java
  examples/pico/basics/src/main/java/io/helidon/examples/pico/basics/package-info.java
  examples/pico/basics/src/main/resources/logging.properties
  examples/pico/configdriven/README.md
  examples/pico/configdriven/pom.xml
  examples/pico/configdriven/src/main/java/io/helidon/examples/pico/configdriven/Drill.java
  examples/pico/configdriven/src/main/java/io/helidon/examples/pico/configdriven/DrillConfig.java
  examples/pico/configdriven/src/main/java/io/helidon/examples/pico/configdriven/Main.java
  examples/pico/configdriven/src/main/java/io/helidon/examples/pico/configdriven/package-info.java
  examples/pico/configdriven/src/main/resources/application.yaml
  examples/pico/configdriven/src/main/resources/logging.properties
  examples/pico/interceptors/README.md
  examples/pico/interceptors/pom.xml
  examples/pico/interceptors/src/main/java/io/helidon/examples/pico/interceptors/Main.java
  examples/pico/interceptors/src/main/java/io/helidon/examples/pico/interceptors/ScrewDriver.java
  examples/pico/interceptors/src/main/java/io/helidon/examples/pico/interceptors/Turn.java
  examples/pico/interceptors/src/main/java/io/helidon/examples/pico/interceptors/TurnInterceptor.java
  examples/pico/interceptors/src/main/java/io/helidon/examples/pico/interceptors/TurningTool.java
  examples/pico/interceptors/src/main/java/io/helidon/examples/pico/interceptors/package-info.java
  examples/pico/interceptors/src/main/resources/logging.properties
  examples/pico/pom.xml
  examples/pico/providers/README.md
  examples/pico/providers/pom.xml
  examples/pico/providers/src/main/java/io/helidon/examples/pico/providers/AngleGrinderSaw.java
  examples/pico/providers/src/main/java/io/helidon/examples/pico/providers/Blade.java
  examples/pico/providers/src/main/java/io/helidon/examples/pico/providers/BladeProvider.java
  examples/pico/providers/src/main/java/io/helidon/examples/pico/providers/CircularSaw.java
  examples/pico/providers/src/main/java/io/helidon/examples/pico/providers/HandSaw.java
  examples/pico/providers/src/main/java/io/helidon/examples/pico/providers/Main.java
  examples/pico/providers/src/main/java/io/helidon/examples/pico/providers/Nail.java
  examples/pico/providers/src/main/java/io/helidon/examples/pico/providers/NailGun.java
  examples/pico/providers/src/main/java/io/helidon/examples/pico/providers/NailProvider.java
  examples/pico/providers/src/main/java/io/helidon/examples/pico/providers/Saw.java
  examples/pico/providers/src/main/java/io/helidon/examples/pico/providers/SizedBlade.java
  examples/pico/providers/src/main/java/io/helidon/examples/pico/providers/StandardNail.java
  examples/pico/providers/src/main/java/io/helidon/examples/pico/providers/TableSaw.java
  examples/pico/providers/src/main/java/io/helidon/examples/pico/providers/package-info.java
  examples/pico/providers/src/main/resources/logging.properties
  examples/pico/providers/src/test/java/io/helidon/examples/pico/providers/AllenWrench.java
  examples/pico/providers/src/test/java/io/helidon/examples/pico/providers/ProvidersTest.java
  examples/pico/providers/src/test/java/io/helidon/examples/pico/providers/Wrench.java
  examples/pom.xml
Labels: 4.x, pico, OCA Verified

#6875 Improved performance of metric lookups in MetricProducer
  metrics/api/src/main/java/io/helidon/metrics/api/AbstractRegistry.java
  microprofile/metrics/pom.xml
  microprofile/metrics/src/main/java/io/helidon/microprofile/metrics/MetricProducer.java
  microprofile/metrics/src/test/java/io/helidon/microprofile/metrics/MetricLookupTest.java
Labels: 2.x, performance, OCA Verified

#6846 Update ByteBufferDataChunk.isReleased and ByteBufDataChunk.isReleased to use AtomicBoolean
  common/http/src/main/java/io/helidon/common/http/ByteBufferDataChunk.java
  tests/integration/pom.xml
  tests/integration/se-gh-6845/pom.xml
  tests/integration/se-gh-6845/src/main/java/io/helidon/tests/integration/gh6845/Main.java
  tests/integration/se-gh-6845/src/test/java/io/helidon/tests/integration/gh6845/ChunkReleaseTest.java
  webserver/webserver/src/main/java/io/helidon/webserver/ByteBufDataChunk.java
Labels: OCA Verified

#6877 Removed examples/webserver/jersey
  examples/webserver/jersey/README.md
  examples/webserver/jersey/pom.xml
  examples/webserver/jersey/src/main/java/io/helidon/reactive/webserver/examples/jersey/HelloWorld.java
  examples/webserver/jersey/src/main/java/io/helidon/reactive/webserver/examples/jersey/Main.java
  examples/webserver/jersey/src/main/java/io/helidon/reactive/webserver/examples/jersey/package-info.java
  examples/webserver/jersey/src/main/resources/logging.properties
  examples/webserver/jersey/src/test/java/io/helidon/reactive/webserver/examples/jersey/HelloWorldTest.java
  examples/webserver/pom.xml
Labels: examples, 4.x, OCA Verified

#6853 MultiPart Builder improvements
  media/multipart/src/main/java/io/helidon/media/multipart/MultiPart.java
  media/multipart/src/main/java/io/helidon/media/multipart/ReadableBodyPart.java
  media/multipart/src/main/java/io/helidon/media/multipart/ReadableBodyPartHeaders.java
  media/multipart/src/main/java/io/helidon/media/multipart/WriteableBodyPart.java
  media/multipart/src/main/java/io/helidon/media/multipart/WriteableBodyPartHeaders.java
  media/multipart/src/main/java/io/helidon/media/multipart/WriteableMultiPart.java
Labels: OCA Verified

#6880 gRPC Unauthenticated status code fix
  security/integration/grpc/src/main/java/io/helidon/security/integration/grpc/GrpcSecurityHandler.java
  security/integration/grpc/src/test/java/io/helidon/security/integration/grpc/SecurityFromConfigIT.java
  security/integration/grpc/src/test/java/io/helidon/security/integration/grpc/ServiceAndMethodLevelSecurityIT.java
  security/integration/grpc/src/test/resources/application.yaml
Labels: OCA Verified

#6725 [3.x] LRA coordinator docker fix
  examples/microprofile/lra/README.md
  lra/coordinator/server/Dockerfile
Labels: lra, OCA Verified

#6898 Avoid calling MimeParser.offer with empty buffers
  media/multipart/src/main/java/io/helidon/media/multipart/MimeParser.java
  media/multipart/src/main/java/io/helidon/media/multipart/MultiPartDecoder.java
  media/multipart/src/test/java/io/helidon/media/multipart/MultiPartDecoderTest.java
Labels: OCA Verified

#6899 Make ByteBufferDataChunk.isReleased and ByteBufDataChunk.isReleased thread-safe
  common/http/src/main/java/io/helidon/common/http/ByteBufferDataChunk.java
  tests/integration/pom.xml
  tests/integration/se-gh-6845/pom.xml
  tests/integration/se-gh-6845/src/main/java/io/helidon/tests/integration/gh6845/Main.java
  tests/integration/se-gh-6845/src/test/java/io/helidon/tests/integration/gh6845/ChunkReleaseTest.java
  webserver/webserver/src/main/java/io/helidon/webserver/ByteBufDataChunk.java
Labels: OCA Verified

#6900 MultiPart Builder improvements
  media/multipart/src/main/java/io/helidon/media/multipart/ReadableBodyPart.java
  media/multipart/src/main/java/io/helidon/media/multipart/ReadableBodyPartHeaders.java
  media/multipart/src/main/java/io/helidon/media/multipart/WriteableBodyPart.java
  media/multipart/src/main/java/io/helidon/media/multipart/WriteableBodyPartHeaders.java
  media/multipart/src/main/java/io/helidon/media/multipart/WriteableMultiPart.java
Labels: OCA Verified

#6854 Update examples/graphql/basics to use Nima
  examples/grpc/basics/pom.xml
  examples/grpc/basics/src/main/java/io/helidon/grpc/examples/basics/Server.java
Labels: OCA Verified

#6688 DOCS: fix links for openapi in 4x
  docs/includes/attributes.adoc
Labels: docs, OCA Verified

#6912 3.x: Upgrade maven-dependency-plugin to 3.6.0
  applications/parent/pom.xml
  examples/quickstarts/helidon-standalone-quickstart-mp/pom.xml
  examples/quickstarts/helidon-standalone-quickstart-se/pom.xml
  pom.xml
Labels: 3.x, OCA Verified

#6834 [4.x] - MpConfig convertToHelidon exception fix
  config/config-mp/src/main/java/io/helidon/config/mp/MpConfig.java
  microprofile/config/src/test/java/io/helidon/microprofile/config/MpConfigConvertTest.java
Labels: bug, P3, 4.x, OCA Verified

#6915 2.x: Upgrade maven-dependency-plugin to 3.6.0
  applications/parent/pom.xml
  examples/quickstarts/helidon-standalone-quickstart-mp/pom.xml
  examples/quickstarts/helidon-standalone-quickstart-se/pom.xml
  pom.xml
Labels: 2.x, OCA Verified

#6914 [1.x] Fix native-image with Netty >= 4.1.83.Final
  webserver/webserver/src/main/resources/META-INF/native-image/helidon-webserver-reflection-config.json
Labels: OCA Verified

#6883 Custom Annotation Processor Refinements
  nima/http/processor/src/main/java/io/helidon/nima/http/processor/HttpMethodCreator.java
  pico/processor/src/main/java/io/helidon/pico/processor/CustomAnnotationProcessor.java
  pico/processor/src/main/java/io/helidon/pico/processor/GenericTemplateCreatorDefault.java
  pico/processor/src/test/java/io/helidon/pico/processor/CustomAnnotationProcessorTest.java
  pico/tools/src/main/java/io/helidon/pico/tools/CustomAnnotationTemplateRequest.java
Labels: pico, OCA Verified

#6910 Skip uri encoding feature
  nima/http2/webclient/src/main/java/io/helidon/nima/http2/webclient/ClientRequestImpl.java
  nima/webclient/webclient/src/main/java/io/helidon/nima/webclient/ClientRequest.java
  nima/webclient/webclient/src/main/java/io/helidon/nima/webclient/UriHelper.java
  nima/webclient/webclient/src/main/java/io/helidon/nima/webclient/http1/ClientRequestImpl.java
  nima/webclient/webclient/src/test/java/io/helidon/nima/webclient/HttpClientTest.java
  nima/webclient/webclient/src/test/java/io/helidon/nima/webclient/http1/ClientRequestImplTest.java
Labels: OCA Verified

#6913 4.x: Upgrade maven-dependency-plugin to 3.6.0
  applications/parent/pom.xml
  examples/quickstarts/helidon-standalone-quickstart-mp/pom.xml
  examples/quickstarts/helidon-standalone-quickstart-se/pom.xml
  pom.xml
Labels: 4.x, OCA Verified

#6916 Response should not be chunked if there is no entity
  webserver/webserver/src/main/java/io/helidon/webserver/BareResponseImpl.java
  webserver/webserver/src/test/java/io/helidon/webserver/PlainTest.java
Labels: OCA Verified
