Repository helidon-io/helidon, pull requests merged in 2023-08, with the labels that each got.

#7228 Fix gRPC to calculate the correct class name for method request and response types
  nima/grpc/webserver/src/main/java/io/helidon/nima/grpc/webserver/Grpc.java
Labels: grpc, 4.x, OCA Verified

#7292 [4.x] - Change default to SYSTEM proxy in WebClient
  jersey/connector/src/main/java/io/helidon/jersey/connector/HelidonConnector.java
  jersey/connector/src/test/java/io/helidon/jersey/connector/ConfigTest.java
  nima/webclient/api/src/main/java/io/helidon/nima/webclient/api/HttpClientConfigSupport.java
  nima/webclient/api/src/test/java/io/helidon/nima/webclient/api/ProxyTest.java
  nima/webclient/http1/src/main/java/io/helidon/nima/webclient/http1/Http1CallChainBase.java
Labels: webclient, 4.x, OCA Verified

#7299 Fix tests disabled during WebClient redesign #7286
  nima/http2/webclient/src/main/java/io/helidon/nima/http2/webclient/Http2ClientResponseImpl.java
  nima/tests/integration/http2/client/src/test/java/io/helidon/nima/tests/integration/http2/client/ClientFlowControlTest.java
  nima/tests/integration/http2/client/src/test/java/io/helidon/nima/tests/integration/http2/client/HeadersTest.java
  nima/tests/integration/http2/client/src/test/resources/logging-test.properties
  nima/tests/integration/http2/server/src/test/java/io/helidon/nima/tests/integration/http2/webserver/FlowControlTest.java
Labels: OCA Verified

#7298 3.x: Upgrade grpc-java to 1.57.1 and remove repackaging of io.grpc
  config/etcd/src/main/java/module-info.java
  dependencies/pom.xml
  grpc/core/pom.xml
  grpc/core/src/main/java/module-info.java
  grpc/io.grpc/pom.xml
  grpc/io.grpc/src/main/java/io/grpc/LoadBalancerProvider.java
  grpc/io.grpc/src/main/java/io/grpc/ManagedChannelProvider.java
  grpc/io.grpc/src/main/java/io/grpc/NameResolverProvider.java
  grpc/io.grpc/src/main/java/io/grpc/ServerProvider.java
  grpc/io.grpc/src/main/java/io/grpc/inprocess/DummyClass.java
  grpc/io.grpc/src/main/java/io/grpc/inprocess/package-info.java
  grpc/io.grpc/src/main/java/io/grpc/internal/BinaryLogProvider.java
  grpc/io.grpc/src/main/java/io/grpc/internal/DnsNameResolverProvider.java
  grpc/io.grpc/src/main/java/io/grpc/internal/PickFirstLoadBalancerProvider.java
  grpc/io.grpc/src/main/java/io/grpc/internal/package-info.java
  grpc/io.grpc/src/main/java/io/grpc/package-info.java
  grpc/io.grpc/src/main/java/io/grpc/stub/DummyClass.java
  grpc/io.grpc/src/main/java/io/grpc/stub/annotations/DummyClass.java
  grpc/io.grpc/src/main/java/io/grpc/stub/annotations/package-info.java
  grpc/io.grpc/src/main/java/io/grpc/stub/package-info.java
  grpc/io.grpc/src/main/java/io/grpc/util/DummyClass.java
  grpc/io.grpc/src/main/java/io/grpc/util/OutlierDetectionLoadBalancerProvider.java
  grpc/io.grpc/src/main/java/io/grpc/util/SecretRoundRobinLoadBalancerProvider.java
  grpc/io.grpc/src/main/java/io/grpc/util/package-info.java
  grpc/io.grpc/src/main/java/module-info.java
  grpc/server/src/main/java/module-info.java
  microprofile/grpc/client/src/main/java/module-info.java
  microprofile/grpc/server/src/main/java/module-info.java
  security/integration/grpc/src/main/java/module-info.java
Labels: grpc, dependencies, 3.x, OCA Verified

#7306 1.x: Upgrade grpc-java to 1.57.1. Remove grpc repackaging. Use grpc bom
  config/etcd/src/main/java9/module-info.java
  dependencies/pom.xml
  grpc/core/pom.xml
  grpc/core/src/main/java9/module-info.java
  grpc/io.grpc/pom.xml
  grpc/io.grpc/src/main/java/io/grpc/LoadBalancerProvider.java
  grpc/io.grpc/src/main/java/io/grpc/ManagedChannelProvider.java
  grpc/io.grpc/src/main/java/io/grpc/NameResolverProvider.java
  grpc/io.grpc/src/main/java/io/grpc/ServerProvider.java
  grpc/io.grpc/src/main/java/io/grpc/inprocess/DummyClass.java
  grpc/io.grpc/src/main/java/io/grpc/inprocess/package-info.java
  grpc/io.grpc/src/main/java/io/grpc/internal/BinaryLogProvider.java
  grpc/io.grpc/src/main/java/io/grpc/internal/DnsNameResolverProvider.java
  grpc/io.grpc/src/main/java/io/grpc/internal/PickFirstLoadBalancerProvider.java
  grpc/io.grpc/src/main/java/io/grpc/internal/package-info.java
  grpc/io.grpc/src/main/java/io/grpc/package-info.java
  grpc/io.grpc/src/main/java/io/grpc/stub/DummyClass.java
  grpc/io.grpc/src/main/java/io/grpc/stub/annotations/DummyClass.java
  grpc/io.grpc/src/main/java/io/grpc/stub/annotations/package-info.java
  grpc/io.grpc/src/main/java/io/grpc/stub/package-info.java
  grpc/io.grpc/src/main/java/io/grpc/util/DummyClass.java
  grpc/io.grpc/src/main/java/io/grpc/util/package-info.java
  grpc/io.grpc/src/main/java9/module-info.java
  grpc/server/src/main/java9/module-info.java
  microprofile/grpc/client/src/main/java9/module-info.java
  microprofile/grpc/server/src/main/java9/module-info.java
Labels: grpc, 1.x, dependencies, OCA Verified

#7317 Resolves issue 7316, which features some intermittently failing H2 database tests
  integrations/jdbc/jdbc/src/test/java/io/helidon/integrations/jdbc/TestConditionallyCloseableConnection.java
  integrations/jdbc/jdbc/src/test/java/io/helidon/integrations/jdbc/TestH2IsolationLevelCases.java
Labels: P2, jpa/jta, 3.x, testing, OCA Verified

#7192 4.x: Use Helidon copyright module for generated code
  builder/tests/builder/pom.xml
  common/configurable/pom.xml
  common/key-util/pom.xml
  common/socket/pom.xml
  config/config/pom.xml
  config/tests/service-registry/pom.xml
  inject/api/pom.xml
  inject/configdriven/api/pom.xml
  inject/configdriven/runtime/pom.xml
  inject/configdriven/tests/config/pom.xml
  inject/configdriven/tests/configuredby-application/pom.xml
  inject/configdriven/tests/configuredby/pom.xml
  inject/processor/pom.xml
  inject/tests/interception/pom.xml
  inject/tests/resources-inject/pom.xml
  inject/tests/resources-inject/src/test/java/io/helidon/inject/tests/inject/interceptor/InterceptorRuntimeTest.java
  inject/tests/resources-inject/src/test/resources/expected/ximpl-interceptor._java_
  integrations/oci/sdk/runtime/pom.xml
  nima/common/tls/pom.xml
  nima/fault-tolerance/fault-tolerance/pom.xml
  nima/grpc/webserver/pom.xml
  nima/http/encoding/encoding/pom.xml
  nima/http2/webserver/pom.xml
  nima/sse/webserver/pom.xml
  nima/webserver/webserver/pom.xml
  nima/websocket/webserver/pom.xml
Labels: OCA Verified

#7330 Integrate build tools 4.0.0-M1
  applications/parent/pom.xml
  etc/scripts/test-packaging-jlink.sh
  examples/nima/quickstart-standalone/pom.xml
  examples/quickstarts/helidon-standalone-quickstart-mp/pom.xml
  examples/quickstarts/helidon-standalone-quickstart-se/pom.xml
  pom.xml
Labels: OCA Verified

#7314 Encode all characters that should be encoded in URI, including % itself.
  common/uri/README.md
  common/uri/src/main/java/io/helidon/common/uri/UriEncoding.java
  common/uri/src/test/java/io/helidon/common/uri/UriPathTest.java
  tests/integration/webclient/src/test/java/io/helidon/tests/integration/webclient/UriPartTest.java
Labels: OCA Verified

#7318 Replace deprecated socket(String) on namedSocket(String) from ServerConfiguration
  webserver/webserver/src/main/java/io/helidon/webserver/NettyWebServer.java
Labels: OCA Verified

#7325 2.x Replace deprecated socket(String) on namedSocket(String) from ServerConfiguration
  webserver/webserver/src/main/java/io/helidon/webserver/NettyWebServer.java
Labels: OCA Verified

#7322 Add automatic support in WebClient for JVM http.proxyHost and related…
  webclient/webclient/src/main/java/io/helidon/webclient/Proxy.java
  webclient/webclient/src/test/java/io/helidon/webclient/ProxyTest.java
Labels: OCA Verified

#7335 Remove public constructors from production types.
  nima/common/tls/src/main/java/io/helidon/nima/common/tls/TrustAllManagerFactory.java
  nima/http2/http2/src/main/java/io/helidon/nima/http2/Http2ConnectionWriter.java
  nima/http2/http2/src/main/java/io/helidon/nima/http2/Http2HuffmanDecoder.java
  nima/http2/http2/src/main/java/io/helidon/nima/http2/Http2HuffmanEncoder.java
  nima/http2/http2/src/test/java/io/helidon/nima/http2/Http2HeadersTest.java
  nima/http2/http2/src/test/java/io/helidon/nima/http2/Http2HuffmanTest.java
  nima/http2/webclient/src/main/java/io/helidon/nima/http2/webclient/Http2ClientStream.java
  nima/http2/webserver/src/main/java/io/helidon/nima/http2/webserver/Http2Connection.java
Labels: OCA Verified

#7338 Using SE flavor instead of Nima
  common/features/api/src/main/java/io/helidon/common/features/api/HelidonFlavor.java
  config/config/src/main/java/module-info.java
  health/health-checks/src/main/java/module-info.java
  integrations/neo4j/health/src/main/java/module-info.java
  integrations/neo4j/metrics/src/main/java/module-info.java
  integrations/neo4j/neo4j/src/main/java/module-info.java
  integrations/vault/auths/approle/src/main/java/module-info.java
  integrations/vault/auths/k8s/src/main/java/module-info.java
  integrations/vault/auths/token/src/main/java/module-info.java
  integrations/vault/secrets/cubbyhole/src/main/java/module-info.java
  integrations/vault/secrets/database/src/main/java/module-info.java
  integrations/vault/secrets/kv1/src/main/java/module-info.java
  integrations/vault/secrets/kv2/src/main/java/module-info.java
  integrations/vault/secrets/pki/src/main/java/module-info.java
  integrations/vault/secrets/transit/src/main/java/module-info.java
  integrations/vault/sys/sys/src/main/java/module-info.java
  integrations/vault/vault/src/main/java/module-info.java
  logging/log4j/src/main/java/module-info.java
  nima/fault-tolerance/fault-tolerance/src/main/java/module-info.java
  nima/graphql/server/src/main/java/module-info.java
  nima/grpc/webserver/src/main/java/module-info.java
  nima/http/encoding/deflate/src/main/java/module-info.java
  nima/http/encoding/encoding/src/main/java/module-info.java
  nima/http/encoding/gzip/src/main/java/module-info.java
  nima/http/media/jackson/src/main/java/module-info.java
  nima/http/media/jsonb/src/main/java/module-info.java
  nima/http/media/jsonp/src/main/java/module-info.java
  nima/http/media/media/src/main/java/module-info.java
  nima/http/media/multipart/src/main/java/module-info.java
  nima/http2/webclient/src/main/java/module-info.java
  nima/http2/webserver/src/main/java/module-info.java
  nima/observe/health/src/main/java/module-info.java
  nima/observe/metrics/src/main/java/module-info.java
  nima/sse/webserver/src/main/java/module-info.java
  nima/webclient/api/src/main/java/module-info.java
  nima/webclient/http1/src/main/java/module-info.java
  nima/webserver/access-log/src/main/java/module-info.java
  nima/webserver/cors/src/main/java/module-info.java
  nima/webserver/static-content/src/main/java/module-info.java
  nima/webserver/tracing/src/main/java/module-info.java
  nima/webserver/webserver/src/main/java/io/helidon/nima/webserver/LoomServer.java
  nima/websocket/client/src/main/java/module-info.java
  nima/websocket/webserver/src/main/java/module-info.java
  nima/websocket/websocket/src/main/java/module-info.java
  security/providers/abac/src/main/java/module-info.java
  security/providers/config-vault/src/main/java/module-info.java
  security/providers/google-login/src/main/java/module-info.java
  security/providers/header/src/main/java/module-info.java
  security/providers/http-auth/src/main/java/module-info.java
  security/providers/http-sign/src/main/java/module-info.java
  security/providers/idcs-mapper/src/main/java/module-info.java
  security/providers/jwt/src/main/java/module-info.java
  security/providers/oidc/src/main/java/module-info.java
  security/security/src/main/java/module-info.java
  tracing/jersey-client/src/main/java/module-info.java
  tracing/jersey/src/main/java/module-info.java
  tracing/providers/jaeger/src/main/java/module-info.java
  tracing/providers/zipkin/src/main/java/module-info.java
  tracing/tracing/src/main/java/module-info.java
Labels: 4.x, OCA Verified

#7340 4.x: Added support for WS endpoints in application scope
  microprofile/websocket/src/main/java/io/helidon/microprofile/tyrus/HelidonComponentProvider.java
  microprofile/websocket/src/test/java/io/helidon/microprofile/tyrus/ApplicationScopeTest.java
Labels: websocket, 4.x, OCA Verified

#7148 Update development guidelines to include naming rules for builder types.
  DEV-GUIDELINES.md
  builder/api/README.md
Labels: OCA Verified

#7334 Make sure JEP-290 is enforced in Níma
  common/common/src/main/java/io/helidon/common/SerializationConfig.java
  helidon/src/main/java/io/helidon/Main.java
  nima/webserver/webserver/src/main/java/io/helidon/nima/webserver/LoomServer.java
Labels: 4.x, OCA Verified

#6885 TCK Tracking: Jakarta EE 10 Core Profile #6799
  dependencies/pom.xml
  microprofile/config/src/main/java/io/helidon/microprofile/config/ConfigCdiExtension.java
  microprofile/tests/arquillian/src/main/java/io/helidon/microprofile/arquillian/HelidonContainerConfiguration.java
  microprofile/tests/arquillian/src/main/java/io/helidon/microprofile/arquillian/HelidonContainerExtension.java
  microprofile/tests/arquillian/src/main/java/io/helidon/microprofile/arquillian/HelidonDeployableContainer.java
  microprofile/tests/arquillian/src/main/resources/templates/beans.xml
  microprofile/tests/tck/pom.xml
  microprofile/tests/tck/tck-annotations/pom.xml
  microprofile/tests/tck/tck-cdi/pom.xml
  microprofile/tests/tck/tck-cdi/src/test/java/io/helidon/microprofile/cdi/tck/UrlLoaderExtension.java
  microprofile/tests/tck/tck-cdi/src/test/java/io/helidon/microprofile/cdi/tck/UrlResourceProvider.java
  microprofile/tests/tck/tck-cdi/src/test/resources/META-INF/beans.xml
  microprofile/tests/tck/tck-cdi/src/test/resources/META-INF/cdi-tck.properties
  microprofile/tests/tck/tck-cdi/src/test/resources/META-INF/services/org.jboss.arquillian.core.spi.LoadableExtension
  microprofile/tests/tck/tck-cdi/src/test/resources/application.yaml
  microprofile/tests/tck/tck-cdi/src/test/resources/arquillian.xml
  microprofile/tests/tck/tck-core-profile/README.md
  microprofile/tests/tck/tck-core-profile/artifact-install.sh
  microprofile/tests/tck/tck-core-profile/pom.xml
  microprofile/tests/tck/tck-core-profile/tck-core-profile-test/pom.xml
  microprofile/tests/tck/tck-core-profile/tck-core-profile-test/src/test/java/io/helidon/microprofile/coreprofile/tck/UrlLoaderExtension.java
  microprofile/tests/tck/tck-core-profile/tck-core-profile-test/src/test/java/io/helidon/microprofile/coreprofile/tck/UrlResourceProvider.java
  microprofile/tests/tck/tck-core-profile/tck-core-profile-test/src/test/resources/META-INF/services/org.jboss.arquillian.core.spi.LoadableExtension
  microprofile/tests/tck/tck-core-profile/tck-core-profile-test/src/test/resources/arquillian.xml
  microprofile/tests/tck/tck-graphql/pom.xml
  microprofile/tests/tck/tck-health/pom.xml
  microprofile/tests/tck/tck-inject/README.md
  microprofile/tests/tck/tck-inject/artifact-install.sh
  microprofile/tests/tck/tck-inject/pom.xml
  microprofile/tests/tck/tck-inject/tck-inject-test/pom.xml
  microprofile/tests/tck/tck-inject/tck-inject-test/src/test/java/io/helidon/microprofile/tests/inject/TckInjectTest.java
  microprofile/tests/tck/tck-inject/tck-inject-test/src/test/resources/META-INF/services/jakarta.enterprise.inject.se.SeContainerInitializer
  microprofile/tests/tck/tck-inject/tck-inject-test/src/test/resources/application.yaml
  microprofile/tests/tck/tck-jsonb/pom.xml
  microprofile/tests/tck/tck-jsonb/tck-jsonb-test/pom.xml
  microprofile/tests/tck/tck-jsonp/README.md
  microprofile/tests/tck/tck-jsonp/artifact-install.sh
  microprofile/tests/tck/tck-jsonp/pom.xml
  microprofile/tests/tck/tck-jsonp/tck-jsonp-test/pom.xml
  microprofile/tests/tck/tck-jwt-auth/pom.xml
  microprofile/tests/tck/tck-openapi/pom.xml
  microprofile/tests/tck/tck-opentracing/pom.xml
  microprofile/tests/tck/tck-reactive-operators/pom.xml
  microprofile/tests/tck/tck-rest-client/pom.xml
  microprofile/tests/tck/tck-restfull/README.md
  microprofile/tests/tck/tck-restfull/artifact-install.sh
  microprofile/tests/tck/tck-restfull/pom.xml
  microprofile/tests/tck/tck-restfull/tck-restfull-test/pom.xml
  microprofile/tests/tck/tck-restfull/tck-restfull-test/src/test/java/io/helidon/microprofile/restfull/tck/UrlLoaderExtension.java
  microprofile/tests/tck/tck-restfull/tck-restfull-test/src/test/java/io/helidon/microprofile/restfull/tck/UrlResourceProvider.java
  microprofile/tests/tck/tck-restfull/tck-restfull-test/src/test/resources/META-INF/services/org.jboss.arquillian.core.spi.LoadableExtension
  microprofile/tests/tck/tck-restfull/tck-restfull-test/src/test/resources/arquillian.xml
  microprofile/tests/tck/tck-telemetry/pom.xml
  pom.xml
Labels: OCA Verified

#7341 WebClient Follow Up
  nima/http/media/media/src/main/java/io/helidon/nima/http/media/ReadableEntityBase.java
  nima/http2/webclient/src/main/java/io/helidon/nima/http2/webclient/Http2CallChainBase.java
  nima/http2/webserver/src/main/java/io/helidon/nima/http2/webserver/Http2ServerResponse.java
  nima/http2/webserver/src/main/java/io/helidon/nima/http2/webserver/Http2Stream.java
  nima/tests/integration/encoding/deflate/pom.xml
  nima/tests/integration/encoding/deflate/src/test/java/io/helidon/nima/tests/integration/encoding/deflate/DeflateEncodingTest.java
  nima/tests/integration/encoding/deflate/src/test/resources/logging-test.properties
  nima/tests/integration/encoding/gzip/pom.xml
  nima/tests/integration/encoding/gzip/src/test/java/io/helidon/nima/tests/integration/encoding/gzip/GzipEncodingTest.java
  nima/tests/integration/encoding/gzip/src/test/resources/logging-test.properties
  nima/webclient/README.md
  nima/webclient/api/src/main/java/io/helidon/nima/webclient/api/HttpClientConfigBlueprint.java
Labels: webclient, OCA Verified

#7251 [3.x] Address maven 3.9.2 plugin issues.
  applications/mp/pom.xml
  applications/parent/pom.xml
  common/common/pom.xml
  config/etcd/pom.xml
  examples/microprofile/messaging-sse/pom.xml
  examples/quickstarts/helidon-standalone-quickstart-mp/pom.xml
  examples/quickstarts/helidon-standalone-quickstart-se/pom.xml
  examples/todo-app/frontend/pom.xml
  parent/pom.xml
  pom.xml
  tests/integration/jpa/simple/pom.xml
  webserver/webserver/src/main/java/io/helidon/webserver/ServerBasicConfig.java
  webserver/webserver/src/test/java/io/helidon/webserver/BytesReuseV2ApiTest.java
  webserver/webserver/src/test/java/io/helidon/webserver/CloseConnectionV2ApiTest.java
  webserver/webserver/src/test/java/io/helidon/webserver/CompressionV2ApiTest.java
  webserver/webserver/src/test/java/io/helidon/webserver/EncodingV2ApiTest.java
  webserver/webserver/src/test/java/io/helidon/webserver/FilterV2ApiTest.java
  webserver/webserver/src/test/java/io/helidon/webserver/Gh377V2ApiTest.java
  webserver/webserver/src/test/java/io/helidon/webserver/HttpPipelineV2ApiTest.java
  webserver/webserver/src/test/java/io/helidon/webserver/KeepAliveV2ApiTest.java
  webserver/webserver/src/test/java/io/helidon/webserver/NettyWebServerV2ApiTest.java
  webserver/webserver/src/test/java/io/helidon/webserver/PlainV2ApiTest.java
  webserver/webserver/src/test/java/io/helidon/webserver/ServerConfigurationTest.java
Labels: OCA Verified

#7342 4.x: Add pull request template
  .github/pull_request_template.md
Labels: 4.x, OCA Verified

#7336 Use common config
  common/config/src/main/java/io/helidon/common/config/Config.java
  common/config/src/main/java/io/helidon/common/config/EmptyConfig.java
  config/config/src/main/java/io/helidon/config/Config.java
  config/config/src/main/java/io/helidon/config/ConfigProducer.java
  dbclient/metrics/src/main/java/io/helidon/dbclient/metrics/MetricBuilderBase.java
  integrations/microstream/metrics/src/main/java/io/helidon/integrations/microstream/metrics/MicrostreamMetricsSupport.java
  lra/coordinator/server/src/main/java/io/helidon/lra/coordinator/CoordinatorService.java
  lra/coordinator/server/src/main/java/io/helidon/lra/coordinator/Main.java
  messaging/connectors/aq/src/main/java/io/helidon/messaging/connectors/aq/AqConnector.java
  metrics/api/pom.xml
  metrics/api/src/main/java/io/helidon/metrics/api/BaseMetricsSettings.java
  metrics/api/src/main/java/io/helidon/metrics/api/BaseMetricsSettingsImpl.java
  metrics/api/src/main/java/io/helidon/metrics/api/ComponentMetricsSettings.java
  metrics/api/src/main/java/io/helidon/metrics/api/ComponentMetricsSettingsImpl.java
  metrics/api/src/main/java/io/helidon/metrics/api/KeyPerformanceIndicatorMetricsSettings.java
  metrics/api/src/main/java/io/helidon/metrics/api/KeyPerformanceIndicatorMetricsSettingsImpl.java
  metrics/api/src/main/java/io/helidon/metrics/api/MetricsSettings.java
  metrics/api/src/main/java/io/helidon/metrics/api/MetricsSettingsImpl.java
  metrics/api/src/main/java/io/helidon/metrics/api/RegistryFactory.java
  metrics/api/src/main/java/io/helidon/metrics/api/RegistryFactoryManager.java
  metrics/api/src/main/java/io/helidon/metrics/api/RegistryFilterSettings.java
  metrics/api/src/main/java/io/helidon/metrics/api/RegistryFilterSettingsImpl.java
  metrics/api/src/main/java/io/helidon/metrics/api/RegistrySettings.java
  metrics/api/src/main/java/io/helidon/metrics/api/RegistrySettingsImpl.java
  metrics/api/src/main/java/module-info.java
  metrics/api/src/test/java/io/helidon/metrics/api/TestGlobalTags.java
  metrics/metrics/src/main/java/io/helidon/metrics/RegistryFactory.java
  metrics/metrics/src/main/java/module-info.java
Labels: OCA Verified

#7362 Create a different config setting for inbound and outbound HTTP1 header
  nima/tests/integration/webclient/webclient/pom.xml
  nima/tests/integration/webclient/webclient/src/test/java/io/helidon/nima/webclient/http1/Http1ClientTest.java
  nima/tests/integration/webclient/webclient/src/test/java/io/helidon/nima/webclient/http1/ValidateHeadersTest.java
  nima/tests/integration/webserver/webserver/src/test/java/io/helidon/nima/tests/integration/server/ContentEncodingDisabledNoValidationTest.java
  nima/tests/integration/webserver/webserver/src/test/java/io/helidon/nima/tests/integration/server/DisableValidateHeadersTest.java
  nima/tests/integration/webserver/webserver/src/test/java/io/helidon/nima/tests/integration/server/ValidateRequestHeadersTest.java
  nima/tests/integration/webserver/webserver/src/test/java/io/helidon/nima/tests/integration/server/ValidateResponseHeadersTest.java
  nima/webclient/http1/src/main/java/io/helidon/nima/webclient/http1/Http1CallChainBase.java
  nima/webclient/http1/src/main/java/io/helidon/nima/webclient/http1/Http1CallEntityChain.java
  nima/webclient/http1/src/main/java/io/helidon/nima/webclient/http1/Http1CallOutputStreamChain.java
  nima/webclient/http1/src/main/java/io/helidon/nima/webclient/http1/Http1ClientProtocolConfigBlueprint.java
  nima/webclient/http1/src/test/java/io/helidon/nima/webclient/http1/Http1ClientTest.java
  nima/webserver/webserver/src/main/java/io/helidon/nima/webserver/http1/Http1ConfigBlueprint.java
  nima/webserver/webserver/src/main/java/io/helidon/nima/webserver/http1/Http1Connection.java
  nima/webserver/webserver/src/main/java/io/helidon/nima/webserver/http1/Http1ServerResponse.java
  nima/webserver/webserver/src/test/java/io/helidon/nima/webserver/http1/ConnectionConfigTest.java
  nima/webserver/webserver/src/test/resources/application.yaml
Labels: OCA Verified

#7352 OCI Global Config Source
  integrations/oci/sdk/README.md
  integrations/oci/sdk/runtime/README.md
  integrations/oci/sdk/runtime/pom.xml
  integrations/oci/sdk/runtime/src/main/java/io/helidon/integrations/oci/sdk/runtime/OciAuthenticationDetailsProvider.java
  integrations/oci/sdk/runtime/src/main/java/io/helidon/integrations/oci/sdk/runtime/OciConfigBlueprint.java
  integrations/oci/sdk/runtime/src/main/java/io/helidon/integrations/oci/sdk/runtime/OciExtension.java
  integrations/oci/sdk/runtime/src/main/java/module-info.java
  integrations/oci/sdk/runtime/src/test/java/io/helidon/integrations/oci/sdk/runtime/OciAuthenticationDetailsProviderTest.java
  integrations/oci/sdk/runtime/src/test/java/io/helidon/integrations/oci/sdk/runtime/OciConfigTest.java
  integrations/oci/sdk/runtime/src/test/java/io/helidon/integrations/oci/sdk/runtime/OciExtensionTest.java
  integrations/oci/sdk/runtime/src/test/java/io/helidon/integrations/oci/sdk/runtime/OciRegionProviderTest.java
  integrations/oci/sdk/runtime/src/test/resources/application.yaml
  integrations/oci/sdk/runtime/src/test/resources/test-oci-config-file.yaml
  integrations/oci/sdk/runtime/src/test/resources/test-oci-resource-principal.yaml
Labels: 3.x, 4.x, OCA Verified

#7346 4.x Http2Connection should ignore a max concurrent streams setting of zero from the client
  nima/http2/webserver/src/main/java/io/helidon/nima/http2/webserver/Http2Connection.java
  nima/tests/integration/grpc/server/pom.xml
  nima/tests/integration/grpc/server/src/main/java/io/helidon/nima/tests/integration/grpc/webserver/EventService.java
  nima/tests/integration/grpc/server/src/main/proto/events.proto
  nima/tests/integration/grpc/server/src/test/java/io/helidon/nima/tests/integration/grpc/webserver/EventsTest.java
Labels: 4.x, OCA Verified

#7365 Provider support in builders
  builder/api/src/main/java/io/helidon/builder/api/Prototype.java
  builder/api/src/main/java/io/helidon/builder/api/ProvidedUtil.java
  builder/processor/src/main/java/io/helidon/builder/processor/GenerateAbstractBuilder.java
  builder/tests/builder/pom.xml
  builder/tests/builder/src/main/java/io/helidon/builder/test/testsubjects/ConfigMethodBlueprint.java
  builder/tests/builder/src/main/java/io/helidon/builder/test/testsubjects/ConfigOptionalMethodBlueprint.java
  builder/tests/builder/src/main/java/io/helidon/builder/test/testsubjects/ProviderNoImpls.java
  builder/tests/builder/src/main/java/io/helidon/builder/test/testsubjects/SomeProvider.java
  builder/tests/builder/src/main/java/io/helidon/builder/test/testsubjects/SomeServiceProvider1.java
  builder/tests/builder/src/main/java/io/helidon/builder/test/testsubjects/SomeServiceProvider2.java
  builder/tests/builder/src/main/java/io/helidon/builder/test/testsubjects/WithProviderBlueprint.java
  builder/tests/builder/src/main/java/module-info.java
  builder/tests/builder/src/test/java/io/helidon/builder/test/ConfigMethodTest.java
  builder/tests/builder/src/test/java/io/helidon/builder/test/ProviderTest.java
  builder/tests/builder/src/test/resources/config-method-test.yaml
  builder/tests/builder/src/test/resources/provider-test.yaml
  builder/tests/common-types/pom.xml
  builder/tests/pom.xml
  config/metadata/src/main/java/io/helidon/config/metadata/ConfiguredOption.java
Labels: OCA Verified, builder

#7333 4.x Make OciMetricsDataTest.beforeEach public
  integrations/oci/metrics/metrics/src/test/java/io/helidon/integrations/oci/metrics/OciMetricsDataTest.java
Labels: OCA Verified

#7332 2.x Make OciMetricsDataTest.beforeEach non private
  integrations/oci/metrics/metrics/src/test/java/io/helidon/integrations/oci/metrics/OciMetricsDataTest.java
Labels: OCA Verified

#7363 [3.x] - Add white paper link to README.MD
  README.md
Labels: OCA Verified

#7378 [4.x] - Add white paper to README.MD
  README.md
Labels: 4.x, OCA Verified

#7379 4.x: Fix intermittently failing test.
  common/testing/http-junit5/src/main/java/io/helidon/common/testing/http/junit5/SocketHttpClient.java
  tests/integration/webserver/resource-limits/src/test/java/io/helidon/tests/integration/webserver/resourcelimit/IdleTimeoutTest.java
  tests/integration/webserver/resource-limits/src/test/java/io/helidon/tests/integration/webserver/resourcelimit/MaxConcurrentRequestsTest.java
  tests/integration/webserver/resource-limits/src/test/java/io/helidon/tests/integration/webserver/resourcelimit/MaxTcpConnectionsTest.java
Labels: intermittent, 4.x, OCA Verified

#7380 4.x: JMS bumpup 3.0 -> 3.1
  dependencies/pom.xml
  messaging/connectors/aq/src/main/java/module-info.java
  messaging/connectors/jms-shim/src/main/java/module-info.java
  messaging/connectors/jms/src/main/java/module-info.java
  messaging/connectors/wls-jms/src/main/java/module-info.java
Labels: dependencies, OCA Verified

#7370 3.x: Add pull request template
  .github/pull_request_template.md
Labels: 3.x, OCA Verified

#7290 Archetypes: Add Docker and Kubernetes files to bare-* and database-* (2.x)
  archetypes/bare-mp/src/main/resources/.dockerignore
  archetypes/bare-mp/src/main/resources/Dockerfile.jlink.mustache
  archetypes/bare-mp/src/main/resources/Dockerfile.mustache
  archetypes/bare-mp/src/main/resources/Dockerfile.native.mustache
  archetypes/bare-mp/src/main/resources/META-INF/helidon-archetype.xml.mustache
  archetypes/bare-mp/src/main/resources/app.yaml.mustache
  archetypes/bare-se/src/main/resources/.dockerignore
  archetypes/bare-se/src/main/resources/Dockerfile.jlink.mustache
  archetypes/bare-se/src/main/resources/Dockerfile.mustache
  archetypes/bare-se/src/main/resources/Dockerfile.native.mustache
  archetypes/bare-se/src/main/resources/META-INF/helidon-archetype.xml.mustache
  archetypes/bare-se/src/main/resources/app.yaml.mustache
  archetypes/database-mp/src/main/resources/.dockerignore
  archetypes/database-mp/src/main/resources/Dockerfile.jlink.mustache
  archetypes/database-mp/src/main/resources/Dockerfile.mustache
  archetypes/database-mp/src/main/resources/Dockerfile.native.mustache
  archetypes/database-mp/src/main/resources/META-INF/helidon-archetype.xml.mustache
  archetypes/database-mp/src/main/resources/app.yaml.mustache
  archetypes/database-se/src/main/resources/.dockerignore
  archetypes/database-se/src/main/resources/Dockerfile.jlink.mustache
  archetypes/database-se/src/main/resources/Dockerfile.mustache
  archetypes/database-se/src/main/resources/Dockerfile.native.mustache
  archetypes/database-se/src/main/resources/META-INF/helidon-archetype.xml.mustache
  archetypes/database-se/src/main/resources/app.yaml.mustache
Labels: OCA Verified

#7315 3.x: Add ability to deploy snapshot builds
  .github/workflows/snapshotrelease.yaml
  etc/scripts/release.sh
  parent/pom.xml
Labels: build, 3.x, OCA Verified

#7384 4.x Support creating routes from standard gRPC bindable services
  nima/grpc/webserver/src/main/java/io/helidon/nima/grpc/webserver/Grpc.java
  nima/grpc/webserver/src/main/java/io/helidon/nima/grpc/webserver/GrpcProtocolHandler.java
  nima/grpc/webserver/src/main/java/io/helidon/nima/grpc/webserver/GrpcRouting.java
  nima/grpc/webserver/src/main/java/io/helidon/nima/grpc/webserver/GrpcStatus.java
  nima/tests/integration/grpc/server/src/main/java/io/helidon/nima/tests/integration/grpc/webserver/BindableStringService.java
  nima/tests/integration/grpc/server/src/main/java/io/helidon/nima/tests/integration/grpc/webserver/StringService.java
  nima/tests/integration/grpc/server/src/test/java/io/helidon/nima/tests/integration/grpc/webserver/BaseStringServiceTest.java
  nima/tests/integration/grpc/server/src/test/java/io/helidon/nima/tests/integration/grpc/webserver/BindableGrpcServiceTest.java
  nima/tests/integration/grpc/server/src/test/java/io/helidon/nima/tests/integration/grpc/webserver/InterceptorGrpcServiceTest.java
  nima/tests/integration/grpc/server/src/test/java/io/helidon/nima/tests/integration/grpc/webserver/ServiceDefinitionGrpcServiceTest.java
  nima/tests/integration/grpc/server/src/test/java/io/helidon/nima/tests/integration/grpc/webserver/StringServiceTest.java
Labels: 4.x, OCA Verified

#7354 3.x Use text blocks in tests
  config/config/src/test/java/io/helidon/config/MapConfigSourcePropertiesTest.java
  config/config/src/test/java/io/helidon/config/spi/OrderedPropertiesTest.java
  config/hocon/src/test/java/io/helidon/config/hocon/HoconConfigParserTest.java
  dbclient/jdbc/src/test/java/io/helidon/dbclient/jdbc/JdbcStatementParserTest.java
  examples/dbclient/pokemons/src/main/java/io/helidon/examples/dbclient/pokemons/PokemonService.java
  examples/integrations/neo4j/neo4j-mp/src/test/java/io/helidon/examples/integrations/neo4j/mp/MainTest.java
  examples/integrations/neo4j/neo4j-se/src/test/java/io/helidon/examples/quickstart/se/MainTest.java
  media/multipart/src/test/java/io/helidon/media/multipart/MimeParserTest.java
  metrics/metrics/src/test/java/io/helidon/metrics/HelidonCounterTest.java
  metrics/metrics/src/test/java/io/helidon/metrics/HelidonHistogramTest.java
  metrics/metrics/src/test/java/io/helidon/metrics/HelidonMeterTest.java
  metrics/metrics/src/test/java/io/helidon/metrics/HelidonTimerTest.java
  metrics/metrics/src/test/java/io/helidon/metrics/MetricImplTest.java
  microprofile/graphql/server/src/test/java/io/helidon/microprofile/graphql/server/SchemaFieldDefinitionTest.java
  webserver/jersey/src/test/java/io/helidon/webserver/jersey/JerseySupportTest.java
Labels: OCA Verified

#7353 7301 WebClient - Local connection cache switch
  nima/http2/webclient/src/main/java/io/helidon/nima/http2/webclient/Http2CallChainBase.java
  nima/http2/webclient/src/main/java/io/helidon/nima/http2/webclient/Http2CallEntityChain.java
  nima/http2/webclient/src/main/java/io/helidon/nima/http2/webclient/Http2CallOutputStreamChain.java
  nima/http2/webclient/src/main/java/io/helidon/nima/http2/webclient/Http2ClientConnection.java
  nima/http2/webclient/src/main/java/io/helidon/nima/http2/webclient/Http2ClientConnectionHandler.java
  nima/http2/webclient/src/main/java/io/helidon/nima/http2/webclient/Http2ClientImpl.java
  nima/http2/webclient/src/main/java/io/helidon/nima/http2/webclient/Http2ClientRequestImpl.java
  nima/http2/webclient/src/main/java/io/helidon/nima/http2/webclient/Http2ClientResponseImpl.java
  nima/http2/webclient/src/main/java/io/helidon/nima/http2/webclient/Http2ClientStream.java
  nima/http2/webclient/src/main/java/io/helidon/nima/http2/webclient/Http2ConnectionCache.java
  nima/http2/webclient/src/test/java/io/helidon/nima/http2/webclient/Http2WebClientTest.java
  nima/tests/integration/http2/client/src/test/java/io/helidon/nima/tests/integration/http2/client/Http2ClientTest.java
  nima/tests/integration/webclient/webclient/src/test/java/io/helidon/nima/webclient/http1/Http1ClientTest.java
  nima/webclient/api/src/main/java/io/helidon/nima/webclient/api/HttpClientConfigBlueprint.java
  nima/webclient/http1/src/main/java/io/helidon/nima/webclient/http1/Http1CallChainBase.java
  nima/webclient/http1/src/main/java/io/helidon/nima/webclient/http1/Http1CallEntityChain.java
  nima/webclient/http1/src/main/java/io/helidon/nima/webclient/http1/Http1CallOutputStreamChain.java
  nima/webclient/http1/src/main/java/io/helidon/nima/webclient/http1/Http1ClientImpl.java
  nima/webclient/http1/src/main/java/io/helidon/nima/webclient/http1/Http1ClientRequestImpl.java
  nima/webclient/http1/src/main/java/io/helidon/nima/webclient/http1/Http1ConnectionCache.java
Labels: OCA Verified

#7395 4.x: ConcurrentModificationException in Http2ClientConnection.writeWindowsUpdate
  webclient/http2/src/main/java/io/helidon/webclient/http2/Http2ClientConnection.java
Labels: OCA Verified

#7390 4.x: Enables OIDC integration tests and fixes a couple of problems in WebClient
  tests/integration/oidc/src/test/java/io/helidon/tests/integration/oidc/CookieBasedLoginIT.java
  tests/integration/oidc/src/test/java/io/helidon/tests/integration/oidc/QueryBasedLoginIT.java
  tests/integration/oidc/src/test/java/io/helidon/tests/integration/oidc/TenantIdentificationIT.java
  tests/integration/oidc/src/test/resources/application.yaml
  webclient/api/src/main/java/io/helidon/webclient/api/ClientUri.java
  webclient/api/src/main/java/io/helidon/webclient/api/WebClientCookieManager.java
  webclient/api/src/test/java/io/helidon/webclient/api/ClientUriTest.java
  webclient/tests/http1/src/test/java/io/helidon/webclient/tests/CookieTest.java
Labels: OCA Verified

#7396 4.x: Media Context and streaming
  examples/webserver/streaming/src/main/java/io/helidon/examples/webserver/streaming/StreamingService.java
  examples/webserver/tutorial/src/test/java/io/helidon/examples/webserver/tutorial/MainTest.java
  http/http/src/main/java/io/helidon/http/HttpToken.java
  http/media/media/src/main/java/io/helidon/http/media/EntityWriter.java
  http/media/media/src/main/java/io/helidon/http/media/InstanceWriter.java
  http/media/media/src/main/java/io/helidon/http/media/MediaContextImpl.java
  http/media/media/src/main/java/io/helidon/http/media/PathSupport.java
  http/media/media/src/main/java/io/helidon/http/media/StringSupport.java
  http/media/media/src/main/java/io/helidon/http/media/UnsupportedTypeException.java
  webclient/api/src/main/java/io/helidon/webclient/api/ClientResponseTypedImpl.java
  webclient/api/src/main/java/io/helidon/webclient/api/HttpClientConfigBlueprint.java
  webclient/http1/src/main/java/io/helidon/webclient/http1/Http1CallChainBase.java
  webclient/http1/src/main/java/io/helidon/webclient/http1/Http1CallEntityChain.java
  webclient/http1/src/main/java/io/helidon/webclient/http1/Http1CallOutputStreamChain.java
  webclient/http1/src/main/java/io/helidon/webclient/http1/Http1ClientRequestImpl.java
  webclient/http1/src/main/java/io/helidon/webclient/http1/Http1ConnectionCache.java
  webclient/http1/src/main/java/io/helidon/webclient/http1/RedirectionProcessor.java
  webclient/http1/src/test/java/io/helidon/webclient/http1/Http1ClientTest.java
  webclient/tests/webclient/src/test/java/io/helidon/webclient/tests/MediaContextTest.java
  webserver/tests/sse/src/test/java/io/helidon/webserver/tests/sse/SseEventTest.java
  webserver/tests/webserver/src/test/java/io/helidon/webserver/tests/FollowRedirectTest.java
  webserver/tests/webserver/src/test/java/io/helidon/webserver/tests/ValidateResponseHeadersTest.java
  webserver/webserver/src/main/java/io/helidon/webserver/ListenerConfigBlueprint.java
  webserver/webserver/src/main/java/io/helidon/webserver/http/ServerResponseBase.java
  webserver/webserver/src/main/java/io/helidon/webserver/http1/Http1Connection.java
  webserver/webserver/src/main/java/io/helidon/webserver/http1/Http1ConnectionListener.java
  webserver/webserver/src/main/java/io/helidon/webserver/http1/Http1LoggingConnectionListener.java
  webserver/webserver/src/main/java/io/helidon/webserver/http1/Http1ServerRequestWithEntity.java
  webserver/webserver/src/main/java/io/helidon/webserver/http1/Http1ServerResponse.java
  webserver/webserver/src/test/java/io/helidon/webserver/WebServerConfigTest.java
Labels: media-support, 4.x, OCA Verified

#7386 [3.x] OCI Global Config Source
  bom/pom.xml
  integrations/oci/sdk/pom.xml
  integrations/oci/sdk/runtime/README.md
  integrations/oci/sdk/runtime/etc/spotbugs/exclude.xml
  integrations/oci/sdk/runtime/pom.xml
  integrations/oci/sdk/runtime/src/main/java/io/helidon/integrations/oci/sdk/runtime/OciAuthenticationDetailsProvider.java
  integrations/oci/sdk/runtime/src/main/java/io/helidon/integrations/oci/sdk/runtime/OciAvailability.java
  integrations/oci/sdk/runtime/src/main/java/io/helidon/integrations/oci/sdk/runtime/OciAvailabilityDefault.java
  integrations/oci/sdk/runtime/src/main/java/io/helidon/integrations/oci/sdk/runtime/OciConfig.java
  integrations/oci/sdk/runtime/src/main/java/io/helidon/integrations/oci/sdk/runtime/OciConfigBlueprint.java
  integrations/oci/sdk/runtime/src/main/java/io/helidon/integrations/oci/sdk/runtime/OciExtension.java
  integrations/oci/sdk/runtime/src/main/java/io/helidon/integrations/oci/sdk/runtime/package-info.java
  integrations/oci/sdk/runtime/src/main/java/module-info.java
  integrations/oci/sdk/runtime/src/test/java/io/helidon/integrations/oci/sdk/runtime/OciAuthenticationDetailsProviderTest.java
  integrations/oci/sdk/runtime/src/test/java/io/helidon/integrations/oci/sdk/runtime/OciAvailabilityTest.java
  integrations/oci/sdk/runtime/src/test/java/io/helidon/integrations/oci/sdk/runtime/OciExtensionTest.java
  integrations/oci/sdk/runtime/src/test/resources/test-oci-config-file.yaml
  integrations/oci/sdk/runtime/src/test/resources/test-oci-resource-principal.yaml
Labels: backport, OCA Verified

#7387 [4.x] Follow-up items for OCI Global Config
  integrations/oci/sdk/runtime/pom.xml
  integrations/oci/sdk/runtime/src/main/java/io/helidon/integrations/oci/sdk/runtime/OciExtension.java
  integrations/oci/sdk/runtime/src/main/java/module-info.java
  integrations/oci/sdk/runtime/src/test/java/io/helidon/integrations/oci/sdk/runtime/OciAuthenticationDetailsProviderTest.java
Labels: OCA Verified

#7324 [4.x] - Remove non-virtual executor support
  common/configurable/src/main/java/io/helidon/common/configurable/ObserverManager.java
  common/configurable/src/main/java/io/helidon/common/configurable/ThreadPoolSupplier.java
  common/configurable/src/main/java/io/helidon/common/configurable/spi/ExecutorServiceSupplierObserver.java
  common/configurable/src/test/java/io/helidon/common/configurable/ObserverForTesting.java
  metrics/metrics/src/main/java/io/helidon/metrics/ExecutorServiceMetricsObserver.java
Labels: 4.x, OCA Verified

#7401 javadocs: update external cross reference links and offline package-lists
  etc/javadoc/eclipselink/element-list
  etc/javadoc/jackson-core/package-list
  etc/javadoc/jackson-databind/package-list
  etc/javadoc/jakarta-cdi/element-list
  etc/javadoc/jakarta-jaxrs/element-list
  etc/javadoc/jakarta-jsonb/element-list
  etc/javadoc/jersey/element-list
  etc/javadoc/microprofile-metrics/element-list
  etc/javadoc/narayana/element-list
  etc/javadoc/narayana/package-list
  etc/javadoc/netty-transport/package-list
  etc/javadoc/netty/package-list
  etc/javadoc/prometheus/element-list
  etc/javadoc/reactive-streams/element-list
  etc/javadoc/weld/element-list
  pom.xml
Labels: 4.x, OCA Verified

#7402 4.x: Supplier in builder
  builder/processor/src/main/java/io/helidon/builder/processor/TypeHandler.java
  builder/processor/src/main/java/io/helidon/builder/processor/TypeHandlerMap.java
  builder/processor/src/main/java/io/helidon/builder/processor/TypeHandlerSupplier.java
  builder/tests/builder/src/main/java/io/helidon/builder/test/testsubjects/SupplierBeanBlueprint.java
  builder/tests/builder/src/test/java/io/helidon/builder/test/SupplierTest.java
  common/config/src/main/java/io/helidon/common/config/ConfigValue.java
  common/config/src/main/java/io/helidon/common/config/EmptyConfig.java
Labels: 4.x, OCA Verified, builder

#7400 4.x: Allowed values are now checked when validating a builder.
  builder/processor/src/main/java/io/helidon/builder/processor/CustomMethods.java
  builder/processor/src/main/java/io/helidon/builder/processor/GenerateAbstractBuilder.java
  builder/processor/src/main/java/io/helidon/builder/processor/PrototypeProperty.java
  builder/processor/src/main/java/io/helidon/builder/processor/TypeContext.java
  builder/tests/builder/src/main/java/io/helidon/builder/test/testsubjects/AllowedValuesBlueprint.java
  builder/tests/builder/src/main/java/io/helidon/builder/test/testsubjects/MyConfigBeanBlueprint.java
  builder/tests/builder/src/test/java/io/helidon/builder/test/AllowedValuesTest.java
  builder/tests/common-types/src/main/java/io/helidon/common/types/AnnotationBlueprint.java
  builder/tests/common-types/src/main/java/io/helidon/common/types/AnnotationSupport.java
  builder/tests/common-types/src/main/java/io/helidon/common/types/TypeNames.java
  common/processor/processor/src/main/java/io/helidon/common/processor/AnnotationFactory.java
  common/processor/processor/src/main/java/io/helidon/common/processor/ToAnnotationValueVisitor.java
  common/processor/processor/src/main/java/io/helidon/common/processor/TypeInfoFactory.java
  common/types/src/main/java/io/helidon/common/types/Annotation.java
  common/types/src/main/java/io/helidon/common/types/AnnotationBlueprint.java
  common/types/src/main/java/io/helidon/common/types/AnnotationSupport.java
  fault-tolerance/processor/src/main/java/io/helidon/faulttolerance/processor/CircuitBreakerMethodCreator.java
  fault-tolerance/processor/src/main/java/io/helidon/faulttolerance/processor/FallbackMethodCreator.java
  fault-tolerance/processor/src/main/java/io/helidon/faulttolerance/processor/RetryMethodCreator.java
  inject/api/src/main/java/io/helidon/inject/api/QualifierBlueprint.java
  inject/maven-plugin/src/main/java/io/helidon/inject/maven/plugin/QualifierConfig.java
  inject/processor/src/main/java/io/helidon/inject/processor/InjectionAnnotationProcessor.java
  inject/tests/resources-inject/src/test/resources/expected/ximpl-interceptor._java_
  inject/tools/src/main/java/io/helidon/inject/tools/InterceptorCreatorDefault.java
  integrations/oci/sdk/runtime/src/test/java/io/helidon/integrations/oci/sdk/runtime/OciExtensionTest.java
Labels: 4.x, OCA Verified, builder

#7391 4.x: Adds OciSecretsConfigSourceProvider.java
  bom/pom.xml
  integrations/oci/oci-secrets-config-source/pom.xml
  integrations/oci/oci-secrets-config-source/src/main/java/io/helidon/integrations/oci/secrets/configsource/OciSecretsConfigSourceProvider.java
  integrations/oci/oci-secrets-config-source/src/main/java/io/helidon/integrations/oci/secrets/configsource/package-info.java
  integrations/oci/oci-secrets-config-source/src/main/java/module-info.java
  integrations/oci/oci-secrets-config-source/src/test/java/io/helidon/integrations/oci/secrets/configsource/IsModifiedTest.java
  integrations/oci/oci-secrets-config-source/src/test/java/io/helidon/integrations/oci/secrets/configsource/UsageTest.java
  integrations/oci/oci-secrets-config-source/src/test/java/io/helidon/integrations/oci/secrets/configsource/ValueNodeTest.java
  integrations/oci/oci-secrets-config-source/src/test/java/logging.properties
  integrations/oci/oci-secrets-config-source/src/test/resources/meta-config.yaml
  integrations/oci/pom.xml
Labels: config, P2, 3.x, OCI, 4.x, OCA Verified

#7414 3.x: Adds OciSecretsConfigSourceProvider.java
  bom/pom.xml
  integrations/oci/oci-secrets-config-source/etc/spotbugs/exclude.xml
  integrations/oci/oci-secrets-config-source/pom.xml
  integrations/oci/oci-secrets-config-source/src/main/java/io/helidon/integrations/oci/secrets/configsource/OciSecretsConfigSourceProvider.java
  integrations/oci/oci-secrets-config-source/src/main/java/io/helidon/integrations/oci/secrets/configsource/package-info.java
  integrations/oci/oci-secrets-config-source/src/main/java/module-info.java
  integrations/oci/oci-secrets-config-source/src/test/java/io/helidon/integrations/oci/secrets/configsource/IsModifiedTest.java
  integrations/oci/oci-secrets-config-source/src/test/java/io/helidon/integrations/oci/secrets/configsource/UsageTest.java
  integrations/oci/oci-secrets-config-source/src/test/java/io/helidon/integrations/oci/secrets/configsource/ValueNodeTest.java
  integrations/oci/oci-secrets-config-source/src/test/java/logging.properties
  integrations/oci/oci-secrets-config-source/src/test/resources/meta-config.yaml
  integrations/oci/pom.xml
Labels: SE, config, P2, 3.x, OCI, backport, OCA Verified

#7405 4.x: Fix references to interceptor. Now using decorator for builders.
  builder/README.md
  builder/api/README.md
  builder/api/src/main/java/io/helidon/builder/api/Prototype.java
Labels: OCA Verified, builder

#7408 4.x: Additional HTTP status codes.
  http/http/src/main/java/io/helidon/http/DateTimeHelper.java
  http/http/src/main/java/io/helidon/http/Http.java
  http/http/src/test/java/io/helidon/http/HttpStatusTest.java
Labels: enhancement, 4.x, OCA Verified

#7420 4.x: Interceptor creator now uses TypeName (and related changes)
  fault-tolerance/processor/src/main/java/io/helidon/faulttolerance/processor/CircuitBreakerMethodCreator.java
  fault-tolerance/processor/src/main/java/io/helidon/faulttolerance/processor/FallbackMethodCreator.java
  fault-tolerance/processor/src/main/java/io/helidon/faulttolerance/processor/RetryMethodCreator.java
  http/processor/src/main/java/io/helidon/http/processor/HttpEndpointCreator.java
  http/processor/src/main/java/io/helidon/http/processor/HttpMethodCreator.java
  inject/processor/src/main/java/io/helidon/inject/processor/CustomAnnotationProcessor.java
  inject/processor/src/main/java/io/helidon/inject/processor/InjectionAnnotationProcessor.java
  inject/processor/src/test/java/io/helidon/inject/processor/ExtensibleGetTemplateProducer.java
  inject/tests/resources-inject/src/test/java/io/helidon/inject/tests/inject/interceptor/InterceptorRuntimeTest.java
  inject/tests/resources-inject/src/test/resources/expected/ximpl-interceptor._java_
  inject/tests/resources-inject/src/test/resources/expected/yimpl-interceptor._java_
  inject/tools/src/main/java/io/helidon/inject/tools/InterceptedElementBlueprint.java
  inject/tools/src/main/java/io/helidon/inject/tools/InterceptionPlanBlueprint.java
  inject/tools/src/main/java/io/helidon/inject/tools/InterceptorCreatorDefault.java
  inject/tools/src/main/java/io/helidon/inject/tools/spi/CustomAnnotationTemplateCreator.java
  inject/tools/src/main/java/io/helidon/inject/tools/spi/InterceptorCreator.java
  inject/tools/src/main/resources/templates/inject/default/interface-based-interceptor.hbs
  inject/tools/src/main/resources/templates/inject/default/no-arg-based-interceptor.hbs
  inject/tools/src/test/java/io/helidon/inject/tools/InterceptorCreatorDefaultTest.java
Labels: api-change, 4.x, pico, OCA Verified

#7431 DOCS: Fix openapi links
  docs/includes/nima.adoc
  docs/includes/openapi/openapi-generator.adoc
  docs/includes/pages.adoc
  docs/se/openapi/openapi-generator.adoc
Labels: docs, 4.x, OCA Verified

#7415 4.x: Unified constants for configuring outbound id and secret.
  examples/security/basic-auth-with-static-content/src/test/java/io/helidon/examples/security/basicauth/BasicExampleTest.java
  examples/security/outbound-override/src/main/java/io/helidon/security/examples/outbound/JwtOverrideService.java
  examples/security/outbound-override/src/main/java/io/helidon/security/examples/outbound/OverrideService.java
  examples/security/outbound-override/src/test/java/io/helidon/security/examples/outbound/OutboundOverrideExampleTest.java
  examples/security/outbound-override/src/test/java/io/helidon/security/examples/outbound/OutboundOverrideJwtExampleTest.java
  examples/security/webserver-signatures/src/test/java/io/helidon/examples/security/signatures/SignatureExampleTest.java
  microprofile/jwt-auth/src/main/java/io/helidon/microprofile/jwt/auth/JwtAuthProvider.java
  microprofile/security/src/test/java/io/helidon/microprofile/security/BasicAuthOutboundOverrideTest.java
  security/providers/http-auth/src/main/java/io/helidon/security/providers/httpauth/HttpBasicAuthProvider.java
  security/providers/jwt/src/main/java/io/helidon/security/providers/jwt/JwtProvider.java
  security/security/src/main/java/io/helidon/security/EndpointConfig.java
  webclient/tests/webclient/src/test/java/io/helidon/webclient/tests/ContextCheckTest.java
  webclient/tests/webclient/src/test/java/io/helidon/webclient/tests/SecurityTest.java
  webserver/security/src/test/java/io/helidon/webserver/security/WebSecurityBuilderGateDefaultsTest.java
  webserver/security/src/test/java/io/helidon/webserver/security/WebSecurityTests.java
Labels: OCA Verified

#7434 4.x: Upgrade microprofile config to 3.0.3
  dependencies/pom.xml
Labels: config, dependencies, 4.x, OCA Verified, microprofile

#7435 4.x: Upgrade eclipselink to 4.0.2
  dependencies/pom.xml
Labels: jpa/jta, dependencies, 4.x, OCA Verified

#7436 4.x: Enable disabled test
  examples/integrations/cdi/pokemons/src/test/java/io/helidon/examples/integrations/cdi/pokemon/MainTest.java
Labels: examples, jpa/jta, testing, OCA Verified

#7438 4.x: Force upgrade of bytebuddy to 1.14.6 to support Java 21.
  applications/mp/pom.xml
  dependencies/pom.xml
  pom.xml
Labels: jpa/jta, dependencies, 4.x, OCA Verified

#7441 Fix intermittent out-of-order chunk #7407
  microprofile/server/src/test/java/io/helidon/microprofile/server/AutoFlushTest.java
  webserver/webserver/src/main/java/io/helidon/webserver/NettyChannel.java
  webserver/webserver/src/test/java/io/helidon/webserver/WaterMarkedBackpressureIT.java
Labels: OCA Verified

#7345 4.x: Support Http.Header.X_HELIDON_CN
  common/tls/src/main/java/io/helidon/common/tls/TlsUtils.java
  examples/webserver/mutual-tls/src/main/java/io/helidon/examples/webserver/mtls/CertificateHelper.java
  examples/webserver/mutual-tls/src/main/java/io/helidon/examples/webserver/mtls/SecureService.java
  http/http2/src/main/java/io/helidon/http/http2/Http2Headers.java
  webclient/tests/webclient/src/test/java/io/helidon/webclient/tests/CertificateHelper.java
  webclient/tests/webclient/src/test/java/io/helidon/webclient/tests/MutualTlsTest.java
  webserver/http2/src/main/java/io/helidon/webserver/http2/Http2Connection.java
  webserver/webserver/src/main/java/io/helidon/webserver/http1/Http1Connection.java
Labels: webserver, 4.x, OCA Verified

#7452 Add -proc:full to javac to explicitly enable annotation processing
  applications/parent/pom.xml
  pom.xml
Labels: build, 4.x, OCA Verified

#7453 4.x: upgrade microprofile-openapi-api to 3.1.1 and add direct dependency
  dependencies/pom.xml
  microprofile/openapi/pom.xml
Labels: open-api, dependencies, 4.x, OCA Verified, microprofile

#7440 4.x: Helidon Arquillian module should only depend on MP core
  microprofile/tests/arquillian/pom.xml
  microprofile/tests/arquillian/src/main/java/io/helidon/microprofile/arquillian/HelidonDeployableContainer.java
  microprofile/tests/tck/tck-cdi/pom.xml
  microprofile/tests/tck/tck-core-profile/tck-core-profile-test/pom.xml
  microprofile/tests/tck/tck-fault-tolerance/pom.xml
  microprofile/tests/tck/tck-health/pom.xml
  microprofile/tests/tck/tck-inject/tck-inject-test/pom.xml
  microprofile/tests/tck/tck-jsonb/tck-jsonb-test/pom.xml
  microprofile/tests/tck/tck-jsonp/tck-jsonp-test/pom.xml
  microprofile/tests/tck/tck-lra/pom.xml
  microprofile/tests/tck/tck-metrics/pom.xml
  microprofile/tests/tck/tck-openapi/pom.xml
  microprofile/tests/tck/tck-opentracing/pom.xml
  microprofile/tests/tck/tck-reactive-operators/pom.xml
  microprofile/tests/tck/tck-rest-client/pom.xml
Labels: OCA Verified

#7404 Change heap functions to get current memory usage
  metrics/metrics/src/main/java/io/helidon/metrics/BaseRegistry.java
Labels: OCA Verified

#7425 6962 include proxy setting for relative uris 4.x
  webclient/api/src/main/java/io/helidon/webclient/api/HttpClientConfigBlueprint.java
  webclient/api/src/main/java/io/helidon/webclient/api/Proxy.java
  webclient/http1/src/main/java/io/helidon/webclient/http1/Http1CallChainBase.java
  webclient/http1/src/test/java/io/helidon/webclient/http1/Http1ClientTest.java
Labels: OCA Verified

#7454 4.x: Upgrade microprofile-health to 4.0.1 and microprofile-lra-api to 2.0
  dependencies/pom.xml
Labels: dependencies, 4.x, OCA Verified, microprofile

#7455 3.x - Refactor TODO app example to remove the of use NodeJS/NPM
  examples/todo-app/README.md
  examples/todo-app/backend/.dockerignore
  examples/todo-app/backend/Dockerfile
  examples/todo-app/backend/app.yaml
  examples/todo-app/backend/pom.xml
  examples/todo-app/backend/src/main/java/io/helidon/demo/todos/backend/DbService.java
  examples/todo-app/backend/src/main/java/io/helidon/demo/todos/backend/JaxRsBackendResource.java
  examples/todo-app/backend/src/main/java/io/helidon/demo/todos/backend/Main.java
  examples/todo-app/backend/src/main/resources/application.yaml
  examples/todo-app/cassandra.yaml
  examples/todo-app/cassandra/Dockerfile
  examples/todo-app/frontend/.dockerignore
  examples/todo-app/frontend/Dockerfile
  examples/todo-app/frontend/app.yaml
  examples/todo-app/frontend/dev.yaml
  examples/todo-app/frontend/package.json
  examples/todo-app/frontend/pom.xml
  examples/todo-app/frontend/src/main/java/io/helidon/demo/todos/frontend/BackendServiceClient.java
  examples/todo-app/frontend/src/main/java/io/helidon/demo/todos/frontend/EnvHandler.java
  examples/todo-app/frontend/src/main/java/io/helidon/demo/todos/frontend/Main.java
  examples/todo-app/frontend/src/main/java/io/helidon/demo/todos/frontend/TodoService.java
  examples/todo-app/frontend/src/main/java/io/helidon/demo/todos/frontend/TodosHandler.java
  examples/todo-app/frontend/src/main/resources/WEB/css/styles.css
  examples/todo-app/frontend/src/main/resources/WEB/index.html
  examples/todo-app/frontend/src/main/resources/WEB/js/app.js
  examples/todo-app/frontend/src/main/resources/application.yaml
  examples/todo-app/frontend/src/main/webapp/css/spinner.css
  examples/todo-app/frontend/src/main/webapp/index.html
  examples/todo-app/frontend/src/main/webapp/js/global.js
  examples/todo-app/frontend/src/main/webapp/js/handlers.js
  examples/todo-app/frontend/src/main/webapp/js/main.js
  examples/todo-app/frontend/src/main/webapp/js/rest.js
  examples/todo-app/frontend/src/main/webapp/js/todo.js
  examples/todo-app/frontend/src/main/webapp/js/todoutil.js
  examples/todo-app/frontend/src/test/java/io/helidon/demo/todos/frontend/FrontendTest.java
  examples/todo-app/frontend/src/test/java/io/helidon/demo/todos/frontend/TodoServiceTest.java
  examples/todo-app/frontend/src/test/resources/application-test.yaml
  examples/todo-app/frontend/src/test/resources/frontend-application.yaml
  examples/todo-app/frontend/webpack.config.js
Labels: OCA Verified

#7456 3.x - Fix google-login behind proxy
  security/providers/google-login/src/main/java/io/helidon/security/providers/google/login/GoogleTokenProvider.java
  security/providers/google-login/src/main/java/module-info.java
Labels: OCA Verified

#7460 7449 out of order chunk 2x
  microprofile/server/src/test/java/io/helidon/microprofile/server/AutoFlushTest.java
  webserver/webserver/src/main/java/io/helidon/webserver/NettyChannel.java
  webserver/webserver/src/main/java/io/helidon/webserver/ServerResponseSubscription.java
  webserver/webserver/src/test/java/io/helidon/webserver/WaterMarkedBackpressureIT.java
Labels: OCA Verified

#7422 4.x: Fix get in evictable cache, as it did not update last accessed timestamp
  security/providers/common/src/main/java/io/helidon/security/providers/common/EvictableCacheImpl.java
  security/providers/common/src/test/java/io/helidon/security/providers/common/EvictableCacheTest.java
Labels: bug, 4.x, OCA Verified

#7421 4.x: Makes SecretBundleConfigSource public; improves modification logic
  integrations/oci/oci-secrets-config-source/src/main/java/io/helidon/integrations/oci/secrets/configsource/OciSecretsConfigSourceProvider.java
  integrations/oci/oci-secrets-config-source/src/main/java/io/helidon/integrations/oci/secrets/configsource/SecretBundleConfigSource.java
  integrations/oci/oci-secrets-config-source/src/main/java/module-info.java
  integrations/oci/oci-secrets-config-source/src/test/java/io/helidon/integrations/oci/secrets/configsource/IsModifiedTest.java
  integrations/oci/oci-secrets-config-source/src/test/java/io/helidon/integrations/oci/secrets/configsource/ValueNodeTest.java
Labels: config, P3, OCI, java, 4.x, OCA Verified

#7465 2.x: Fix get in evictable cache, as it did not update last accessed timestamp
  security/providers/common/src/main/java/io/helidon/security/providers/common/EvictableCacheImpl.java
  security/providers/common/src/test/java/io/helidon/security/providers/common/EvictableCacheTest.java
Labels: 2.x, backport, OCA Verified

#7461 4.x: Update CHANGELOG in preparation for 4.0.0-M2 release.
  CHANGELOG.md
Labels: 4.x, OCA Verified

#7464 3.x: Fix get in evictable cache, as it did not update last accessed timestamp
  security/providers/common/src/main/java/io/helidon/security/providers/common/EvictableCacheImpl.java
  security/providers/common/src/test/java/io/helidon/security/providers/common/EvictableCacheTest.java
Labels: 3.x, backport, OCA Verified

#7468 3.x: Makes SecretBundleConfigSource public; improves modification logic
  integrations/oci/oci-secrets-config-source/etc/spotbugs/exclude.xml
  integrations/oci/oci-secrets-config-source/src/main/java/io/helidon/integrations/oci/secrets/configsource/OciSecretsConfigSourceProvider.java
  integrations/oci/oci-secrets-config-source/src/main/java/io/helidon/integrations/oci/secrets/configsource/SecretBundleConfigSource.java
  integrations/oci/oci-secrets-config-source/src/main/java/module-info.java
  integrations/oci/oci-secrets-config-source/src/test/java/io/helidon/integrations/oci/secrets/configsource/IsModifiedTest.java
  integrations/oci/oci-secrets-config-source/src/test/java/io/helidon/integrations/oci/secrets/configsource/ValueNodeTest.java
Labels: config, P2, 3.x, OCI, backport, OCA Verified

#7467 [2.x] Refactor TODO app examples to not use NodeJS/NPM
  examples/todo-app/README.md
  examples/todo-app/backend/.dockerignore
  examples/todo-app/backend/Dockerfile
  examples/todo-app/backend/app.yaml
  examples/todo-app/backend/dev.yaml
  examples/todo-app/backend/pom.xml
  examples/todo-app/backend/src/main/java/io/helidon/demo/todos/backend/DbService.java
  examples/todo-app/backend/src/main/java/io/helidon/demo/todos/backend/JaxRsBackendResource.java
  examples/todo-app/backend/src/main/java/io/helidon/demo/todos/backend/Main.java
  examples/todo-app/backend/src/main/resources/application.yaml
  examples/todo-app/cassandra.yaml
  examples/todo-app/cassandra/Dockerfile
  examples/todo-app/frontend/.dockerignore
  examples/todo-app/frontend/Dockerfile
  examples/todo-app/frontend/app.yaml
  examples/todo-app/frontend/dev.yaml
  examples/todo-app/frontend/package.json
  examples/todo-app/frontend/pom.xml
  examples/todo-app/frontend/src/main/java/io/helidon/demo/todos/frontend/BackendServiceClient.java
  examples/todo-app/frontend/src/main/java/io/helidon/demo/todos/frontend/EnvHandler.java
  examples/todo-app/frontend/src/main/java/io/helidon/demo/todos/frontend/Main.java
  examples/todo-app/frontend/src/main/java/io/helidon/demo/todos/frontend/TodoService.java
  examples/todo-app/frontend/src/main/java/io/helidon/demo/todos/frontend/TodosHandler.java
  examples/todo-app/frontend/src/main/resources/WEB/css/styles.css
  examples/todo-app/frontend/src/main/resources/WEB/index.html
  examples/todo-app/frontend/src/main/resources/WEB/js/app.js
  examples/todo-app/frontend/src/main/resources/application.yaml
  examples/todo-app/frontend/src/main/webapp/css/spinner.css
  examples/todo-app/frontend/src/main/webapp/index.html
  examples/todo-app/frontend/src/main/webapp/js/global.js
  examples/todo-app/frontend/src/main/webapp/js/handlers.js
  examples/todo-app/frontend/src/main/webapp/js/main.js
  examples/todo-app/frontend/src/main/webapp/js/rest.js
  examples/todo-app/frontend/src/main/webapp/js/todo.js
  examples/todo-app/frontend/src/main/webapp/js/todoutil.js
  examples/todo-app/frontend/src/test/java/io/helidon/demo/todos/frontend/FrontendTest.java
  examples/todo-app/frontend/src/test/java/io/helidon/demo/todos/frontend/TodoServiceTest.java
  examples/todo-app/frontend/src/test/resources/application-test.yaml
  examples/todo-app/frontend/webpack.config.js
Labels: OCA Verified

#7469 3.x: Correctly handle IPv6 addresses for requested URI.
  microprofile/server/src/test/java/io/helidon/microprofile/server/RedirectionTest.java
  webserver/webserver/src/main/java/io/helidon/webserver/Request.java
  webserver/webserver/src/test/java/io/helidon/webserver/RequestedUriTest.java
Labels: webserver, 3.x, OCA Verified

#7470 4.x: Introduces Lazy OCI Vault ConfigSource
  integrations/oci/oci-secrets-config-source/pom.xml
  integrations/oci/oci-secrets-config-source/src/main/java/io/helidon/integrations/oci/secrets/configsource/AbstractSecretBundleConfigSource.java
  integrations/oci/oci-secrets-config-source/src/main/java/io/helidon/integrations/oci/secrets/configsource/OciSecretsConfigSourceProvider.java
  integrations/oci/oci-secrets-config-source/src/main/java/io/helidon/integrations/oci/secrets/configsource/SecretBundleLazyConfigSource.java
  integrations/oci/oci-secrets-config-source/src/main/java/io/helidon/integrations/oci/secrets/configsource/SecretBundleNodeConfigSource.java
  integrations/oci/oci-secrets-config-source/src/test/java/io/helidon/integrations/oci/secrets/configsource/IsModifiedTest.java
  integrations/oci/oci-secrets-config-source/src/test/java/io/helidon/integrations/oci/secrets/configsource/ValueNodeTest.java
  integrations/oci/oci-secrets-config-source/src/test/resources/meta-config.yaml
Labels: config, P4, OCI, java, 4.x, OCA Verified

#7473 2.x: Fix google-login behind proxy
  security/providers/google-login/src/main/java/io/helidon/security/providers/google/login/GoogleTokenProvider.java
  security/providers/google-login/src/main/java/module-info.java
Labels: OCA Verified

#7472 4.x: Fix google-login behind proxy
  security/providers/google-login/src/main/java/io/helidon/security/providers/google/login/GoogleTokenProvider.java
  security/providers/google-login/src/main/java/module-info.java
Labels: OCA Verified

#7466 4.x: HTTP/2 Unconsumed entity
  webserver/http2/src/main/java/io/helidon/webserver/http2/Http2ServerStream.java
  webserver/tests/http2/src/test/java/io/helidon/webserver/tests/http2/ConsumeTest.java
Labels: OCA Verified

#7459 4.x: small archetype issues
  archetypes/helidon/src/main/archetype/common/extra.xml
  archetypes/helidon/src/main/archetype/common/observability.xml
  archetypes/helidon/src/main/archetype/mp/custom/database.xml
  archetypes/helidon/src/main/archetype/se/custom/database.xml
  archetypes/helidon/src/main/archetype/se/custom/files/src/main/java/__pkg__/HttpStatusMetricService.java.mustache
  archetypes/helidon/src/main/archetype/se/custom/files/src/main/java/__pkg__/MetricsService.java.mustache
  archetypes/helidon/src/main/archetype/se/custom/files/src/test/java/__pkg__/StatusService.java.mustache
  archetypes/helidon/src/main/archetype/se/custom/files/src/test/java/__pkg__/StatusTest.java.mustache
  archetypes/helidon/src/main/archetype/se/custom/observability.xml
  webserver/testing/junit5/junit5/src/main/java/io/helidon/webserver/testing/junit5/DirectClient.java
  webserver/testing/junit5/junit5/src/main/java/io/helidon/webserver/testing/junit5/DirectWebClient.java
  webserver/testing/junit5/junit5/src/main/java/io/helidon/webserver/testing/junit5/Http1DirectJunitExtension.java
Labels: archetypes, 4.x, OCA Verified

#7480 4.x: Tests to validate requested URI is correctly used with IPv6
  microprofile/server/src/test/java/io/helidon/microprofile/server/RedirectionTest.java
  webserver/tests/webserver/src/test/java/io/helidon/webserver/tests/RequestedUriTest.java
Labels: webserver, 4.x, OCA Verified

#7479 2.x: Correctly handle IPv6 addresses for requested URI.
  microprofile/server/src/test/java/io/helidon/microprofile/server/RedirectionTest.java
  webserver/webserver/src/main/java/io/helidon/webserver/Request.java
  webserver/webserver/src/test/java/io/helidon/webserver/RequestedUriTest.java
Labels: 2.x, backport, OCA Verified

#6818 [3.x]: Add OpenAPI annotations to examples/quickstarts/helidon-quickstart-mp (#1190)
  examples/quickstarts/helidon-quickstart-mp/src/main/java/io/helidon/examples/quickstart/mp/GreetResource.java
Labels: OCA Verified

#7419 [3.x] - Simple to Batch Span exporter
  tracing/jaeger/src/main/java/io/helidon/tracing/jaeger/JaegerTracerBuilder.java
  tracing/jaeger/src/test/java/io/helidon/tracing/jaeger/JaegerTracerBuilderTest.java
  tracing/jaeger/src/test/resources/application.yaml
Labels: tracing, 3.x, OCA Verified

#7418 [4.x] - Simple to Batch Span exporter
  tracing/providers/jaeger/src/main/java/io/helidon/tracing/providers/jaeger/JaegerTracerBuilder.java
  tracing/providers/jaeger/src/test/java/io/helidon/tracing/providers/jaeger/JaegerTracerBuilderTest.java
  tracing/providers/jaeger/src/test/resources/application.yaml
Labels: tracing, 4.x, OCA Verified

#7457 3.x - Fix SeConfig.asMap to not truncate keys
  config/config-mp/src/main/java/io/helidon/config/mp/SeConfig.java
  config/config-mp/src/test/java/io/helidon/config/mp/MpConfigTest.java
Labels: OCA Verified

#7493 2.x: Fix SeConfig.asMap to not truncate keys
  config/config-mp/src/main/java/io/helidon/config/mp/SeConfig.java
  config/config-mp/src/test/java/io/helidon/config/mp/MpConfigTest.java
Labels: OCA Verified

#7494 4.x: Fix SeConfig.asMap to not truncate keys
  config/config-mp/src/main/java/io/helidon/config/mp/SeConfig.java
  config/config-mp/src/test/java/io/helidon/config/mp/MpConfigTest.java
Labels: OCA Verified

#7490 3.x: Upgrade ByteBuddy and ASM for Java 21
  applications/mp/pom.xml
  dependencies/pom.xml
  pom.xml
  tests/integration/dbclient/appl/pom.xml
  tests/integration/tools/example/pom.xml
Labels: dependencies, 3.x, OCA Verified

#7495 2.x: Upgrade EclipseLink and ByteBuddy for Java 21
  applications/mp/pom.xml
  dependencies/pom.xml
  pom.xml
Labels: 2.x, OCA Verified

#7500 3.x: Docs: Remove description of Config.changes() API
  docs/se/config/mutability-support.adoc
Labels: docs, config, 3.x, OCA Verified

#7499 4.x: HTTP/2 Locally half-closed streams needs to be able to receive frames
  webserver/http2/src/main/java/io/helidon/webserver/http2/Http2Connection.java
  webserver/http2/src/main/java/io/helidon/webserver/http2/Http2ServerStream.java
  webserver/tests/http2/src/test/java/io/helidon/webserver/tests/http2/HalfClosedStreamsTest.java
Labels: OCA Verified

#7481 3.x: Introduces Lazy OCI Vault ConfigSource
  integrations/oci/oci-secrets-config-source/etc/spotbugs/exclude.xml
  integrations/oci/oci-secrets-config-source/pom.xml
  integrations/oci/oci-secrets-config-source/src/main/java/io/helidon/integrations/oci/secrets/configsource/AbstractSecretBundleConfigSource.java
  integrations/oci/oci-secrets-config-source/src/main/java/io/helidon/integrations/oci/secrets/configsource/OciSecretsConfigSourceProvider.java
  integrations/oci/oci-secrets-config-source/src/main/java/io/helidon/integrations/oci/secrets/configsource/SecretBundleLazyConfigSource.java
  integrations/oci/oci-secrets-config-source/src/main/java/io/helidon/integrations/oci/secrets/configsource/SecretBundleNodeConfigSource.java
  integrations/oci/oci-secrets-config-source/src/test/java/io/helidon/integrations/oci/secrets/configsource/IsModifiedTest.java
  integrations/oci/oci-secrets-config-source/src/test/java/io/helidon/integrations/oci/secrets/configsource/ValueNodeTest.java
  integrations/oci/oci-secrets-config-source/src/test/resources/meta-config.yaml
Labels: config, 3.x, OCI, backport, java, OCA Verified

#7497 [3.x] Updates version of Micronaut libraries
  dependencies/pom.xml
Labels: dependencies, 3.x, integration, OCA Verified
