Repository helidon-io/helidon, pull requests merged in 2023-06, with the labels that each got.

#6863 Fixes incremental compilation for Pico services and running unit tests from IDE
  pico/processor/pom.xml
  pico/processor/src/main/java/io/helidon/pico/processor/ActiveProcessorUtils.java
  pico/processor/src/main/java/io/helidon/pico/processor/CustomAnnotationProcessor.java
  pico/processor/src/main/java/io/helidon/pico/processor/PicoAnnotationProcessor.java
  pico/processor/src/main/java/io/helidon/pico/processor/ProcessingTracker.java
  pico/processor/src/test/java/io/helidon/pico/processor/ProcessingTrackerTest.java
  pico/tests/interception/src/main/java/io/helidon/pico/tests/interception/TheOtherService.java
  pico/tests/resources-pico/pom.xml
  pico/tests/resources-pico/src/main/java/module-info.java
  pico/tests/resources-pico/src/test/resources/expected/module-info.java._pico_
  pico/tests/resources-pico/src/test/resources/expected/tests-module-info.java._pico_
  pico/tools/src/main/java/io/helidon/pico/tools/ActivatorCreatorCodeGen.java
  pico/tools/src/main/java/io/helidon/pico/tools/ActivatorCreatorDefault.java
  pico/tools/src/main/java/io/helidon/pico/tools/ActivatorCreatorResponse.java
  pico/tools/src/main/java/io/helidon/pico/tools/CodeGenFiler.java
Labels: pico, OCA Verified

#6938 2.x: Update Jenkinsfile to archive nexus staging repo
  Jenkinsfile
Labels: build, 2.x, OCA Verified

#6934 3.x: Update validate workflow to use Oracle jdk
  .github/workflows/validate.yaml
Labels: build, 3.x, OCA Verified

#6929 Níma WebClient redirect support
  common/http/src/main/java/io/helidon/common/http/Http.java
  examples/media/multipart/src/test/java/io/helidon/examples/media/multipart/FileServiceTest.java
  nima/http2/webclient/src/main/java/io/helidon/nima/http2/webclient/ClientRequestImpl.java
  nima/tests/integration/webclient/webclient/src/test/java/io/helidon/nima/webclient/http1/ClientRequestImplTest.java
  nima/tests/integration/webserver/webserver/src/test/java/io/helidon/nima/tests/integration/server/MultiPortTest.java
  nima/webclient/webclient/src/main/java/io/helidon/nima/webclient/ClientConfig.java
  nima/webclient/webclient/src/main/java/io/helidon/nima/webclient/ClientRequest.java
  nima/webclient/webclient/src/main/java/io/helidon/nima/webclient/LoomClient.java
  nima/webclient/webclient/src/main/java/io/helidon/nima/webclient/UriHelper.java
  nima/webclient/webclient/src/main/java/io/helidon/nima/webclient/WebClient.java
  nima/webclient/webclient/src/main/java/io/helidon/nima/webclient/http1/ClientRequestImpl.java
  nima/webclient/webclient/src/main/java/io/helidon/nima/webclient/http1/Http1Client.java
  nima/webclient/webclient/src/test/java/io/helidon/nima/webclient/HttpClientTest.java
Labels: OCA Verified

#6537 [3.x] - Make Jaeger Tracer OpenTelemetry Agent aware.
  tracing/jaeger/src/main/java/io/helidon/tracing/jaeger/JaegerTracerBuilder.java
  tracing/opentelemetry/pom.xml
  tracing/opentelemetry/src/main/java/io/helidon/tracing/opentelemetry/HelidonOpenTelemetry.java
  tracing/opentelemetry/src/test/java/io/helidon/tracing/opentelemetry/AgentDetectorTest.java
  tracing/opentelemetry/src/test/java/io/helidon/tracing/opentelemetry/BaggageTest.java
Labels: tracing, 3.x, OCA Verified

#6941 3.x: Upgrade guava to 32.0.0
  dependencies/pom.xml
  security/providers/google-login/pom.xml
Labels: dependencies, OCA Verified

#6942 2.x: Upgrade guava to 32.0.0
  dependencies/pom.xml
  security/providers/google-login/pom.xml
Labels: dependencies, OCA Verified

#6948 [2.x] CipherSuiteTest intermittent failure
  webclient/webclient/src/main/java/io/helidon/webclient/NettyClientHandler.java
  webserver/webserver/src/test/java/io/helidon/webserver/CipherSuiteTest.java
Labels: webserver, 2.x, testing, OCA Verified

#6940 3.x: Upgrade graphql to 18.5 and scalars to 18.3
  dependencies/pom.xml
  microprofile/graphql/server/src/main/java/module-info.java
Labels: dependencies, 3.x, graphql, OCA Verified

#6939 2.x: Upgrade graphql to 18.5 and scalars to 18.3
  dependencies/pom.xml
  microprofile/graphql/server/src/main/java/module-info.java
Labels: 2.x, dependencies, graphql, OCA Verified

#6949 [3.x] CipherSuiteTest intermittent failure
  webclient/webclient/src/main/java/io/helidon/webclient/NettyClientHandler.java
  webserver/webserver/src/test/java/io/helidon/webserver/CipherSuiteTest.java
Labels: webserver, 3.x, testing, OCA Verified

#6952 Add relativeUris configuration to determine if relative or absolute URI will be used in the request
  nima/webclient/webclient/pom.xml
  nima/webclient/webclient/src/main/java/io/helidon/nima/webclient/http1/Http1Client.java
  nima/webclient/webclient/src/main/java/io/helidon/nima/webclient/http1/Http1ClientConfig.java
  nima/webclient/webclient/src/main/java/io/helidon/nima/webclient/http1/HttpCallChainBase.java
  nima/webclient/webclient/src/test/java/io/helidon/nima/webclient/http1/ClientRequestImplTest.java
Labels: OCA Verified

#6956 Remove metrics app registry clear-out code from metrics extension; add doc
  docs/mp/metrics/metrics.adoc
  microprofile/metrics/src/main/java/io/helidon/microprofile/metrics/MetricsCdiExtension.java
  microprofile/tests/tck/tck-metrics/src/test/java/io/helidon/microprofile/metrics/tck/MetricsTckCdiExtension.java
Labels: OCA Verified

#6887 6871 Writing to closed socket with a silent error
  nima/http2/http2/src/main/java/io/helidon/nima/http2/Http2ConnectionWriter.java
  nima/http2/webserver/src/main/java/io/helidon/nima/http2/webserver/Http2Connection.java
  nima/tests/integration/http2/server/src/test/java/io/helidon/nima/tests/integration/http2/webserver/CutConnectionTest.java
Labels: OCA Verified

#6907 6543 HTTP/2 header continuation
  nima/http2/http2/src/main/java/io/helidon/nima/http2/Http2ConnectionWriter.java
  nima/http2/http2/src/main/java/io/helidon/nima/http2/Http2ErrorCode.java
  nima/http2/http2/src/main/java/io/helidon/nima/http2/Http2Headers.java
  nima/http2/http2/src/test/java/io/helidon/nima/http2/MaxFrameSizeSplitTest.java
  nima/http2/webserver/src/main/java/io/helidon/nima/http2/webserver/Http2Config.java
  nima/http2/webserver/src/main/java/io/helidon/nima/http2/webserver/Http2Connection.java
  nima/tests/integration/http2/client/src/test/java/io/helidon/nima/tests/integration/http2/client/HeadersTest.java
  nima/tests/integration/http2/server/src/test/java/io/helidon/nima/tests/integration/http2/webserver/HeadersTest.java
Labels: OCA Verified

#6936 Preparation for Pico Extensibility Enhancements
  pico/api/src/main/java/io/helidon/pico/api/CommonQualifiers.java
  pico/api/src/main/java/io/helidon/pico/api/ServiceProviderBindable.java
  pico/configdriven/runtime/src/main/java/io/helidon/pico/configdriven/runtime/AbstractConfiguredServiceProvider.java
  pico/configdriven/runtime/src/main/java/io/helidon/pico/configdriven/runtime/UnconfiguredServiceProvider.java
  pico/maven-plugin/src/main/java/io/helidon/pico/maven/plugin/AbstractApplicationCreatorMojo.java
  pico/maven-plugin/src/main/java/io/helidon/pico/maven/plugin/AbstractCreatorMojo.java
  pico/processor/pom.xml
  pico/processor/src/main/java/io/helidon/pico/processor/GeneralProcessorUtils.java
  pico/processor/src/main/java/io/helidon/pico/processor/PicoAnnotationProcessor.java
  pico/processor/src/main/java/io/helidon/pico/processor/spi/PicoAnnotationProcessorObserver.java
  pico/processor/src/main/java/io/helidon/pico/processor/spi/ProcessingEvent.java
  pico/processor/src/main/java/io/helidon/pico/processor/spi/package-info.java
  pico/processor/src/main/java/module-info.java
  pico/runtime/src/main/java/io/helidon/pico/runtime/AbstractServiceProvider.java
  pico/runtime/src/main/java/io/helidon/pico/runtime/NonSingletonServiceProvider.java
  pico/runtime/src/main/java/io/helidon/pico/runtime/ServiceBinderDefault.java
  pico/tools/src/main/java/io/helidon/pico/tools/ApplicationCreatorDefault.java
  pico/tools/src/main/java/io/helidon/pico/tools/ModuleUtils.java
  pico/tools/src/main/java/io/helidon/pico/tools/ServicesToProcess.java
  pico/tools/src/main/java/io/helidon/pico/tools/TypeTools.java
  pico/tools/src/main/java/io/helidon/pico/tools/spi/ModuleComponentNamer.java
  pico/tools/src/main/java/module-info.java
Labels: pico, OCA Verified

#6980 Disable intermittently-failing async metrics MP test until we understand the failure
  microprofile/metrics/src/test/java/io/helidon/microprofile/metrics/HelloWorldAsyncResponseTest.java
Labels: OCA Verified

#6975 2.x: Upgrade graphql to 18.6
  dependencies/pom.xml
Labels: 2.x, dependencies, graphql, OCA Verified

#6974 3.x: Upgrade graphql to 18.6
  dependencies/pom.xml
Labels: dependencies, 3.x, graphql, OCA Verified

#6965 Upgrade graphql-java to 18.x
  dependencies/pom.xml
  microprofile/graphql/server/src/main/java/module-info.java
Labels: OCA Verified

#6981 Avoid reflecting back user data coming from exception messages. Make …
  webserver/webserver/src/main/java/io/helidon/webserver/ForwardingHandler.java
  webserver/webserver/src/test/java/io/helidon/webserver/TestNettyRejectRequest.java
Labels: security, webserver, 2.x, OCA Verified

#6772 [4.x] - MP Telemetry Documentation
  docs/images/telemetry/telemetry-custom-jaeger.png
  docs/images/telemetry/telemetry-general.png
  docs/images/telemetry/telemetry-greeting-jaeger.png
  docs/images/telemetry/telemetry-outbound-jaeger.png
  docs/mp/telemetry.adoc
Labels: docs, tracing, 4.x, OCA Verified, telemetry

#6711 [4.x] - [DOC] - Testing
  docs/nima/testing.adoc
Labels: docs, testing, 4.x, OCA Verified

#6988 [3.x] Avoid reflecting back user data coming from exception messages
  webserver/webserver/src/main/java/io/helidon/webserver/ForwardingHandler.java
  webserver/webserver/src/test/java/io/helidon/webserver/TestNettyRejectRequest.java
Labels: security, webserver, 3.x, OCA Verified

#6983 [4.x] - Additional methods for Http1ClientRequest
  nima/webclient/webclient/src/main/java/io/helidon/nima/webclient/http1/ClientRequestImpl.java
  nima/webclient/webclient/src/main/java/io/helidon/nima/webclient/http1/Http1ClientRequest.java
Labels: 4.x, OCA Verified

#6990 [4.x] Avoid reflecting back user data in exception messages
  common/http/src/main/java/io/helidon/common/http/DirectHandler.java
  common/http/src/main/java/io/helidon/common/http/RequestException.java
  nima/tests/integration/webserver/webserver/src/test/java/io/helidon/nima/tests/integration/server/ExceptionMessageTest.java
  nima/webserver/webserver/src/main/java/io/helidon/nima/webserver/http1/Http1Connection.java
  nima/webserver/webserver/src/main/java/io/helidon/nima/webserver/http1/Http1Prologue.java
Labels: security, webserver, 4.x, OCA Verified

#6821 Fix table formatting
  docs/config/io_helidon_microprofile_jwt.adoc
Labels: OCA Verified

#6987 [3.x ] - Fix OpenTracingSpan Baggage propagation issue
  tests/integration/gh-6970/pom.xml
  tests/integration/gh-6970/src/test/java/io/helidon/tests/integration/tracerbaggage/MainTest.java
  tests/integration/gh-6970/src/test/resources/application.yaml
  tests/integration/pom.xml
  tracing/opentelemetry/src/main/java/io/helidon/tracing/opentelemetry/OpenTelemetrySpan.java
  tracing/opentelemetry/src/test/java/io/helidon/tracing/opentelemetry/BaggageTest.java
Labels: tracing, 3.x, OCA Verified, telemetry

#6982 Pico extensibility support for the OCI SDK
  bom/pom.xml
  etc/checkstyle-suppressions.xml
  integrations/oci/sdk/README.md
  integrations/oci/sdk/cdi/src/main/java/io/helidon/integrations/oci/sdk/cdi/AdpSelectionStrategy.java
  integrations/oci/sdk/cdi/src/main/java/io/helidon/integrations/oci/sdk/cdi/OciExtension.java
  integrations/oci/sdk/pom.xml
  integrations/oci/sdk/processor/README.md
  integrations/oci/sdk/processor/pom.xml
  integrations/oci/sdk/processor/src/main/java/io/helidon/integrations/oci/sdk/processor/InjectionProcessorObserverForOCI.java
  integrations/oci/sdk/processor/src/main/java/io/helidon/integrations/oci/sdk/processor/ModuleComponentNamerDefault.java
  integrations/oci/sdk/processor/src/main/java/io/helidon/integrations/oci/sdk/processor/package-info.java
  integrations/oci/sdk/processor/src/main/java/module-info.java
  integrations/oci/sdk/processor/src/main/resources/io/helidon/integrations/oci/sdk/processor/builder-name-exceptions.txt
  integrations/oci/sdk/processor/src/main/resources/io/helidon/integrations/oci/sdk/processor/codegen-exclusions.txt
  integrations/oci/sdk/processor/src/main/resources/io/helidon/integrations/oci/sdk/processor/templates/service-client-builder-provider.hbs
  integrations/oci/sdk/processor/src/main/resources/io/helidon/integrations/oci/sdk/processor/templates/service-client-provider.hbs
  integrations/oci/sdk/processor/src/test/java/io/helidon/integrations/oci/sdk/processor/InjectionProcessorObserverForOCITest.java
  integrations/oci/sdk/processor/src/test/java/io/helidon/integrations/oci/sdk/processor/ModuleComponentNamerDefaultTest.java
  integrations/oci/sdk/processor/src/test/resources/expected/objectstorage$$Oci$$Client._java_
  integrations/oci/sdk/processor/src/test/resources/expected/objectstorage$$Oci$$ClientBuilder._java_
  integrations/oci/sdk/processor/src/test/resources/io/helidon/integrations/oci/sdk/processor/builder-name-exceptions.txt
  integrations/oci/sdk/processor/src/test/resources/io/helidon/integrations/oci/sdk/processor/codegen-exclusions.txt
  integrations/oci/sdk/runtime/README.md
  integrations/oci/sdk/runtime/etc/spotbugs/exclude.xml
  integrations/oci/sdk/runtime/pom.xml
  integrations/oci/sdk/runtime/src/main/java/io/helidon/integrations/oci/sdk/runtime/OciAuthenticationDetailsProvider.java
  integrations/oci/sdk/runtime/src/main/java/io/helidon/integrations/oci/sdk/runtime/OciAvailability.java
  integrations/oci/sdk/runtime/src/main/java/io/helidon/integrations/oci/sdk/runtime/OciAvailabilityDefault.java
  integrations/oci/sdk/runtime/src/main/java/io/helidon/integrations/oci/sdk/runtime/OciConfigBean.java
  integrations/oci/sdk/runtime/src/main/java/io/helidon/integrations/oci/sdk/runtime/OciExtension.java
  integrations/oci/sdk/runtime/src/main/java/io/helidon/integrations/oci/sdk/runtime/OciRegionProvider.java
  integrations/oci/sdk/runtime/src/main/java/io/helidon/integrations/oci/sdk/runtime/package-info.java
  integrations/oci/sdk/runtime/src/main/java/module-info.java
  integrations/oci/sdk/runtime/src/test/java/io/helidon/integrations/oci/sdk/runtime/OciAuthenticationDetailsProviderTest.java
  integrations/oci/sdk/runtime/src/test/java/io/helidon/integrations/oci/sdk/runtime/OciAvailabilityTest.java
  integrations/oci/sdk/runtime/src/test/java/io/helidon/integrations/oci/sdk/runtime/OciConfigBeanTest.java
  integrations/oci/sdk/runtime/src/test/java/io/helidon/integrations/oci/sdk/runtime/OciExtensionTest.java
  integrations/oci/sdk/runtime/src/test/java/io/helidon/integrations/oci/sdk/runtime/OciRegionProviderTest.java
  integrations/oci/sdk/tests/README.md
  integrations/oci/sdk/tests/pom.xml
  integrations/oci/sdk/tests/test-application/pom.xml
  integrations/oci/sdk/tests/test-application/src/test/java/io/helidon/integrations/oci/sdk/tests/test/application/TestOciServices.java
  integrations/oci/sdk/tests/test-module1/pom.xml
  integrations/oci/sdk/tests/test-module1/src/main/java/io/helidon/integrations/oci/sdk/tests/test/module1/AServiceUsingObjectStorage.java
  integrations/oci/sdk/tests/test-module1/src/main/java/io/helidon/integrations/oci/sdk/tests/test/module1/package-info.java
  integrations/oci/sdk/tests/test-module2/pom.xml
  integrations/oci/sdk/tests/test-module2/src/main/java/io/helidon/integrations/oci/sdk/tests/test/module2/AnotherServiceUsingObjectStorage.java
  integrations/oci/sdk/tests/test-module2/src/main/java/io/helidon/integrations/oci/sdk/tests/test/module2/package-info.java
  pico/README.md
  pico/api/src/main/java/io/helidon/pico/api/InjectionPointProvider.java
  pico/maven-plugin/src/main/java/io/helidon/pico/maven/plugin/AbstractApplicationCreatorMojo.java
  pico/runtime/src/main/java/io/helidon/pico/runtime/AbstractServiceProvider.java
  pico/runtime/src/main/java/io/helidon/pico/runtime/BoundedServiceProvider.java
  pico/runtime/src/main/java/io/helidon/pico/runtime/DefaultInjectionPlans.java
  pico/runtime/src/main/java/io/helidon/pico/runtime/DefaultPicoServices.java
  pico/tools/src/main/java/io/helidon/pico/tools/ApplicationCreatorConfigOptions.java
Labels: 4.x, OCA Verified

#6994 Filter complex environment properties configuration
  config/config-mp/src/main/java/io/helidon/config/mp/MpEnvironmentVariablesSource.java
  config/config/src/main/java/io/helidon/config/EnvironmentVariables.java
  config/config/src/main/java/io/helidon/config/PropertiesFilter.java
  config/config/src/test/java/io/helidon/config/PropertiesFilterTest.java
Labels: MP, config, OCA Verified

#6971 Nima WebClient configuration for timeouts and keepAlive
  nima/http2/webclient/src/main/java/io/helidon/nima/http2/webclient/Http2Client.java
  nima/webclient/webclient/src/main/java/io/helidon/nima/webclient/WebClient.java
  nima/webclient/webclient/src/main/java/io/helidon/nima/webclient/http1/Http1Client.java
  nima/websocket/client/src/main/java/io/helidon/nima/websocket/client/WsClient.java
Labels: OCA Verified

#7027 [3.x] - Move tracer tags to process
  tracing/jaeger/src/main/java/io/helidon/tracing/jaeger/JaegerTracerBuilder.java
Labels: enhancement, tracing, 3.x, OCA Verified

#7022 [3.x] - Add support for multiple baggage items
  tests/integration/gh-6970/src/test/java/io/helidon/tests/integration/tracerbaggage/MainTest.java
  tests/integration/gh-6970/src/test/resources/application.yaml
  tracing/opentelemetry/src/main/java/io/helidon/tracing/opentelemetry/OpenTelemetrySpan.java
Labels: enhancement, tracing, 3.x, OCA Verified

#7028 Nima webclient support for properties
  nima/http2/webclient/src/main/java/io/helidon/nima/http2/webclient/ClientRequestImpl.java
  nima/webclient/webclient/src/main/java/io/helidon/nima/webclient/ClientRequest.java
  nima/webclient/webclient/src/main/java/io/helidon/nima/webclient/LoomClient.java
  nima/webclient/webclient/src/main/java/io/helidon/nima/webclient/WebClient.java
  nima/webclient/webclient/src/main/java/io/helidon/nima/webclient/http1/ClientRequestImpl.java
  nima/webclient/webclient/src/main/java/io/helidon/nima/webclient/http1/Http1ClientImpl.java
  nima/webclient/webclient/src/test/java/io/helidon/nima/webclient/HttpClientTest.java
Labels: webclient, 4.x, OCA Verified

#7042 Release Netty ByteBuf after it is consumed by Tyrus
  webserver/websocket/pom.xml
  webserver/websocket/src/main/java/io/helidon/webserver/websocket/WebSocketHandler.java
Labels: 3.x, websocket, OCA Verified

#7014 Use current context instead of creating new one in ClientRequest
  nima/webclient/webclient/src/main/java/io/helidon/nima/webclient/http1/ClientRequestImpl.java
Labels: webclient, 4.x, OCA Verified

#7070 Fix error messages in validation task of builder processor.
  builder/processor/src/main/java/io/helidon/builder/processor/ValidationTask.java
Labels: 4.x, OCA Verified, builder

#7050 Reset channel auto-read config before upgrading websocket connection
  webserver/websocket/src/main/java/io/helidon/webserver/websocket/WebSocketHandler.java
Labels: OCA Verified

#7057 3.x: Upgrade grpc, guava, netty, snappy-java, use slim neo4j driver
  dependencies/pom.xml
  integrations/neo4j/health/pom.xml
  integrations/neo4j/metrics/pom.xml
  integrations/neo4j/neo4j/pom.xml
  pom.xml
Labels: dependencies, 3.x, OCA Verified

#7040 improve pico integration docs for oci sdk
  integrations/oci/sdk/README.md
  integrations/oci/sdk/runtime/src/main/java/io/helidon/integrations/oci/sdk/runtime/OciConfigBlueprint.java
Labels: 4.x, OCA Verified

#7056 Add header and config builder method to webclient builder
  common/http/src/main/java/io/helidon/common/http/ClientRequestHeaders.java
  nima/http2/webclient/src/main/java/io/helidon/nima/http2/webclient/ClientRequestImpl.java
  nima/webclient/webclient/src/main/java/io/helidon/nima/webclient/ClientRequest.java
  nima/webclient/webclient/src/main/java/io/helidon/nima/webclient/WebClient.java
  nima/webclient/webclient/src/main/java/io/helidon/nima/webclient/http1/ClientRequestImpl.java
  nima/webclient/webclient/src/test/java/io/helidon/nima/webclient/HttpClientTest.java
Labels: OCA Verified

#7085 2.x: Upgrade netty, grpc, guava, snappy-java and use slim neo4j driver
  dependencies/pom.xml
  integrations/neo4j/health/pom.xml
  integrations/neo4j/metrics/pom.xml
  integrations/neo4j/neo4j/pom.xml
  pom.xml
Labels: 2.x, dependencies, OCA Verified

#7072 Document assumptions about types of current processing round
  builder/processor/src/main/java/io/helidon/builder/processor/CustomMethods.java
  builder/processor/src/main/java/io/helidon/builder/processor/FactoryMethods.java
  common/processor/processor/src/main/java/io/helidon/common/processor/TypeFactory.java
Labels: 4.x, OCA Verified, builder

#7074 Follow up changes for builders PR
  nima/http/media/jackson/src/main/java/io/helidon/nima/http/media/jackson/JacksonSupport.java
  nima/http/media/jsonb/src/main/java/io/helidon/nima/http/media/jsonb/JsonbSupport.java
  nima/http/media/media/src/main/java/io/helidon/nima/http/media/PathSupport.java
  nima/http/media/media/src/main/java/io/helidon/nima/http/media/StringSupport.java
  nima/http/media/multipart/src/main/java/io/helidon/nima/http/media/multipart/MultiPartSupport.java
  nima/webserver/webserver/src/main/java/io/helidon/nima/webserver/ProtocolConfigs.java
  nima/webserver/webserver/src/main/java/io/helidon/nima/webserver/ServerConfigBlueprint.java
Labels: 4.x, OCA Verified

#7086 4.x: Switch validate workflow to Oracle JDK distribution
  .github/workflows/validate.yml
Labels: build, 4.x, OCA Verified

#7098 3.x release workflow
  .github/workflows/release.yaml
  .github/workflows/validate.yaml
  etc/scripts/includes/pipeline-env.sh
  etc/scripts/release.sh
Labels: build, 3.x, OCA Verified

#7108 [4.x] - Rename `ServerConfig` to `WebServerConfig`
  microprofile/server/src/main/java/io/helidon/microprofile/server/ServerCdiExtension.java
  nima/http2/webclient/src/test/java/io/helidon/nima/http2/webclient/Http2WebClientTest.java
  nima/testing/junit5/webserver/src/main/java/io/helidon/nima/testing/junit5/webserver/HelidonServerJunitExtension.java
  nima/testing/junit5/webserver/src/main/java/io/helidon/nima/testing/junit5/webserver/Http1ServerJunitExtension.java
  nima/testing/junit5/webserver/src/main/java/io/helidon/nima/testing/junit5/webserver/spi/ServerJunitExtension.java
  nima/testing/junit5/webserver/src/test/java/io/helidon/nima/testing/junit5/webserver/TestServerTest.java
  nima/testing/junit5/websocket/src/main/java/io/helidon/nima/testing/junit5/websocket/WsServerExtension.java
  nima/tests/integration/http2/client/src/test/java/io/helidon/nima/tests/integration/http2/client/Http2ClientTest.java
  nima/tests/integration/http2/server/src/test/java/io/helidon/nima/tests/integration/http2/webserver/FlowControlTest.java
  nima/tests/integration/http2/server/src/test/java/io/helidon/nima/tests/integration/http2/webserver/HeadersTest.java
  nima/tests/integration/http2/server/src/test/java/io/helidon/nima/tests/integration/http2/webserver/Http2ErrorHandlingWithOutputStreamTest.java
  nima/tests/integration/http2/server/src/test/java/io/helidon/nima/tests/integration/http2/webserver/Http2ServerTest.java
  nima/tests/integration/webserver/mtls/src/test/java/io/helidon/nima/tests/integration/server/mtls/MtlsTest.java
  nima/tests/integration/webserver/webserver/src/test/java/io/helidon/nima/tests/integration/server/BadRequestTest.java
  nima/tests/integration/webserver/webserver/src/test/java/io/helidon/nima/tests/integration/server/ConfiguredLimitsTest.java
  nima/tests/integration/webserver/webserver/src/test/java/io/helidon/nima/tests/integration/server/ContentEncodingContextTest.java
  nima/tests/integration/webserver/webserver/src/test/java/io/helidon/nima/tests/integration/server/ContentEncodingDisabledNoValidationTest.java
  nima/tests/integration/webserver/webserver/src/test/java/io/helidon/nima/tests/integration/server/ContentEncodingDisabledTest.java
  nima/tests/integration/webserver/webserver/src/test/java/io/helidon/nima/tests/integration/server/Continue100ImmediatelyTest.java
  nima/tests/integration/webserver/webserver/src/test/java/io/helidon/nima/tests/integration/server/MaxPayloadSizeTest.java
  nima/tests/integration/webserver/webserver/src/test/java/io/helidon/nima/tests/integration/server/MediaContextTest.java
  nima/tests/integration/webserver/webserver/src/test/java/io/helidon/nima/tests/integration/server/RoutingTest.java
  nima/tests/integration/websocket/server/src/test/java/io/helidon/nima/tests/integration/websocket/webserver/WebSocketOriginTest.java
  nima/webserver/webserver/src/main/java/io/helidon/nima/webserver/ListenerConfigBlueprint.java
  nima/webserver/webserver/src/main/java/io/helidon/nima/webserver/LoomServer.java
  nima/webserver/webserver/src/main/java/io/helidon/nima/webserver/WebServer.java
  nima/webserver/webserver/src/main/java/io/helidon/nima/webserver/WebServerConfigBlueprint.java
  tests/apps/bookstore/bookstore-se/src/main/java/io/helidon/tests/apps/bookstore/se/Main.java
Labels: 4.x, OCA Verified

#7113 Support for lastEndpointUri() in Webclient responses
  nima/http2/webclient/src/main/java/io/helidon/nima/http2/webclient/ClientRequestImpl.java
  nima/http2/webclient/src/main/java/io/helidon/nima/http2/webclient/ClientResponseImpl.java
  nima/tests/integration/webclient/webclient/src/test/java/io/helidon/nima/webclient/http1/ClientRequestImplTest.java
  nima/webclient/webclient/src/main/java/io/helidon/nima/webclient/ClientResponse.java
  nima/webclient/webclient/src/main/java/io/helidon/nima/webclient/UriHelper.java
  nima/webclient/webclient/src/main/java/io/helidon/nima/webclient/http1/ClientRequestImpl.java
  nima/webclient/webclient/src/main/java/io/helidon/nima/webclient/http1/ClientResponseImpl.java
Labels: webclient, 4.x, OCA Verified

#7090 Nima: MicroMeter now contains Nima and SE integration
  examples/integrations/micrometer/se/pom.xml
  examples/integrations/micrometer/se/src/main/java/io/helidon/examples/micrometer/se/GreetService.java
  examples/integrations/micrometer/se/src/main/java/io/helidon/examples/micrometer/se/Main.java
  examples/integrations/micrometer/se/src/test/java/io/helidon/examples/micrometer/se/MainTest.java
  integrations/micrometer/micrometer/pom.xml
  integrations/micrometer/micrometer/src/main/java/io/helidon/integrations/micrometer/MeterRegistryFactory.java
  integrations/micrometer/micrometer/src/main/java/io/helidon/integrations/micrometer/MicrometerBuiltInRegistrySupport.java
  integrations/micrometer/micrometer/src/main/java/io/helidon/integrations/micrometer/MicrometerPrometheusRegistrySupport.java
  integrations/micrometer/micrometer/src/main/java/io/helidon/integrations/micrometer/MicrometerSupport.java
  integrations/micrometer/micrometer/src/main/java/io/helidon/integrations/micrometer/PrometheusHandler.java
  integrations/micrometer/micrometer/src/main/java/io/helidon/integrations/micrometer/ReactivePrometheusHandler.java
  integrations/micrometer/micrometer/src/main/java/module-info.java
  integrations/micrometer/micrometer/src/test/java/io/helidon/integrations/micrometer/MicrometerEndpointTests.java
  integrations/micrometer/micrometer/src/test/java/io/helidon/integrations/micrometer/MicrometerFeatureBuilderTest.java
  integrations/micrometer/micrometer/src/test/java/io/helidon/integrations/micrometer/MicrometerSimplePrometheusTest.java
  integrations/micrometer/micrometer/src/test/java/io/helidon/integrations/micrometer/MicrometerTestAddingMeters.java
  integrations/micrometer/micrometer/src/test/java/io/helidon/integrations/micrometer/MicrometerTestUtil.java
Labels: OCA Verified

#7104 3.x: Enable release workflow and remove Jenkinsfile
  .github/workflows/release.yaml
  Jenkinsfile
Labels: build, OCA Verified

#7115 Fix post merge compile error in examples.micrometer.se.MainTest
  examples/integrations/micrometer/se/src/test/java/io/helidon/examples/micrometer/se/MainTest.java
Labels: build, OCA Verified

#6490 [3.x] Add @target(ElementType.METHOD) for annotation @mptest
  tests/integration/jpa/appl/src/main/java/io/helidon/tests/integration/jpa/appl/MPTest.java
Labels: OCA Verified

#6489 [main] Add @target(ElementType.METHOD) for annotation @mptest
  tests/integration/jpa/appl/src/main/java/io/helidon/tests/integration/jpa/appl/MPTest.java
Labels: OCA Verified

#7114 Add metrics to SE quickstarts
  archetypes/helidon/src/main/archetype/nima/quickstart/quickstart-nima.xml
  examples/quickstarts/helidon-quickstart-se/pom.xml
  examples/quickstarts/helidon-quickstart-se/src/test/java/io/helidon/examples/quickstart/se/MainTest.java
  examples/quickstarts/helidon-standalone-quickstart-se/pom.xml
  examples/quickstarts/helidon-standalone-quickstart-se/src/test/java/io/helidon/examples/quickstart/se/MainTest.java
Labels: examples, archetypes, 4.x, OCA Verified

#7117 3.x: Restore env for Jenkins and do some minor cleanup
  .github/workflows/validate.yaml
  etc/scripts/includes/pipeline-env.sh
Labels: build, 3.x, OCA Verified

#6922 [3.x] 6847 WLS JMS connector doesn't support named factory bean
  messaging/connectors/jms/src/main/java/io/helidon/messaging/connectors/jms/ConnectionContext.java
  messaging/connectors/wls-jms/src/main/java/io/helidon/messaging/connectors/wls/ThinClientClassLoader.java
  messaging/connectors/wls-jms/src/main/resources/META-INF/helidon/serial-config.properties
Labels: OCA Verified

#6923 [4.x] 6921 WLS JMS connector doesn't support named factory bean
  messaging/connectors/jms/src/main/java/io/helidon/messaging/connectors/jms/ConnectionContext.java
  messaging/connectors/wls-jms/src/main/java/io/helidon/messaging/connectors/wls/ThinClientClassLoader.java
  messaging/connectors/wls-jms/src/main/resources/META-INF/helidon/serial-config.properties
Labels: OCA Verified

#6515 Validate http request and response headers when using the webclient
  common/buffers/src/main/java/io/helidon/common/buffers/LazyString.java
  common/buffers/src/test/java/io/helidon/common/buffers/LazyStringTest.java
  common/http/pom.xml
  common/http/src/main/java/io/helidon/common/http/Http.java
  common/http/src/main/java/io/helidon/common/http/Http1HeadersParser.java
  common/http/src/test/java/io/helidon/common/http/Http1HeadersParserTest.java
  common/http/src/test/java/io/helidon/common/http/HttpTest.java
  nima/webclient/webclient/src/main/java/io/helidon/nima/webclient/http1/HttpCallChainBase.java
  nima/webclient/webclient/src/main/java/io/helidon/nima/webclient/http1/HttpCallEntityChain.java
  nima/webclient/webclient/src/main/java/io/helidon/nima/webclient/http1/HttpCallOutputStreamChain.java
  nima/webclient/webclient/src/test/java/io/helidon/nima/webclient/http1/ClientRequestImplTest.java
Labels: OCA Verified

#7119 Add static factory methods to Http1Client
  nima/webclient/webclient/src/main/java/io/helidon/nima/webclient/http1/Http1Client.java
  nima/webclient/webclient/src/main/java/module-info.java
Labels: OCA Verified

#7123 3.x: Replace use of PIPELINE env variable in script
  etc/scripts/owasp-dependency-check.sh
Labels: build, 3.x, OCA Verified

#7124 3.x: Upgrade Jackson to 2.15.2
  dependencies/pom.xml
Labels: dependencies, 3.x, OCA Verified

#7125 2.x: Release workflow: Fix tagging. Remove use of PIPELINE env variable. Restore Jenkins env.
  .github/workflows/validate.yml
  etc/scripts/includes/pipeline-env.sh
  etc/scripts/owasp-dependency-check.sh
  etc/scripts/release.sh
Labels: build, 2.x, OCA Verified

#7039 Initial implementation of Helidon connector for Jakarta REST client
  jersey/connector/pom.xml
  jersey/connector/src/main/java/io/helidon/jersey/connector/HelidonConnector.java
  jersey/connector/src/main/java/io/helidon/jersey/connector/HelidonConnectorProvider.java
  jersey/connector/src/main/java/io/helidon/jersey/connector/HelidonEntity.java
  jersey/connector/src/main/java/io/helidon/jersey/connector/HelidonProperties.java
  jersey/connector/src/main/java/io/helidon/jersey/connector/HelidonStructures.java
  jersey/connector/src/main/java/io/helidon/jersey/connector/OutputStreamChannel.java
  jersey/connector/src/main/java/module-info.java
  jersey/connector/src/test/java/io/helidon/jersey/connector/AbstractTest.java
  jersey/connector/src/test/java/io/helidon/jersey/connector/AsyncRequestTest.java
  jersey/connector/src/test/java/io/helidon/jersey/connector/BasicRequestTest.java
  jersey/connector/src/test/java/io/helidon/jersey/connector/FollowRedirectsTest.java
  jersey/connector/src/test/java/io/helidon/jersey/connector/LargeDataTest.java
  jersey/connector/src/test/java/io/helidon/jersey/connector/ParallelTest.java
  jersey/connector/src/test/java/io/helidon/jersey/connector/TimeoutTest.java
  tests/apps/bookstore/bookstore-se/src/test/java/io/helidon/tests/apps/bookstore/se/Http2SslTest.java
  tests/apps/bookstore/bookstore-se/src/test/java/io/helidon/tests/apps/bookstore/se/MainTest.java
  tests/apps/bookstore/bookstore-se/src/test/java/io/helidon/tests/apps/bookstore/se/SslTest.java
  tests/apps/bookstore/bookstore-se/src/test/java/io/helidon/tests/apps/bookstore/se/TestServer.java
  tests/functional/mp-compression/src/test/java/io/helidon/tests/functional/mpcompression/MpCompressionTest.java
  tests/integration/jersey-connector/pom.xml
  tests/integration/jersey-connector/src/test/java/io/helidon/jersey/connector/JerseyConnectorTest.java
  tests/integration/jersey-connector/src/test/resources/logging-test.properties
  tests/integration/oidc/src/test/java/io/helidon/tests/integration/oidc/CommonLoginBase.java
  tests/integration/oidc/src/test/java/io/helidon/tests/integration/oidc/CookieBasedLoginIT.java
  tests/integration/oidc/src/test/java/io/helidon/tests/integration/oidc/QueryBasedLoginIT.java
  tests/integration/oidc/src/test/java/io/helidon/tests/integration/oidc/TenantIdentificationIT.java
  tests/integration/pom.xml
Labels: jax-rs, 4.x, OCA Verified

#7122 Keep alive is now configurable per request
  nima/http2/webclient/src/main/java/io/helidon/nima/http2/webclient/ClientRequestImpl.java
  nima/tests/integration/webclient/webclient/src/test/java/io/helidon/nima/webclient/http1/ClientRequestImplTest.java
  nima/webclient/webclient/src/main/java/io/helidon/nima/webclient/ClientRequest.java
  nima/webclient/webclient/src/main/java/io/helidon/nima/webclient/http1/ClientRequestImpl.java
  nima/webclient/webclient/src/main/java/io/helidon/nima/webclient/http1/ConnectionCache.java
  nima/webclient/webclient/src/main/java/io/helidon/nima/webclient/http1/HttpCallChainBase.java
  nima/webclient/webclient/src/main/java/io/helidon/nima/webclient/http1/HttpCallEntityChain.java
  nima/webclient/webclient/src/main/java/io/helidon/nima/webclient/http1/HttpCallOutputStreamChain.java
  nima/webclient/webclient/src/test/java/io/helidon/nima/webclient/HttpClientTest.java
Labels: OCA Verified

#7116 Update serial config for ojdbc driver
  archetypes/helidon/src/main/archetype/mp/custom/database.xml
  archetypes/helidon/src/main/archetype/mp/database/files/src/main/resources/META-INF/helidon/serial-config.properties
  archetypes/helidon/src/main/archetype/se/custom/database.xml
  archetypes/helidon/src/main/archetype/se/database/files/src/main/resources/META-INF/helidon/serial-config.properties
  docs/mp/persistence.adoc
  examples/employee-app/pom.xml
  examples/integrations/cdi/datasource-hikaricp/pom.xml
  examples/integrations/micronaut/data/README.md
  examples/integrations/oci/atp-cdi/pom.xml
  examples/integrations/oci/atp-cdi/src/main/resources/META-INF/helidon/serial-config.properties
  examples/integrations/oci/atp-reactive/pom.xml
  examples/integrations/oci/atp-reactive/src/main/resources/META-INF/helidon/serial-config.properties
  integrations/cdi/datasource-ucp/pom.xml
  integrations/db/ojdbc/src/main/resources/META-INF/helidon/serial-config.properties
  messaging/connectors/aq/pom.xml
  messaging/connectors/aq/src/main/resources/META-INF/helidon/serial-config.properties
Labels: OCA Verified

#7128 Build log fix
  pico/processor/src/main/java/io/helidon/pico/processor/PicoAnnotationProcessor.java
  pico/tools/pom.xml
  pico/tools/src/main/java/io/helidon/pico/tools/InterceptorCreatorDefault.java
Labels: build, OCA Verified

#7135 WebClient read timeout per request
  nima/testing/junit5/webserver/src/main/java/io/helidon/nima/testing/junit5/webserver/DirectClientConnection.java
  nima/tests/integration/webclient/webclient/src/test/java/io/helidon/nima/webclient/http1/ClientRequestImplTest.java
  nima/webclient/webclient/src/main/java/io/helidon/nima/webclient/ClientConnection.java
  nima/webclient/webclient/src/main/java/io/helidon/nima/webclient/http1/ClientRequestImpl.java
  nima/webclient/webclient/src/main/java/io/helidon/nima/webclient/http1/Http1ClientConnection.java
  nima/webclient/webclient/src/main/java/io/helidon/nima/webclient/http1/Http1ClientRequest.java
  nima/webclient/webclient/src/main/java/io/helidon/nima/webclient/http1/HttpCallEntityChain.java
  nima/webclient/webclient/src/test/java/io/helidon/nima/webclient/http1/ClientRequestImplTest.java
Labels: OCA Verified

#7134 3.x: Another Jenkins environment fix
  etc/scripts/includes/pipeline-env.sh
Labels: build, 3.x, OCA Verified

#6428 [Nima] Set running flag to false in shutdownhook
  nima/webserver/webserver/src/main/java/io/helidon/nima/webserver/LoomServer.java
Labels: OCA Verified

#7137 7097 flaky HTTP/2 bookstore test
  tests/apps/bookstore/bookstore-se/pom.xml
  tests/apps/bookstore/bookstore-se/src/main/java/io/helidon/tests/apps/bookstore/se/Main.java
  tests/apps/bookstore/bookstore-se/src/main/resources/application.yaml
  tests/apps/bookstore/bookstore-se/src/main/resources/logging.properties
  tests/apps/bookstore/bookstore-se/src/test/java/io/helidon/tests/apps/bookstore/se/Http2SslTest.java
  tests/apps/bookstore/bookstore-se/src/test/java/io/helidon/tests/apps/bookstore/se/MainTest.java
  tests/apps/bookstore/bookstore-se/src/test/java/io/helidon/tests/apps/bookstore/se/SslTest.java
  tests/apps/bookstore/bookstore-se/src/test/java/io/helidon/tests/apps/bookstore/se/TestServer.java
Labels: OCA Verified

#6501 Fix TODO to handle close call on entity
  nima/http/media/media/src/main/java/io/helidon/nima/http/media/ReadableEntityBase.java
Labels: OCA Verified

#7136 4.x: Helidon main class
  applications/mp/pom.xml
  bom/pom.xml
  config/config/src/main/java/io/helidon/config/ConfigMappers.java
  examples/nima/fault-tolerance/pom.xml
  examples/nima/fault-tolerance/src/main/java/io/helidon/examples/nima/faulttolerance/FtMain.java
  examples/nima/fault-tolerance/src/main/java/io/helidon/examples/nima/faulttolerance/GreetEndpoint.java
  examples/nima/fault-tolerance/src/main/resources/application.yaml
  examples/nima/fault-tolerance/src/test/java/io/helidon/examples/nima/faulttolerance/FaultToleranceTest.java
  examples/nima/imperative/pom.xml
  examples/nima/imperative/src/main/java/io/helidon/examples/nima/imperative/ImperativeMain.java
  helidon/pom.xml
  helidon/src/main/java/io/helidon/Main.java
  helidon/src/main/java/io/helidon/package-info.java
  helidon/src/main/java/io/helidon/spi/HelidonStartupProvider.java
  helidon/src/main/java/io/helidon/spi/package-info.java
  helidon/src/main/java/module-info.java
  integrations/micrometer/micrometer/src/main/java/io/helidon/integrations/micrometer/MeterRegistryFactory.java
  integrations/micrometer/micrometer/src/main/java/io/helidon/integrations/micrometer/MicrometerBuiltInRegistrySupport.java
  integrations/micrometer/micrometer/src/main/java/io/helidon/integrations/micrometer/MicrometerFeature.java
  integrations/micrometer/micrometer/src/main/java/io/helidon/integrations/micrometer/MicrometerPrometheusRegistrySupport.java
  microprofile/cdi/pom.xml
  microprofile/cdi/src/main/java/io/helidon/microprofile/cdi/CdiStartupProvider.java
  microprofile/cdi/src/main/java/module-info.java
  microprofile/service-common/src/test/java/io/helidon/microprofile/servicecommon/ConfiguredTestSupport.java
  nima/nima/src/main/java/io/helidon/nima/Nima.java
  nima/observe/config/pom.xml
  nima/observe/config/src/main/java/io/helidon/nima/observe/config/ConfigObserveProvider.java
  nima/observe/config/src/main/java/io/helidon/nima/observe/config/ConfigService.java
  nima/observe/config/src/main/java/module-info.java
  nima/observe/health/src/main/java/io/helidon/nima/observe/health/HealthFeature.java
  nima/observe/health/src/main/java/io/helidon/nima/observe/health/HealthObserveProvider.java
  nima/observe/info/src/main/java/io/helidon/nima/observe/info/InfoObserveProvider.java
  nima/observe/info/src/main/java/io/helidon/nima/observe/info/InfoService.java
  nima/observe/log/src/main/java/io/helidon/nima/observe/log/LogObserveProvider.java
  nima/observe/log/src/main/java/io/helidon/nima/observe/log/LogService.java
  nima/observe/log/src/main/java/module-info.java
  nima/observe/metrics/src/main/java/io/helidon/nima/observe/metrics/MetricsObserveProvider.java
  nima/observe/observe/pom.xml
  nima/observe/observe/src/main/java/io/helidon/nima/observe/ObserveFeature.java
  nima/observe/observe/src/main/java/io/helidon/nima/observe/spi/ObserveProvider.java
  nima/observe/observe/src/main/java/module-info.java
  nima/pom.xml
  nima/service-common/src/main/java/io/helidon/nima/servicecommon/HelidonFeatureSupport.java
  nima/testing/junit5/webserver/src/main/java/io/helidon/nima/testing/junit5/webserver/HelidonServerJunitExtension.java
  nima/tests/integration/imperative/pom.xml
  nima/tests/integration/imperative/src/main/java/io/helidon/nima/tests/integration/imperative/ImperativeMain.java
  nima/tests/integration/imperative/src/main/resources/application.yaml
  nima/tests/integration/imperative/src/test/java/io/helidon/nima/tests/integration/imperative/ImperativeMainTest.java
  nima/tests/integration/pom.xml
  nima/webclient/webclient/src/main/java/io/helidon/nima/webclient/DefaultDnsResolver.java
  nima/webserver/cors/src/main/java/io/helidon/nima/webserver/cors/CorsSupport.java
  nima/webserver/webserver/src/main/java/io/helidon/nima/webserver/LoomServer.java
  pico/api/pom.xml
  pico/api/src/main/java/io/helidon/pico/api/Helidon.java
  pico/api/src/main/java/io/helidon/pico/api/Startable.java
  pico/api/src/main/java/module-info.java
  pico/runtime/pom.xml
  pico/runtime/src/main/java/io/helidon/pico/runtime/HelidonInjectionStartupProvider.java
  pico/runtime/src/main/java/module-info.java
  pom.xml
Labels: 4.x, pico, OCA Verified

#6864 Draft of the integration doc for 3.x
  docs/includes/attributes.adoc
  docs/includes/security/jep-290.adoc
  docs/mp/integrations/oci.adoc
  docs/mp/integrations/wls.adoc
  docs/mp/reactivemessaging/weblogic.adoc
  docs/sitegen.yaml
Labels: docs, OCA Verified
