Repository helidon-io/helidon, pull requests merged in 2023-07, with the labels that each got.

#7140 TLS reloading fixed
  nima/tests/integration/webserver/mtls/src/test/java/io/helidon/nima/tests/integration/server/mtls/MtlsTest.java
  nima/webserver/webserver/src/main/java/io/helidon/nima/webserver/ServerListener.java
Labels: OCA Verified

#7142 builder `toString` method update
  builder/processor/src/main/java/io/helidon/builder/processor/GenerateAbstractBuilder.java
  builder/tests/builder/src/main/java/io/helidon/builder/test/testsubjects/tostring/ChildBlueprint.java
  builder/tests/builder/src/main/java/io/helidon/builder/test/testsubjects/tostring/EmptyChildBlueprint.java
  builder/tests/builder/src/main/java/io/helidon/builder/test/testsubjects/tostring/EmptyParentBlueprint.java
  builder/tests/builder/src/main/java/io/helidon/builder/test/testsubjects/tostring/ParentBlueprint.java
  builder/tests/builder/src/test/java/io/helidon/builder/test/MyDerivedConfigBeanTest.java
  builder/tests/builder/src/test/java/io/helidon/builder/test/ParentParentChildTest.java
Labels: OCA Verified, builder

#6441 Nima: WebClient Proxy Support
  common/http/src/main/java/io/helidon/common/http/Http.java
  common/socket/src/main/java/io/helidon/common/socket/SocketWriter.java
  nima/common/tls/src/main/java/io/helidon/nima/common/tls/Tls.java
  nima/http2/webclient/src/main/java/io/helidon/nima/http2/webclient/ClientRequestImpl.java
  nima/tests/integration/webclient/pom.xml
  nima/tests/integration/webclient/webclient/pom.xml
  nima/tests/integration/webclient/webclient/src/test/java/io/helidon/nima/tests/integration/client/HttpProxy.java
  nima/tests/integration/webclient/webclient/src/test/java/io/helidon/nima/tests/integration/client/HttpProxyTest.java
  nima/tests/integration/webclient/webclient/src/test/java/io/helidon/nima/tests/integration/client/HttpsProxyTest.java
  nima/tests/integration/webclient/webclient/src/test/java/io/helidon/nima/webclient/http1/ClientRequestImplTest.java
  nima/tests/integration/webclient/webclient/src/test/resources/server.p12
  nima/webclient/webclient/etc/spotbugs/exclude.xml
  nima/webclient/webclient/pom.xml
  nima/webclient/webclient/src/main/java/io/helidon/nima/webclient/ClientRequest.java
  nima/webclient/webclient/src/main/java/io/helidon/nima/webclient/Proxy.java
  nima/webclient/webclient/src/main/java/io/helidon/nima/webclient/UriHelper.java
  nima/webclient/webclient/src/main/java/io/helidon/nima/webclient/http1/ClientRequestImpl.java
  nima/webclient/webclient/src/main/java/io/helidon/nima/webclient/http1/ConnectionCache.java
  nima/webclient/webclient/src/main/java/io/helidon/nima/webclient/http1/ConnectionKey.java
  nima/webclient/webclient/src/main/java/io/helidon/nima/webclient/http1/Http1ClientConnection.java
  nima/webclient/webclient/src/main/java/io/helidon/nima/webclient/http1/HttpCallChainBase.java
  nima/webclient/webclient/src/main/java/io/helidon/nima/webclient/http1/HttpCallEntityChain.java
  nima/webclient/webclient/src/main/java/io/helidon/nima/webclient/http1/HttpCallOutputStreamChain.java
  nima/webclient/webclient/src/main/java/module-info.java
  nima/webclient/webclient/src/test/java/io/helidon/nima/webclient/HttpClientTest.java
  nima/webclient/webclient/src/test/java/io/helidon/nima/webclient/ProxyTest.java
Labels: OCA Verified

#7145 Generate config metadata fix.
  config/metadata-processor/src/main/java/io/helidon/config/metadata/processor/ConfigMetadataHandler.java
Labels: 4.x, OCA Verified

#7150 2.x: Upgrade to Jersey 2.40
  dependencies/pom.xml
  integrations/cdi/oci-objectstorage-cdi/pom.xml
  integrations/oci/metrics/metrics/pom.xml
  integrations/oci/sdk/cdi/pom.xml
Labels: 2.x, dependencies, OCA Verified

#7147 4.x: Upgrade jersey to 3.1.2
  dependencies/pom.xml
  integrations/oci/sdk/cdi/pom.xml
Labels: dependencies, 4.x, OCA Verified

#7158 Support for grpc proto packages.
  nima/grpc/webserver/src/main/java/io/helidon/nima/grpc/webserver/Grpc.java
  nima/tests/integration/http2/server/src/test/java/io/helidon/nima/tests/integration/http2/webserver/FlowControlTest.java
Labels: grpc, 4.x, OCA Verified

#7162 4.x dependency upgrades: grpc, guava, jackson, netty
  dependencies/pom.xml
  integrations/neo4j/health/pom.xml
  integrations/neo4j/metrics/pom.xml
  integrations/neo4j/neo4j/pom.xml
  security/providers/google-login/pom.xml
Labels: dependencies, 4.x, OCA Verified

#7160 Allow empty list injection
  config/config/src/main/java/io/helidon/config/ConfigProducer.java
  pico/api/src/main/java/io/helidon/pico/api/ServiceInjectionPlanBinder.java
  pico/runtime/src/main/java/io/helidon/pico/runtime/DefaultInjectionPlans.java
  pico/tests/resources-pico/src/main/java/io/helidon/pico/tests/pico/AContractWithNoServiceImplementations.java
  pico/tests/resources-pico/src/main/java/io/helidon/pico/tests/pico/AServiceUsingAContractWithNoServiceImplementations.java
  pico/tests/resources-pico/src/test/java/io/helidon/pico/tests/pico/EmptyListInjectionTest.java
  pico/tools/src/main/java/io/helidon/pico/tools/ApplicationCreatorDefault.java
Labels: 4.x, pico, OCA Verified

#7156 module-info parsing
  pico/tests/resources-pico/src/test/resources/expected/module-info.java._pico_
  pico/tests/resources-pico/src/test/resources/expected/tests-module-info.java._pico_
  pico/tools/src/main/java/io/helidon/pico/tools/AbstractCreator.java
  pico/tools/src/main/java/io/helidon/pico/tools/ModuleInfoDescriptorBlueprint.java
  pico/tools/src/main/java/io/helidon/pico/tools/ModuleInfoDescriptorSupport.java
  pico/tools/src/main/java/io/helidon/pico/tools/ModuleInfoItemBlueprint.java
  pico/tools/src/test/java/io/helidon/pico/tools/ModuleInfoDescriptorTest.java
  pico/tools/src/test/resources/testsubjects/m0._java_
Labels: 4.x, pico, OCA Verified

#7163 Upgrade to OCI SDK 3.12.1
  archetypes/helidon/src/main/archetype/mp/oci/files/server/src/test/java/__pkg__/server/GreetResourceMockedTest.java.mustache
  dependencies/pom.xml
  integrations/oci/metrics/cdi/src/test/java/io/helidon/integrations/oci/metrics/cdi/OciMetricsCdiExtensionTest.java
Labels: OCA Verified

#7155 Attempt to do type regeneration turned into an error condition instead of being logged
  pico/maven-plugin/src/main/java/io/helidon/pico/maven/plugin/AbstractApplicationCreatorMojo.java
  pico/processor/src/main/java/io/helidon/pico/processor/CustomAnnotationProcessor.java
  pico/processor/src/main/java/io/helidon/pico/processor/PicoAnnotationProcessor.java
  pico/tools/src/main/java/io/helidon/pico/tools/ActivatorCreatorDefault.java
  pico/tools/src/main/java/io/helidon/pico/tools/CodeGenFiler.java
  pico/tools/src/main/java/io/helidon/pico/tools/ExternalModuleCreatorDefault.java
  pico/tools/src/main/java/io/helidon/pico/tools/GeneralCreatorRequestBlueprint.java
  pico/tools/src/main/java/io/helidon/pico/tools/ServicesToProcess.java
  pico/tools/src/test/java/io/helidon/pico/tools/ActivatorCreatorDefaultTest.java
  pico/tools/src/test/java/io/helidon/pico/tools/ApplicationCreatorDefaultTest.java
Labels: 4.x, pico, OCA Verified

#7169 4.x: Helidon connector configuration and redirects
  jersey/connector/pom.xml
  jersey/connector/src/main/java/io/helidon/jersey/connector/HelidonConnector.java
  jersey/connector/src/main/java/io/helidon/jersey/connector/HelidonProperties.java
  jersey/connector/src/main/java/module-info.java
  jersey/connector/src/test/java/io/helidon/jersey/connector/ConfigTest.java
  jersey/connector/src/test/java/io/helidon/jersey/connector/TimeoutTest.java
  jersey/connector/src/test/resources/application.yaml
  nima/webclient/webclient/src/main/java/io/helidon/nima/webclient/http1/ClientRequestImpl.java
  nima/webclient/webclient/src/main/java/io/helidon/nima/webclient/http1/Http1ClientRequest.java
Labels: jax-rs, 4.x, OCA Verified

#6946 Draft of the wls-helidon integration for 2.x
  docs/mp/integration/wls.adoc
  docs/sitegen.yaml
Labels: docs, 2.x, OCA Verified

#7177 Fix archetype build
  archetypes/helidon/pom.xml
  archetypes/helidon/src/main/cli/versions.xml.mustache
Labels: archetypes, 4.x, OCA Verified

#7179 2.x fix jenkins env
  etc/scripts/includes/pipeline-env.sh
  etc/scripts/release.sh
Labels: build, 2.x, OCA Verified

#7178 Fix path handling for metrics observe provider
  nima/observe/metrics/src/main/java/io/helidon/nima/observe/metrics/MetricsFeature.java
  nima/observe/metrics/src/main/java/io/helidon/nima/observe/metrics/MetricsObserveProvider.java
Labels: OCA Verified

#7175 3.x: Upgrade Jersey to 3.0.11
  dependencies/pom.xml
  integrations/oci/sdk/cdi/pom.xml
Labels: dependencies, 3.x, OCA Verified

#7185 JWK signature now follows P1363 pair format
  security/jwt/src/main/java/io/helidon/security/jwt/jwk/JwkEC.java
Labels: OCA Verified

#7196 JWK signature now follows P1363 pair format - 4.x backport
  security/jwt/src/main/java/io/helidon/security/jwt/jwk/JwkEC.java
Labels: OCA Verified

#6327 Nima custom archetype
  archetypes/helidon/filters.properties
  archetypes/helidon/pom.xml
  archetypes/helidon/src/main/archetype/common/extra.xml
  archetypes/helidon/src/main/archetype/common/files/README.md.mustache
  archetypes/helidon/src/main/archetype/common/media.xml
  archetypes/helidon/src/main/archetype/common/observability.xml
  archetypes/helidon/src/main/archetype/nima/common/common-nima.xml
  archetypes/helidon/src/main/archetype/nima/common/files/src/main/java/__pkg__/Main.java.mustache
  archetypes/helidon/src/main/archetype/nima/custom/custom-nima.xml
  archetypes/helidon/src/main/archetype/nima/custom/extra.xml
  archetypes/helidon/src/main/archetype/nima/custom/files/src/main/java/__pkg__/FileService.java.multipart.mustache
  archetypes/helidon/src/main/archetype/nima/custom/files/src/main/java/__pkg__/FtService.java.mustache
  archetypes/helidon/src/main/archetype/nima/custom/files/src/main/java/__pkg__/GreetService.java.json.mustache
  archetypes/helidon/src/main/archetype/nima/custom/files/src/main/java/__pkg__/GreetService.java.jsonp.mustache
  archetypes/helidon/src/main/archetype/nima/custom/files/src/main/java/__pkg__/Message.java.json.mustache
  archetypes/helidon/src/main/archetype/nima/custom/files/src/main/resources/WEB/index.html
  archetypes/helidon/src/main/archetype/nima/custom/observability.xml
  archetypes/helidon/src/main/archetype/nima/nima.xml
  archetypes/helidon/src/main/archetype/nima/quickstart/quickstart-nima.xml
Labels: archetypes, OCA Verified

#7198 Injection Stacking
  inject/tests/resources-inject/src/main/java/io/helidon/inject/tests/inject/stacking/CommonContract.java
  inject/tests/resources-inject/src/main/java/io/helidon/inject/tests/inject/stacking/CommonContractImpl.java
  inject/tests/resources-inject/src/main/java/io/helidon/inject/tests/inject/stacking/Intercepted.java
  inject/tests/resources-inject/src/main/java/io/helidon/inject/tests/inject/stacking/MostOuterCommonContractImpl.java
  inject/tests/resources-inject/src/main/java/io/helidon/inject/tests/inject/stacking/OuterCommonContractImpl.java
  inject/tests/resources-inject/src/test/java/io/helidon/inject/tests/inject/TestingSingleton.java
  inject/tests/resources-inject/src/test/java/io/helidon/inject/tests/inject/stacking/InjectionOfCommonContractStackingTest.java
  inject/tests/resources-inject/src/test/java/io/helidon/inject/tests/inject/tbox/ToolBoxTest.java
Labels: 4.x, pico, OCA Verified

#7191 4.x: Update CHANGELOG to prep for 4.0.0-M1 release
  CHANGELOG.md
Labels: 4.x, OCA Verified

#7208 7020 GRPC outbound flow-control
  nima/grpc/webserver/src/main/java/io/helidon/nima/grpc/webserver/GrpcProtocolHandler.java
  nima/grpc/webserver/src/main/java/io/helidon/nima/grpc/webserver/GrpcProtocolSelector.java
  nima/http2/http2/src/main/java/io/helidon/nima/http2/ConnectionFlowControl.java
  nima/http2/http2/src/main/java/io/helidon/nima/http2/StreamFlowControl.java
  nima/http2/webclient/src/main/java/io/helidon/nima/http2/webclient/Http2ClientStream.java
  nima/http2/webserver/src/main/java/io/helidon/nima/http2/webserver/Http2ConfigBlueprint.java
  nima/http2/webserver/src/main/java/io/helidon/nima/http2/webserver/Http2Connection.java
  nima/http2/webserver/src/main/java/io/helidon/nima/http2/webserver/Http2Stream.java
  nima/http2/webserver/src/main/java/io/helidon/nima/http2/webserver/spi/Http2SubProtocolSelector.java
  nima/tests/integration/http2/server/src/test/java/io/helidon/nima/tests/integration/http2/webserver/FlowControlTest.java
Labels: OCA Verified

#7211 Upgrade to OCI SDK 3.12.1 (#7163)
  archetypes/helidon/src/main/archetype/mp/oci/files/server/src/test/java/__pkg__/server/GreetResourceMockedTest.java.mustache
  dependencies/pom.xml
  integrations/oci/metrics/cdi/src/test/java/io/helidon/integrations/oci/metrics/cdi/OciMetricsCdiExtensionTest.java
Labels: OCA Verified

#7200 LoomServer parallel listener start
  inject/api/src/main/java/io/helidon/inject/api/InjectionServices.java
  inject/runtime/src/main/java/io/helidon/inject/runtime/DefaultInjectionServices.java
  inject/runtime/src/main/java/io/helidon/inject/runtime/DefaultServices.java
  inject/tests/resources-inject/src/test/java/io/helidon/inject/tests/inject/tbox/ToolBoxTest.java
  inject/tests/runtime/src/test/java/io/helidon/inject/runtime/LockContentionTest.java
  nima/webserver/webserver/src/main/java/io/helidon/nima/webserver/LoomServer.java
Labels: 4.x, pico, OCA Verified

#7231 Issue #7187 - Blocking DBClient Part 2
  examples/dbclient/common/src/main/java/io/helidon/examples/dbclient/common/AbstractPokemonService.java
  examples/dbclient/pokemons/src/main/java/io/helidon/examples/dbclient/pokemons/InitializeDb.java
Labels: OCA Verified

#7235 3.x remove license headers in archetype generated files
  archetypes/helidon/src/main/archetype/mp/database/files/src/main/resources/META-INF/persistence.xml.mustache
  archetypes/helidon/src/main/archetype/mp/database/files/src/main/resources/hibernate.properties.mustache
Labels: OCA Verified

#7236 4.x remove license headers in archetype generated files
  archetypes/helidon/src/main/archetype/mp/database/files/src/main/resources/META-INF/persistence.xml.mustache
  archetypes/helidon/src/main/archetype/mp/database/files/src/main/resources/hibernate.properties.mustache
Labels: OCA Verified

#7233 Archetypes: Remove license from generated files (2.x)
  archetypes/database-se/src/main/resources/pom.xml.mustache
  archetypes/quickstart-mp/src/main/resources/app.yaml.mustache
  archetypes/quickstart-mp/src/main/resources/pom.xml.mustache
  archetypes/quickstart-se/src/main/resources/app.yaml.mustache
Labels: OCA Verified

#7217 Add app.yaml to quickstart
  archetypes/helidon/src/main/archetype/common/presets.xml
Labels: archetypes, 4.x, OCA Verified

#7216 Add app.yaml to quickstart
  archetypes/helidon/src/main/archetype/common/presets.xml
Labels: 3.x, archetypes, OCA Verified

#7197 JWK signature now follows P1363 pair format - 2.x backport
  security/jwt/src/main/java/io/helidon/security/jwt/jwk/JwkEC.java
Labels: OCA Verified

#7167 [3.x] - Update Tracing Context on return
  tracing/opentracing/src/main/java/io/helidon/tracing/opentracing/OpenTracingSpan.java
Labels: tracing, 3.x, OCA Verified

#6679 Several Refactor commits to improve code readability
  microprofile/fault-tolerance/src/main/java/io/helidon/microprofile/faulttolerance/FaultToleranceExtension.java
  microprofile/messaging/core/src/main/java/io/helidon/microprofile/messaging/ChannelRouter.java
  microprofile/server/src/main/java/io/helidon/microprofile/server/ServerCdiExtension.java
  microprofile/weld/weld-core-impl/src/main/java/org/jboss/weld/bean/proxy/ProxyFactory.java
  openapi/src/main/java/io/helidon/openapi/ExpandedTypeDescription.java
  openapi/src/main/java/io/helidon/openapi/OpenAPISupport.java
Labels: OCA Verified

#7245 Added support for WS endpoints in application scope
  microprofile/websocket/src/main/java/io/helidon/microprofile/tyrus/HelidonComponentProvider.java
  microprofile/websocket/src/test/java/io/helidon/microprofile/tyrus/ApplicationScopeTest.java
Labels: bug, 3.x, OCA Verified

#7190 Support for proxy config properties in client and request
  jersey/connector/src/main/java/io/helidon/jersey/connector/HelidonConnector.java
  jersey/connector/src/main/java/io/helidon/jersey/connector/ProxyBuilder.java
  jersey/connector/src/test/java/io/helidon/jersey/connector/ConfigTest.java
  nima/webclient/webclient/src/main/java/io/helidon/nima/webclient/Proxy.java
Labels: jax-rs, webclient, 4.x, OCA Verified

#7246 Issue #7230 - JDBC type specific setters based on EclipseLink
  dbclient/dbclient/src/main/java/io/helidon/dbclient/DbClientContext.java
  dbclient/dbclient/src/main/java/io/helidon/dbclient/DbExecuteBase.java
  dbclient/dbclient/src/main/java/io/helidon/dbclient/DbExecuteContext.java
  dbclient/dbclient/src/main/java/io/helidon/dbclient/DbStatementBase.java
  dbclient/jdbc/pom.xml
  dbclient/jdbc/src/main/java/io/helidon/dbclient/jdbc/JdbcClient.java
  dbclient/jdbc/src/main/java/io/helidon/dbclient/jdbc/JdbcClientBuilder.java
  dbclient/jdbc/src/main/java/io/helidon/dbclient/jdbc/JdbcClientContext.java
  dbclient/jdbc/src/main/java/io/helidon/dbclient/jdbc/JdbcExecute.java
  dbclient/jdbc/src/main/java/io/helidon/dbclient/jdbc/JdbcExecuteContext.java
  dbclient/jdbc/src/main/java/io/helidon/dbclient/jdbc/JdbcParametersConfigBlueprint.java
  dbclient/jdbc/src/main/java/io/helidon/dbclient/jdbc/JdbcStatement.java
  dbclient/jdbc/src/main/java/io/helidon/dbclient/jdbc/JdbcStatementDml.java
  dbclient/jdbc/src/main/java/io/helidon/dbclient/jdbc/JdbcStatementGet.java
  dbclient/jdbc/src/main/java/io/helidon/dbclient/jdbc/JdbcStatementQuery.java
  dbclient/jdbc/src/main/java/io/helidon/dbclient/jdbc/JdbcTransaction.java
  dbclient/jdbc/src/main/java/io/helidon/dbclient/jdbc/JdbcTransactionStatement.java
  dbclient/jdbc/src/main/java/io/helidon/dbclient/jdbc/JdbcTransactionStatementDml.java
  dbclient/jdbc/src/main/java/io/helidon/dbclient/jdbc/JdbcTransactionStatementGet.java
  dbclient/jdbc/src/main/java/io/helidon/dbclient/jdbc/JdbcTransactionStatementQuery.java
  dbclient/jdbc/src/main/java/module-info.java
  dbclient/jdbc/src/test/java/io/helidon/dbclient/jdbc/JdbcClientBuilderTest.java
  dbclient/jdbc/src/test/resources/params.yaml
Labels: OCA Verified

#7232 Archetype : generate module-info file
  archetypes/helidon/src/main/archetype/common/common.xml
  archetypes/helidon/src/main/archetype/common/extra.xml
  archetypes/helidon/src/main/archetype/common/files/src/main/java/module-info.java.mustache
  archetypes/helidon/src/main/archetype/common/media.xml
  archetypes/helidon/src/main/archetype/common/observability.xml
  archetypes/helidon/src/main/archetype/mp/common/common-mp.xml
  archetypes/helidon/src/main/archetype/mp/custom/custom-mp.xml
  archetypes/helidon/src/main/archetype/mp/custom/database.xml
  archetypes/helidon/src/main/archetype/mp/database/database-mp.xml
  archetypes/helidon/src/main/archetype/mp/quickstart/quickstart-mp.xml
  archetypes/helidon/src/main/archetype/nima/common/common-nima.xml
  archetypes/helidon/src/main/archetype/nima/custom/custom-nima.xml
  archetypes/helidon/src/main/archetype/nima/custom/observability.xml
  archetypes/helidon/src/main/archetype/nima/quickstart/quickstart-nima.xml
Labels: archetypes, 4.x, OCA Verified

#7253 4.x: Archetype: remove unused file
  archetypes/helidon/src/main/archetype/mp/database/files/src/main/resources/META-INF/native-image/native-image.properties
Labels: archetypes, 4.x, OCA Verified

#7252 3.x: Archetype : generate module-info file
  archetypes/helidon/src/main/archetype/common/common.xml
  archetypes/helidon/src/main/archetype/common/extra.xml
  archetypes/helidon/src/main/archetype/common/files/src/main/java/module-info.java.mustache
  archetypes/helidon/src/main/archetype/common/media.xml
  archetypes/helidon/src/main/archetype/common/observability.xml
  archetypes/helidon/src/main/archetype/common/security.xml
  archetypes/helidon/src/main/archetype/mp/common/common-mp.xml
  archetypes/helidon/src/main/archetype/mp/custom/custom-mp.xml
  archetypes/helidon/src/main/archetype/mp/custom/database.xml
  archetypes/helidon/src/main/archetype/mp/database/database-mp.xml
  archetypes/helidon/src/main/archetype/mp/quickstart/quickstart-mp.xml
  archetypes/helidon/src/main/archetype/se/common/common-se.xml
  archetypes/helidon/src/main/archetype/se/custom/custom-se.xml
  archetypes/helidon/src/main/archetype/se/custom/database.xml
Labels: 3.x, archetypes, OCA Verified

#7254 3.x: Upgrade to oci sdk 3.21.0
  dependencies/pom.xml
Labels: dependencies, 3.x, OCA Verified

#7250 Remove license from generated hibernate.properties (2.x)
  archetypes/database-mp/src/main/resources/src/main/resources/hibernate.properties
Labels: OCA Verified

#7238 3.x: upgrade okio to 3.4.0
  applications/parent/pom.xml
  dependencies/pom.xml
  etc/dependency-check-suppression.xml
  tracing/jaeger/pom.xml
  tracing/jaeger/src/main/java/module-info.java
Labels: dependencies, 3.x, OCA Verified

#7257 3.x: Suppress disputed Jackson positive
  etc/dependency-check-suppression.xml
Labels: 3.x, OCA Verified

#7258 4.x: Upgrade Jersey to 3.1.3
  dependencies/pom.xml
Labels: dependencies, 4.x, OCA Verified

#6955 Add configuration support for EXECUTOR_SHUTDOWN_MILLIS
  nima/webserver/webserver/src/main/java/io/helidon/nima/webserver/ListenerConfigBlueprint.java
  nima/webserver/webserver/src/main/java/io/helidon/nima/webserver/ServerListener.java
  nima/webserver/webserver/src/test/java/io/helidon/nima/webserver/ListenerConfigTest.java
  nima/webserver/webserver/src/test/resources/application.yaml
Labels: OCA Verified

#7260 2.x: Add suppressions for graalvm and jackson
  etc/dependency-check-suppression.xml
Labels: 2.x, OCA Verified

#7262 4.x: Upgrade okio and oci-sdk
  applications/parent/pom.xml
  dependencies/pom.xml
Labels: dependencies, 4.x, OCA Verified

#7259 2.x: upgrade okio to 3.4.0
  applications/parent/pom.xml
  dependencies/pom.xml
  tracing/jaeger/pom.xml
  tracing/jaeger/src/main/java/module-info.java
Labels: 2.x, dependencies, OCA Verified

#7266 4.x: Add suppressions for Jackson and graal-sdk
  etc/dependency-check-suppression.xml
  pom.xml
Labels: 4.x, OCA Verified

#7267 1.x: Upgrade grpc, jackson, okio, netty and add a couple suppressions
  applications/pom.xml
  dependencies/pom.xml
  etc/dependency-check-suppression.xml
  microprofile/tests/tck/tck-openapi/pom.xml
  pom.xml
Labels: 1.x, dependencies, OCA Verified

#7263 Remove VirtualExecutorUtil.java
  common/configurable/src/main/java/io/helidon/common/configurable/ObserverManager.java
  common/configurable/src/main/java/io/helidon/common/configurable/ThreadPoolSupplier.java
  common/configurable/src/main/java/io/helidon/common/configurable/VirtualExecutorUtil.java
Labels: OCA Verified
