Repository helidon-io/helidon, pull requests merged in 2024-04, with the labels that each got.

#8588 Add `unwrap` support to metrics builders
  docs/src/main/asciidoc/se/metrics/metrics.adoc
  metrics/api/src/main/java/io/helidon/metrics/api/Meter.java
  metrics/api/src/main/java/io/helidon/metrics/api/NoOpMeter.java
  metrics/providers/micrometer/src/main/java/io/helidon/metrics/providers/micrometer/MMeter.java
  metrics/providers/micrometer/src/test/java/io/helidon/metrics/providers/micrometer/TestCounter.java
  metrics/providers/micrometer/src/test/java/io/helidon/metrics/providers/micrometer/TestDistributionSummary.java
  metrics/providers/micrometer/src/test/java/io/helidon/metrics/providers/micrometer/TestGauge.java
  metrics/providers/micrometer/src/test/java/io/helidon/metrics/providers/micrometer/TestTimer.java
Labels: OCA Verified

#8592 3.x: Fix wrong example for Config.onChange (#7716)
  config/config/src/main/java/io/helidon/config/Config.java
  docs/se/config/mutability-support.adoc
Labels: OCA Verified

#8595 1.x: upgrade netty to 4.1.108.Final
  dependencies/pom.xml
  etc/scripts/owasp-dependency-check.sh
  pom.xml
  webserver/webserver/src/main/resources/META-INF/native-image/native-image.properties
Labels: 1.x, dependencies, OCA Verified

#8598 2.x: Fix attributions for jsr305
  THIRD_PARTY_LICENSES.txt
  etc/HELIDON_THIRD_PARTY_LICENSES.xml
Labels: 2.x, OCA Verified

#8599 [4.x]: Fix static content sending 304 with entity.
  http/http/src/main/java/io/helidon/http/HttpException.java
  webclient/http1/src/main/java/io/helidon/webclient/http1/RedirectionProcessor.java
  webserver/static-content/src/main/java/io/helidon/webserver/staticcontent/StaticContentHandler.java
  webserver/static-content/src/test/java/io/helidon/webserver/staticcontent/StaticContentHandlerTest.java
  webserver/tests/static-content/src/test/java/io/helidon/webserver/tests/staticcontent/StaticContentTest.java
  webserver/webserver/src/main/java/io/helidon/webserver/http/DirectHandlers.java
  webserver/webserver/src/main/java/io/helidon/webserver/http/ErrorHandlers.java
Labels: bug, webserver, 4.x, OCA Verified

#8602 4.x: Update attributions for reactive-streams to be MIT-0
  THIRD_PARTY_LICENSES.txt
  etc/HELIDON_THIRD_PARTY_LICENSES.xml
Labels: 4.x, OCA Verified

#8601 3.x: Update attributions for reactive-streams to be MIT-0
  THIRD_PARTY_LICENSES.txt
  etc/HELIDON_THIRD_PARTY_LICENSES.xml
Labels: 3.x, OCA Verified

#8600 2.x: Update attributions for reactive-streams to be MIT-0
  THIRD_PARTY_LICENSES.txt
  etc/HELIDON_THIRD_PARTY_LICENSES.xml
Labels: 2.x, OCA Verified

#8603 [4.x] If there is no configuration of oidc provider, it is considered disabled
  security/providers/oidc/src/main/java/io/helidon/security/providers/oidc/OidcFeature.java
  tests/integration/mp-gh-8493/pom.xml
  tests/integration/mp-gh-8493/src/main/java/io/helidon/tests/integration/gh8493/Gh8493Resource.java
  tests/integration/mp-gh-8493/src/main/resources/META-INF/beans.xml
  tests/integration/mp-gh-8493/src/main/resources/logging.properties
  tests/integration/mp-gh-8493/src/test/java/io/helidon/tests/integration/gh8493/Gh8493Test.java
  tests/integration/pom.xml
Labels: security, config, 4.x, OCA Verified

#8523 4.x: Make HttpRouting an interface
  microprofile/websocket/src/main/java/io/helidon/microprofile/tyrus/TyrusRouting.java
  webserver/grpc/src/main/java/io/helidon/webserver/grpc/GrpcRouting.java
  webserver/webserver/src/main/java/io/helidon/webserver/RouterImpl.java
  webserver/webserver/src/main/java/io/helidon/webserver/Routing.java
  webserver/webserver/src/main/java/io/helidon/webserver/http/HttpRouting.java
  webserver/webserver/src/main/java/io/helidon/webserver/http/HttpRoutingImpl.java
  webserver/websocket/src/main/java/io/helidon/webserver/websocket/WsRouting.java
Labels: webserver, design, contribution, OCA Verified

#8606 4.x: Upgrade core profile tests to version 10.0.3
  pom.xml
Labels: OCA Verified

#8594 Adds support for users to control the outcome of a WebSocket upgrade request
  webserver/websocket/src/main/java/io/helidon/webserver/websocket/WebSocketHandler.java
  webserver/websocket/src/main/java/io/helidon/webserver/websocket/WebSocketUpgradeCodec.java
  webserver/websocket/src/test/java/io/helidon/webserver/websocket/test/EchoEndpoint.java
  webserver/websocket/src/test/java/io/helidon/webserver/websocket/test/HandshakeFailureTest.java
  webserver/websocket/src/test/java/io/helidon/webserver/websocket/test/SocketHttpClient.java
Labels: 3.x, websocket, OCA Verified

#8597 2.x: Fix wrong example for Config.onChange (#8596)
  config/config/src/main/java/io/helidon/config/Config.java
  docs/se/config/05_mutability-support.adoc
Labels: OCA Verified

#8576 4.x: threading example
  examples/webserver/threads/README.md
  examples/webserver/threads/pom.xml
  examples/webserver/threads/src/main/java/io/helidon/examples/webserver/threads/Main.java
  examples/webserver/threads/src/main/java/io/helidon/examples/webserver/threads/ThreadService.java
  examples/webserver/threads/src/main/java/io/helidon/examples/webserver/threads/package-info.java
  examples/webserver/threads/src/main/resources/application.yaml
  examples/webserver/threads/src/main/resources/logging.properties
  examples/webserver/threads/src/test/java/io/helidon/examples/webserver/threads/MainTest.java
Labels: examples, webserver, 4.x, OCA Verified

#8610 4.x: Upgrade upload-artifact to v4
  .github/workflows/release.yaml
Labels: build, 4.x, OCA Verified

#8611 4.x: Upgrade oci-sdk to 3.39.0
  dependencies/pom.xml
Labels: 4.x, OCA Verified

#8621 3.x: Upgrade oci sdk to 3.39.0
  dependencies/pom.xml
Labels: dependencies, 3.x, OCI, OCA Verified

#8622 2.x: Upgrade OCI sdk to 3.39.0
  archetypes/oci-mp/src/main/resources/server/src/test/java/__pkg__/server/GreetResourceMockedTest.java.mustache
  dependencies/pom.xml
Labels: 2.x, dependencies, OCI, OCA Verified

#8626 [2.x] Oidc feature is not failing if not configured.
  security/providers/oidc/src/main/java/io/helidon/security/providers/oidc/OidcSupport.java
  tests/integration/mp-gh-8493/pom.xml
  tests/integration/mp-gh-8493/src/main/java/io/helidon/tests/integration/gh8493/Gh8493Resource.java
  tests/integration/mp-gh-8493/src/main/resources/META-INF/beans.xml
  tests/integration/mp-gh-8493/src/main/resources/logging.properties
  tests/integration/mp-gh-8493/src/test/java/io/helidon/tests/integration/gh8493/Gh8493Test.java
  tests/integration/pom.xml
Labels: security, 2.x, backport, OCA Verified

#8625 [3.x] Oidc feature is not failing if not configured.
  security/providers/oidc/src/main/java/io/helidon/security/providers/oidc/OidcSupport.java
  tests/integration/mp-gh-8493/pom.xml
  tests/integration/mp-gh-8493/src/main/java/io/helidon/tests/integration/gh8493/Gh8493Resource.java
  tests/integration/mp-gh-8493/src/main/resources/META-INF/beans.xml
  tests/integration/mp-gh-8493/src/main/resources/logging.properties
  tests/integration/mp-gh-8493/src/test/java/io/helidon/tests/integration/gh8493/Gh8493Test.java
  tests/integration/pom.xml
Labels: security, 3.x, backport, OCA Verified

#7087 2.x: resolve native-image warnings after Netty upgrade
  integrations/graal/native-image-extension/pom.xml
  integrations/graal/native-image-extension/src/main/resources/META-INF/native-image/io.helidon/helidon/native-image.properties
Labels: build, 2.x, native-image, OCA Verified

#7084 3.x: resolve native-image warnings after Netty upgrade
  integrations/graal/native-image-extension/pom.xml
  integrations/graal/native-image-extension/src/main/resources/META-INF/native-image/io.helidon.integrations.graal/helidon-graal-native-image-extension/native-image.properties
Labels: build, dependencies, native-image, 3.x, OCA Verified

#8641 4.x: Upgrade github checkout action to v4
  .github/workflows/assign-issue-to-project.yml
  .github/workflows/create-backport-issues.yml
Labels: build, 4.x, OCA Verified

#8640 3.x: upgrade more github actions to v4
  .github/workflows/assign-issue-to-project.yml
  .github/workflows/create-backport-issues.yml
  .github/workflows/release.yaml
  .github/workflows/validate.yaml
Labels: build, 3.x, OCA Verified

#8639 2.x: Upgrade upload-artifact github action to v4
  .github/workflows/release.yaml
  .github/workflows/validate.yml
Labels: build, 2.x, OCA Verified

#8642 Addresses a shortcoming of the Universal Connection Pool pool creation logic in certain test scenarios
  integrations/cdi/datasource-ucp/src/main/java/io/helidon/integrations/datasource/ucp/cdi/UCPBackedDataSourceExtension.java
  integrations/cdi/datasource-ucp/src/test/java/io/helidon/integrations/datasource/ucp/cdi/TestUcpApi.java
Labels: enhancement, MP, P4, jpa/jta, java, 4.x, OCA Verified

#8486 Retires dependency of ...cdi.OciExtension on ...runtime.OciExtension
  etc/javadoc/oci-addons-oke-workload-identity/package-list
  etc/javadoc/oci-common/package-list
  integrations/oci/sdk/cdi/etc/spotbugs/exclude.xml
  integrations/oci/sdk/cdi/pom.xml
  integrations/oci/sdk/cdi/src/main/java/io/helidon/integrations/oci/sdk/cdi/AdpStrategyDescriptors.java
  integrations/oci/sdk/cdi/src/main/java/io/helidon/integrations/oci/sdk/cdi/AdpSupplier.java
  integrations/oci/sdk/cdi/src/main/java/io/helidon/integrations/oci/sdk/cdi/AdpSupplierSelector.java
  integrations/oci/sdk/cdi/src/main/java/io/helidon/integrations/oci/sdk/cdi/CascadingAdpSupplier.java
  integrations/oci/sdk/cdi/src/main/java/io/helidon/integrations/oci/sdk/cdi/ConfigAccessor.java
  integrations/oci/sdk/cdi/src/main/java/io/helidon/integrations/oci/sdk/cdi/ConfigFileAdpSupplier.java
  integrations/oci/sdk/cdi/src/main/java/io/helidon/integrations/oci/sdk/cdi/ConfigFiles.java
  integrations/oci/sdk/cdi/src/main/java/io/helidon/integrations/oci/sdk/cdi/EmptyAdpSupplier.java
  integrations/oci/sdk/cdi/src/main/java/io/helidon/integrations/oci/sdk/cdi/InstancePrincipalsAdpSupplier.java
  integrations/oci/sdk/cdi/src/main/java/io/helidon/integrations/oci/sdk/cdi/MicroProfileConfigConfigAccessor.java
  integrations/oci/sdk/cdi/src/main/java/io/helidon/integrations/oci/sdk/cdi/OciConfig.java
  integrations/oci/sdk/cdi/src/main/java/io/helidon/integrations/oci/sdk/cdi/OciExtension.java
  integrations/oci/sdk/cdi/src/main/java/io/helidon/integrations/oci/sdk/cdi/OkeWorkloadIdentityAdpSupplier.java
  integrations/oci/sdk/cdi/src/main/java/io/helidon/integrations/oci/sdk/cdi/ResourcePrincipalAdpSupplier.java
  integrations/oci/sdk/cdi/src/main/java/io/helidon/integrations/oci/sdk/cdi/SessionTokenAdpSupplier.java
  integrations/oci/sdk/cdi/src/main/java/io/helidon/integrations/oci/sdk/cdi/SimpleAdpSupplier.java
  integrations/oci/sdk/cdi/src/main/java/module-info.java
  integrations/oci/sdk/cdi/src/test/java/io/helidon/integrations/oci/sdk/cdi/TestInstancePrincipalsAuthenticationDetailsProvider.java
  integrations/oci/sdk/cdi/src/test/java/io/helidon/integrations/oci/sdk/cdi/TestOciSdkRuntimeOciExtension.java
  integrations/oci/sdk/cdi/src/test/java/io/helidon/integrations/oci/sdk/cdi/TestSessionTokenAuthenticationDetailsProvider.java
  pom.xml
Labels: enhancement, MP, P3, cdi, integration, OCI, java, 4.x, OCA Verified

#8624 4.x: Remove unused private methods from HelloWorldAsyncResponseWithRestRequestTest
  microprofile/metrics/src/test/java/io/helidon/microprofile/metrics/HelloWorldAsyncResponseWithRestRequestTest.java
Labels: OCA Verified

#8634 4.x: ErrorHandlers class swallows exception object if response can't be reset
  webserver/webserver/src/main/java/io/helidon/webserver/http/ErrorHandlers.java
  webserver/webserver/src/test/java/io/helidon/webserver/http/ErrorHandlersTest.java
Labels: OCA Verified

#8628 Client header duplication fixed
  webclient/api/src/main/java/io/helidon/webclient/api/ClientRequestBase.java
  webclient/tests/webclient/src/test/java/io/helidon/webclient/tests/GreetService.java
  webclient/tests/webclient/src/test/java/io/helidon/webclient/tests/HeaderTest.java
Labels: OCA Verified

#8648 Generated builders service discovery honoring
  builder/codegen/src/main/java/io/helidon/builder/codegen/GenerateAbstractBuilder.java
  builder/tests/builder/src/test/java/io/helidon/builder/test/ProviderTest.java
Labels: OCA Verified

#8179 [2.x] Helidon Arquillian module should only depend on MP core #7613
  microprofile/tests/arquillian/pom.xml
  microprofile/tests/arquillian/src/main/java/io/helidon/microprofile/arquillian/HelidonDeployableContainer.java
  microprofile/tests/tck/tck-fault-tolerance/pom.xml
  microprofile/tests/tck/tck-health/pom.xml
  microprofile/tests/tck/tck-jwt-auth/pom.xml
  microprofile/tests/tck/tck-lra/pom.xml
  microprofile/tests/tck/tck-openapi/pom.xml
  microprofile/tests/tck/tck-opentracing/pom.xml
  microprofile/tests/tck/tck-reactive-operators/pom.xml
  microprofile/tests/tck/tck-rest-client/pom.xml
Labels: OCA Verified

#8650 4.x: Remove dependency on jakarta.activation-api as no longer needed
  archetypes/archetypes/src/main/archetype/mp/common/common-mp.xml
  microprofile/telemetry/pom.xml
Labels: 4.x, OCA Verified

#8654 3.x: Remove dependency on jakarta.activation-api
  archetypes/helidon/src/main/archetype/mp/common/common-mp.xml
  grpc/metrics/pom.xml
  integrations/micrometer/cdi/pom.xml
  microprofile/fault-tolerance/pom.xml
  microprofile/grpc/server/pom.xml
  microprofile/metrics/pom.xml
  microprofile/tests/tck/tck-fault-tolerance/pom.xml
  microprofile/tests/tck/tck-health/pom.xml
  microprofile/tests/tck/tck-metrics/pom.xml
  microprofile/tests/tck/tck-openapi/pom.xml
  microprofile/tracing/pom.xml
  security/integration/grpc/pom.xml
  security/integration/webserver/pom.xml
  security/providers/http-auth/pom.xml
  service-common/rest-cdi/pom.xml
  tests/integration/jpa/simple/pom.xml
  tests/integration/oidc/pom.xml
  tests/integration/zipkin-mp-2.2/pom.xml
  webserver/jersey/pom.xml
  webserver/webserver/pom.xml
Labels: dependencies, 3.x, OCA Verified

#8657 2.x: Further removal of dependencies on jakarta.activation-api
  examples/istio/helidon-config/pom.xml
  examples/istio/helidon-jpa/pom.xml
  examples/jbatch/pom.xml
  examples/microprofile/http-status-count-mp/pom.xml
  grpc/metrics/pom.xml
  integrations/cdi/jpa-cdi/pom.xml
  integrations/micrometer/cdi/pom.xml
  microprofile/fault-tolerance/pom.xml
  microprofile/grpc/server/pom.xml
  microprofile/metrics/pom.xml
  microprofile/tests/tck/tck-fault-tolerance/pom.xml
  microprofile/tests/tck/tck-health/pom.xml
  microprofile/tests/tck/tck-metrics/pom.xml
  microprofile/tests/tck/tck-openapi/pom.xml
  microprofile/tracing/pom.xml
  security/integration/grpc/pom.xml
  security/integration/webserver/pom.xml
  security/providers/http-auth/pom.xml
  service-common/rest-cdi/pom.xml
  tests/integration/jpa/simple/pom.xml
  tests/integration/oidc/pom.xml
  tests/integration/zipkin-mp-2.2/pom.xml
  webserver/jersey/pom.xml
  webserver/webserver/pom.xml
Labels: 2.x, dependencies, OCA Verified

#8662 Use delegation instead of inheritance from BufferedOutputStream
  webserver/webserver/src/main/java/io/helidon/webserver/http1/Http1ServerResponse.java
  webserver/webserver/src/test/java/io/helidon/webserver/http1/ClosingBufferedOutputStreamTest.java
Labels: performance, 4.x, OCA Verified

#8556 4.x: Fix wrong description for bean validation annotations (#8505)
  docs/src/main/asciidoc/mp/beanvalidation.adoc
Labels: OCA Verified

#8665 4.x: Upgrade kafka-clients to 3.6.2
  dependencies/pom.xml
Labels: dependencies, 4.x, OCA Verified

#8664 2.x: Upgrade kafka-clients to 3.6.2
  dependencies/pom.xml
Labels: 2.x, dependencies, OCA Verified

#8663 3.x: Upgrade kafka-clients to 3.6.2
  dependencies/pom.xml
Labels: dependencies, messaging, 3.x, OCA Verified

#8669 4.x: Proper handling of invalid Accept types
  http/http/src/main/java/io/helidon/http/ServerRequestHeaders.java
  http/http/src/main/java/io/helidon/http/ServerRequestHeadersImpl.java
  webserver/observe/metrics/src/main/java/io/helidon/webserver/observe/metrics/MetricsFeature.java
  webserver/observe/metrics/src/test/java/io/helidon/webserver/observe/metrics/TestInvalidAcceptType.java
Labels: metrics, webserver, 4.x, OCA Verified

#8679 3.x: Improves handling of invalid Accept types
  metrics/metrics/src/test/java/io/helidon/metrics/BadRequestTest.java
  webserver/webserver/src/main/java/io/helidon/webserver/HashRequestHeaders.java
  webserver/webserver/src/main/java/io/helidon/webserver/Response.java
Labels: metrics, webserver, 3.x, OCA Verified

#8629 4.x: Archetype - Implement MP JSON and metrics combination
  archetypes/archetypes/src/main/archetype/common/observability.xml
  archetypes/archetypes/src/main/archetype/mp/custom/files/src/main/java/__pkg__/SimpleGreetResource.java.mustache
  archetypes/archetypes/src/main/archetype/mp/custom/metrics-micrometer.xml
  archetypes/archetypes/src/main/archetype/mp/custom/metrics-microprofile.xml
  archetypes/archetypes/src/main/archetype/mp/custom/observability.xml
Labels: MP, archetypes, 4.x, OCA Verified

#8688 2.x: Improves handling of invalid Accept types
  metrics/metrics/src/test/java/io/helidon/metrics/BadRequestTest.java
  webserver/webserver/src/main/java/io/helidon/webserver/HashRequestHeaders.java
  webserver/webserver/src/main/java/io/helidon/webserver/Response.java
Labels: metrics, webserver, 2.x, OCA Verified

#8689 Fixes bug in OkeWorkloadIdentityAdpSupplier.available() method
  integrations/oci/sdk/cdi/src/main/java/io/helidon/integrations/oci/sdk/cdi/OkeWorkloadIdentityAdpSupplier.java
  integrations/oci/sdk/cdi/src/test/java/io/helidon/integrations/oci/sdk/cdi/TestOkeWorkloadIdentityAdpSupplier.java
Labels: bug, MP, P1, OCI, java, 4.x, OCA Verified

#8675 4.x: WsClient accept `Connection` header with `upgrade` value lowercase
  webclient/websocket/src/main/java/io/helidon/webclient/websocket/WsClientImpl.java
Labels: websocket, 4.x, OCA Verified

#8694 Properly handles an empty input stream in GrowingBufferData
  common/buffers/src/main/java/io/helidon/common/buffers/GrowingBufferData.java
  common/buffers/src/test/java/io/helidon/common/buffers/BufferDataTest.java
Labels: bug, common, 4.x, OCA Verified

#8697 Preserve stability in details JSON output
  health/health/src/main/java/io/helidon/health/HealthCheckResponse.java
Labels: OCA Verified

#8695 Clear default propagator when one is explicitly added
  tracing/providers/jaeger/src/main/java/io/helidon/tracing/providers/jaeger/JaegerTracerBuilder.java
  tracing/providers/jaeger/src/test/java/io/helidon/tracing/providers/jaeger/BuilderPropagatorDefaultTest.java
Labels: OCA Verified

#8680 OIDC double outbound fix
  security/providers/oidc/src/main/java/io/helidon/security/providers/oidc/OidcProvider.java
Labels: OCA Verified

#8178 [3.x] Helidon Arquillian module should only depend on MP core #7614
  microprofile/tests/arquillian/pom.xml
  microprofile/tests/arquillian/src/main/java/io/helidon/microprofile/arquillian/HelidonDeployableContainer.java
  microprofile/tests/tck/tck-fault-tolerance/pom.xml
  microprofile/tests/tck/tck-health/pom.xml
  microprofile/tests/tck/tck-jwt-auth/pom.xml
  microprofile/tests/tck/tck-lra/pom.xml
  microprofile/tests/tck/tck-openapi/pom.xml
  microprofile/tests/tck/tck-opentracing/pom.xml
  microprofile/tests/tck/tck-reactive-operators/pom.xml
  microprofile/tests/tck/tck-rest-client/pom.xml
Labels: OCA Verified

#8699 4.x: Move example WebClient code into a snippet
  docs/src/main/asciidoc/se/webclient.adoc
  docs/src/main/java/io/helidon/docs/se/WebClientSnippets.java
Labels: docs, webclient, 4.x, OCA Verified

#8701 [4.x] OIDC original uri resolving query fix
  security/providers/oidc-common/src/main/java/io/helidon/security/providers/oidc/common/Tenant.java
  security/providers/oidc/src/main/java/io/helidon/security/providers/oidc/OidcFeature.java
  security/providers/oidc/src/main/java/io/helidon/security/providers/oidc/TenantAuthenticationHandler.java
  security/providers/oidc/src/test/java/io/helidon/security/providers/oidc/TenantAuthenticationHandlerTest.java
Labels: OCA Verified

#8571 [4.x] Closeable jdbc pool
  dbclient/dbclient/src/main/java/io/helidon/dbclient/DbClient.java
  dbclient/dbclient/src/main/java/io/helidon/dbclient/DbClientBase.java
  dbclient/hikari/src/main/java/io/helidon/dbclient/hikari/HikariConnectionPool.java
  dbclient/jdbc/src/main/java/io/helidon/dbclient/jdbc/CloseableJdbcConnectionPool.java
  dbclient/jdbc/src/main/java/io/helidon/dbclient/jdbc/JdbcClient.java
Labels: contribution, OCA Verified

#8702 Allows transition from HEADERS to END in HTTP2 client stream
  webclient/http2/src/main/java/io/helidon/webclient/http2/Http2ClientStream.java
  webclient/http2/src/test/java/io/helidon/webclient/http2/ReadStateTest.java
Labels: bug, webserver, 4.x, OCA Verified

#8658 4.x: Remove unnecessary comments from DropwizardMetricsListener
  dbclient/metrics-hikari/src/main/java/io/helidon/dbclient/metrics/hikari/DropwizardMetricsListener.java
Labels: OCA Verified

#8668 3.x Messaging TCK runs tests twice #7584
  microprofile/tests/tck/pom.xml
  microprofile/tests/tck/tck-graphql/pom.xml
  microprofile/tests/tck/tck-health/pom.xml
  microprofile/tests/tck/tck-messaging/pom.xml
  microprofile/tests/tck/tck-metrics/pom.xml
  microprofile/tests/tck/tck-reactive-operators/pom.xml
Labels: OCA Verified

#8687 [4.x] Plugin updates
  codegen/apt/pom.xml
  codegen/class-model/pom.xml
  codegen/class-model/src/main/java/io/helidon/codegen/classmodel/ModelComponent.java
  codegen/codegen/pom.xml
  codegen/codegen/src/main/java/io/helidon/codegen/CodegenException.java
  codegen/compiler/pom.xml
  codegen/helidon-copyright/pom.xml
  codegen/helidon-copyright/src/main/java/io/helidon/codegen/helidon/copyright/HelidonCopyrightProvider.java
  codegen/pom.xml
  common/buffers/pom.xml
  common/buffers/src/main/java/io/helidon/common/buffers/DataReader.java
  common/buffers/src/main/java/module-info.java
  common/common/src/main/java/io/helidon/common/Errors.java
  common/config/pom.xml
  common/configurable/pom.xml
  common/context/src/main/java/io/helidon/common/context/Context.java
  common/key-util/pom.xml
  common/mapper/src/main/java/io/helidon/common/mapper/Value.java
  common/pom.xml
  common/processor/class-model/pom.xml
  common/processor/class-model/src/main/java/io/helidon/common/processor/classmodel/Content.java
  common/processor/class-model/src/main/java/io/helidon/common/processor/classmodel/ModelComponent.java
  common/processor/class-model/src/main/java/io/helidon/common/processor/classmodel/package-info.java
  common/processor/helidon-copyright/pom.xml
  common/processor/helidon-copyright/src/main/java/io/helidon/common/processor/helidon/copyright/HelidonCopyrightProvider.java
  common/processor/helidon-copyright/src/main/java/io/helidon/common/processor/helidon/copyright/package-info.java
  common/processor/processor/pom.xml
  common/processor/processor/src/main/java/io/helidon/common/processor/package-info.java
  common/processor/processor/src/main/java/io/helidon/common/processor/spi/package-info.java
  common/processor/processor/src/main/java/module-info.java
  common/reactive/pom.xml
  common/reactive/src/main/java/io/helidon/common/reactive/BufferedEmittingPublisher.java
  common/reactive/src/main/java/io/helidon/common/reactive/CompletionSingle.java
  common/reactive/src/main/java/io/helidon/common/reactive/MultiFromByteChannel.java
  common/reactive/src/main/java/io/helidon/common/reactive/MultiMapperPublisher.java
  common/reactive/src/main/java/io/helidon/common/reactive/Single.java
  common/reactive/src/main/java/io/helidon/common/reactive/SingleMapperPublisher.java
  common/reactive/src/main/java/io/helidon/common/reactive/SingleSubscriberHolder.java
  common/reactive/src/main/java/module-info.java
  common/socket/pom.xml
  common/testing/http-junit5/pom.xml
  common/testing/http-junit5/src/main/java/io/helidon/common/testing/http/junit5/SocketHttpClient.java
  common/testing/junit5/pom.xml
  common/testing/junit5/src/main/java/io/helidon/common/testing/junit5/RestoreSystemPropertiesExt.java
  common/tls/pom.xml
  common/types/pom.xml
  common/types/src/main/java/io/helidon/common/types/TypeInfoBlueprint.java
  common/types/src/main/java/io/helidon/common/types/TypedElementInfoBlueprint.java
  common/types/src/main/java/module-info.java
  common/uri/pom.xml
  common/uri/src/main/java/io/helidon/common/uri/UriBuilderSupport.java
  jersey/connector/pom.xml
  microprofile/reactive-streams/src/main/java/module-info.java
  pom.xml
  webserver/webserver/pom.xml
Labels: build, 4.x, OCA Verified
