Repository helidon-io/helidon, pull requests merged in 2024-08, with the labels that each got.

#9074 4.x: Use string constructor of BigDecimal to avoid bad decimals in output.
  metadata/hson/src/main/java/io/helidon/metadata/hson/Hson.java
  metadata/hson/src/main/java/io/helidon/metadata/hson/HsonArray.java
  metadata/hson/src/main/java/io/helidon/metadata/hson/HsonObject.java
  metadata/hson/src/test/java/io/helidon/metadata/hson/HsonTest.java
Labels: 4.x, OCA Verified

#9066 3.x: Add classesDirectory to failsafe plugin configuration
  applications/parent/pom.xml
Labels: 3.x, testing, backport, OCA Verified

#9067 2.x: Add classesDirectory to failsafe plugin configuration
  applications/parent/pom.xml
Labels: 2.x, testing, backport, OCA Verified

#9060 Issue #7101 - WebClient should have a mode that is resilient to bad media/content types
  common/http/src/main/java/io/helidon/common/http/MediaType.java
  tests/integration/webclient/src/test/java/io/helidon/tests/integration/webclient/HeadersTest.java
  webclient/webclient/src/main/java/io/helidon/webclient/NettyClientHandler.java
  webclient/webclient/src/main/java/io/helidon/webclient/WebClient.java
  webclient/webclient/src/main/java/io/helidon/webclient/WebClientConfiguration.java
  webclient/webclient/src/main/java/io/helidon/webclient/WebClientResponseHeadersImpl.java
  webclient/webclient/src/main/java/io/helidon/webclient/WebClientResponseImpl.java
Labels: enhancement, 2.x, webclient, OCA Verified

#9080 4.x: Use Hson.Struct instead of Hson.Object to prevent confusion with java.lang.Object
  config/metadata/codegen/src/main/java/io/helidon/config/metadata/codegen/ConfigMetadataCodegenExtension.java
  config/metadata/codegen/src/main/java/io/helidon/config/metadata/codegen/ConfiguredType.java
  config/metadata/processor/src/main/java/io/helidon/config/metadata/processor/ConfigMetadataHandler.java
  config/metadata/processor/src/main/java/io/helidon/config/metadata/processor/ConfiguredType.java
  metadata/hson/src/main/java/io/helidon/metadata/hson/Hson.java
  metadata/hson/src/main/java/io/helidon/metadata/hson/HsonArray.java
  metadata/hson/src/main/java/io/helidon/metadata/hson/HsonParser.java
  metadata/hson/src/main/java/io/helidon/metadata/hson/HsonStruct.java
  metadata/hson/src/main/java/io/helidon/metadata/hson/package-info.java
  metadata/hson/src/test/java/io/helidon/metadata/hson/ExistingTypesTest.java
  metadata/hson/src/test/java/io/helidon/metadata/hson/HsonTest.java
  service/codegen/src/main/java/io/helidon/service/codegen/HelidonMetaInfServices.java
  service/metadata/src/main/java/io/helidon/service/metadata/DescriptorMetadata.java
  service/metadata/src/main/java/io/helidon/service/metadata/DescriptorMetadataImpl.java
  service/metadata/src/main/java/io/helidon/service/metadata/Descriptors.java
  service/registry/src/main/java/io/helidon/service/registry/CoreServiceDiscovery.java
Labels: OCA Verified

#9086 Uptake Helidon Build Tools v4.0.9
  applications/parent/pom.xml
  examples/quickstarts/helidon-standalone-quickstart-mp/pom.xml
  examples/quickstarts/helidon-standalone-quickstart-se/pom.xml
  pom.xml
Labels: build, 4.x, OCA Verified

#9082 4.x: Excluding generated service descriptors from javadoc plugin(s).
  docs/pom.xml
  integrations/oci/authentication/instance/pom.xml
  integrations/oci/authentication/oke-workload/pom.xml
  integrations/oci/authentication/resource/pom.xml
  pom.xml
Labels: docs, build, 4.x, OCA Verified

#9087 Fix release.sh
  etc/scripts/release.sh
Labels: build, 4.x, OCA Verified

#9083 4.x: Upgrade oci-sdk to 3.45.0
  dependencies/pom.xml
Labels: dependencies, OCI, 4.x, OCA Verified

#9038 4.x: Updates versions of beans.xml resources to 4.0
  archetypes/archetypes/src/main/archetype/mp/common/files/src/main/resources/META-INF/beans.xml
  health/health-checks/src/main/resources/META-INF/beans.xml
  integrations/cdi/datasource-hikaricp/src/main/resources/META-INF/beans.xml
  integrations/cdi/datasource-hikaricp/src/test/resources/META-INF/beans.xml
  integrations/cdi/datasource-ucp/src/test/resources/META-INF/beans.xml
  integrations/cdi/hibernate-cdi/src/main/resources/META-INF/beans.xml
  integrations/cdi/jpa-cdi/src/main/resources/META-INF/beans.xml
  integrations/cdi/jta-cdi/src/main/resources/META-INF/beans.xml
  integrations/micronaut/cdi/src/test/resources/META-INF/beans.xml
  integrations/oci/tls-certificates/src/test/resources/META-INF/beans.xml
  messaging/connectors/aq/src/main/resources/META-INF/beans.xml
  messaging/connectors/jms/src/main/resources/META-INF/beans.xml
  messaging/connectors/kafka/src/main/resources/META-INF/beans.xml
  messaging/connectors/mock/src/main/resources/META-INF/beans.xml
  messaging/connectors/wls-jms/src/main/resources/META-INF/beans.xml
  microprofile/bean-validation/src/main/resources/META-INF/beans.xml
  microprofile/fault-tolerance/src/main/resources/META-INF/beans.xml
  microprofile/fault-tolerance/src/test/resources/META-INF/beans.xml
  microprofile/graphql/server/src/test/resources/META-INF/beans.xml
  microprofile/grpc/tests/src/test/resources/META-INF/beans.xml
  microprofile/messaging/health/src/main/resources/META-INF/beans.xml
  microprofile/messaging/metrics/src/main/resources/META-INF/beans.xml
  microprofile/metrics/src/test/resources/META-INF/beans.xml
  microprofile/server/src/test/resources/META-INF/beans.xml
  microprofile/tests/tck/tck-opentracing/src/test/resources/META-INF/beans.xml
  microprofile/websocket/src/test/resources/META-INF/beans.xml
  tests/apps/bookstore/bookstore-mp/src/main/resources/META-INF/beans.xml
  tests/apps/bookstore/common/src/main/resources/META-INF/beans.xml
  tests/functional/context-propagation/src/main/resources/META-INF/beans.xml
  tests/functional/jax-rs-multiple-apps/src/main/resources/META-INF/beans.xml
  tests/functional/jax-rs-subresource/src/main/resources/META-INF/beans.xml
  tests/functional/mp-compression/src/main/resources/META-INF/beans.xml
  tests/functional/mp-synthetic-app/src/main/resources/META-INF/beans.xml
  tests/functional/multiport/src/main/resources/META-INF/beans.xml
  tests/functional/param-converter-provider/src/main/resources/META-INF/beans.xml
  tests/functional/request-scope-cdi/src/main/resources/META-INF/beans.xml
  tests/functional/request-scope-injection/src/main/resources/META-INF/beans.xml
  tests/functional/request-scope/src/main/resources/META-INF/beans.xml
  tests/integration/jpa/appl/src/main/resources/META-INF/beans.xml
  tests/integration/jpa/model/src/main/resources/META-INF/beans.xml
  tests/integration/mp-bean-validation/src/main/resources/META-INF/beans.xml
  tests/integration/mp-gh-4123/src/main/resources/META-INF/beans.xml
  tests/integration/mp-graphql/src/test/resources/META-INF/beans.xml
  tests/integration/mp-security-client/src/main/resources/META-INF/beans.xml
  tests/integration/mp-ws-services/src/main/resources/META-INF/beans.xml
  tests/integration/native-image/mp-1/src/main/resources/META-INF/beans.xml
  tests/integration/native-image/mp-2/src/main/resources/META-INF/beans.xml
  tests/integration/native-image/mp-3/src/main/resources/META-INF/beans.xml
  tests/integration/security/gh1487/src/main/resources/META-INF/beans.xml
  tests/integration/security/gh2297/src/main/resources/META-INF/beans.xml
  tests/integration/security/gh2772/src/main/resources/META-INF/beans.xml
  tests/integration/security/path-params/src/main/resources/META-INF/beans.xml
  tests/integration/security/security-annotation/src/main/resources/META-INF/beans.xml
  tests/integration/zipkin-mp-2.2/src/main/resources/META-INF/beans.xml
Labels: MP, P5, cdi, 4.x, OCA Verified

#9085 Mark deprecations for Micrometer integration component
  integrations/micrometer/cdi/pom.xml
  integrations/micrometer/cdi/src/test/java/io/helidon/integrations/micrometer/cdi/MixedAnnotationsResource.java
  integrations/micrometer/cdi/src/test/java/io/helidon/integrations/micrometer/cdi/TestMixedAnnotations.java
  integrations/micrometer/micrometer/src/main/java/io/helidon/integrations/micrometer/MeterRegistryFactory.java
  integrations/micrometer/micrometer/src/main/java/io/helidon/integrations/micrometer/MicrometerFeature.java
  metrics/providers/micrometer/src/test/java/io/helidon/metrics/providers/micrometer/TestIntegration.java
Labels: OCA Verified

#9070 3.x: Upgrade hibernate-validator to 7.0.5 and Jakarta EE validation-api to 3.0.2
  dependencies/pom.xml
  microprofile/server/src/main/java/module-info.java
Labels: dependencies, 3.x, OCA Verified

#9093 3.x: Fixes links in documentation to point to `helidon-examples` repository.
  docs/includes/cors.adoc
  docs/includes/guides/gradle-build.adoc
  docs/includes/guides/metrics.adoc
  docs/includes/metrics/metrics-shared.adoc
  docs/includes/metrics/micrometer-shared.adoc
  docs/includes/metrics/prometheus-exemplar-support.adoc
  docs/includes/openapi.adoc
  docs/includes/openapi/openapi.adoc
  docs/includes/security/providers/abac.adoc
  docs/includes/security/providers/google-login.adoc
  docs/includes/security/providers/idcs-role-mapper.adoc
  docs/includes/security/providers/jwt.adoc
  docs/includes/security/providers/oidc.adoc
  docs/mp/cors/cors.adoc
  docs/mp/grpc/client.adoc
  docs/mp/grpc/server.adoc
  docs/mp/health.adoc
  docs/mp/integrations/hcv.adoc
  docs/mp/integrations/jedis.adoc
  docs/mp/integrations/oci.adoc
  docs/mp/metrics/metrics.adoc
  docs/mp/openapi.adoc
  docs/mp/openapi/openapi.adoc
  docs/mp/reactivemessaging/kafka.adoc
  docs/mp/websocket.adoc
  docs/se/cors.adoc
  docs/se/dbclient.adoc
  docs/se/grpc/client.adoc
  docs/se/grpc/server.adoc
  docs/se/integrations/hcv.adoc
  docs/se/integrations/oci.adoc
  docs/se/openapi/openapi.adoc
  docs/se/reactive-messaging.adoc
  docs/se/websocket.adoc
Labels: docs, 3.x, OCA Verified

#9094 4.x : Updates links to examples that are in documentation to point to the `helidon-examples` repository.
  docs/src/main/asciidoc/includes/attributes.adoc
  docs/src/main/asciidoc/includes/guides/gradle-build.adoc
  docs/src/main/asciidoc/includes/guides/maven-build.adoc
  docs/src/main/asciidoc/includes/metrics/metrics-shared.adoc
  docs/src/main/asciidoc/includes/metrics/micrometer-shared.adoc
  docs/src/main/asciidoc/includes/metrics/prometheus-exemplar-support.adoc
  docs/src/main/asciidoc/includes/openapi/openapi.adoc
  docs/src/main/asciidoc/includes/security/providers/abac.adoc
  docs/src/main/asciidoc/includes/security/providers/google-login.adoc
  docs/src/main/asciidoc/includes/security/providers/http-basic-auth.adoc
  docs/src/main/asciidoc/includes/security/providers/http-signatures.adoc
  docs/src/main/asciidoc/includes/security/providers/idcs-role-mapper.adoc
  docs/src/main/asciidoc/includes/security/providers/jwt.adoc
  docs/src/main/asciidoc/includes/security/providers/oidc.adoc
  docs/src/main/asciidoc/includes/security/providers/provider-template.adoc
  docs/src/main/asciidoc/mp/beanvalidation.adoc
  docs/src/main/asciidoc/mp/cors/cors.adoc
  docs/src/main/asciidoc/mp/graphql.adoc
  docs/src/main/asciidoc/mp/health.adoc
  docs/src/main/asciidoc/mp/integrations/hcv.adoc
  docs/src/main/asciidoc/mp/integrations/neo4j.adoc
  docs/src/main/asciidoc/mp/integrations/oci.adoc
  docs/src/main/asciidoc/mp/metrics/metrics.adoc
  docs/src/main/asciidoc/mp/openapi/openapi.adoc
  docs/src/main/asciidoc/mp/persistence.adoc
  docs/src/main/asciidoc/mp/reactivemessaging/kafka.adoc
  docs/src/main/asciidoc/mp/telemetry.adoc
  docs/src/main/asciidoc/mp/websocket.adoc
  docs/src/main/asciidoc/se/cors.adoc
  docs/src/main/asciidoc/se/dbclient.adoc
  docs/src/main/asciidoc/se/grpc/server.adoc
  docs/src/main/asciidoc/se/guides/dbclient.adoc
  docs/src/main/asciidoc/se/guides/upgrade_4x.adoc
  docs/src/main/asciidoc/se/integrations/hcv.adoc
  docs/src/main/asciidoc/se/integrations/neo4j.adoc
  docs/src/main/asciidoc/se/integrations/oci.adoc
  docs/src/main/asciidoc/se/openapi/openapi.adoc
  docs/src/main/asciidoc/se/reactive-messaging.adoc
  docs/src/main/asciidoc/se/websocket.adoc
  examples/README.md
Labels: docs, examples, 4.x, OCA Verified

#9089 4.x jakarta ee upgrades
  dependencies/pom.xml
  integrations/jta/jdbc/pom.xml
  microprofile/server/src/main/java/module-info.java
  microprofile/tests/tck/tck-jsonb/pom.xml
  microprofile/tests/tck/tck-jsonb/tck-jsonb-test/pom.xml
Labels: dependencies, 4.x, OCA Verified

#9095 4.x: Update microprofile spec versions in docs
  docs/src/main/asciidoc/includes/attributes.adoc
Labels: docs, 4.x, OCA Verified

#9102 Fix DbClientService for Mongo DbClient
  dbclient/mongodb/src/main/java/io/helidon/dbclient/mongodb/MongoDbStatementDml.java
  dbclient/mongodb/src/main/java/io/helidon/dbclient/mongodb/MongoDbStatementQuery.java
  dbclient/mongodb/src/test/java/io/helidon/dbclient/mongodb/MongoDbClientTest.java
Labels: DB client, 4.x, OCA Verified

#9105 Upgrades gRPC dependencies to latest versions
  dependencies/pom.xml
  grpc/core/src/main/java/module-info.java
  microprofile/grpc/server/src/main/java/module-info.java
  webserver/grpc/src/main/java/io/helidon/webserver/grpc/ProtoMarshaller.java
Labels: grpc, dependencies, 4.x, OCA Verified

#9107 DbClient IT tests job
  .github/workflows/validate.yml
  pom.xml
  tests/integration/pom.xml
Labels: build, DB client, 4.x, OCA Verified

#9108 Cleanup validate workflow
  .github/workflows/validate.yml
  etc/scripts/build-examples.sh
  etc/scripts/test-quickstarts.sh
  metrics/metrics/pom.xml
  metrics/provider-tests/pom.xml
  microprofile/metrics/pom.xml
Labels: build, 4.x, OCA Verified

#9109 4.x: GraphQL upgrade
  all/pom.xml
  config/metadata/docs/pom.xml
  dependencies/pom.xml
  docs/pom.xml
  graphql/server/src/main/java/io/helidon/graphql/server/InvocationHandlerImpl.java
  microprofile/graphql/server/src/main/java/io/helidon/microprofile/graphql/server/DataFetcherUtils.java
  microprofile/tests/tck/tck-graphql/src/test/resources/arquillian.xml
Labels: dependencies, graphql, 4.x, OCA Verified

#9052 Add back and enhance the page describing OpenAPI generation for Helidon 4
  docs/etc/petstorex.yaml
  docs/src/main/asciidoc/includes/attributes.adoc
  docs/src/main/asciidoc/includes/openapi/openapi-generator.adoc
  docs/src/main/asciidoc/mp/openapi/openapi-generator.adoc
  docs/src/main/asciidoc/se/openapi/openapi-generator.adoc
  docs/src/main/java/io/helidon/docs/mp/openapi/OpenApiGeneratorSnippets.java
  docs/src/main/java/io/helidon/docs/se/openapi/OpenApiGeneratorSnippets.java
Labels: OCA Verified

#9111 Parallelized pipelines
  .github/actions/common/action.yml
  .github/workflows/validate.yml
  .mvn/cache-config.xml
  .mvn/extensions.xml
  microprofile/tests/tck/pom.xml
  parent/pom.xml
  pom.xml
  tests/integration/pom.xml
Labels: build, 4.x, OCA Verified

#9112 Re-add tck-fault-tolerance module in the reactor
  microprofile/tests/tck/pom.xml
Labels: build, 4.x, OCA Verified

#9115 4.x: Client connection properly returned to the cache
  http/media/media/src/main/java/io/helidon/http/media/ReadableEntityBase.java
Labels: OCA Verified

#9114 4.x: ConcurrentHashMap guarding added
  microprofile/security/src/main/java/io/helidon/microprofile/security/SecurityFilter.java
Labels: OCA Verified

#9117 Avoids running the encoders (such as GZIP) when no data is written
  webserver/tests/webserver/src/test/java/io/helidon/webserver/tests/ContentEncodingEmptyTest.java
  webserver/webserver/src/main/java/io/helidon/webserver/http1/Http1ServerResponse.java
Labels: webserver, 4.x, OCA Verified

#9120 Bump up cron-utils #9099
  dependencies/pom.xml
Labels: dependencies, OCA Verified

#9121 4.x: Mapper manager cache key fix
  common/mapper/src/main/java/io/helidon/common/mapper/MapperManagerImpl.java
  common/mapper/src/test/java/io/helidon/common/mapper/MapperManagerTest.java
Labels: 4.x, OCA Verified

#9123 Documents the gRPC MP server API
  docs/src/main/asciidoc/mp/grpc/client.adoc
  docs/src/main/asciidoc/mp/grpc/server.adoc
  docs/src/main/asciidoc/sitegen.yaml
  docs/src/main/java/io/helidon/docs/mp/grpc/GrpcSnippets.java
Labels: docs, grpc, 4.x, OCA Verified

#9142 4.x: Ugprade dependency check plugin and clean up suppression file
  etc/dependency-check-suppression.xml
  pom.xml
Labels: build, 4.x, OCA Verified

#9134 [2.x] Upgrade GraphQL Java to 22.x
  dependencies/pom.xml
  graphql/server/src/main/java/io/helidon/graphql/server/InvocationHandlerImpl.java
  microprofile/graphql/server/src/main/java/io/helidon/microprofile/graphql/server/DataFetcherUtils.java
  microprofile/tests/tck/tck-graphql/src/test/resources/arquillian.xml
Labels: 2.x, dependencies, graphql, OCA Verified

#9135 [3.x] Upgrade GraphQL Java to 22.x
  dependencies/pom.xml
  graphql/server/src/main/java/io/helidon/graphql/server/InvocationHandlerImpl.java
  microprofile/graphql/server/src/main/java/io/helidon/microprofile/graphql/server/DataFetcherUtils.java
  microprofile/tests/tck/tck-graphql/src/test/resources/arquillian.xml
Labels: dependencies, 3.x, graphql, OCA Verified

#9143 4.x: Upgrade slf4j to 2.0.16
  dependencies/pom.xml
Labels: dependencies, logging, 4.x, OCA Verified

#9152 Do not automatically trigger assign-issue-to-project workflow
  .github/workflows/assign-issue-to-project.yml
Labels: OCA Verified

#9150 Documents gRPC MP Client API
  docs/src/main/asciidoc/mp/grpc/client.adoc
  docs/src/main/asciidoc/mp/grpc/server.adoc
  docs/src/main/asciidoc/sitegen.yaml
  docs/src/main/java/io/helidon/docs/mp/grpc/GrpcSnippets.java
Labels: docs, grpc, 4.x, OCA Verified

#9141 4.x: Upgrade microprofile-cdi-tck to 4.0.13
  pom.xml
Labels: testing, 4.x, OCA Verified, TCK

#9154 4.x: Builder tests that confidential options are not printed in toString()
  builder/tests/builder/src/main/java/io/helidon/builder/test/testsubjects/tostring/SecretBlueprint.java
  builder/tests/builder/src/test/java/io/helidon/builder/test/ToStringTest.java
Labels: task, 4.x, OCA Verified

#9155 Implements support for client gRPC channel injections
  docs/src/main/asciidoc/mp/grpc/client.adoc
  docs/src/main/java/io/helidon/docs/mp/grpc/GrpcSnippets.java
  grpc/api/src/main/java/io/helidon/grpc/api/Grpc.java
  microprofile/grpc/client/src/main/java/io/helidon/microprofile/grpc/client/ChannelProducer.java
  microprofile/grpc/client/src/test/java/io/helidon/microprofile/grpc/client/ChannelInjectionTest.java
Labels: MP, grpc, client, 4.x, OCA Verified

#9144 4.x: forward port release fixes from 4.1.0 release branch
  CHANGELOG.md
  integrations/oci/authentication/instance/pom.xml
  integrations/oci/authentication/oke-workload/pom.xml
  integrations/oci/authentication/resource/pom.xml
  microprofile/grpc/tests/pom.xml
Labels: build, 4.x, OCA Verified

#9161 2.x: upgrade dependency check plugin. Cleanup suppression file
  etc/dependency-check-suppression.xml
  pom.xml
Labels: 2.x, OCA Verified

#9162 Downgrades version of protobuf for backwards compatibility
  dependencies/pom.xml
Labels: grpc, 4.x, OCA Verified

#9166 4.x: Support for validation of Duration and URI default values.
  builder/codegen/src/main/java/io/helidon/builder/codegen/PrototypeProperty.java
  builder/codegen/src/main/java/io/helidon/builder/codegen/TypeHandler.java
  builder/codegen/src/main/java/io/helidon/builder/codegen/TypeHandlerCollection.java
  builder/codegen/src/main/java/io/helidon/builder/codegen/TypeHandlerList.java
  builder/codegen/src/main/java/io/helidon/builder/codegen/TypeHandlerMap.java
  builder/codegen/src/main/java/io/helidon/builder/codegen/TypeHandlerOptional.java
  builder/codegen/src/main/java/io/helidon/builder/codegen/TypeHandlerSet.java
  builder/codegen/src/main/java/io/helidon/builder/codegen/TypeHandlerSupplier.java
  codegen/codegen/src/main/java/io/helidon/codegen/CodegenValidator.java
  codegen/codegen/src/test/java/io/helidon/codegen/CodegenValidatorTest.java
Labels: 4.x, OCA Verified

#9167 4.x: Handling enum and type values in a consistent way in code generation.
  builder/tests/common-types/src/main/java/io/helidon/common/types/AnnotationSupport.java
  builder/tests/common-types/src/main/java/io/helidon/common/types/EnumValue.java
  codegen/apt/src/main/java/io/helidon/codegen/apt/ToAnnotationValueVisitor.java
  codegen/class-model/src/main/java/io/helidon/codegen/classmodel/AnnotationParameter.java
  codegen/scan/src/main/java/io/helidon/codegen/scan/ScanAnnotationFactory.java
  common/types/src/main/java/io/helidon/common/types/AnnotationSupport.java
  common/types/src/main/java/io/helidon/common/types/EnumValue.java
Labels: 4.x, OCA Verified

#9175 Remove headers from request adapter logging output that do not affect CORS decision-making
  microprofile/cors/pom.xml
  microprofile/cors/src/main/java/io/helidon/microprofile/cors/CorsSupportMp.java
  microprofile/cors/src/test/java/io/helidon/microprofile/cors/TestHeaders.java
  webserver/cors/pom.xml
  webserver/cors/src/main/java/io/helidon/webserver/cors/CorsSupportBase.java
  webserver/cors/src/main/java/io/helidon/webserver/cors/RequestAdapterSe.java
  webserver/cors/src/test/java/io/helidon/webserver/cors/TestHeaders.java
Labels: OCA Verified

#9176 Remove headers that do not affect CORS decision-making from request adapter logging output
  microprofile/cors/pom.xml
  microprofile/cors/src/main/java/io/helidon/microprofile/cors/CorsSupportMp.java
  microprofile/cors/src/test/java/io/helidon/microprofile/cors/HeadersTest.java
  webserver/cors/pom.xml
  webserver/cors/src/main/java/io/helidon/webserver/cors/CorsSupportBase.java
  webserver/cors/src/main/java/io/helidon/webserver/cors/RequestAdapterSe.java
  webserver/cors/src/test/java/io/helidon/webserver/cors/HeadersTest.java
Labels: OCA Verified

#9169 2.x: Upgrade OCI SDK
  dependencies/pom.xml
Labels: 2.x, dependencies, OCI, OCA Verified

#9177 3.x: Upgrade oci sdk to 3.46.1
  dependencies/pom.xml
Labels: dependencies, 3.x, OCI, OCA Verified

#9168 4.x: Udpates to types and annotation processing
  codegen/apt/src/main/java/io/helidon/codegen/apt/AptAnnotationFactory.java
  codegen/apt/src/main/java/io/helidon/codegen/apt/AptContext.java
  codegen/apt/src/main/java/io/helidon/codegen/apt/AptContextImpl.java
  codegen/apt/src/main/java/io/helidon/codegen/apt/AptProcessor.java
  codegen/apt/src/main/java/io/helidon/codegen/apt/AptTypeFactory.java
  codegen/apt/src/main/java/io/helidon/codegen/apt/AptTypeInfoFactory.java
  codegen/class-model/src/main/java/io/helidon/codegen/classmodel/ContentSupport.java
  codegen/class-model/src/main/java/io/helidon/codegen/classmodel/Field.java
  codegen/codegen/src/main/java/io/helidon/codegen/Codegen.java
  codegen/codegen/src/main/java/io/helidon/codegen/RoundContext.java
  codegen/codegen/src/main/java/io/helidon/codegen/RoundContextImpl.java
  codegen/codegen/src/main/java/io/helidon/codegen/TypeHierarchy.java
  common/types/src/main/java/io/helidon/common/types/Annotated.java
  common/types/src/main/java/io/helidon/common/types/Annotation.java
  common/types/src/main/java/io/helidon/common/types/TypeName.java
  config/metadata/codegen/src/main/java/io/helidon/config/metadata/codegen/ConfigMetadataCodegenExtension.java
  config/metadata/processor/src/main/java/io/helidon/config/metadata/processor/ConfigMetadataHandler.java
Labels: OCA Verified

#9173 Renames package-private Grpc type to GrpcRouteHandler
  webserver/grpc/src/main/java/io/helidon/webserver/grpc/GrpcProtocolHandler.java
  webserver/grpc/src/main/java/io/helidon/webserver/grpc/GrpcProtocolSelector.java
  webserver/grpc/src/main/java/io/helidon/webserver/grpc/GrpcRoute.java
  webserver/grpc/src/main/java/io/helidon/webserver/grpc/GrpcRouteHandler.java
  webserver/grpc/src/main/java/io/helidon/webserver/grpc/GrpcRouting.java
  webserver/grpc/src/main/java/io/helidon/webserver/grpc/GrpcServiceRoute.java
  webserver/grpc/src/main/java/module-info.java
Labels: webserver, grpc, 4.x, OCA Verified

#9178 [4.x] Remove headers that do not affect CORS decision-making from request adapter logging output
  microprofile/cors/pom.xml
  microprofile/cors/src/main/java/io/helidon/microprofile/cors/CorsSupportMp.java
  microprofile/cors/src/test/java/io/helidon/microprofile/cors/HeadersTest.java
  webserver/cors/pom.xml
  webserver/cors/src/main/java/io/helidon/webserver/cors/CorsServerRequestAdapter.java
  webserver/cors/src/test/java/io/helidon/webserver/cors/HeadersTest.java
Labels: OCA Verified

#9179 4.x: Upgrade oci sdk to 3.46.1
  dependencies/pom.xml
Labels: dependencies, OCI, 4.x, OCA Verified

#9153 3.x: Bump up cron-utils #9124
  dependencies/pom.xml
Labels: dependencies, OCA Verified

#9182 4.x: Fix generation of annotations, including lists, nested annotations etc.
  codegen/class-model/src/main/java/io/helidon/codegen/classmodel/Annotation.java
  codegen/class-model/src/main/java/io/helidon/codegen/classmodel/AnnotationParameter.java
  codegen/class-model/src/main/java/io/helidon/codegen/classmodel/ContentSupport.java
  codegen/class-model/src/main/java/io/helidon/codegen/classmodel/ImportOrganizer.java
  codegen/class-model/src/test/java/io/helidon/codegen/classmodel/AnnotationTest.java
  codegen/class-model/src/test/java/io/helidon/codegen/classmodel/TypesCodegenTest.java
  codegen/pom.xml
  codegen/tests/pom.xml
  codegen/tests/test-codegen-use/pom.xml
  codegen/tests/test-codegen-use/src/main/java/io/helidon/codegen/test/codegen/use/CrazyAnnotation.java
  codegen/tests/test-codegen-use/src/main/java/io/helidon/codegen/test/codegen/use/TriggerType.java
  codegen/tests/test-codegen-use/src/main/java/module-info.java
  codegen/tests/test-codegen-use/src/test/java/io/helidon/codegen/test/codegen/use/CodegenValidationTest.java
  codegen/tests/test-codegen/pom.xml
  codegen/tests/test-codegen/src/main/java/io/helidon/codegen/test/codegen/TestCodegenExtension.java
  codegen/tests/test-codegen/src/main/java/io/helidon/codegen/test/codegen/TestCodegenExtensionProvider.java
  codegen/tests/test-codegen/src/main/java/module-info.java
  common/types/src/main/java/io/helidon/common/types/EnumValue.java
  common/types/src/main/java/io/helidon/common/types/EnumValueImpl.java
Labels: 4.x, OCA Verified, codegen

#9188 4.x: Clarify description of config profiles
  docs/src/main/asciidoc/mp/config/introduction.adoc
Labels: docs, config, OCA Verified

#9187 3.x: Clarify description of config profiles
  docs/mp/config/introduction.adoc
Labels: docs, 3.x, OCA Verified

#9201 Add support for additional modifiers
  codegen/scan/src/main/java/io/helidon/codegen/scan/ScanTypeInfoFactory.java
  codegen/tests/test-codegen-use/src/main/java/io/helidon/codegen/test/codegen/use/TriggerType.java
  codegen/tests/test-codegen-use/src/test/java/io/helidon/codegen/test/codegen/use/CodegenValidationTest.java
  codegen/tests/test-codegen/src/main/java/io/helidon/codegen/test/codegen/TestCodegenExtension.java
  common/types/src/main/java/io/helidon/common/types/Modifier.java
Labels: 4.x, OCA Verified, codegen

#9194 3.x: Adds ability to close idle HTTP connections after a certain time
  webserver/webserver/src/main/java/io/helidon/webserver/HttpInitializer.java
  webserver/webserver/src/main/java/io/helidon/webserver/ServerBasicConfig.java
  webserver/webserver/src/main/java/io/helidon/webserver/ServerConfiguration.java
  webserver/webserver/src/main/java/io/helidon/webserver/SocketConfiguration.java
  webserver/webserver/src/main/java/io/helidon/webserver/WebServer.java
  webserver/webserver/src/test/java/io/helidon/webserver/ConnectionIdleTest.java
Labels: enhancement, webserver, 3.x, OCA Verified

#9203 2.x: Adds ability to close idle HTTP connections after a certain time
  webserver/webserver/src/main/java/io/helidon/webserver/HttpInitializer.java
  webserver/webserver/src/main/java/io/helidon/webserver/ServerBasicConfig.java
  webserver/webserver/src/main/java/io/helidon/webserver/ServerConfiguration.java
  webserver/webserver/src/main/java/io/helidon/webserver/SocketConfiguration.java
  webserver/webserver/src/main/java/io/helidon/webserver/WebServer.java
  webserver/webserver/src/test/java/io/helidon/webserver/ConnectionIdleTest.java
Labels: enhancement, webserver, 2.x, OCA Verified

#9211 2.x: add support for manually producing snapshot releases
  .github/workflows/snapshotrelease.yaml
  etc/scripts/release.sh
Labels: build, 2.x, OCA Verified

#9209 4.x: Replace manual casts on pattern with instanceof in HoconConfigParser
  config/hocon/src/main/java/io/helidon/config/hocon/HoconConfigParser.java
Labels: OCA Verified

#9212 2.x: Rename snapshotrelease to snapshot
  .github/workflows/snapshot.yaml
Labels: build, 2.x, OCA Verified

#9207 Allows the creation of empty SSE events
  http/sse/src/main/java/io/helidon/http/sse/SseEvent.java
  webserver/sse/src/main/java/io/helidon/webserver/sse/SseSink.java
  webserver/tests/sse/src/test/java/io/helidon/webserver/tests/sse/SseEventTest.java
Labels: webserver, 4.x, OCA Verified

#9215 2.x: Upgrade plugins to match what is used in Helidon 3
  parent/pom.xml
Labels: build, 2.x, OCA Verified

#9190 Increases default value of write-buffer-size to 4K
  webserver/webserver/src/main/java/io/helidon/webserver/ListenerConfigBlueprint.java
  webserver/webserver/src/test/java/io/helidon/webserver/ListenerConfigTest.java
Labels: webserver, performance, 4.x, OCA Verified

#9216 3.x: Rename snapshotrelease workflow to match what is in main
  .github/workflows/snapshot.yaml
Labels: build, 3.x, OCA Verified

#9213 Remove assign-issues workflow
  .github/workflows/assign-issue.yml
  etc/scripts/assign-issue.sh
Labels: 4.x, OCA Verified

#9217 3.x: Replace manual casts on pattern with instanceof in HoconConfigParser
  config/hocon/src/main/java/io/helidon/config/hocon/HoconConfigParser.java
Labels: OCA Verified

#9206 4.x: UncheckedIOException no longer a special case
  microprofile/server/src/test/java/io/helidon/microprofile/server/JaxRsApplicationPathTest.java
  webserver/http2/src/main/java/io/helidon/webserver/http2/Http2ServerResponse.java
  webserver/http2/src/main/java/io/helidon/webserver/http2/Http2ServerStream.java
  webserver/tests/webserver/src/test/java/io/helidon/webserver/tests/UncheckedIoExceptionTest.java
  webserver/webserver/src/main/java/io/helidon/webserver/ConnectionHandler.java
  webserver/webserver/src/main/java/io/helidon/webserver/ServerConnectionException.java
  webserver/webserver/src/main/java/io/helidon/webserver/http/ErrorHandlers.java
  webserver/webserver/src/main/java/io/helidon/webserver/http/ServerResponseBase.java
  webserver/webserver/src/main/java/io/helidon/webserver/http1/Http1Connection.java
  webserver/webserver/src/main/java/io/helidon/webserver/http1/Http1ServerResponse.java
Labels: webserver, 4.x, OCA Verified

#9205 4.x Allow users to direct Helidon to use an existing global `OpenTelemetry` instance rather than create its own
  microprofile/telemetry/src/main/java/io/helidon/microprofile/telemetry/OpenTelemetryProducer.java
  tracing/providers/opentelemetry/pom.xml
  tracing/providers/opentelemetry/src/main/java/io/helidon/tracing/providers/opentelemetry/HelidonOpenTelemetry.java
  tracing/providers/opentelemetry/src/test/java/io/helidon/tracing/providers/opentelemetry/AgentDetectorTest.java
Labels: OCA Verified

#9184 deprecate old injection integration for oci
  integrations/oci/sdk/processor/src/main/java/io/helidon/integrations/oci/sdk/processor/OciInjectionProcessorObserver.java
  integrations/oci/sdk/processor/src/main/java/io/helidon/integrations/oci/sdk/processor/OciModuleComponentNamer.java
  integrations/oci/sdk/processor/src/main/java/module-info.java
Labels: OCA Verified

#9222 Adopt Micrometer 1.13.3
  dependencies/pom.xml
Labels: metrics, dependencies, 4.x, OCA Verified

#9221 Fix nightly script
  etc/scripts/test-nightly.sh
Labels: testing, 4.x, OCA Verified

#9098 4.x: Replace deprecated method Scheduling.fixedRateBuilder() on Scheduling.fixedRate()
  lra/coordinator/server/src/main/java/io/helidon/lra/coordinator/CoordinatorService.java
Labels: 4.x, OCA Verified

#9226 Temporarily restore original Micrometer release
  dependencies/pom.xml
Labels: OCA Verified
