Repository helidon-io/helidon, pull requests merged in 2024-06, with the labels that each got.

#8823 Retrieve the correct requested URI info path value, indpt of the routing path used to locate the handler
  webserver/http2/src/main/java/io/helidon/webserver/http2/Http2ServerRequest.java
  webserver/tests/pom.xml
  webserver/tests/requested-uri-path-gh8818/pom.xml
  webserver/tests/requested-uri-path-gh8818/src/main/java/io/helidon/webserver/tests/gh2631/Gh8818.java
  webserver/tests/requested-uri-path-gh8818/src/main/resources/logging.properties
  webserver/tests/requested-uri-path-gh8818/src/test/java/io/helidon/webserver/tests/gh2631/Gh8818Test.java
  webserver/webserver/src/main/java/io/helidon/webserver/http1/Http1ServerRequest.java
Labels: OCA Verified

#8831 4.x: improvement of header parsing error handling
  common/testing/http-junit5/src/main/java/io/helidon/common/testing/http/junit5/SocketHttpClient.java
  webserver/tests/webserver/src/test/java/io/helidon/webserver/tests/BadRequestTest.java
  webserver/webserver/src/main/java/io/helidon/webserver/http1/Http1Headers.java
Labels: webserver, 4.x, OCA Verified

#8825 Doc for @AddConfigBlock #8807
  docs/src/main/asciidoc/mp/guides/testing-junit5.adoc
  docs/src/main/asciidoc/mp/testing-ng.adoc
  docs/src/main/asciidoc/mp/testing.adoc
  docs/src/main/java/io/helidon/docs/mp/guides/TestingJunit5Snippets.java
Labels: OCA Verified

#8826 4.x: register routing in weighted order of Server and HTTP Features
  docs-internal/http-features.md
  docs/src/main/asciidoc/se/webserver.adoc
  webserver/cors/src/main/java/io/helidon/webserver/cors/CorsFeature.java
  webserver/tests/webserver/src/test/java/io/helidon/webserver/tests/FeaturesOrderingTest.java
  webserver/webserver/src/main/java/io/helidon/webserver/LoomServer.java
  webserver/webserver/src/main/java/io/helidon/webserver/ServerFeatureContextImpl.java
  webserver/webserver/src/main/java/io/helidon/webserver/ServerToHttpFeatureBuilder.java
  webserver/webserver/src/main/java/io/helidon/webserver/http/HttpRoutingFeature.java
  webserver/webserver/src/main/java/io/helidon/webserver/http/Registration.java
  webserver/webserver/src/main/java/io/helidon/webserver/http/Registrations.java
Labels: bug, docs, webserver, 4.x, OCA Verified

#8835 4.x - Archetype: fix Native image build for `quickstart` with `jackson`
  archetypes/archetypes/src/main/archetype/common/docker.xml
  archetypes/archetypes/src/main/archetype/common/files/src/main/resources/META-INF/native-image/groupid/artifactid/native-image.properties.mustache
  archetypes/archetypes/src/main/archetype/common/files/src/main/resources/META-INF/native-image/jakarta/xml/bind/jakarta.xml.bind-api/resource-config.json
  archetypes/archetypes/src/main/archetype/common/media.xml
Labels: MP, native-image, archetypes, 4.x, OCA Verified

#8840 4.0.10: register routing in weighted order of Server and HTTP Features
  docs-internal/http-features.md
  docs/src/main/asciidoc/se/webserver.adoc
  webserver/cors/src/main/java/io/helidon/webserver/cors/CorsFeature.java
  webserver/tests/webserver/src/test/java/io/helidon/webserver/tests/FeaturesOrderingTest.java
  webserver/webserver/src/main/java/io/helidon/webserver/LoomServer.java
  webserver/webserver/src/main/java/io/helidon/webserver/ServerFeatureContextImpl.java
  webserver/webserver/src/main/java/io/helidon/webserver/ServerToHttpFeatureBuilder.java
  webserver/webserver/src/main/java/io/helidon/webserver/http/HttpRoutingFeature.java
  webserver/webserver/src/main/java/io/helidon/webserver/http/Registration.java
  webserver/webserver/src/main/java/io/helidon/webserver/http/Registrations.java
Labels: webserver, backport, 4.x, OCA Verified

#8841 Fix tracer information propagation across threads using Helidon context
  tracing/provider-tests/src/main/java/io/helidon/tracing/providers/tests/TestTracerAndSpanPropagation.java
  tracing/provider-tests/src/main/java/module-info.java
  tracing/providers/opentelemetry/src/main/java/io/helidon/tracing/providers/opentelemetry/OpenTelemetryDataPropagationProvider.java
  tracing/providers/zipkin/pom.xml
Labels: OCA Verified

#8844 4.0.10: Retrieve the correct requested URI info path value, indpt of the routing path used to locate the handler
  webserver/http2/src/main/java/io/helidon/webserver/http2/Http2ServerRequest.java
  webserver/tests/pom.xml
  webserver/tests/requested-uri-path-gh8818/pom.xml
  webserver/tests/requested-uri-path-gh8818/src/main/java/io/helidon/webserver/tests/gh2631/Gh8818.java
  webserver/tests/requested-uri-path-gh8818/src/main/resources/logging.properties
  webserver/tests/requested-uri-path-gh8818/src/test/java/io/helidon/webserver/tests/gh2631/Gh8818Test.java
  webserver/webserver/src/main/java/io/helidon/webserver/http1/Http1ServerRequest.java
Labels: webserver, backport, 4.x, OCA Verified

#8843 4.0.10: Fix handling of invalid end of line in HTTP header parsing. Added tests
  common/testing/http-junit5/src/main/java/io/helidon/common/testing/http/junit5/SocketHttpClient.java
  webserver/tests/webserver/src/test/java/io/helidon/webserver/tests/BadRequestTest.java
  webserver/webserver/src/main/java/io/helidon/webserver/http1/Http1Headers.java
Labels: webserver, backport, 4.x, OCA Verified

#8847 4.0.10: Fix tracer information propagation across threads using Helidon context
  tracing/provider-tests/src/main/java/io/helidon/tracing/providers/tests/TestTracerAndSpanPropagation.java
  tracing/provider-tests/src/main/java/module-info.java
  tracing/providers/opentelemetry/src/main/java/io/helidon/tracing/providers/opentelemetry/OpenTelemetryDataPropagationProvider.java
  tracing/providers/zipkin/pom.xml
Labels: tracing, backport, 4.x, OCA Verified

#8787 4.x: Mocking documentation
  docs/pom.xml
  docs/src/main/asciidoc/mp/guides/testing-junit5.adoc
  docs/src/main/asciidoc/mp/testing/testing-ng.adoc
  docs/src/main/asciidoc/mp/testing/testing.adoc
  docs/src/main/asciidoc/sitegen.yaml
  docs/src/main/java/io/helidon/docs/mp/testing/CDIMockingSnippets.java
  docs/src/main/java/io/helidon/docs/mp/testing/HelidonMockingSnippets.java
  docs/src/main/java/io/helidon/docs/mp/testing/TestingNgSnippets.java
  docs/src/main/java/io/helidon/docs/mp/testing/TestingSnippets.java
Labels: MP, docs, testing, 4.x, OCA Verified

#8845 4.x: HTTP2-Settings needs to be encoded/decoded to Base64 with url dialect
  webclient/http2/src/main/java/io/helidon/webclient/http2/Http2ClientConnectionHandler.java
  webserver/http2/src/main/java/io/helidon/webserver/http2/Http2Connection.java
  webserver/http2/src/main/java/io/helidon/webserver/http2/Http2Upgrader.java
  webserver/http2/src/test/java/io/helidon/webserver/http2/UpgradeSettingsTest.java
Labels: OCA Verified

#8853 4.0.10: HTTP2-Settings needs to be encoded/decoded to Base64 with url dialect
  webclient/http2/src/main/java/io/helidon/webclient/http2/Http2ClientConnectionHandler.java
  webserver/http2/src/main/java/io/helidon/webserver/http2/Http2Connection.java
  webserver/http2/src/main/java/io/helidon/webserver/http2/Http2Upgrader.java
  webserver/http2/src/test/java/io/helidon/webserver/http2/UpgradeSettingsTest.java
Labels: webserver, backport, 4.x, OCA Verified

#8859 4.0.10: Reorder checking of delegate vs. wrapper in OTel tracer unwrap (
  tracing/providers/opentelemetry/src/main/java/io/helidon/tracing/providers/opentelemetry/OpenTelemetryTracer.java
  tracing/providers/opentelemetry/src/test/java/io/helidon/tracing/providers/opentelemetry/TestUnwrap.java
Labels: tracing, backport, 4.x, OCA Verified

#8860 Update CHANGELOG for 4.0.10 release
  CHANGELOG.md
Labels: 4.x, OCA Verified

#8838 4.x: Updates to support latest dev release of GraalVM native image
  common/configurable/src/main/resources/META-INF/native-image/io.helidon.common/helidon-common-configurable/native-image.properties
  integrations/graal/mp-native-image-extension/src/main/resources/META-INF/native-image/io.helidon.integrations.graal/helidon-mp-graal-native-image-extension/native-image.properties
  logging/jul/src/main/resources/META-INF/native-image/io.helidon.logging/helidon-logging-jul/native-image.properties
  security/providers/oidc/src/main/java/io/helidon/security/providers/oidc/TenantAuthenticationHandler.java
Labels: native-image, 4.x, OCA Verified

#8850 4.x: Add uses io.helidon.dbclient.jdbc.spi.JdbcConnectionPoolProvider to io.helidon.dbclient.jdbc module (#8237)
  dbclient/jdbc/src/main/java/module-info.java
Labels: OCA Verified

#8865 Jwt improvements
  etc/checkstyle-suppressions.xml
  microprofile/jwt-auth/src/main/java/io/helidon/microprofile/jwt/auth/JwtAuthProvider.java
  security/jwt/src/main/java/io/helidon/security/jwt/AudienceValidator.java
  security/jwt/src/main/java/io/helidon/security/jwt/ClaimValidator.java
  security/jwt/src/main/java/io/helidon/security/jwt/CommonValidator.java
  security/jwt/src/main/java/io/helidon/security/jwt/CriticalValidator.java
  security/jwt/src/main/java/io/helidon/security/jwt/EncryptedJwt.java
  security/jwt/src/main/java/io/helidon/security/jwt/ExpirationValidator.java
  security/jwt/src/main/java/io/helidon/security/jwt/FieldValidator.java
  security/jwt/src/main/java/io/helidon/security/jwt/InstantValidator.java
  security/jwt/src/main/java/io/helidon/security/jwt/IssueTimeValidator.java
  security/jwt/src/main/java/io/helidon/security/jwt/Jwt.java
  security/jwt/src/main/java/io/helidon/security/jwt/JwtHeaders.java
  security/jwt/src/main/java/io/helidon/security/jwt/JwtScope.java
  security/jwt/src/main/java/io/helidon/security/jwt/JwtUtil.java
  security/jwt/src/main/java/io/helidon/security/jwt/JwtValidator.java
  security/jwt/src/main/java/io/helidon/security/jwt/JwtValidators.java
  security/jwt/src/main/java/io/helidon/security/jwt/MaxTokenAgeValidator.java
  security/jwt/src/main/java/io/helidon/security/jwt/NotBeforeValidator.java
  security/jwt/src/main/java/io/helidon/security/jwt/OptionalValidator.java
  security/jwt/src/main/java/io/helidon/security/jwt/UserPrincipalValidator.java
  security/jwt/src/main/java/io/helidon/security/jwt/ValidatorWrapper.java
  security/jwt/src/main/java/io/helidon/security/jwt/jwk/JwkOctet.java
  security/jwt/src/test/java/io/helidon/security/jwt/JwtTest.java
  security/jwt/src/test/java/io/helidon/security/jwt/JwtValidatorTest.java
  security/providers/idcs-mapper/src/main/java/io/helidon/security/providers/idcs/mapper/IdcsRoleMapperProviderBase.java
  security/providers/jwt/src/main/java/io/helidon/security/providers/jwt/JwtProvider.java
  security/providers/oidc/src/main/java/io/helidon/security/providers/oidc/TenantAuthenticationHandler.java
Labels: OCA Verified

#8874 Jwt improvements & Updates to support latest dev release of GraalVM native image
  CHANGELOG.md
  common/configurable/src/main/resources/META-INF/native-image/io.helidon.common/helidon-common-configurable/native-image.properties
  etc/checkstyle-suppressions.xml
  integrations/graal/mp-native-image-extension/src/main/resources/META-INF/native-image/io.helidon.integrations.graal/helidon-mp-graal-native-image-extension/native-image.properties
  logging/jul/src/main/resources/META-INF/native-image/io.helidon.logging/helidon-logging-jul/native-image.properties
  microprofile/jwt-auth/src/main/java/io/helidon/microprofile/jwt/auth/JwtAuthProvider.java
  security/jwt/src/main/java/io/helidon/security/jwt/AudienceValidator.java
  security/jwt/src/main/java/io/helidon/security/jwt/ClaimValidator.java
  security/jwt/src/main/java/io/helidon/security/jwt/CommonValidator.java
  security/jwt/src/main/java/io/helidon/security/jwt/CriticalValidator.java
  security/jwt/src/main/java/io/helidon/security/jwt/EncryptedJwt.java
  security/jwt/src/main/java/io/helidon/security/jwt/ExpirationValidator.java
  security/jwt/src/main/java/io/helidon/security/jwt/FieldValidator.java
  security/jwt/src/main/java/io/helidon/security/jwt/InstantValidator.java
  security/jwt/src/main/java/io/helidon/security/jwt/IssueTimeValidator.java
  security/jwt/src/main/java/io/helidon/security/jwt/Jwt.java
  security/jwt/src/main/java/io/helidon/security/jwt/JwtHeaders.java
  security/jwt/src/main/java/io/helidon/security/jwt/JwtScope.java
  security/jwt/src/main/java/io/helidon/security/jwt/JwtUtil.java
  security/jwt/src/main/java/io/helidon/security/jwt/JwtValidator.java
  security/jwt/src/main/java/io/helidon/security/jwt/JwtValidators.java
  security/jwt/src/main/java/io/helidon/security/jwt/MaxTokenAgeValidator.java
  security/jwt/src/main/java/io/helidon/security/jwt/NotBeforeValidator.java
  security/jwt/src/main/java/io/helidon/security/jwt/OptionalValidator.java
  security/jwt/src/main/java/io/helidon/security/jwt/UserPrincipalValidator.java
  security/jwt/src/main/java/io/helidon/security/jwt/ValidatorWrapper.java
  security/jwt/src/main/java/io/helidon/security/jwt/jwk/JwkOctet.java
  security/jwt/src/test/java/io/helidon/security/jwt/JwtTest.java
  security/jwt/src/test/java/io/helidon/security/jwt/JwtValidatorTest.java
  security/providers/idcs-mapper/src/main/java/io/helidon/security/providers/idcs/mapper/IdcsRoleMapperProviderBase.java
  security/providers/jwt/src/main/java/io/helidon/security/providers/jwt/JwtProvider.java
  security/providers/oidc/src/main/java/io/helidon/security/providers/oidc/TenantAuthenticationHandler.java
Labels: OCA Verified

#8873 4.x: Replace deprecated method Header.value() on Header.get()
  common/testing/http-junit5/src/main/java/io/helidon/common/testing/http/junit5/HttpHeaderMatcher.java
  examples/security/basic-auth-with-static-content/src/test/java/io/helidon/examples/security/basicauth/BasicExampleTest.java
  examples/webserver/echo/src/main/java/io/helidon/examples/webserver/echo/EchoClient.java
  http/encoding/encoding/src/main/java/io/helidon/http/encoding/ContentEncodingSupportImpl.java
  http/http/src/main/java/io/helidon/http/ClientResponseHeadersImpl.java
  http/http/src/main/java/io/helidon/http/ServerRequestHeaders.java
  http/http/src/main/java/io/helidon/http/ServerRequestHeadersImpl.java
  http/http/src/test/java/io/helidon/http/ContentDispositionTest.java
  http/http2/src/main/java/io/helidon/http/http2/Http2Headers.java
  http/http2/src/test/java/io/helidon/http/http2/Http2HeadersTest.java
  http/media/multipart/src/main/java/io/helidon/http/media/multipart/ReadablePartAbstract.java
  integrations/common/rest/src/test/java/io/helidon/integrations/common/rest/RestApiTest.java
  webclient/http1/src/main/java/io/helidon/webclient/http1/Http1CallChainBase.java
  webclient/http1/src/main/java/io/helidon/webclient/http1/Http1CallOutputStreamChain.java
  webclient/http1/src/main/java/io/helidon/webclient/http1/RedirectionProcessor.java
  webclient/websocket/src/main/java/io/helidon/webclient/websocket/WsClientImpl.java
  webserver/cors/src/test/java/io/helidon/webserver/cors/AbstractCorsTest.java
  webserver/webserver/src/main/java/io/helidon/webserver/http1/Http1ServerRequest.java
  webserver/websocket/src/main/java/io/helidon/webserver/websocket/WsUpgrader.java
Labels: OCA Verified

#8884 Correct the ordering of whenSent in doc snippet
  docs/src/main/java/io/helidon/docs/se/guides/MetricsSnippets.java
Labels: OCA Verified

#8889 Fix multi-value query string parsing
  common/uri/src/main/java/io/helidon/common/uri/UriQueryWriteable.java
  common/uri/src/main/java/io/helidon/common/uri/UriQueryWriteableImpl.java
  common/uri/src/test/java/io/helidon/common/uri/UriQueryTest.java
  webclient/api/src/main/java/io/helidon/webclient/api/ClientUri.java
  webclient/api/src/test/java/io/helidon/webclient/api/ClientUriTest.java
Labels: bug, 4.x, OCA Verified

#8891 4.x: Fixed configuration metadata of blueprints that are configured and provide a service
  builder/codegen/src/main/java/io/helidon/builder/codegen/Types.java
  builder/codegen/src/main/java/io/helidon/builder/codegen/ValidationTask.java
  builder/tests/codegen/src/test/java/io/helidon/builder/codegen/TypesTest.java
  docs/src/main/asciidoc/config/io_helidon_webserver_ListenerConfig.adoc
  docs/src/main/asciidoc/config/io_helidon_webserver_WebServer.adoc
  docs/src/main/asciidoc/config/io_helidon_webserver_cors_CorsConfig.adoc
  docs/src/main/asciidoc/config/io_helidon_webserver_cors_CorsFeature.adoc
  docs/src/main/asciidoc/config/io_helidon_webserver_grpc_GrpcConfig.adoc
  docs/src/main/asciidoc/config/io_helidon_webserver_http1_Http1Config.adoc
  docs/src/main/asciidoc/config/io_helidon_webserver_http2_Http2Config.adoc
  docs/src/main/asciidoc/config/io_helidon_webserver_observe_ObserveFeature.adoc
  docs/src/main/asciidoc/config/io_helidon_webserver_observe_config_ConfigObserver.adoc
  docs/src/main/asciidoc/config/io_helidon_webserver_observe_info_InfoObserver.adoc
  docs/src/main/asciidoc/config/io_helidon_webserver_observe_log_LogObserver.adoc
  docs/src/main/asciidoc/config/io_helidon_webserver_observe_tracing_TracingObserver.adoc
  docs/src/main/asciidoc/config/io_helidon_webserver_websocket_WsConfig.adoc
  webserver/grpc/src/main/java/io/helidon/webserver/grpc/GrpcConfigBlueprint.java
  webserver/http2/src/main/java/io/helidon/webserver/http2/Http2ConfigBlueprint.java
  webserver/observe/config/src/main/java/io/helidon/webserver/observe/config/ConfigObserverConfigBlueprint.java
  webserver/observe/info/src/main/java/io/helidon/webserver/observe/info/InfoObserverConfigBlueprint.java
  webserver/observe/log/src/main/java/io/helidon/webserver/observe/log/LogObserverConfigBlueprint.java
  webserver/observe/tracing/pom.xml
  webserver/observe/tracing/src/main/java/io/helidon/webserver/observe/tracing/TracingObserverConfigBlueprint.java
  webserver/webserver/src/main/java/io/helidon/webserver/http1/Http1ConfigBlueprint.java
  webserver/websocket/src/main/java/io/helidon/webserver/websocket/WsConfigBlueprint.java
Labels: docs, config, OCA Verified

#8890 4.x: Improved parsing of HTTP/1 prologue and headers.
  common/buffers/src/main/java/io/helidon/common/buffers/Bytes.java
  common/buffers/src/main/java/io/helidon/common/buffers/DataReader.java
  common/buffers/src/main/java/io/helidon/common/buffers/LazyString.java
  http/http/src/main/java/io/helidon/http/HeadersImpl.java
  http/http/src/main/java/io/helidon/http/Http1HeadersParser.java
  tests/benchmark/jmh/src/main/java/io/helidon/webserver/benchmark/jmh/HuJmhTest.java
  tests/benchmark/jmh/src/main/java/io/helidon/webserver/benchmark/jmh/ParsingJmhTest.java
  webserver/webserver/src/main/java/io/helidon/webserver/http1/Http1Prologue.java
Labels: performance, 4.x, OCA Verified

#8899 4.x: Bump oci-sdk to 3.43.2
  dependencies/pom.xml
Labels: dependencies, 4.x, OCA Verified

#8900 Removes usage of ConcurrentHashMap in LocalXAResource.java to avoid thread pinning in JDKs of version 22 and lower
  integrations/jta/jdbc/src/main/java/io/helidon/integrations/jta/jdbc/LocalXAResource.java
Labels: P3, jpa/jta, performance, java, 4.x, OCA Verified

#8902 2.x: Update OCI SDK to 3.43.2
  dependencies/pom.xml
Labels: 2.x, dependencies, OCI, OCA Verified

#8905 2.x: Upgrade classgraph to 4.8.165
  pom.xml
Labels: 2.x, dependencies, OCA Verified

#8904 3.x: Upgrade glassgraph to 4.8.165
  pom.xml
Labels: dependencies, 3.x, OCA Verified

#8885 After retrieval check baggage entry for null before dereferencing it
  tracing/provider-tests/src/main/java/io/helidon/tracing/providers/tests/BaggageOptionalTests.java
  tracing/providers/opentelemetry/src/main/java/io/helidon/tracing/providers/opentelemetry/MutableOpenTelemetryBaggage.java
Labels: OCA Verified

#8908 Properly handle disabled metrics in MP
  microprofile/metrics/pom.xml
  microprofile/metrics/src/main/java/io/helidon/microprofile/metrics/HelidonCounter.java
  microprofile/metrics/src/main/java/io/helidon/microprofile/metrics/HelidonGauge.java
  microprofile/metrics/src/main/java/io/helidon/microprofile/metrics/HelidonHistogram.java
  microprofile/metrics/src/main/java/io/helidon/microprofile/metrics/HelidonTimer.java
  microprofile/metrics/src/main/java/io/helidon/microprofile/metrics/MetricImpl.java
  microprofile/metrics/src/main/java/io/helidon/microprofile/metrics/Registry.java
  microprofile/metrics/src/test/java/io/helidon/microprofile/metrics/TestSelectivelyDisabledMetric.java
Labels: OCA Verified

#8912 Update metrics config default for `rest-request-enabled` and add doc text explaining SE vs. MP defaults for some values
  docs/src/main/asciidoc/config/io_helidon_metrics_api_MetricsConfig.adoc
  docs/src/main/asciidoc/includes/metrics/metrics-config.adoc
  metrics/api/src/main/java/io/helidon/metrics/api/MetricsConfigBlueprint.java
Labels: OCA Verified

#8883 4.x: Use Hamcrest assertions instead of JUnit in common/buffers (#1749)
  common/buffers/src/test/java/io/helidon/common/buffers/AsciiTest.java
Labels: OCA Verified

#8479 Refactors JtaConnection to allow status enforcement by JTA implementation
  integrations/cdi/jpa-cdi/pom.xml
  integrations/cdi/jpa-cdi/src/main/java/io/helidon/integrations/cdi/jpa/JtaAdaptingDataSourceProvider.java
  integrations/jta/jdbc/src/main/java/io/helidon/integrations/jta/jdbc/JtaAdaptingDataSource.java
  integrations/jta/jdbc/src/main/java/io/helidon/integrations/jta/jdbc/JtaConnection.java
  integrations/jta/jdbc/src/main/java/io/helidon/integrations/jta/jdbc/LocalXAResource.java
  integrations/jta/jdbc/src/test/java/io/helidon/integrations/jta/jdbc/TestJtaConnection.java
  integrations/jta/jdbc/src/test/java/io/helidon/integrations/jta/jdbc/TestNarayanaBehavior.java
Labels: enhancement, P4, jpa/jta, integration, java, 4.x, OCA Verified

#8919 4.x: Add post pr merge workflow to support continuous snapshot deployments
  .github/workflows/pr-merge.yaml
  .github/workflows/snapshotrelease.yaml
  .github/workflows/validate.yml
Labels: build, 4.x, OCA Verified

#8923 4.x: Fix typo in pr-merge workflow
  .github/workflows/pr-merge.yaml
Labels: build, 4.x, OCA Verified

#8924 4.x pr merge workflow concurrency
  .github/workflows/pr-merge.yaml
  .github/workflows/validate.yml
Labels: build, 4.x, OCA Verified

#8925 4.x: Allow snapshot workflow to inherit secrets
  .github/workflows/pr-merge.yaml
Labels: build, 4.x, OCA Verified

#8921 4.x: Service registry OCI integration update
  docs/src/main/asciidoc/config/io_helidon_integrations_oci_sdk_runtime_OciConfig.adoc
  integrations/oci/authentication/README.md
  integrations/oci/authentication/instance/src/main/java/io/helidon/integrations/oci/authentication/instance/AuthenticationMethodInstancePrincipal.java
  integrations/oci/authentication/instance/src/main/java/io/helidon/integrations/oci/authentication/instance/InstancePrincipalBuilderProvider.java
  integrations/oci/authentication/oke-workload/src/main/java/io/helidon/integrations/oci/authentication/okeworkload/AuthenticationMethodOkeWorkload.java
  integrations/oci/authentication/oke-workload/src/main/java/io/helidon/integrations/oci/authentication/okeworkload/OkeWorkloadBuilderProvider.java
  integrations/oci/authentication/resource/src/main/java/io/helidon/integrations/oci/authentication/resource/AuthenticationMethodResourcePrincipal.java
  integrations/oci/authentication/resource/src/main/java/io/helidon/integrations/oci/authentication/resource/ResourcePrincipalBuilderProvider.java
  integrations/oci/oci/README.md
  integrations/oci/oci/src/main/java/io/helidon/integrations/oci/AdpProvider.java
  integrations/oci/oci/src/main/java/io/helidon/integrations/oci/AuthenticationMethodConfig.java
  integrations/oci/oci/src/main/java/io/helidon/integrations/oci/AuthenticationMethodConfigFile.java
  integrations/oci/oci/src/main/java/io/helidon/integrations/oci/AuthenticationMethodSessionToken.java
  integrations/oci/oci/src/main/java/io/helidon/integrations/oci/OciConfigBlueprint.java
  integrations/oci/oci/src/main/java/io/helidon/integrations/oci/RegionProviderAuthenticationMethod.java
  integrations/oci/oci/src/main/java/io/helidon/integrations/oci/spi/OciAuthenticationMethod.java
  integrations/oci/oci/src/main/java/module-info.java
  integrations/oci/oci/src/test/java/io/helidon/integrations/oci/OciIntegrationTest.java
  integrations/oci/tests/authentication/src/test/java/io/helidon/integrations/oci/AuthenticationDetailsProvidersTest.java
Labels: OCI, 4.x, OCA Verified
