Repository helidon-io/helidon, pull requests merged in 2024-01, with the labels that each got.

#7328 3.x Make OciMetricsDataTest.beforeEach non private
  integrations/oci/metrics/metrics/src/test/java/io/helidon/integrations/oci/metrics/OciMetricsDataTest.java
Labels: OCA Verified

#8174 4.x: Jersey 3.1.5
  dependencies/pom.xml
  microprofile/tests/tck/tck-restful/tck-restful-test/pom.xml
Labels: dependencies, 4.x, OCA Verified, jersey

#8194 Fix copyrights from an earlier merge
  dependencies/pom.xml
  inject/tests/resources-inject/src/test/java/io/helidon/inject/tests/inject/interceptor/InterceptorRuntimeTest.java
  inject/tests/resources-inject/src/test/resources/expected/yimpl-interceptor._java_
  microprofile/tests/tck/tck-restful/tck-restful-test/pom.xml
Labels: OCA Verified

#8193 4.x Realign SE tracing guide to code
  docs/src/main/asciidoc/images/guides/tracing_se_expanded_trace.png
  docs/src/main/asciidoc/images/guides/tracing_se_first_span.png
  docs/src/main/asciidoc/images/guides/tracing_se_first_trace.png
  docs/src/main/asciidoc/images/guides/tracing_se_second_expanded_trace.png
  docs/src/main/asciidoc/images/guides/tracing_se_second_trace_list.png
  docs/src/main/asciidoc/images/guides/tracing_se_span_detail.png
  docs/src/main/asciidoc/images/guides/tracing_se_trace_list.png
  docs/src/main/asciidoc/se/guides/tracing.adoc
Labels: OCA Verified

#8201 Fix image sizing in SE tracing guide
  docs/src/main/asciidoc/css/styles.css
  docs/src/main/asciidoc/se/guides/tracing.adoc
Labels: OCA Verified

#8166 4.x Include scheme and port of origin and host in deciding whether to classify a request as CORS or not
  cors/src/main/java/io/helidon/cors/CorsRequestAdapter.java
  cors/src/main/java/io/helidon/cors/CorsSupportHelper.java
  cors/src/main/java/io/helidon/cors/LogHelper.java
  cors/src/test/java/io/helidon/cors/CorsSupportHelperTest.java
  cors/src/test/java/io/helidon/cors/TestCorsServerRequestAdapter.java
  cors/src/test/java/io/helidon/cors/TestCorsServerResponseAdapter.java
  cors/src/test/resources/configMapperTest.yaml
  microprofile/cors/src/main/java/io/helidon/microprofile/cors/CorsSupportMp.java
  webserver/cors/src/main/java/io/helidon/webserver/cors/CorsServerRequestAdapter.java
Labels: OCA Verified

#8203 3.x upgrade jsonp-api to 2.0.2
  dependencies/pom.xml
  integrations/oci/metrics/metrics/src/test/java/io/helidon/integrations/oci/metrics/OciMetricsDataTest.java
Labels: dependencies, 3.x, OCA Verified

#8198 The Helidon WS client must include a Connection header
  webclient/websocket/src/main/java/io/helidon/webclient/websocket/WsClientImpl.java
  webserver/tests/websocket/src/main/java/io/helidon/webserver/tests/websocket/EchoService.java
Labels: bug, websocket, 4.x, OCA Verified

#8207 Fixed IDCS role obtaining
  security/providers/idcs-mapper/src/main/java/io/helidon/security/providers/idcs/mapper/IdcsRoleMapperProvider.java
Labels: OCA Verified

#8210 4.x Allow programmatic look-up of MetricRegistry via CDI without NPE
  microprofile/metrics/src/main/java/io/helidon/microprofile/metrics/RegistryProducer.java
  microprofile/metrics/src/test/java/io/helidon/microprofile/metrics/ProducerTest.java
Labels: OCA Verified

#8153 OIDC id token validation and token refresh
  docs/src/main/asciidoc/config/io_helidon_security_providers_oidc_OidcProvider.adoc
  docs/src/main/asciidoc/config/io_helidon_security_providers_oidc_common_OidcConfig.adoc
  microprofile/security/src/main/java/io/helidon/microprofile/security/SecurityFilter.java
  microprofile/security/src/main/java/io/helidon/microprofile/security/SecurityFilterCommon.java
  security/providers/oidc-common/src/main/java/io/helidon/security/providers/oidc/common/OidcConfig.java
  security/providers/oidc/src/main/java/io/helidon/security/providers/oidc/OidcFeature.java
  security/providers/oidc/src/main/java/io/helidon/security/providers/oidc/TenantAuthenticationHandler.java
  tests/integration/oidc/src/test/java/io/helidon/tests/integration/oidc/CommonLoginBase.java
  tests/integration/oidc/src/test/java/io/helidon/tests/integration/oidc/IdTokenIT.java
  tests/integration/oidc/src/test/java/io/helidon/tests/integration/oidc/QueryBasedLoginIT.java
  tests/integration/oidc/src/test/java/io/helidon/tests/integration/oidc/RefreshTokenIT.java
  tests/integration/oidc/src/test/resources/application-no-cookie.yaml
  webserver/security/src/main/java/io/helidon/webserver/security/SecurityHttpFeature.java
Labels: OCA Verified

#8197 Fix issue for checking if app is running in an OCI instance which causes Instance Principal auth to fail
  integrations/oci/sdk/runtime/pom.xml
  integrations/oci/sdk/runtime/src/main/java/io/helidon/integrations/oci/sdk/runtime/OciAvailabilityDefault.java
  integrations/oci/sdk/runtime/src/test/java/io/helidon/integrations/oci/sdk/runtime/OciAvailabilityTest.java
Labels: OCI, OCA Verified

#8202 4.x upgrade jsonp 2.1.3
  dependencies/pom.xml
  microprofile/tests/tck/tck-jsonp/tck-jsonp-pluggability-test/pom.xml
  microprofile/tests/tck/tck-jsonp/tck-jsonp-test/pom.xml
  pom.xml
Labels: dependencies, 4.x, OCA Verified

#8214 4.x depcheck 9.0.8
  etc/dependency-check-suppression.xml
  pom.xml
Labels: 4.x, OCA Verified

#8213 Remove references to any JDK from examples
  examples/cors/README.md
  examples/integrations/micrometer/mp/README.md
  examples/integrations/micrometer/se/README.md
  examples/jbatch/README.md
  examples/metrics/exemplar/README.md
  examples/metrics/http-status-count-se/README.md
  examples/metrics/kpi/README.md
  examples/microprofile/bean-validation/README.md
  examples/microprofile/http-status-count-mp/README.md
  examples/microprofile/messaging-sse/README.md
  examples/microprofile/multiport/README.md
  examples/microprofile/telemetry/README.md
  examples/quickstarts/helidon-quickstart-mp/README.md
  examples/quickstarts/helidon-standalone-quickstart-mp/README.md
  examples/quickstarts/helidon-standalone-quickstart-se/README.md
  examples/webserver/multiport/README.md
Labels: examples, 4.x, OCA Verified

#8206 4.x: TLS default config values
  common/tls/src/main/java/io/helidon/common/tls/ConfiguredTlsManager.java
  common/tls/src/main/java/io/helidon/common/tls/TlsConfigBlueprint.java
Labels: OCA Verified

#8215 Check result of Integer.parseUnsignedInt() to be non-negative
  common/common/src/main/java/io/helidon/common/ParserHelper.java
  common/common/src/test/java/io/helidon/common/ParserHelperTest.java
  webclient/http1/src/main/java/io/helidon/webclient/http1/Http1CallChainBase.java
  webserver/webserver/src/main/java/io/helidon/webserver/http1/Http1Connection.java
Labels: webserver, webclient, OCA Verified

#8219 4.x: fix broken documentation links Part 1
  docs/src/main/asciidoc/guides/jib.adoc
  docs/src/main/asciidoc/includes/attributes.adoc
  docs/src/main/asciidoc/includes/openapi/openapi.adoc
  docs/src/main/asciidoc/mp/beanvalidation.adoc
  docs/src/main/asciidoc/mp/config/introduction.adoc
  docs/src/main/asciidoc/mp/fault-tolerance.adoc
  docs/src/main/asciidoc/mp/guides/mp-tutorial.adoc
  docs/src/main/asciidoc/mp/guides/upgrade_4x.adoc
  docs/src/main/asciidoc/mp/metrics/metrics.adoc
  docs/src/main/asciidoc/mp/openapi/openapi.adoc
  docs/src/main/asciidoc/mp/persistence.adoc
  docs/src/main/asciidoc/mp/testing-ng.adoc
  docs/src/main/asciidoc/se/guides/tracing.adoc
  docs/src/main/asciidoc/se/security/providers.adoc
Labels: docs, 4.x, OCA Verified

#7902 3.x: TLS replace in HelidonConnector fix
  jersey/connector/src/main/java/io/helidon/jersey/connector/HelidonConnector.java
  tests/integration/pom.xml
  tests/integration/restclient-connector/pom.xml
  tests/integration/restclient-connector/src/main/java/io/helidon/tests/integration/resclient/connector/GreetResource.java
  tests/integration/restclient-connector/src/main/java/io/helidon/tests/integration/resclient/connector/GreetResourceClient.java
  tests/integration/restclient-connector/src/main/java/io/helidon/tests/integration/resclient/connector/GreetResourceFilter.java
  tests/integration/restclient-connector/src/main/java/io/helidon/tests/integration/resclient/connector/package-info.java
  tests/integration/restclient-connector/src/main/resources/META-INF/beans.xml
  tests/integration/restclient-connector/src/test/java/io/helidon/tests/integration/restclient/connector/TlsTest.java
  tests/integration/restclient-connector/src/test/resources/server.p12
  tests/integration/restclient-connector/src/test/resources/tls-config.properties
Labels: OCA Verified

#8224 WebClientService duplication fix
  webclient/api/src/main/java/io/helidon/webclient/spi/WebClientService.java
  webclient/metrics/src/main/java/io/helidon/webclient/metrics/WebClientMetric.java
  webclient/security/src/main/java/io/helidon/webclient/security/WebClientSecurity.java
  webclient/tests/webclient/src/test/java/io/helidon/webclient/tests/WebClientServiceTest.java
  webclient/tracing/src/main/java/io/helidon/webclient/tracing/WebClientTracing.java
Labels: OCA Verified

#8212 Add a little logic to CORS config processing and significantly update the CORS doc
  cors/src/main/java/io/helidon/cors/Aggregator.java
  cors/src/main/java/io/helidon/cors/CorsSupportHelper.java
  cors/src/main/java/io/helidon/cors/LogHelper.java
  cors/src/test/java/io/helidon/cors/CrossOriginConfigTest.java
  cors/src/test/resources/configMapperTest.yaml
  docs/src/main/asciidoc/includes/attributes.adoc
  docs/src/main/asciidoc/includes/cors.adoc
  docs/src/main/asciidoc/mp/cors/cors.adoc
  docs/src/main/asciidoc/se/cors.adoc
Labels: OCA Verified

#8216 4.x Add support for `@SpanAttribute` annotation, use entire path for REST resource span name
  common/testing/junit5/src/main/java/io/helidon/common/testing/junit5/MatcherWithRetry.java
  microprofile/telemetry/pom.xml
  microprofile/telemetry/src/main/java/io/helidon/microprofile/telemetry/HelidonTelemetryContainerFilter.java
  microprofile/telemetry/src/main/java/io/helidon/microprofile/telemetry/TelemetryCdiExtension.java
  microprofile/telemetry/src/main/java/io/helidon/microprofile/telemetry/WithSpanInterceptor.java
  microprofile/telemetry/src/main/java/module-info.java
  microprofile/telemetry/src/test/java/io/helidon/microprofile/telemetry/App.java
  microprofile/telemetry/src/test/java/io/helidon/microprofile/telemetry/AppTracedResource.java
  microprofile/telemetry/src/test/java/io/helidon/microprofile/telemetry/TestSpanExporter.java
  microprofile/telemetry/src/test/java/io/helidon/microprofile/telemetry/TestSpanExporterProvider.java
  microprofile/telemetry/src/test/java/io/helidon/microprofile/telemetry/TracedResource.java
  microprofile/telemetry/src/test/java/io/helidon/microprofile/telemetry/WithSpanBean.java
  microprofile/telemetry/src/test/java/io/helidon/microprofile/telemetry/WithSpanTest.java
  microprofile/telemetry/src/test/java/io/helidon/microprofile/telemetry/WithSpanTestBase.java
  microprofile/telemetry/src/test/java/io/helidon/microprofile/telemetry/WithSpanWithExplicitAppTest.java
  microprofile/telemetry/src/test/resources/META-INF/services/io.opentelemetry.sdk.autoconfigure.spi.traces.ConfigurableSpanExporterProvider
  microprofile/tests/telemetry/src/test/java/io/helidon/microprofile/telemetry/RestSpanHierarchyTest.java
Labels: OCA Verified

#8231 Support for Map<String, String> in configured builders.
  builder/processor/src/main/java/io/helidon/builder/processor/TypeHandlerMap.java
  builder/tests/builder/src/main/java/io/helidon/builder/test/testsubjects/ConfigMapBlueprint.java
  builder/tests/builder/src/test/java/io/helidon/builder/test/ConfigMapTest.java
  builder/tests/builder/src/test/resources/config-map-test.yaml
Labels: config, OCA Verified, builder

#8225 Manage scopes correctly with baggage; allow baggage to be mutable to honor the Helidon `Span#baggage` semantics
  tracing/providers/opentelemetry/pom.xml
  tracing/providers/opentelemetry/src/main/java/io/helidon/tracing/providers/opentelemetry/MutableOpenTelemetryBaggage.java
  tracing/providers/opentelemetry/src/main/java/io/helidon/tracing/providers/opentelemetry/OpenTelemetryScope.java
  tracing/providers/opentelemetry/src/main/java/io/helidon/tracing/providers/opentelemetry/OpenTelemetrySpan.java
  tracing/providers/opentelemetry/src/test/java/io/helidon/tracing/providers/opentelemetry/TestSpanAndBaggage.java
Labels: OCA Verified

#8232 Prevent Helidon connector from re-encoding URI
  common/uri/src/main/java/io/helidon/common/uri/UriEncoding.java
  common/uri/src/test/java/io/helidon/common/uri/UriEncodingTest.java
  jersey/connector/src/main/java/io/helidon/jersey/connector/HelidonConnector.java
  jersey/tests/connector/src/test/java/io/helidon/jersey/connector/ConnectorBase.java
Labels: webserver, jax-rs, webclient, 4.x, OCA Verified

#8235 Ensures that the enabled flag is honored in JpaExtension's observer methods
  archetypes/helidon/src/main/archetype/common/observability.xml
  integrations/cdi/jpa-cdi/src/main/java/io/helidon/integrations/cdi/jpa/JpaExtension.java
  integrations/cdi/jpa-cdi/src/main/java/io/helidon/integrations/cdi/jpa/PersistenceExtension.java
  integrations/cdi/jpa-cdi/src/test/java/io/helidon/integrations/cdi/jpa/TestAnnotationRewriting.java
Labels: bug, MP, P4, cdi, jpa/jta, integration, java, 4.x, OCA Verified

#8184 Remove unnecessary GreetingProvider from example custom liveness health check
  docs/src/main/asciidoc/mp/guides/health.adoc
Labels: OCA Verified

#8251 4.x: Fix for buffer data when created with an offset.
  common/buffers/src/main/java/io/helidon/common/buffers/FixedBufferData.java
Labels: webserver, 4.x, OCA Verified

#8238 Add back span name test containing an explicit Application bean
  microprofile/telemetry/pom.xml
  microprofile/telemetry/src/test/java/io/helidon/microprofile/telemetry/WithSpanTestBase.java
  microprofile/telemetry/src/test/java/io/helidon/microprofile/telemetry/WithSpanWithExplicitAppTest.java
Labels: OCA Verified

#8244 3.x Backport of scope/baggage fix
  tracing/opentelemetry/pom.xml
  tracing/opentelemetry/src/main/java/io/helidon/tracing/opentelemetry/MutableOpenTelemetryBaggage.java
  tracing/opentelemetry/src/main/java/io/helidon/tracing/opentelemetry/OpenTelemetryScope.java
  tracing/opentelemetry/src/main/java/io/helidon/tracing/opentelemetry/OpenTelemetrySpan.java
  tracing/opentelemetry/src/test/java/io/helidon/tracing/opentelemetry/TestSpanAndBaggage.java
Labels: OCA Verified

#8240 2.x: Security propagation is now disabled with not configured
  microprofile/jwt-auth/src/main/java/io/helidon/microprofile/jwt/auth/JwtAuthProvider.java
  microprofile/jwt-auth/src/test/java/io/helidon/microprofile/jwt/auth/JwtAuthProviderTest.java
  microprofile/jwt-auth/src/test/resources/application.yaml
Labels: OCA Verified

#8239 4.x: Security propagation is now disabled with not configured
  microprofile/jwt-auth/src/main/java/io/helidon/microprofile/jwt/auth/JwtAuthProvider.java
  microprofile/jwt-auth/src/test/java/io/helidon/microprofile/jwt/auth/JwtAuthProviderTest.java
  microprofile/jwt-auth/src/test/resources/application.yaml
Labels: OCA Verified

#8258 Slight clean-up of recent baggage and span scope fix
  tracing/providers/opentelemetry/src/main/java/io/helidon/tracing/providers/opentelemetry/OpenTelemetryScope.java
  tracing/providers/opentelemetry/src/main/java/io/helidon/tracing/providers/opentelemetry/OpenTelemetrySpan.java
Labels: OCA Verified

#8242 Some minor optimizations in WebServer
  common/buffers/src/main/java/io/helidon/common/buffers/CompositeArrayBufferData.java
  common/buffers/src/main/java/io/helidon/common/buffers/CompositeListBufferData.java
  http/http/src/main/java/io/helidon/http/HeadersImpl.java
Labels: performance, 4.x, OCA Verified

#8253 4.x: JSON unicode detection without UTF-32 workaround
  security/jwt/src/main/java/io/helidon/security/jwt/jwk/JwkKeys.java
Labels: native-image, OCA Verified

#8259 4.x: Doc broken link fix
  docs/src/main/asciidoc/se/webclient.adoc
Labels: docs, OCA Verified

#8236 Change backport action to accept target versions for porting via checkboxes and select current issue's version from a list
  .github/workflows/create-backport-issues.yml
  etc/scripts/actions/create-backport-issues.sh
Labels: OCA Verified

#8257 [4.x] Guard against NPE during early invocation of Span.current()
  tracing/tracing/src/main/java/io/helidon/tracing/TracerProviderHelper.java
  tracing/tracing/src/test/java/io/helidon/tracing/TestEarlyUseOfSpanCurrent.java
  tracing/tracing/src/test/java/io/helidon/tracing/TestTracerProvider.java
  tracing/tracing/src/test/resources/META-INF/services/io.helidon.tracing.spi.TracerProvider
Labels: OCA Verified

#8256 [3.x] Guard against NPE during early invocation of Span.current()
  tracing/tracing/src/main/java/io/helidon/tracing/TracerProviderHelper.java
  tracing/tracing/src/test/java/io/helidon/tracing/TestEarlyUseOfSpanCurrent.java
  tracing/tracing/src/test/java/io/helidon/tracing/TestTracerProvider.java
  tracing/tracing/src/test/resources/META-INF/services/io.helidon.tracing.spi.TracerProvider
Labels: OCA Verified

#8261 4.x: Docs: change WebServer.Builder to WebServerConfig.Builder.
  docs/src/main/asciidoc/se/guides/health.adoc
  docs/src/main/asciidoc/se/testing.adoc
Labels: docs, 4.x, OCA Verified

#8273 3.x: upgrade dependency check. Suppress fp
  etc/dependency-check-suppression.xml
  pom.xml
Labels: 4.x, OCA Verified

#8277 3x.: Upgrading to latest Tyrus 2.1.5
  dependencies/pom.xml
Labels: 3.x, websocket, OCA Verified

#8279 4.x: Fix vault tests
  tests/integration/pom.xml
  tests/integration/vault/src/test/java/io/helidon/examples/integrations/vault/hcp/VaultTest.java
Labels: testing, OCA Verified

#8274 [4.x] Set weight for `WebClientTracing` provider greater than that for `WebClientSecurity` provider
  webclient/security/pom.xml
  webclient/security/src/test/java/io/helidon/webclient/security/ServiceProviderWeightTest.java
  webclient/tracing/src/main/java/io/helidon/webclient/tracing/WebClientTracingProvider.java
Labels: OCA Verified

#8272 Upgrade Yasson to 3.0.3
  dependencies/pom.xml
Labels: json, dependencies, 4.x, OCA Verified

#8278 4.x: Upgrading to latest Tyrus 2.1.5
  dependencies/pom.xml
Labels: 4.x, OCA Verified

#8264 Manually count number of offered tasks instead of relying on pool active count
  common/configurable/src/main/java/io/helidon/common/configurable/ThreadPool.java
  common/configurable/src/test/java/io/helidon/common/configurable/ThreadPoolTest.java
Labels: bug, 3.x, common, OCA Verified

#8247 4.x: TLS replace in HelidonConnector fix
  jersey/connector/src/main/java/io/helidon/jersey/connector/HelidonConnector.java
  tests/integration/pom.xml
  tests/integration/restclient-connector/pom.xml
  tests/integration/restclient-connector/src/main/java/io/helidon/tests/integration/resclient/connector/GreetResource.java
  tests/integration/restclient-connector/src/main/java/io/helidon/tests/integration/resclient/connector/GreetResourceClient.java
  tests/integration/restclient-connector/src/main/java/io/helidon/tests/integration/resclient/connector/GreetResourceFilter.java
  tests/integration/restclient-connector/src/main/java/io/helidon/tests/integration/resclient/connector/package-info.java
  tests/integration/restclient-connector/src/main/resources/META-INF/beans.xml
  tests/integration/restclient-connector/src/test/java/io/helidon/tests/integration/restclient/connector/TlsTest.java
  tests/integration/restclient-connector/src/test/resources/server.p12
  tests/integration/restclient-connector/src/test/resources/tls-config.properties
Labels: OCA Verified

#8280 Cleans up and simplifies logic to determine which type of IP addresses to consider
  webclient/api/pom.xml
  webclient/api/src/main/java/io/helidon/webclient/api/DefaultAddressLookupFinder.java
  webclient/api/src/main/java/io/helidon/webclient/api/DefaultDnsResolver.java
  webclient/api/src/main/java/io/helidon/webclient/api/TcpClientConnection.java
  webclient/api/src/main/java/io/helidon/webclient/spi/DnsResolver.java
  webclient/api/src/test/java/io/helidon/webclient/api/DefaultDnsResolverTest.java
  webclient/api/src/test/java/io/helidon/webclient/api/Ipv4LookupFinderTest.java
  webclient/api/src/test/java/io/helidon/webclient/api/Ipv6LookupFinderTest.java
  webserver/tests/http2/src/test/java/io/helidon/webserver/tests/http2/EmptyFrameCntTest.java
Labels: webclient, 4.x, OCA Verified

#8284 Http client protocol creation not honoring disabled service discovery
  webclient/http1/src/main/java/io/helidon/webclient/http1/Http1ClientSpiProvider.java
  webclient/http2/src/main/java/io/helidon/webclient/http2/Http2ClientSpiProvider.java
Labels: OCA Verified

#8295 Authorized set to false fix
  microprofile/security/src/main/java/io/helidon/microprofile/security/SecurityDefinition.java
  tests/integration/security/pom.xml
  tests/integration/security/security-annotation/pom.xml
  tests/integration/security/security-annotation/src/main/java/io/helidon/tests/integration/security/annotation/AdminResource.java
  tests/integration/security/security-annotation/src/main/resources/META-INF/beans.xml
  tests/integration/security/security-annotation/src/main/resources/application.yaml
  tests/integration/security/security-annotation/src/main/resources/logging.properties
  tests/integration/security/security-annotation/src/test/java/io/helidon/tests/integration/security/pathparams/AdminTest.java
Labels: OCA Verified

#8300 4.x: fix broken documentation links Part 2
  docs/src/main/asciidoc/includes/attributes.adoc
  docs/src/main/asciidoc/includes/cors.adoc
  docs/src/main/asciidoc/includes/metrics/metrics-shared.adoc
  docs/src/main/asciidoc/mp/cors/cors.adoc
  docs/src/main/asciidoc/mp/fault-tolerance.adoc
  docs/src/main/asciidoc/se/config/advanced-configuration.adoc
  docs/src/main/asciidoc/se/config/config-profiles.adoc
  docs/src/main/asciidoc/se/config/supported-formats.adoc
  docs/src/main/asciidoc/se/metrics/metrics.adoc
  docs/src/main/asciidoc/se/metrics/micrometer.adoc
  docs/src/main/asciidoc/se/openapi/openapi-generator.adoc
  docs/src/main/asciidoc/se/openapi/openapi-ui.adoc
  docs/src/main/asciidoc/se/openapi/openapi.adoc
  docs/src/main/asciidoc/se/webserver.adoc
Labels: OCA Verified

#8301 4.x: Use vararg instead of optional (as a name).
  codegen/class-model/src/main/java/io/helidon/codegen/classmodel/Parameter.java
Labels: 4.x, OCA Verified, codegen

#8292 Remove clear-out of registries from extension; do it in TCK-only shutdown observer; update doc
  docs/src/main/asciidoc/mp/metrics/metrics.adoc
  microprofile/metrics/src/main/java/io/helidon/microprofile/metrics/MetricsCdiExtension.java
  microprofile/metrics/src/main/java/io/helidon/microprofile/metrics/RegistryFactory.java
  microprofile/tests/tck/tck-metrics/src/test/java/io/helidon/microprofile/metrics/tck/MetricsTckCdiExtension.java
Labels: 4.x, OCA Verified

#8304 Upgrade OCI SDK to 3.31.1
  dependencies/pom.xml
Labels: dependencies, OCI, 4.x, OCA Verified

#8303 Set incoming baggage from parent on Span
  tracing/providers/opentelemetry/src/main/java/io/helidon/tracing/providers/opentelemetry/OpenTelemetrySpanBuilder.java
  tracing/providers/opentelemetry/src/test/java/io/helidon/tracing/providers/opentelemetry/MapHeaderProvider.java
  tracing/providers/opentelemetry/src/test/java/io/helidon/tracing/providers/opentelemetry/TestSpanAndBaggage.java
  tracing/providers/opentracing/src/main/java/io/helidon/tracing/providers/opentracing/OpenTracingSpanBuilder.java
Labels: OCA Verified

#8298 Fix unwrap methods to return cast delegates rather than cast 'this'
  tracing/providers/opentelemetry/pom.xml
  tracing/providers/opentelemetry/src/main/java/io/helidon/tracing/providers/opentelemetry/OpenTelemetrySpan.java
  tracing/providers/opentelemetry/src/main/java/io/helidon/tracing/providers/opentelemetry/OpenTelemetrySpanBuilder.java
  tracing/providers/opentelemetry/src/main/java/io/helidon/tracing/providers/opentelemetry/OpenTelemetrySpanContext.java
  tracing/providers/opentelemetry/src/test/java/io/helidon/tracing/providers/opentelemetry/OtelTestsJunitExtension.java
  tracing/providers/opentelemetry/src/test/java/io/helidon/tracing/providers/opentelemetry/TestSpanAndBaggage.java
  tracing/providers/opentelemetry/src/test/java/io/helidon/tracing/providers/opentelemetry/TestUnwrap.java
  tracing/providers/opentelemetry/src/test/resources/META-INF/services/org.junit.jupiter.api.extension.Extension
  tracing/providers/opentracing/src/main/java/io/helidon/tracing/providers/opentracing/OpenTracingContext.java
  tracing/providers/opentracing/src/main/java/io/helidon/tracing/providers/opentracing/OpenTracingSpan.java
  tracing/providers/opentracing/src/main/java/io/helidon/tracing/providers/opentracing/OpenTracingSpanBuilder.java
  tracing/providers/opentracing/src/test/java/io/helidon/tracing/providers/opentracing/TestUnwrap.java
  tracing/tracing/src/main/java/io/helidon/tracing/NoOpTracer.java
  tracing/tracing/src/main/java/io/helidon/tracing/Tracer.java
Labels: OCA Verified

#8312 Add null check for resource path in filter
  microprofile/telemetry/src/main/java/io/helidon/microprofile/telemetry/HelidonTelemetryContainerFilter.java
Labels: OCA Verified
