Repository helidon-io/helidon, pull requests merged in 2024-02, with the labels that each got.

#8318 [4.x] Fix CachedHandlerTest.testFsFromInMemory on Windows
  webserver/static-content/src/main/java/io/helidon/webserver/staticcontent/FileSystemContentHandler.java
Labels: webserver, 4.x, OCA Verified

#8322 [4.x] Fix KafkaSeTest on Windows
  tests/integration/kafka/src/test/java/io/helidon/messaging/connectors/kafka/KafkaSeTest.java
Labels: testing, 4.x, OCA Verified

#8323 OIDC improvement
  security/providers/oidc-common/src/main/java/io/helidon/security/providers/oidc/common/OidcConfig.java
  security/providers/oidc/src/main/java/io/helidon/security/providers/oidc/OidcFeature.java
  security/providers/oidc/src/main/java/io/helidon/security/providers/oidc/TenantAuthenticationHandler.java
  tests/integration/oidc/src/test/java/io/helidon/tests/integration/oidc/CommonLoginBase.java
  tests/integration/oidc/src/test/java/io/helidon/tests/integration/oidc/CookieBasedLoginIT.java
  tests/integration/oidc/src/test/java/io/helidon/tests/integration/oidc/IdTokenIT.java
  tests/integration/oidc/src/test/java/io/helidon/tests/integration/oidc/QueryBasedLoginIT.java
  tests/integration/oidc/src/test/java/io/helidon/tests/integration/oidc/RefreshTokenIT.java
  tests/integration/oidc/src/test/java/io/helidon/tests/integration/oidc/SecurityPartsIT.java
Labels: OCA Verified

#8327 Fixes a few problems handling character encodings in URIs
  common/uri/src/main/java/io/helidon/common/uri/UriQueryWriteableImpl.java
  jersey/connector/src/main/java/io/helidon/jersey/connector/HelidonConnector.java
  jersey/tests/connector/src/test/java/io/helidon/jersey/connector/ConnectorBase.java
  microprofile/telemetry/pom.xml
  webclient/api/src/main/java/io/helidon/webclient/api/ClientUri.java
  webclient/api/src/test/java/io/helidon/webclient/api/ClientUriTest.java
Labels: rest-client, 4.x, OCA Verified, jersey

#8328 Calls clearData() on all data propagation providers.
  webclient/webclient/src/main/java/io/helidon/webclient/WebClientRequestBuilderImpl.java
Labels: webclient, 3.x, OCA Verified

#8332 [2.x] Archetype - Add Main class to MP projects
  archetypes/bare-mp/src/main/resources/pom.xml.mustache
  archetypes/bare-mp/src/main/resources/src/main/java/__pkg__/Main.java.mustache
  archetypes/database-mp/src/main/resources/pom.xml.mustache
  archetypes/database-mp/src/main/resources/src/main/java/__pkg__/Main.java.mustache
  archetypes/quickstart-mp/src/main/resources/pom.xml.mustache
  archetypes/quickstart-mp/src/main/resources/src/main/java/__pkg__/Main.java.mustache
Labels: 2.x, archetypes, OCA Verified

#8346 3.x: Upgrade to Jersey 3.0.12
  dependencies/pom.xml
Labels: dependencies, 3.x, OCA Verified, jersey

#8347 Upgrade to Jersey 2.41
  dependencies/pom.xml
Labels: 2.x, dependencies, OCA Verified, jersey

#8351 3.x: Upgrade OCI SDK to 3.34.0
  archetypes/helidon/src/main/archetype/mp/oci/files/server/src/test/java/__pkg__/server/GreetResourceMockedTest.java.mustache
  dependencies/pom.xml
  integrations/oci/metrics/cdi/src/test/java/io/helidon/integrations/oci/metrics/cdi/OciMetricsCdiExtensionTest.java
Labels: dependencies, 3.x, OCI, OCA Verified

#8354 Introduces Dependabot configuration file to help manage OCI updates
  .github/dependabot.yml
Labels: build, dependencies, 4.x, OCA Verified

#8359 4.x: Installs a convenient default for connectionPoolName in UCPBackedDataSourceExtension when appropriate
  integrations/cdi/datasource-ucp/src/main/java/io/helidon/integrations/datasource/ucp/cdi/UCPBackedDataSourceExtension.java
  integrations/cdi/datasource-ucp/src/test/java/io/helidon/integrations/datasource/ucp/cdi/TestDataSourceAcquisition.java
  integrations/cdi/datasource-ucp/src/test/java/io/helidon/integrations/datasource/ucp/cdi/TestUcpApi.java
Labels: P4, jpa/jta, 4.x, OCA Verified

#8368 4.x: Restfull tck 3.1.5
  microprofile/tests/tck/tck-restful/tck-restful-test/pom.xml
  pom.xml
Labels: OCA Verified

#8374 Use OTel AgentDetector instead of just system property - review comments from earlier PR
  microprofile/telemetry/src/main/java/io/helidon/microprofile/telemetry/HelidonTelemetryContainerFilter.java
  microprofile/telemetry/src/main/java/io/helidon/microprofile/telemetry/TelemetryCdiExtension.java
  microprofile/telemetry/src/main/java/io/helidon/microprofile/telemetry/WithSpanInterceptor.java
  microprofile/telemetry/src/test/java/io/helidon/microprofile/telemetry/AgentDetectorTest.java
  tracing/providers/opentelemetry/src/main/java/io/helidon/tracing/providers/opentelemetry/HelidonOpenTelemetry.java
Labels: OCA Verified

#8375 4.x: Multipart fixes (streaming, consume)
  http/media/multipart/src/main/java/io/helidon/http/media/multipart/ReadablePartLength.java
  http/media/multipart/src/main/java/io/helidon/http/media/multipart/ReadablePartNoLength.java
  webserver/tests/webserver/pom.xml
  webserver/tests/webserver/src/test/java/io/helidon/webserver/tests/MultipartTest.java
Labels: bug, webserver, 4.x, OCA Verified

#8334 Replace deprecated Awaitable.await(long, TimeUnit) on Awaitable.await(Duration)
  common/reactive/src/test/java/io/helidon/common/reactive/AwaitTest.java
  common/reactive/src/test/java/io/helidon/common/reactive/BufferedEmittingPublisherTest.java
  common/reactive/src/test/java/io/helidon/common/reactive/IgnoreElementsTest.java
  common/reactive/src/test/java/io/helidon/common/reactive/MultiFlatMapCompletionStageTest.java
  common/reactive/src/test/java/io/helidon/common/reactive/MultiFlatMapPublisherTest.java
  common/reactive/src/test/java/io/helidon/common/reactive/MultiFromByteChannelTest.java
  common/reactive/src/test/java/io/helidon/common/reactive/MultiFromInputStreamTest.java
  common/reactive/src/test/java/io/helidon/common/reactive/MultiLogTest.java
  common/reactive/src/test/java/io/helidon/common/reactive/MultiTest.java
  common/reactive/src/test/java/io/helidon/common/reactive/SingleFlatMapCompletionStageTest.java
  common/reactive/src/test/java/io/helidon/common/reactive/SingleLogTest.java
  common/reactive/src/test/java/io/helidon/common/reactive/SingleTest.java
  microprofile/messaging/health/src/test/java/io/helidon/microprofile/messaging/health/MessagingHealthTest.java
  microprofile/tests/tck/tck-lra/src/test/java/io/helidon/microprofile/lra/tck/CoordinatorAppService.java
Labels: OCA Verified

#8340 Replace deprecated MediaType.fullType() on MediaType.text()
  common/media-type/src/main/java/io/helidon/common/media/type/MediaTypeImpl.java
  common/media-type/src/test/java/io/helidon/common/media/type/MediaTypesTest.java
  config/config/src/test/java/io/helidon/config/UrlConfigSourceServerMockTest.java
  config/config/src/test/java/io/helidon/config/UrlOverrideSourceServerMockTest.java
  http/http/src/main/java/io/helidon/http/HttpMediaTypeImpl.java
Labels: OCA Verified

#8355 Replace deprecated java.util.Locale constructors on factory methods
  config/tests/module-mappers-1-base/src/main/java/io/helidon/config/tests/module/mappers1/LocaleConfigMapper.java
  config/tests/module-mappers-2-override/src/main/java/io/helidon/config/tests/module/mappers2/LocaleConfigMapper.java
  config/tests/test-mappers-1-common/src/test/java/io/helidon/config/tests/mappers1/MapperServicesEnabledOverrideTest.java
  config/tests/test-mappers-1-common/src/test/java/io/helidon/config/tests/mappers1/MapperServicesEnabledTest.java
  config/tests/test-mappers-1-common/src/test/java/io/helidon/config/tests/mappers1/MyLocaleConfigMapper.java
  config/tests/test-mappers-2-complex/src/test/java/io/helidon/config/tests/mappers2/MapperServicesEnabledTest.java
  config/tests/test-mappers-2-complex/src/test/java/io/helidon/config/tests/mappers2/MyLocaleConfigMapper.java
  security/jwt/src/main/java/io/helidon/security/jwt/JwtUtil.java
Labels: OCA Verified

#8376 4.x: Releasing entity count down latch even if connection is set to close.
  webserver/webserver/src/main/java/io/helidon/webserver/http1/Http1Connection.java
Labels: bug, webserver, OCA Verified

#8364 Set incoming baggage from parent on Span
  tracing/opentelemetry/src/main/java/io/helidon/tracing/opentelemetry/OpenTelemetrySpanBuilder.java
  tracing/opentelemetry/src/test/java/io/helidon/tracing/opentelemetry/MapHeaderProvider.java
  tracing/opentelemetry/src/test/java/io/helidon/tracing/opentelemetry/TestSpanAndBaggage.java
  tracing/opentracing/src/main/java/io/helidon/tracing/opentracing/OpenTracingSpanBuilder.java
Labels: OCA Verified

#8296 `OidcEncryption#generateMasterPassword` check file system support posix before setting permission
  security/providers/oidc-common/src/main/java/io/helidon/security/providers/oidc/common/OidcEncryption.java
Labels: security, 4.x, OCA Verified

#8381 4.x: Update javadocs of Meter builders to cross reference MeterRegistry.getOrCreate()
  metrics/api/src/main/java/io/helidon/metrics/api/Counter.java
  metrics/api/src/main/java/io/helidon/metrics/api/DistributionSummary.java
  metrics/api/src/main/java/io/helidon/metrics/api/FunctionalCounter.java
  metrics/api/src/main/java/io/helidon/metrics/api/Gauge.java
  metrics/api/src/main/java/io/helidon/metrics/api/Meter.java
  metrics/api/src/main/java/io/helidon/metrics/api/Timer.java
Labels: docs, metrics, 4.x, OCA Verified

#8336 OIDC refresh token optionality fix
  security/providers/oidc/src/main/java/io/helidon/security/providers/oidc/OidcFeature.java
Labels: OCA Verified

#8221 Upgrades Oracle database libraries to version 21.9.0.0. Adds tests under datasource-ucp CDI integration.
  dependencies/pom.xml
  examples/employee-app/pom.xml
  examples/integrations/cdi/datasource-hikaricp/pom.xml
  examples/integrations/oci/atp-cdi/pom.xml
  examples/integrations/oci/atp/pom.xml
  integrations/cdi/datasource-ucp/pom.xml
  integrations/cdi/datasource-ucp/src/test/java/io/helidon/integrations/datasource/ucp/cdi/TestUcpAndH2.java
  integrations/cdi/datasource-ucp/src/test/java/io/helidon/integrations/datasource/ucp/cdi/TestUcpConnectionStateResetBehavior.java
  integrations/cdi/datasource-ucp/src/test/logging.properties
  integrations/db/ojdbc/pom.xml
  messaging/connectors/aq/pom.xml
Labels: P3, dependencies, integration, java, 4.x, OCA Verified, junit

#8397 [4.x] Replace deprecated session.writeTransaction on session.executeWrite in Neo4jHealthCheck
  integrations/neo4j/health/src/main/java/io/helidon/integrations/neo4j/health/Neo4jHealthCheck.java
Labels: OCA Verified

#8401 4.x: generate a .gitignore files from archetype
  archetypes/archetypes/src/main/archetype/common/common.xml
  archetypes/archetypes/src/main/archetype/common/files/.gitignore.mustache
  archetypes/archetypes/src/main/archetype/mp/custom/database-outputs.xml
  archetypes/archetypes/src/main/archetype/se/custom/database-output.xml
Labels: archetypes, 4.x, OCA Verified

#8032 3.x: 8029 Bad media type logging level
  webserver/webserver/src/main/java/io/helidon/webserver/RequestRouting.java
Labels: OCA Verified

#8404 Replace deprecated OutputStreamMultiBuilder.timeout(long,TimeUnit) on OutputStreamMultiBuilder.timeout(Duration)
  common/reactive/src/test/java/io/helidon/common/reactive/MultiFromOutputStreamTest.java
Labels: OCA Verified

#8389 More carefully handle re-creation of global meter registry
  metrics/api/src/main/java/io/helidon/metrics/api/MetricsConfigBlueprint.java
  metrics/providers/micrometer/pom.xml
  metrics/providers/micrometer/src/main/java/io/helidon/metrics/providers/micrometer/MMeterRegistry.java
  metrics/providers/micrometer/src/main/java/io/helidon/metrics/providers/micrometer/MicrometerMetricsFactory.java
  metrics/providers/micrometer/src/main/java/module-info.java
Labels: OCA Verified

#8387 OIDC updates
  config/config/src/main/java/io/helidon/config/DeprecatedConfig.java
  security/providers/idcs-mapper/src/main/java/io/helidon/security/providers/idcs/mapper/IdcsRoleMapperProviderBase.java
  security/providers/oidc-common/src/main/java/io/helidon/security/providers/oidc/common/BaseBuilder.java
  security/providers/oidc-common/src/main/java/io/helidon/security/providers/oidc/common/OidcConfig.java
  security/providers/oidc/src/main/java/io/helidon/security/providers/oidc/OidcFeature.java
  security/providers/oidc/src/main/java/io/helidon/security/providers/oidc/TenantAuthenticationHandler.java
  tests/integration/oidc/src/test/java/io/helidon/tests/integration/oidc/CommonLoginBase.java
  tests/integration/oidc/src/test/java/io/helidon/tests/integration/oidc/IdTokenIT.java
  tests/integration/oidc/src/test/java/io/helidon/tests/integration/oidc/RefreshTokenIT.java
  tests/integration/oidc/src/test/java/io/helidon/tests/integration/oidc/SecurityPartsIT.java
Labels: OCA Verified

#8270 Support Multipart with HelidonConnector/WebClient
  jersey/connector/pom.xml
  jersey/connector/src/main/java/io/helidon/jersey/connector/HelidonConnector.java
  jersey/connector/src/main/java/io/helidon/jersey/connector/HelidonEntity.java
  jersey/connector/src/test/java/io/helidon/jersey/connector/MultipartTest.java
Labels: OCA Verified

#8031 2.x: 7110 Bad media type log level
  webserver/webserver/src/main/java/io/helidon/webserver/RequestRouting.java
Labels: OCA Verified

#8405 [3.x] Replace deprecated session.writeTransaction on session.executeWrite in Neo4jHealthCheck
  integrations/neo4j/health/src/main/java/io/helidon/integrations/neo4j/health/Neo4jHealthCheck.java
Labels: OCA Verified

#7652 2.x - Support Jersey Multipart feature by Helidon Connector
  jersey/connector/pom.xml
  jersey/connector/src/main/java/io/helidon/jersey/connector/HelidonConnector.java
  jersey/connector/src/main/java/io/helidon/jersey/connector/HelidonEntity.java
  jersey/connector/src/main/java/module-info.java
  jersey/connector/src/test/java/io/helidon/jersey/connector/MultipartTest.java
Labels: OCA Verified

#8403 4.x: Fixes for problems discovered in service registry work
  builder/api/src/main/java/io/helidon/builder/api/GeneratedBuilder.java
  builder/api/src/main/java/io/helidon/builder/api/Prototype.java
  builder/codegen/src/main/java/io/helidon/builder/codegen/FactoryMethods.java
  builder/codegen/src/main/java/io/helidon/builder/codegen/GenerateAbstractBuilder.java
  builder/codegen/src/main/java/io/helidon/builder/codegen/TypeHandler.java
  builder/codegen/src/main/java/io/helidon/builder/codegen/TypeHandlerCollection.java
  builder/codegen/src/main/java/io/helidon/builder/codegen/TypeHandlerMap.java
  builder/codegen/src/main/java/io/helidon/builder/codegen/TypeHandlerOptional.java
  builder/codegen/src/main/java/io/helidon/builder/codegen/TypeHandlerSupplier.java
  builder/codegen/src/main/java/io/helidon/builder/codegen/Types.java
  builder/tests/builder/src/test/java/io/helidon/builder/test/ParentParentChildTest.java
  common/mapper/src/main/java/io/helidon/common/mapper/BuiltInMappers.java
  common/parameters/src/main/java/io/helidon/common/parameters/Parameters.java
  common/parameters/src/main/java/io/helidon/common/parameters/ParametersEmpty.java
  common/parameters/src/main/java/io/helidon/common/parameters/ParametersMap.java
  common/parameters/src/main/java/io/helidon/common/parameters/ParametersSingleValueMap.java
  common/uri/src/main/java/io/helidon/common/uri/UriMatrixParameters.java
  common/uri/src/main/java/io/helidon/common/uri/UriQueryEmpty.java
  common/uri/src/main/java/io/helidon/common/uri/UriQueryImpl.java
  common/uri/src/main/java/io/helidon/common/uri/UriQueryWriteableImpl.java
  etc/scripts/build.sh
Labels: 4.x, OCA Verified

#8409 4.x - Fix WebServer Mutual TLS example
  examples/webserver/mutual-tls/README.md
  examples/webserver/mutual-tls/pom.xml
  examples/webserver/mutual-tls/src/main/java/io/helidon/examples/webserver/mtls/SecureService.java
  examples/webserver/mutual-tls/src/main/resources/application.yaml
  examples/webserver/mutual-tls/src/test/java/io/helidon/examples/webserver/mtls/MutualTlsExampleBuilderTest.java
  examples/webserver/mutual-tls/src/test/java/io/helidon/examples/webserver/mtls/MutualTlsExampleConfigTest.java
  examples/webserver/mutual-tls/src/test/resources/application-test.yaml
  examples/webserver/mutual-tls/src/test/resources/meta-config.yaml
Labels: bug, examples, webserver, 4.x, OCA Verified

#8342 Fix for #8344 - Incorrect SQL Type for null Parameters in JDBC Parameter Binding
  dbclient/jdbc/src/main/java/io/helidon/dbclient/jdbc/JdbcStatement.java
Labels: OCA Verified

#8415 [2.x] PostgreSQL JDBC driver updated to 42.4.4.
  dependencies/pom.xml
Labels: OCA Verified

#8414 [3.x] PostgreSQL JDBC driver updated to 42.4.4.
  dependencies/pom.xml
Labels: OCA Verified

#8408 Adds support for sending websocket CLOSE frames without a payload
  webclient/websocket/src/main/java/io/helidon/webclient/websocket/ClientWsConnection.java
  webserver/tests/websocket/src/test/java/io/helidon/webserver/tests/websocket/WebSocketClientTest.java
  webserver/websocket/src/main/java/io/helidon/webserver/websocket/WsConnection.java
  websocket/src/main/java/io/helidon/websocket/AbstractWsFrame.java
Labels: OCA Verified

#8417 [4.x] Replace deprecated classInfo.classAnnotation(DotName) on classInfo.declaredAnnotation(DotName)
  microprofile/lra/jax-rs/src/main/java/io/helidon/microprofile/lra/InspectionService.java
Labels: OCA Verified

#8420 [4.x] Replace deprecated session.readTransaction on session.executeRead
  docs/src/main/java/io/helidon/docs/mp/integrations/Neo4jSnippets.java
  docs/src/main/java/io/helidon/docs/se/integrations/Neo4jSnippets.java
  examples/integrations/neo4j/src/main/java/io/helidon/examples/integrations/neo4j/domain/MovieRepository.java
Labels: OCA Verified

#8316 4.x: TLS peer certs
  common/key-util/src/main/java/io/helidon/common/pki/PkiUtil.java
  common/socket/pom.xml
  common/socket/src/main/java/io/helidon/common/socket/PeerInfoImpl.java
  common/socket/src/main/java/io/helidon/common/socket/TlsSocket.java
  common/socket/src/test/java/io/helidon/common/socket/TlsSocketTest.java
  common/tls/src/main/java/io/helidon/common/tls/TlsReloadableX509KeyManager.java
  webserver/tests/mtls/pom.xml
  webserver/tests/mtls/src/main/resources/logging.properties
Labels: OCA Verified

#8419 Generalize OCI metrics support; add tests for the generalization
  integrations/oci/metrics/cdi/pom.xml
  integrations/oci/metrics/cdi/src/main/java/io/helidon/integrations/oci/metrics/cdi/OciMetricsBean.java
  integrations/oci/metrics/cdi/src/test/java/io/helidon/integrations/oci/metrics/cdi/OciMetricsCdiExtensionTest.java
  integrations/oci/metrics/cdi/src/test/java/io/helidon/integrations/oci/metrics/cdi/OverridingOciMetricsBean.java
  integrations/oci/metrics/cdi/src/test/java/io/helidon/integrations/oci/metrics/cdi/TestObserverPriorities.java
  integrations/oci/metrics/cdi/src/test/java/io/helidon/integrations/oci/metrics/cdi/TestOverridingBean.java
Labels: OCA Verified

#8426 4.x: Archetype - Fix sql script for oracle database
  archetypes/archetypes/src/main/archetype/mp/custom/database-outputs.xml
  archetypes/archetypes/src/main/archetype/mp/database/files/src/main/resources/META-INF/init_script.sql.default
  archetypes/archetypes/src/main/archetype/mp/database/files/src/main/resources/META-INF/init_script.sql.oracle
Labels: MP, archetypes, 4.x, OCA Verified

#8424 [4.x] Replace deprecated Multi.from(Stream) on Multi.create(Stream)
  tests/integration/kafka/src/test/java/io/helidon/messaging/connectors/kafka/KafkaSeTest.java
Labels: OCA Verified

#8431 [4.x] Generalize the creation of the `OciMetricsSupport` instance from CDI
  integrations/oci/metrics/cdi/pom.xml
  integrations/oci/metrics/cdi/src/main/java/io/helidon/integrations/oci/metrics/cdi/OciMetricsBean.java
  integrations/oci/metrics/cdi/src/test/java/io/helidon/integrations/oci/metrics/cdi/OciMetricsCdiExtensionTest.java
  integrations/oci/metrics/cdi/src/test/java/io/helidon/integrations/oci/metrics/cdi/OverridingOciMetricsBean.java
  integrations/oci/metrics/cdi/src/test/java/io/helidon/integrations/oci/metrics/cdi/TestObserverPriorities.java
  integrations/oci/metrics/cdi/src/test/java/io/helidon/integrations/oci/metrics/cdi/TestOverridingBean.java
Labels: OCA Verified

#8438 [3.x] Replace deprecated Multi.from(Stream) on Multi.create(Stream)
  tests/integration/kafka/src/test/java/io/helidon/messaging/connectors/kafka/KafkaSeTest.java
Labels: OCA Verified

#8427 4.x: Update `context-root` config documentation
  docs/src/main/asciidoc/mp/jaxrs/jaxrs-applications.adoc
  docs/src/main/asciidoc/mp/server.adoc
  docs/src/main/java/io/helidon/docs/mp/jaxrs/JaxrsApplicationsSnippets.java
Labels: MP, docs, 4.x, OCA Verified
