Repository helidon-io/helidon, pull requests merged in 2024-05, with the labels that each got.

#8696 2.x: Fix bug with empty Accept header (#7536)
  openapi/src/main/java/io/helidon/openapi/OpenAPISupport.java
  openapi/src/test/java/io/helidon/openapi/ServerTest.java
Labels: OCA Verified

#8715 4.x: Pin GitHub runner to macos-13 (not latest) to ensure x86 to workaround protoc issue
  .github/workflows/validate.yml
Labels: build, 4.x, OCA Verified

#8717 4.x: upgrade MacOS runner to 14 and fix protoc version
  .github/workflows/validate.yml
  examples/webserver/protocols/pom.xml
  webserver/tests/grpc/pom.xml
Labels: build, grpc, 4.x, OCA Verified

#8713 4.x: Update CHANGELOG for 4.0.8
  CHANGELOG.md
Labels: 4.x, OCA Verified

#8656 4.x: Use LevelChangePropagator in examples/logging/slf4j (#7737)
  examples/logging/slf4j/pom.xml
  examples/logging/slf4j/src/main/resources/logback.xml
  examples/logging/slf4j/src/main/resources/logging.properties
Labels: OCA Verified

#8681 3.x: Fix wrong description for bean validation annotations (#8667)
  docs/mp/beanvalidation.adoc
Labels: OCA Verified

#8655 4.x: Add text block support
  microprofile/testing/junit5/src/main/java/io/helidon/microprofile/testing/junit5/AddConfigBlock.java
  microprofile/testing/junit5/src/main/java/io/helidon/microprofile/testing/junit5/HelidonJunitExtension.java
  microprofile/testing/testng/src/main/java/io/helidon/microprofile/testing/testng/AddConfigBlock.java
  microprofile/testing/testng/src/main/java/io/helidon/microprofile/testing/testng/HelidonTestNgListener.java
  microprofile/tests/testing/junit5/src/test/java/io/helidon/microprofile/tests/testing/junit5/TestAddConfigBlockProperties.java
  microprofile/tests/testing/junit5/src/test/java/io/helidon/microprofile/tests/testing/junit5/TestAddConfigBlockYaml.java
  microprofile/tests/testing/testng/src/test/java/io/helidon/microprofile/tests/testing/testng/TestAddConfigBlockProperties.java
  microprofile/tests/testing/testng/src/test/java/io/helidon/microprofile/tests/testing/testng/TestAddConfigBlockYaml.java
Labels: OCA Verified

#8707 [4.x] LazyConfigSource is now queried when an unknown node is requested
  config/config/src/main/java/io/helidon/config/ConfigFactory.java
  config/config/src/main/java/io/helidon/config/ConfigSourcesRuntime.java
  config/config/src/main/java/io/helidon/config/ProviderImpl.java
  config/tests/pom.xml
  config/tests/test-lazy-source/pom.xml
  config/tests/test-lazy-source/src/test/java/io/helidon/config/tests/lazy/source/LazySourceTest.java
Labels: config, 4.x, OCA Verified

#8730 4.x: Upgrade microprofile rest client to 3.0.1
  dependencies/pom.xml
Labels: rest-client, dependencies, 4.x, OCA Verified, microprofile

#8723 Helidon 4.x: Parameters.first(String) generates java.lang.IndexOutOfB…
  common/parameters/src/main/java/io/helidon/common/parameters/ParametersMap.java
  common/parameters/src/test/java/io/helidon/common/parameters/ParametersTest.java
  common/uri/src/main/java/io/helidon/common/uri/UriQueryImpl.java
  common/uri/src/test/java/io/helidon/common/uri/UriQueryTest.java
  webclient/tests/webclient/src/test/java/io/helidon/webclient/tests/FormTest.java
Labels: OCA Verified

#8721 4.x: @HelidonTest / @AddConfig* Provide a config parser by type #8718
  config/config-mp/src/main/java/io/helidon/config/mp/MpConfigBuilder.java
  config/config-mp/src/main/java/io/helidon/config/mp/MpConfigSources.java
  config/config-mp/src/main/java/io/helidon/config/mp/MpEnvironmentVariablesMetaConfigProvider.java
  config/config-mp/src/main/java/io/helidon/config/mp/MpPropertiesMetaConfigProvider.java
  config/config-mp/src/main/java/io/helidon/config/mp/MpSystemPropertiesMetaConfigProvider.java
  config/config-mp/src/main/java/io/helidon/config/mp/spi/MpMetaConfigProvider.java
  config/config-mp/src/test/java/io/helidon/config/mp/MpConfigSourcesTest.java
  config/hocon-mp/src/main/java/io/helidon/config/hocon/mp/HoconMpConfigSource.java
  config/hocon-mp/src/main/java/io/helidon/config/hocon/mp/HoconMpMetaConfigProvider.java
  config/hocon-mp/src/test/java/io/helidon/config/hocon/mp/HoconJsonMpConfigSourceTest.java
  config/yaml-mp/src/main/java/io/helidon/config/yaml/mp/YamlMetaConfigProvider.java
  config/yaml-mp/src/test/java/io/helidon/config/yaml/mp/YamlMpConfigSourceTest.java
  integrations/oci/oci-secrets-mp-config-source/src/main/java/io/helidon/integrations/oci/secrets/mp/configsource/OciSecretsMpMetaConfigProvider.java
  microprofile/testing/junit5/src/main/java/io/helidon/microprofile/testing/junit5/HelidonJunitExtension.java
  microprofile/testing/testng/src/main/java/io/helidon/microprofile/testing/testng/HelidonTestNgListener.java
  microprofile/tests/testing/junit5/src/test/java/io/helidon/microprofile/tests/testing/junit5/TestAddConfigBlockYaml.java
  microprofile/tests/testing/testng/src/test/java/io/helidon/microprofile/tests/testing/testng/TestAddConfigBlockYaml.java
Labels: OCA Verified

#8731 4.x: Capitalized received message in io.helidon.examples.webserver.websocket.MessageBoardEndpoint (#8725)
  examples/webserver/websocket/src/main/java/io/helidon/examples/webserver/websocket/MessageBoardEndpoint.java
  examples/webserver/websocket/src/test/java/io/helidon/examples/webserver/websocket/MessageBoardTest.java
Labels: OCA Verified

#8733 4.x: Update Dockerfiles to use jdk-no-fee-term instead of openjdk
  archetypes/archetypes/src/main/archetype/common/files/Dockerfile.jlink.mustache
  archetypes/archetypes/src/main/archetype/common/files/Dockerfile.mustache
  examples/employee-app/Dockerfile
  examples/integrations/cdi/datasource-hikaricp/Dockerfile
  examples/messaging/docker/kafka/Dockerfile.kafka
  examples/quickstarts/helidon-quickstart-mp/Dockerfile
  examples/quickstarts/helidon-quickstart-mp/Dockerfile.jlink
  examples/quickstarts/helidon-quickstart-se/Dockerfile
  examples/quickstarts/helidon-quickstart-se/Dockerfile.jlink
  examples/quickstarts/helidon-standalone-quickstart-mp/Dockerfile
  examples/quickstarts/helidon-standalone-quickstart-mp/Dockerfile.jlink
  examples/quickstarts/helidon-standalone-quickstart-se/Dockerfile
  examples/quickstarts/helidon-standalone-quickstart-se/Dockerfile.jlink
  examples/translator-app/backend/Dockerfile
  examples/translator-app/frontend/Dockerfile
  examples/webserver/opentracing/Dockerfile
  lra/coordinator/server/Dockerfile
Labels: examples, 4.x, OCA Verified

#8741 3.x: Get JDK and linux images from container-registry.oracle.com
  archetypes/helidon/src/main/archetype/common/files/Dockerfile.jlink.mustache
  archetypes/helidon/src/main/archetype/common/files/Dockerfile.mustache
  lra/coordinator/server/Dockerfile
Labels: 3.x, archetypes, OCA Verified

#8643 Proposal for a new annotation @ExecuteOn
  microprofile/cdi/pom.xml
  microprofile/cdi/src/main/java/io/helidon/microprofile/cdi/ExecuteOn.java
  microprofile/cdi/src/main/java/io/helidon/microprofile/cdi/ExecuteOnExtension.java
  microprofile/cdi/src/main/java/io/helidon/microprofile/cdi/ExecuteOnInterceptor.java
  microprofile/cdi/src/main/java/module-info.java
  microprofile/cdi/src/test/java/io/helidon/microprofile/cdi/ExecuteOnTest.java
  microprofile/cdi/src/test/resources/application.yaml
Labels: MP, 1.x, OCA Verified

#8740 4.x: Force hibernate to use no-op bytecode provider with native-image
  dependencies/pom.xml
  integrations/cdi/hibernate-cdi/pom.xml
  integrations/cdi/hibernate-cdi/src/main/java/io/helidon/integrations/cdi/hibernate/BytecodeProvider.java
  integrations/cdi/hibernate-cdi/src/main/java/io/helidon/integrations/cdi/hibernate/BytecodeProviderInitiator.java
  integrations/cdi/hibernate-cdi/src/main/java/module-info.java
  integrations/cdi/hibernate-cdi/src/main/resources/META-INF/helidon/native-image/reflection-config.json
Labels: native-image, 4.x, OCA Verified

#8753 2.x: fix getOrdinal for system property and environment variable config sources
  .github/workflows/validate.yml
  config/config-mp/src/main/java/io/helidon/config/mp/MpEnvironmentVariablesSource.java
  config/config-mp/src/main/java/io/helidon/config/mp/MpSystemPropertiesSource.java
  config/config-mp/src/test/java/io/helidon/config/mp/MpConfigSourcesTest.java
Labels: MP, config, 2.x, backport, OCA Verified

#8752 3.x: fix getOrdinal for system property and environment variable config sources
  config/config-mp/src/main/java/io/helidon/config/mp/MpEnvironmentVariablesSource.java
  config/config-mp/src/main/java/io/helidon/config/mp/MpSystemPropertiesSource.java
  config/config-mp/src/test/java/io/helidon/config/mp/MpConfigSourcesTest.java
Labels: MP, config, 3.x, backport, OCA Verified

#8758 4.x: Register additional hibernate classes for reflection
  integrations/cdi/hibernate-cdi/src/main/resources/META-INF/helidon/native-image/reflection-config.json
  integrations/cdi/hibernate-cdi/src/main/resources/META-INF/native-image/io.helidon.integrations.cdi/helidon-integrations-cdi-hibernate/reflect-config.json
Labels: native-image, 4.x, OCA Verified

#8764 4.x Associate tracer-level tags with Jaeger process level (instead of span level)
  tracing/providers/jaeger/pom.xml
  tracing/providers/jaeger/src/main/java/io/helidon/tracing/providers/jaeger/JaegerTracerBuilder.java
  tracing/providers/jaeger/src/test/java/io/helidon/tracing/providers/jaeger/JaegerTracerBuilderTest.java
  tracing/providers/jaeger/src/test/java/io/helidon/tracing/providers/jaeger/TestSpanExporter.java
  tracing/providers/jaeger/src/test/java/io/helidon/tracing/providers/jaeger/TestSpanExporterProvider.java
Labels: OCA Verified

#8745 Refactor OCI metrics library a bit
  integrations/oci/metrics/cdi/src/main/java/io/helidon/integrations/oci/metrics/cdi/OciMetricsBean.java
  integrations/oci/metrics/cdi/src/main/java/io/helidon/integrations/oci/metrics/cdi/OciMetricsCdiExtension.java
  integrations/oci/metrics/metrics/src/main/java/io/helidon/integrations/oci/metrics/OciMetricsSupport.java
  integrations/oci/metrics/metrics/src/main/java/io/helidon/integrations/oci/metrics/OciMetricsSupportFactory.java
  integrations/oci/metrics/metrics/src/main/java/module-info.java
Labels: OCA Verified

#8762 4.x: helidon-common sources JAR contains absolute paths #8761
  common/common/pom.xml
Labels: OCA Verified

#8742 Fix problems with tracing data propagation
  tracing/providers/jaeger/src/main/java/io/helidon/tracing/providers/jaeger/JaegerDataPropagationProvider.java
  tracing/providers/opentelemetry/src/main/java/io/helidon/tracing/providers/opentelemetry/OpenTelemetryDataPropagationProvider.java
  tracing/providers/opentelemetry/src/main/java/module-info.java
  tracing/providers/opentelemetry/src/test/java/io/helidon/tracing/providers/opentelemetry/TestDataPropagation.java
  webserver/observe/tracing/src/main/java/io/helidon/webserver/observe/tracing/TracingObserver.java
Labels: OCA Verified

#8768 Switched implementation of MpEnvironmentVariablesSource to use an LRU cache
  config/config-mp/pom.xml
  config/config-mp/src/main/java/io/helidon/config/mp/MpEnvironmentVariablesSource.java
  config/config-mp/src/main/java/module-info.java
  config/config-mp/src/test/java/io/helidon/config/mp/MpEnvironmentVariablesSourceTest.java
Labels: config, performance, 4.x, OCA Verified

#8771 4.x - AbstractConfigurableExtension native-image fix
  integrations/cdi/common-cdi/configurable/etc/spotbugs/exclude.xml
  integrations/cdi/common-cdi/configurable/pom.xml
  integrations/cdi/common-cdi/configurable/src/main/java/io/helidon/integrations/cdi/configurable/AbstractConfigurableExtension.java
  integrations/cdi/common-cdi/configurable/src/main/java/io/helidon/integrations/cdi/configurable/ComputedProperties.java
Labels: MP, native-image, 4.x, OCA Verified

#8756 New document that describes the ExecuteOn annotation
  docs/src/main/asciidoc/mp/threading.adoc
  docs/src/main/asciidoc/sitegen.yaml
  docs/src/main/java/io/helidon/docs/mp/ExecuteOnSnippets.java
Labels: duplicate, docs, common, OCA Verified

#8783 4.x: cleanup helidon-bom and helidon-all
  all/pom.xml
  bom/pom.xml
  inject/tests/resources-inject/pom.xml
  inject/tests/tck-jsr330/pom.xml
  metrics/providers/pom.xml
  tracing/providers/pom.xml
Labels: 4.x, OCA Verified

#8786 [4.x] Cannot read config from environment with environment modules variables
  config/config-mp/src/main/java/io/helidon/config/mp/MpEnvironmentVariablesSource.java
  config/config/src/main/java/io/helidon/config/EnvironmentVariables.java
  config/config/src/main/java/io/helidon/config/PropertiesFilter.java
  config/config/src/test/java/io/helidon/config/PropertiesFilterTest.java
Labels: config, 4.x, OCA Verified

#8788 4.x: Update setup-java for snapshot workflow
  .github/workflows/snapshotrelease.yaml
Labels: build, 4.x, OCA Verified

#8789 4.x: Fix typo in java-version for setup java action
  .github/workflows/snapshotrelease.yaml
Labels: build, 4.x, OCA Verified

#8790 4.x: Bump deploy plugin to 3.1.1
  parent/pom.xml
Labels: 4.x, OCA Verified

#8795 4.x: include SE upgrade guide in docs navbar
  docs/src/main/asciidoc/se/guides/upgrade_4x.adoc
  docs/src/main/asciidoc/sitegen.yaml
Labels: docs, 4.x, OCA Verified

#8792 4.x: Archetype - Add SLF4J dependency
  archetypes/archetypes/src/main/archetype/mp/custom/database-outputs.xml
  archetypes/archetypes/src/main/archetype/mp/oci/oci-mp.xml
Labels: archetypes, 4.x, OCA Verified

#8798 Upgrades to Jersey to 3.1.7
  dependencies/pom.xml
Labels: 4.x

#8778 Use Helidon tracer, span builder, span types instead of OTel ones so we can trigger span listeners
  microprofile/telemetry/pom.xml
  microprofile/telemetry/src/main/java/io/helidon/microprofile/telemetry/HelidonTelemetryClientFilter.java
  microprofile/telemetry/src/main/java/io/helidon/microprofile/telemetry/HelidonTelemetryContainerFilter.java
  microprofile/telemetry/src/main/java/io/helidon/microprofile/telemetry/RequestContextHeaderProvider.java
  microprofile/telemetry/src/main/java/io/helidon/microprofile/telemetry/WithSpanInterceptor.java
  microprofile/telemetry/src/main/java/module-info.java
  microprofile/telemetry/src/test/java/io/helidon/microprofile/telemetry/WithSpanListenerTest.java
  microprofile/tests/tck/tck-telemetry/pom.xml
  microprofile/tests/tck/tck-telemetry/src/test/resources/application.yaml
  microprofile/tests/tck/tck-telemetry/src/test/resources/arquillian.xml
  tracing/providers/opentelemetry/src/main/java/io/helidon/tracing/providers/opentelemetry/HelidonOpenTelemetry.java
  tracing/providers/opentelemetry/src/main/java/io/helidon/tracing/providers/opentelemetry/OpenTelemetryTracer.java
  tracing/providers/opentelemetry/src/test/java/io/helidon/tracing/providers/opentelemetry/TestAutoCurrentSpanAsParent.java
Labels: OCA Verified

#8765 Improvements to gRPC server-side support
  webserver/grpc/src/main/java/io/helidon/webserver/grpc/GrpcHeadersUtil.java
  webserver/grpc/src/main/java/io/helidon/webserver/grpc/GrpcProtocolHandler.java
  webserver/tests/grpc/src/test/java/io/helidon/webserver/tests/grpc/BaseStringServiceTest.java
  webserver/tests/grpc/src/test/java/io/helidon/webserver/tests/grpc/GzipStringServiceTest.java
Labels: OCA Verified

#8801 4.x - Fix tests/integration/native-image/mp-2
  integrations/cdi/hibernate-cdi/src/main/resources/META-INF/native-image/io.helidon.integrations.cdi/helidon-integrations-cdi-hibernate/reflect-config.json
  tests/integration/native-image/mp-2/README.md
  tests/integration/native-image/mp-2/init.sql
  tests/integration/native-image/mp-2/pom.xml
  tests/integration/native-image/mp-2/src/main/java/io/helidon/tests/integration/nativeimage/mp2/Mp2Main.java
  tests/integration/native-image/mp-2/src/main/resources/hibernate.properties
Labels: jpa/jta, native-image, 4.x, OCA Verified

#8802 4.x - Use native-image:compile-no-fork instead of native-image:compile
  applications/mp/pom.xml
  applications/parent/pom.xml
  applications/se/pom.xml
  examples/quickstarts/helidon-standalone-quickstart-mp/pom.xml
  examples/quickstarts/helidon-standalone-quickstart-se/pom.xml
Labels: native-image, 4.x, OCA Verified

#8719 4.x: Add tests for building native-image for quickstart examples
  .github/workflows/validate.yml
  etc/scripts/test-quickstarts.sh
Labels: examples, native-image, testing, 4.x, OCA Verified

#8808 4.x - Fix native-image properties layout.
  common/key-util/src/main/resources/META-INF/native-image/io.helidon.common/helidon-common-key-util/native-image.properties
  examples/quickstarts/helidon-quickstart-mp/pom.xml
  examples/quickstarts/helidon-quickstart-se/pom.xml
  examples/quickstarts/helidon-standalone-quickstart-se/src/main/resources/META-INF/native-image/io.helidon.examples.quickstarts/helidon-standalone-quickstart-se/helidon-example-reflection-config.json
  examples/quickstarts/helidon-standalone-quickstart-se/src/main/resources/META-INF/native-image/io.helidon.examples.quickstarts/helidon-standalone-quickstart-se/native-image.properties
  integrations/db/mysql/src/main/resources/META-INF/native-image/io.helidon.integrations.db/helidon-integrations-db-mysql/native-image.properties
  integrations/db/mysql/src/main/resources/META-INF/native-image/io.helidon.integrations.db/helidon-integrations-db-mysql/resource-config.json
  integrations/db/pgsql/src/main/resources/META-INF/native-image/io.helidon.integrations.db/helidon-integrations-db-pgsql/native-image.properties
  integrations/microstream/cache/src/main/resources/META-INF/native-image/io.helidon.integrations.microstream/helidon-integrations-microstream-cache/native-image.properties
  microprofile/tracing/src/main/resources/META-INF/native-image/io.helidon.microprofile.tracing/helidon-microprofile-tracing/native-image.properties
  tests/integration/native-image/mp-1/pom.xml
  tests/integration/native-image/mp-1/src/main/resources/META-INF/native-image/io.helidon.tests.integration.native-image/helidon-tests-native-image-mp-1/native-image.properties
  tests/integration/native-image/mp-2/pom.xml
  tests/integration/native-image/mp-2/src/main/resources/META-INF/native-image/io.helidon.tests.integration.native-image/helidon-tests-native-image-mp-2/native-image.properties
  tests/integration/native-image/mp-3/pom.xml
  tests/integration/native-image/mp-3/src/main/resources/META-INF/native-image/io.helidon.tests.integration.native-image/helidon-tests-native-image-mp-3/native-image.properties
  tests/integration/native-image/se-1/pom.xml
  tracing/providers/jaeger/src/main/resources/META-INF/native-image/io.helidon.tracing.providers/helidon-tracing-providers-jaeger/native-image.properties
  tracing/providers/jaeger/src/main/resources/META-INF/native-image/io.helidon.tracing.providers/helidon-tracing-providers-jaeger/reflect-config.json
  tracing/providers/jaeger/src/main/resources/META-INF/native-image/io.helidon.tracing.providers/helidon-tracing-providers-jaeger/resource-config.json
  tracing/providers/zipkin/src/main/resources/META-INF/native-image/io.helidon.tracing.providers/helidon-tracing-providers-zipkin/native-image.properties
Labels: native-image, 4.x, OCA Verified

#8809 Harden WebClientSecurity against absent or disabled tracing
  webclient/security/src/main/java/io/helidon/webclient/security/WebClientSecurity.java
Labels: OCA Verified

#7288 Address additional issues related to Weld upgrade
  microprofile/weld/weld-core-impl/pom.xml
  microprofile/weld/weld-core-impl/src/main/java/org/jboss/weld/bean/proxy/ProxyFactory.java
Labels: OCA Verified

#8757 4.x: Upgrade to MP Config 3.1 and fix an issue with profile specific properties
  config/config-mp/src/main/java/io/helidon/config/mp/MpConfigImpl.java
  config/config-mp/src/test/java/io/helidon/config/mp/MpConfigReferenceTest.java
  config/config-mp/src/test/java/io/helidon/config/mp/MpConfigSourcesTest.java
  dependencies/pom.xml
  docs/src/main/asciidoc/includes/attributes.adoc
  docs/src/main/asciidoc/mp/config/introduction.adoc
Labels: MP, config, dependencies, 4.x, OCA Verified

#8820 4.x: Repair version strings
  examples/webserver/threads/pom.xml
  grpc/core/pom.xml
  grpc/pom.xml
  tests/integration/dbclient/mongodb/pom.xml
  webclient/grpc/pom.xml
  webclient/tests/grpc/pom.xml
  webserver/testing/junit5/grpc/pom.xml
Labels: build, 4.x, OCA Verified

#8821 Temporarily disables hanging test to help pipeline
  tests/functional/request-scope/src/test/java/io/helidon/tests/functional/requestscope/TenantTest.java
Labels: bug, 4.x, OCA Verified
