Repository helidon-io/helidon, pull requests merged in 2024-07, with the labels that each got.

#8927 4.x: Oci integration fixes
  integrations/oci/oci/pom.xml
  integrations/oci/oci/src/main/java/io/helidon/integrations/oci/HelidonOci.java
  integrations/oci/oci/src/main/java/io/helidon/integrations/oci/OciConfigBlueprint.java
  integrations/oci/oci/src/main/java/io/helidon/integrations/oci/OciConfigSupport.java
  integrations/oci/oci/src/main/java/io/helidon/integrations/oci/RegionProviderSdk.java
  integrations/oci/oci/src/main/java/module-info.java
Labels: OCI, 4.x, OCA Verified

#8933 Moves client protocol ID caching from HttpClientRequest to WebClient
  webclient/api/src/main/java/io/helidon/webclient/api/HttpClientRequest.java
  webclient/api/src/main/java/io/helidon/webclient/api/LoomClient.java
  webserver/tests/mtls/src/test/java/io/helidon/webserver/tests/mtls/MtlsTest.java
Labels: website, performance, 4.x, OCA Verified

#8928 Add Imds data retriever as a service provider
  integrations/oci/oci/README.md
  integrations/oci/oci/pom.xml
  integrations/oci/oci/src/main/java/io/helidon/integrations/oci/HelidonOci.java
  integrations/oci/oci/src/main/java/io/helidon/integrations/oci/ImdsInstanceInfoBlueprint.java
  integrations/oci/oci/src/main/java/io/helidon/integrations/oci/ImdsInstanceInfoProvider.java
  integrations/oci/oci/src/main/java/io/helidon/integrations/oci/OciConfigBlueprint.java
  integrations/oci/oci/src/main/java/module-info.java
  integrations/oci/oci/src/test/java/io/helidon/integrations/oci/InstanceInfoProviderTest.java
  service/README.md
  service/codegen/src/main/java/io/helidon/service/codegen/GenerateServiceDescriptor.java
Labels: OCA Verified

#8950 4.x: upgrade owasp dependency check plugin to 10.0.2
  integrations/oci/oci/pom.xml
  pom.xml
Labels: build, 4.x, OCA Verified

#8951 3.x: Upgrade owasp dependency check plugin to 10.0.2
  pom.xml
Labels: build, 3.x, OCA Verified

#8952 2.x: upgrade owasp dependency check plugin to 10.0.2
  pom.xml
Labels: build, 2.x, OCA Verified

#8953 1.x: upgrade owasp dependency check to 10.0.2
  dependencies/pom.xml
  etc/dependency-check-suppression.xml
  pom.xml
Labels: build, 1.x, dependencies, OCA Verified

#8945 Fix typo in example code
  docs/se/metrics/micrometer.adoc
Labels: docs, OCA Verified

#8944 Makes SocketContext available to a WsSession
  microprofile/websocket/src/main/java/io/helidon/microprofile/tyrus/TyrusConnection.java
  webclient/websocket/src/main/java/io/helidon/webclient/websocket/ClientWsConnection.java
  webserver/tests/websocket/src/main/java/io/helidon/webserver/tests/websocket/EchoService.java
  webserver/tests/websocket/src/test/java/io/helidon/webserver/tests/websocket/WebSocketClientTest.java
  webserver/websocket/src/main/java/io/helidon/webserver/websocket/WsConnection.java
  websocket/src/main/java/io/helidon/websocket/WsSession.java
Labels: enhancement, 4.x, OCA Verified

#8961 4.0.11: Upgrade oci-sdk to 3.43.2
  dependencies/pom.xml
Labels: dependencies, OCI, 4.x, OCA Verified

#8960 4.0.11: upgrade owasp dependency check plugin to 10.0.2
  pom.xml
Labels: build, 4.x, OCA Verified

#8975 4.0.11: After retrieval check baggage entry for null before dereferencing it
  tracing/provider-tests/src/main/java/io/helidon/tracing/providers/tests/BaggageOptionalTests.java
  tracing/providers/opentelemetry/src/main/java/io/helidon/tracing/providers/opentelemetry/MutableOpenTelemetryBaggage.java
Labels: tracing, backport, 4.x, OCA Verified

#8976 4.0.11: Properly handle disabled metrics in MP
  microprofile/metrics/pom.xml
  microprofile/metrics/src/main/java/io/helidon/microprofile/metrics/HelidonCounter.java
  microprofile/metrics/src/main/java/io/helidon/microprofile/metrics/HelidonGauge.java
  microprofile/metrics/src/main/java/io/helidon/microprofile/metrics/HelidonHistogram.java
  microprofile/metrics/src/main/java/io/helidon/microprofile/metrics/HelidonTimer.java
  microprofile/metrics/src/main/java/io/helidon/microprofile/metrics/MetricImpl.java
  microprofile/metrics/src/main/java/io/helidon/microprofile/metrics/Registry.java
  microprofile/metrics/src/test/java/io/helidon/microprofile/metrics/TestSelectivelyDisabledMetric.java
Labels: metrics, backport, 4.x, OCA Verified

#8965 4.x - Archetype: Remove unused config property from generated code
  archetypes/archetypes/src/main/archetype/se/custom/database-output.xml
Labels: config, archetypes, 4.x, OCA Verified

#8983 Use correct exception when retrying in FT
  fault-tolerance/fault-tolerance/src/main/java/io/helidon/faulttolerance/RetryImpl.java
  microprofile/fault-tolerance/src/test/java/io/helidon/microprofile/faulttolerance/RetryBean.java
  microprofile/fault-tolerance/src/test/java/io/helidon/microprofile/faulttolerance/RetryTest.java
Labels: 4.x, OCA Verified

#8977 Convert `ConcurrentHashMap` which does service loading to `HashMap` with `ReentrantLock`
  common/configurable/src/main/java/io/helidon/common/configurable/ObserverManager.java
Labels: OCA Verified

#8988 4.0.11: Removes usage of ConcurrentHashMap in LocalXAResource.java
  integrations/jta/jdbc/src/main/java/io/helidon/integrations/jta/jdbc/LocalXAResource.java
Labels: jpa/jta, backport, 4.x, OCA Verified

#8989 4.0.11: Archetype: fix database app-type typo (#8963)
  archetypes/archetypes/src/main/archetype/se/se.xml
Labels: archetypes, backport, 4.x, OCA Verified

#8985 Skip test if InstancePrincipal UT if Imds is available
  integrations/oci/sdk/cdi/src/test/java/io/helidon/integrations/oci/sdk/cdi/TestInstancePrincipalsAuthenticationDetailsProvider.java
  integrations/oci/sdk/cdi/src/test/java/io/helidon/integrations/oci/sdk/cdi/TestProcessProviderInjectionPoint.java
  integrations/oci/sdk/cdi/src/test/java/io/helidon/integrations/oci/sdk/cdi/TestSpike.java
  integrations/oci/sdk/cdi/src/test/java/io/helidon/integrations/oci/sdk/cdi/Utils.java
Labels: OCA Verified

#8991 4.0.11: Convert `ConcurrentHashMap` which does service loading to `HashMap` with reentrant lock
  common/configurable/src/main/java/io/helidon/common/configurable/ObserverManager.java
Labels: backport, 4.x, OCA Verified, observability

#8994 4.x: Fix example to use the configured values.
  examples/webserver/tls/src/main/java/io/helidon/examples/webserver/tls/Main.java
Labels: bug, examples, 4.x, OCA Verified

#8992 4.0.11: Skip test if InstancePrincipal UT if Imds is available
  integrations/oci/sdk/cdi/src/test/java/io/helidon/integrations/oci/sdk/cdi/TestInstancePrincipalsAuthenticationDetailsProvider.java
  integrations/oci/sdk/cdi/src/test/java/io/helidon/integrations/oci/sdk/cdi/TestProcessProviderInjectionPoint.java
  integrations/oci/sdk/cdi/src/test/java/io/helidon/integrations/oci/sdk/cdi/TestSpike.java
  integrations/oci/sdk/cdi/src/test/java/io/helidon/integrations/oci/sdk/cdi/Utils.java
Labels: testing, OCI, backport, 4.x, OCA Verified

#8936 Fix confusing log message on breach of overallTimeout duration
  fault-tolerance/fault-tolerance/src/main/java/io/helidon/faulttolerance/RetryImpl.java
Labels: fault-tolerance, 4.x, OCA Verified

#8995 Replaces ConcurrentHashMap to avoid potential thread pinning
  webserver/static-content/src/main/java/io/helidon/webserver/staticcontent/ClassPathContentHandler.java
Labels: 1.x, performance, OCA Verified

#8943 Attempt to read an unconsumed response entity to allow connection caching
  webclient/http1/src/main/java/io/helidon/webclient/http1/Http1ClientResponseImpl.java
  webclient/tests/http1/src/test/java/io/helidon/webclient/http1/Http1ClientTest.java
Labels: performance, 4.x, OCA Verified

#8996 4.0.11: Attempt to read an unconsumed response entity to allow connection caching
  webclient/http1/src/main/java/io/helidon/webclient/http1/Http1ClientResponseImpl.java
  webclient/tests/http1/src/test/java/io/helidon/webclient/http1/Http1ClientTest.java
Labels: webclient, backport, 4.x, OCA Verified

#8997 Add RW locking to better manage concurrency
  metrics/providers/micrometer/src/main/java/io/helidon/metrics/providers/micrometer/MMeterRegistry.java
Labels: OCA Verified

#8999 4.0.11: Add RW locking to better manage concurrency
  metrics/providers/micrometer/src/main/java/io/helidon/metrics/providers/micrometer/MMeterRegistry.java
Labels: metrics, backport, 4.x, OCA Verified

#8956 4.x: Java 22 support. Upgrade ASM, byte-buddy, and eclipselink
  applications/mp/pom.xml
  dependencies/pom.xml
  microprofile/graphql/server/src/test/java/io/helidon/microprofile/graphql/server/SchemaGeneratorTest.java
  pom.xml
Labels: build, 4.x, OCA Verified

#9003 3.x: Upgrade Jersey to 3.0.14
  dependencies/pom.xml
Labels: dependencies, 3.x, OCA Verified

#9000 Skips content encoding of empty entities
  webserver/tests/webserver/pom.xml
  webserver/tests/webserver/src/test/java/io/helidon/webserver/tests/ContentEncodingEmptyTest.java
  webserver/webserver/src/main/java/io/helidon/webserver/http/ServerResponseBase.java
Labels: 4.x, OCA Verified

#9007 Update max-prologue-length from 2048 to 4096 to align with 3.x
  webserver/webserver/src/main/java/io/helidon/webserver/http1/Http1ConfigBlueprint.java
Labels: OCA Verified

#9008 4.0.11: Skips content encoding of empty entities.
  webserver/tests/webserver/pom.xml
  webserver/tests/webserver/src/test/java/io/helidon/webserver/tests/ContentEncodingEmptyTest.java
  webserver/webserver/src/main/java/io/helidon/webserver/http/ServerResponseBase.java
Labels: webserver, 4.x, OCA Verified

#9009 4.0.11: Update UriEncoding.decode to expose a decodeQuery method
  common/uri/src/main/java/io/helidon/common/uri/UriEncoding.java
  common/uri/src/main/java/io/helidon/common/uri/UriQueryImpl.java
  common/uri/src/test/java/io/helidon/common/uri/UriEncodingTest.java
  common/uri/src/test/java/io/helidon/common/uri/UriQueryTest.java
Labels: common, 4.x, OCA Verified

#9010 4.0.11: Update max-prologue-length from 2048 to 4096 to align with 3.x
  webserver/webserver/src/main/java/io/helidon/webserver/http1/Http1ConfigBlueprint.java
Labels: webserver, 4.x, OCA Verified

#9014 4.x: Fix problem where throwing an Error would close connection but send keep-alive
  webserver/tests/webserver/src/test/java/io/helidon/webserver/tests/ErrorHandlingThrowableTest.java
  webserver/webserver/src/main/java/io/helidon/webserver/http/ErrorHandlers.java
  webserver/webserver/src/main/java/io/helidon/webserver/http1/Http1Connection.java
Labels: bug, webserver, OCA Verified

#9015 4.x: Update eclipselink to 4.0.4
  dependencies/pom.xml
Labels: dependencies, 4.x, OCA Verified

#9016 4.0.11: Fix problem where throwing an Error would close connection but send keep-alive
  webserver/tests/webserver/src/test/java/io/helidon/webserver/tests/ErrorHandlingThrowableTest.java
  webserver/webserver/src/main/java/io/helidon/webserver/http/ErrorHandlers.java
  webserver/webserver/src/main/java/io/helidon/webserver/http1/Http1Connection.java
Labels: webserver, backport, 4.x, OCA Verified

#9017 4.0.11: Update eclipselink to 4.0.4
  dependencies/pom.xml
Labels: jpa/jta, dependencies, backport, 4.x, OCA Verified

#9018 4.0.11: Update CHANGELOG for 4.0.11 release
  CHANGELOG.md
Labels: 4.x, OCA Verified

#9001 4.1: Return correct status on too long prologue
  webserver/tests/webserver/src/test/java/io/helidon/webserver/tests/ConfiguredLimitsTest.java
  webserver/webserver/src/main/java/io/helidon/webserver/http1/Http1Prologue.java
  webserver/webserver/src/test/java/io/helidon/webserver/http1/Http1PrologueTest.java
Labels: webserver, 4.x, OCA Verified

#8934 4.x: Use Hamcrest assertions instead of JUnit in dbclient/mongodb (#1749)
  dbclient/mongodb/src/test/java/io/helidon/dbclient/mongodb/StatementParsersTest.java
Labels: OCA Verified

#8915 4.x: Remove unnecessary field length from ContentLengthInputStream
  webclient/http1/src/main/java/io/helidon/webclient/http1/Http1CallChainBase.java
Labels: OCA Verified

#8937 [4.x] Server TLS - Add path key description
  README.md
  docs/src/main/asciidoc/mp/server.adoc
  docs/src/main/asciidoc/se/webserver.adoc
Labels: docs, webserver, 4.x, OCA Verified

#9027 [3.x] Fixed native image build for webserver and GraalVM 17.0.12+8.1
  tests/integration/jpa/appl/pom.xml
Labels: OCA Verified

#9029 4.x: Fix SetCookie to work for client side as well
  http/http/src/main/java/io/helidon/http/SetCookie.java
  http/http/src/test/java/io/helidon/http/SetCookieTest.java
Labels: bug, common, 4.x, OCA Verified

#9030 4.x: Fixed concurrent access to identity hash map with reentrant lock.
  microprofile/jwt-auth/src/main/java/io/helidon/microprofile/jwt/auth/JwtAuthProvider.java
Labels: security, 4.x, OCA Verified

#9031 4.x: Correctly guard concurrent access to hash map
  security/providers/oidc/src/main/java/io/helidon/security/providers/oidc/OidcProvider.java
Labels: OCA Verified

#8957 4.x MDC propagation without context
  common/context/src/main/java/io/helidon/common/context/ContextAwareExecutorImpl.java
  logging/jul/src/test/java/io/helidon/logging/jul/JulMdcTest.java
  logging/log4j/src/test/java/io/helidon/logging/log4j/Log4jMdcTest.java
  logging/slf4j/src/test/java/Slf4jMdcTest.java
Labels: OCA Verified

#8922 4.x: SSE mediaType comes null after first consumed event
  webclient/sse/src/main/java/io/helidon/webclient/sse/SseSourceHandlerProvider.java
Labels: OCA Verified

#9037 4.x: Reenables failing JPA test
  integrations/cdi/jpa-cdi/src/test/java/io/helidon/integrations/cdi/jpa/TestAnnotationRewriting.java
Labels: MP, P2, cdi, jpa/jta, testing, java, 4.x, OCA Verified

#9048 3.x: Add suppression for graalvm compiler
  etc/dependency-check-suppression.xml
Labels: build, 3.x, OCA Verified

#9047 4.x: Add suppression for graalvm compiler
  etc/dependency-check-suppression.xml
Labels: build, 4.x, OCA Verified

#8979 4.x: Remove unused parameters from JsonpWriter
  http/media/jsonp/src/main/java/io/helidon/http/media/jsonp/JsonpWriter.java
Labels: OCA Verified

#9050 4.x: Introduction of HSON library to write and parse Helidon metadata files.
  all/pom.xml
  bom/pom.xml
  metadata/hson/pom.xml
  metadata/hson/src/main/java/io/helidon/metadata/hson/Hson.java
  metadata/hson/src/main/java/io/helidon/metadata/hson/HsonArray.java
  metadata/hson/src/main/java/io/helidon/metadata/hson/HsonException.java
  metadata/hson/src/main/java/io/helidon/metadata/hson/HsonObject.java
  metadata/hson/src/main/java/io/helidon/metadata/hson/HsonParser.java
  metadata/hson/src/main/java/io/helidon/metadata/hson/HsonValues.java
  metadata/hson/src/main/java/io/helidon/metadata/hson/package-info.java
  metadata/hson/src/main/java/module-info.java
  metadata/hson/src/test/java/io/helidon/metadata/hson/ExistingTypesTest.java
  metadata/hson/src/test/java/io/helidon/metadata/hson/HsonTest.java
  metadata/hson/src/test/resources/config-metadata.json
  metadata/hson/src/test/resources/json-features.json
  metadata/hson/src/test/resources/reflection-config.json
  metadata/hson/src/test/resources/service-registry.json
  metadata/pom.xml
  pom.xml
Labels: 4.x, OCA Verified

#9051 4.x: Bugfixes log builder
  builder/codegen/src/main/java/io/helidon/builder/codegen/BuilderCodegen.java
  logging/jul/src/main/java/io/helidon/logging/jul/JulProvider.java
Labels: bug, 4.x, OCA Verified

#9020 4.x: Remove unused constructor parameter from io.helidon.faulttolerance.AsyncImpl
  fault-tolerance/fault-tolerance/src/main/java/io/helidon/faulttolerance/Async.java
  fault-tolerance/fault-tolerance/src/main/java/io/helidon/faulttolerance/AsyncImpl.java
Labels: OCA Verified

#8871 4.x: native-image - Add required reflection configuration for EclipseLink
  integrations/cdi/eclipselink-cdi/src/main/resources/META-INF/native-image/io/helidon/integrations/cdi/helidon-integrations-cdi-eclipselink/native-image.properties
  integrations/cdi/eclipselink-cdi/src/main/resources/META-INF/native-image/io/helidon/integrations/cdi/helidon-integrations-cdi-eclipselink/reflect-config.json
  integrations/cdi/eclipselink-cdi/src/main/resources/META-INF/native-image/org/eclipse/persistence/org.eclipse.persistence.core/resource-config.json
Labels: native-image, 4.x, OCA Verified

#9040 Issue #7102 - WebClient should have a mode that is resilient to bad media/content types
  common/http/src/main/java/io/helidon/common/http/MediaType.java
  tests/integration/webclient/src/test/java/io/helidon/tests/integration/webclient/HeadersTest.java
  webclient/webclient/src/main/java/io/helidon/webclient/NettyClientHandler.java
  webclient/webclient/src/main/java/io/helidon/webclient/WebClient.java
  webclient/webclient/src/main/java/io/helidon/webclient/WebClientConfiguration.java
  webclient/webclient/src/main/java/io/helidon/webclient/WebClientResponseHeadersImpl.java
  webclient/webclient/src/main/java/io/helidon/webclient/WebClientResponseImpl.java
Labels: OCA Verified

#9042 4.x: Replace deprecated method Span.baggage(key) on Span.baggage().get(key)
  tracing/providers/jaeger/src/test/java/io/helidon/tracing/providers/jaeger/JaegerBaggageTest.java
  tracing/providers/opentelemetry/src/main/java/io/helidon/tracing/providers/opentelemetry/OpenTelemetrySpan.java
  tracing/providers/opentelemetry/src/test/java/io/helidon/tracing/providers/opentelemetry/TestBaggageApi.java
  tracing/providers/opentelemetry/src/test/java/io/helidon/tracing/providers/opentelemetry/TestSpanAndBaggage.java
  tracing/providers/opentracing/src/main/java/io/helidon/tracing/providers/opentracing/OpenTracingSpan.java
  tracing/providers/opentracing/src/test/java/io/helidon/tracing/providers/opentracing/TestBaggageApi.java
Labels: OCA Verified

#9043 4.x: Clarify javadoc for HealthCheckResponse.Builder.status(boolean)
  health/health/src/main/java/io/helidon/health/HealthCheckResponse.java
Labels: OCA Verified

#8938 4.x: Document supported GraalVM version for native-image
  docs/src/main/asciidoc/includes/prerequisites.adoc
Labels: docs, graal, 4.x, OCA Verified

#9059 4.x: Add `classesDirectory` configuration to failsafe plugin
  applications/parent/pom.xml
Labels: testing, 4.x, OCA Verified

#8868 4.x: Update Keycloak version to 24 in OIDC guide
  docs/src/main/asciidoc/mp/guides/security-oidc.adoc
  docs/src/main/asciidoc/se/guides/security-oidc.adoc
  docs/src/main/java/io/helidon/docs/mp/guides/SecurityOidcSnippets.java
  docs/src/main/java/io/helidon/docs/se/guides/SecurityOidcSnippets.java
Labels: docs, security, 4.x, OCA Verified

#9032 MP Metrics 5.1 support
  config/metadata-processor/src/main/java/io/helidon/config/metadata/processor/TypeHandlerBase.java
  dependencies/pom.xml
  docs/src/main/asciidoc/config/io_helidon_metrics_api_MetricsConfig.adoc
  docs/src/main/asciidoc/includes/metrics/metrics-config.adoc
  docs/src/main/asciidoc/includes/metrics/metrics-shared.adoc
  metrics/api/src/main/java/io/helidon/metrics/api/DistributionSummary.java
  metrics/api/src/main/java/io/helidon/metrics/api/GcTimeType.java
  metrics/api/src/main/java/io/helidon/metrics/api/MetricsConfigBlueprint.java
  metrics/api/src/main/java/io/helidon/metrics/api/NoOpMeter.java
  metrics/api/src/main/java/io/helidon/metrics/api/Timer.java
  metrics/api/src/test/java/io/helidon/metrics/api/TestGcTimeTypeChoice.java
  metrics/provider-tests/src/main/java/io/helidon/metrics/provider/tests/TestDistributionSummary.java
  metrics/providers/micrometer/src/main/java/io/helidon/metrics/providers/micrometer/MDistributionStatisticsConfig.java
  metrics/providers/micrometer/src/main/java/io/helidon/metrics/providers/micrometer/MDistributionSummary.java
  metrics/providers/micrometer/src/main/java/io/helidon/metrics/providers/micrometer/MTimer.java
  metrics/providers/micrometer/src/main/java/io/helidon/metrics/providers/micrometer/MicrometerMetricsFactory.java
  metrics/providers/micrometer/src/main/java/io/helidon/metrics/providers/micrometer/MicrometerPrometheusFormatter.java
  metrics/system-meters/src/main/java/io/helidon/metrics/systemmeters/SystemMetersProvider.java
  microprofile/metrics/src/main/java/io/helidon/microprofile/metrics/DistributionCustomizations.java
  microprofile/metrics/src/main/java/io/helidon/microprofile/metrics/HelidonHistogram.java
  microprofile/metrics/src/main/java/io/helidon/microprofile/metrics/HelidonSnapshot.java
  microprofile/metrics/src/main/java/io/helidon/microprofile/metrics/HelidonTimer.java
  microprofile/metrics/src/main/java/io/helidon/microprofile/metrics/MetricsCdiExtension.java
  microprofile/metrics/src/main/java/io/helidon/microprofile/metrics/Registry.java
  microprofile/metrics/src/main/java/io/helidon/microprofile/metrics/RegistryProducer.java
  microprofile/metrics/src/test/java/io/helidon/microprofile/metrics/HelloWorldAsyncResponseTest.java
  microprofile/metrics/src/test/java/io/helidon/microprofile/metrics/HelloWorldResource.java
  microprofile/metrics/src/test/java/io/helidon/microprofile/metrics/HelloWorldRestEndpointSimpleTimerDisabledTest.java
  microprofile/metrics/src/test/java/io/helidon/microprofile/metrics/MetricsMpServiceTest.java
  microprofile/metrics/src/test/java/io/helidon/microprofile/metrics/TestDistributionCustomizations.java
  microprofile/metrics/src/test/java/io/helidon/microprofile/metrics/TestGcTimeCounter.java
  microprofile/metrics/src/test/java/io/helidon/microprofile/metrics/TestGcTimeGauge.java
  microprofile/tests/tck/tck-metrics/pom.xml
Labels: OCA Verified

#9023 4.x: Helidon Webclient (4.0.10) is not routing the requests through proxy configured using Proxy Builder. #9022
  pom.xml
  webclient/api/src/main/java/io/helidon/webclient/api/ClientRequestBase.java
  webclient/api/src/main/java/io/helidon/webclient/api/Proxy.java
  webclient/http1/src/main/java/io/helidon/webclient/http1/Http1ClientRequestImpl.java
  webclient/tests/http1/pom.xml
  webclient/tests/http1/src/test/java/io/helidon/webclient/tests/HttpMockProxyTest.java
  webclient/tests/http1/src/test/java/io/helidon/webclient/tests/HttpProxyTest.java
  webclient/tests/http1/src/test/java/io/helidon/webclient/tests/HttpsProxyTest.java
Labels: OCA Verified

#9072 4.x: Upgrade snakeyaml to 2.2
  dependencies/pom.xml
Labels: dependencies, 4.x, OCA Verified

#9071 3.x: Upgrade snakeyaml to 2.2
  dependencies/pom.xml
Labels: dependencies, 3.x, OCA Verified

#9069 4.x: Update CHANGELOG and remove cruft file
  CHANGELOG.md
  all-config-meta.json
Labels: 4.x, OCA Verified

#9063 4.x: docs: Cleanup prerequisites and use of prereq table
  docs/src/main/asciidoc/about/cli.adoc
  docs/src/main/asciidoc/about/introduction.adoc
  docs/src/main/asciidoc/includes/prerequisites.adoc
  docs/src/main/asciidoc/mp/guides/quickstart.adoc
  docs/src/main/asciidoc/se/guides/quickstart.adoc
Labels: docs, 4.x, OCA Verified
