Repository helidon-io/helidon, pull requests merged in 2025-07, with the labels that each got.

#10303 Proper handling of ACK frames and long gRPC data frames
  webclient/grpc/src/main/java/io/helidon/webclient/grpc/GrpcBaseClientCall.java
  webclient/grpc/src/main/java/io/helidon/webclient/grpc/GrpcClientCall.java
  webclient/grpc/src/main/java/io/helidon/webclient/grpc/GrpcUnaryClientCall.java
  webclient/http2/src/main/java/io/helidon/webclient/http2/Http2ClientConnection.java
  webclient/tests/grpc/src/main/proto/downloads.proto
  webclient/tests/grpc/src/test/java/io/helidon/webclient/grpc/tests/DownloadServiceTest.java
Labels: OCA Verified

#10315 4.x: Use Maven 3.9.9
  .github/actions/common/action.yml
  .github/workflows/nightly.yaml
  .github/workflows/release.yaml
  .github/workflows/snapshot.yaml
  .github/workflows/validate.yml
Labels: build, OCA Verified

#10316 4.x: Remove unused code from HelidonGauge and MetricStore
  microprofile/metrics/src/main/java/io/helidon/microprofile/metrics/HelidonGauge.java
  microprofile/metrics/src/main/java/io/helidon/microprofile/metrics/MetricStore.java
  microprofile/metrics/src/main/java/io/helidon/microprofile/metrics/MetricsForMetadata.java
Labels: OCA Verified

#10172 3.x: Adjusts OCI vault config sources to read only secret versions that are extant and in the Current rotation state
  integrations/oci/oci-secrets-config-source/src/main/java/io/helidon/integrations/oci/secrets/configsource/SecretBundleLazyConfigSource.java
  integrations/oci/oci-secrets-config-source/src/main/java/io/helidon/integrations/oci/secrets/configsource/SecretBundleNodeConfigSource.java
Labels: OCA Verified

#10332 4.2.4: Shutdown services in reverse order (fixes issue #10239)
  docs/src/main/asciidoc/se/injection.adoc
  docs/src/main/java/io/helidon/docs/se/inject/RunLevelExample.java
  service/registry/src/main/java/io/helidon/service/registry/ScopedRegistryImpl.java
  service/tests/registry/src/main/java/io/helidon/service/test/registry/StartStopFixture.java
  service/tests/registry/src/test/java/io/helidon/service/test/registry/StartStopTest.java
Labels: backport, 4.x, OCA Verified

#10336 Check consistency of x-forwarded- headers; fix incorrect port assignment in compatibility helper
  http/http/src/main/java/io/helidon/http/RequestedUriDiscoveryContext.java
  http/http/src/main/java/io/helidon/http/UriInfoCompatibilityHelper.java
  http/http/src/test/java/io/helidon/http/RequestedUriDiscoveryContextTest.java
Labels: OCA Verified

#10346 4.2.4: Full debugging possible for HTTP client requests
  webclient/http1/src/main/java/io/helidon/webclient/http1/Http1CallChainBase.java
  webclient/http1/src/main/java/io/helidon/webclient/http1/Http1CallEntityChain.java
  webclient/http1/src/main/java/io/helidon/webclient/http1/Http1CallOutputStreamChain.java
  webclient/http1/src/main/java/io/helidon/webclient/http1/Http1ClientImpl.java
  webclient/http1/src/main/java/io/helidon/webclient/http1/Http1ClientRequestImpl.java
  webclient/http2/src/main/java/io/helidon/webclient/http2/Http2ClientImpl.java
  webclient/http2/src/main/java/io/helidon/webclient/http2/Http2ClientRequestImpl.java
  webclient/tests/http1/src/test/java/io/helidon/webclient/http1/Http1ClientTest.java
  webclient/tests/http2/src/test/java/io/helidon/webclient/tests/http2/Http2ClientTest.java
Labels: webclient, backport, 4.x, OCA Verified

#10345 4.2.4: Update to security documentation to clarify a statement
  docs/src/main/asciidoc/includes/security/helidon-endpoints.adoc
  docs/src/main/asciidoc/se/security/containers-integration.adoc
Labels: docs, backport, 4.x, OCA Verified

#10342 4.2.4: Helidon MP app on OCI Guide (8353)
  .gitignore
  docs/src/main/asciidoc/includes/attributes.adoc
  docs/src/main/asciidoc/includes/dependencies.adoc
  docs/src/main/asciidoc/mp/guides/oci-guide.adoc
  docs/src/main/asciidoc/mp/integrations/oci.adoc
  docs/src/main/asciidoc/sitegen.yaml
Labels: docs, backport, OCA Verified

#10341 4.2.4: Adds service registry-sourced beans as selected alternatives to fix #10096
  integrations/oci/sdk/cdi/pom.xml
  integrations/oci/sdk/cdi/src/test/java/io/helidon/integrations/oci/sdk/cdi/TestServiceRegistryInterop.java
  integrations/oci/sdk/cdi/src/test/java/io/helidon/integrations/oci/sdk/cdi/TestSpike.java
  integrations/oci/sdk/cdi/src/test/java/io/helidon/integrations/oci/sdk/cdi/Utils.java
  microprofile/cdi/src/main/java/io/helidon/microprofile/cdi/ServiceRegistryExtension.java
  microprofile/cdi/src/main/java/module-info.java
Labels: MP, cdi, integration, backport, java, 4.x, OCA Verified, microprofile

#10339 Use Services.get(Config.class) instead of global config
  metrics/api/pom.xml
  metrics/api/src/main/java/io/helidon/metrics/api/MetricsConfigSupport.java
  metrics/api/src/main/java/io/helidon/metrics/api/MetricsFactory.java
  metrics/api/src/main/java/io/helidon/metrics/api/MetricsFactoryManager.java
  metrics/api/src/main/java/module-info.java
  metrics/providers/micrometer/pom.xml
  metrics/providers/micrometer/src/main/java/io/helidon/metrics/providers/micrometer/MicrometerMetricsFactory.java
  metrics/providers/micrometer/src/main/java/module-info.java
Labels: OCA Verified

#10347 Improvements to gRPC SE and MP docs
  docs/src/main/asciidoc/mp/grpc/server.adoc
  docs/src/main/asciidoc/se/grpc/client.adoc
  docs/src/main/asciidoc/se/grpc/server.adoc
  docs/src/main/java/io/helidon/docs/mp/grpc/GrpcSnippets.java
  docs/src/main/java/io/helidon/docs/mp/grpc/Strings.java
  docs/src/main/java/io/helidon/docs/se/grpc/ClientSnippets.java
Labels: docs, grpc, 4.x, OCA Verified

#10343 4.2.4: Fix Jackson when charset is used for Accept header.
  http/media/jackson/src/main/java/io/helidon/http/media/jackson/JacksonWriter.java
  http/media/jackson/src/test/java/io/helidon/http/media/jackson/JacksonMediaTest.java
  http/tests/media/jackson/pom.xml
  http/tests/media/jackson/src/test/java/io/helidon/http/tests/integration/media/jackson/JacksonTest.java
  http/tests/media/jackson/src/test/resources/logging.properties
  http/tests/media/pom.xml
Labels: bug, backport, 4.x, OCA Verified

#10351 Updates class comment dropping remark about interal use only
  webclient/http2/src/main/java/io/helidon/webclient/http2/Http2ClientStream.java
Labels: docs, webclient, 4.x, OCA Verified

#10348 4.2.4: PKCE and Client credential flow added to the OIDC
  security/providers/oidc-common/src/main/java/io/helidon/security/providers/oidc/common/BaseBuilder.java
  security/providers/oidc-common/src/main/java/io/helidon/security/providers/oidc/common/OidcConfig.java
  security/providers/oidc-common/src/main/java/io/helidon/security/providers/oidc/common/OidcOutboundType.java
  security/providers/oidc-common/src/main/java/io/helidon/security/providers/oidc/common/PkceChallengeMethod.java
  security/providers/oidc/src/main/java/io/helidon/security/providers/oidc/OidcFeature.java
  security/providers/oidc/src/main/java/io/helidon/security/providers/oidc/OidcProvider.java
  security/providers/oidc/src/main/java/io/helidon/security/providers/oidc/OidcUtil.java
  security/providers/oidc/src/main/java/io/helidon/security/providers/oidc/TenantAuthenticationHandler.java
  tests/integration/oidc/pom.xml
  tests/integration/oidc/src/main/java/io/helidon/tests/integration/oidc/TestResource.java
  tests/integration/oidc/src/test/java/io/helidon/tests/integration/oidc/ClientCredentialsIT.java
  tests/integration/oidc/src/test/java/io/helidon/tests/integration/oidc/PkceIT.java
  tests/integration/oidc/src/test/resources/application.yaml
  tests/integration/oidc/src/test/resources/logging.properties
  tests/integration/oidc/src/test/resources/test-realm.json
Labels: backport, OCA Verified

#10273 4.x: Check supertypes during validation of runtime types. Added test
  builder/codegen/src/main/java/io/helidon/builder/codegen/ValidationTask.java
  builder/tests/inheritance/pom.xml
  builder/tests/inheritance/src/main/java/io/helidon/builder/tests/inheritance/Inheritance.java
  builder/tests/inheritance/src/main/java/io/helidon/builder/tests/inheritance/InheritanceBase.java
  builder/tests/inheritance/src/main/java/io/helidon/builder/tests/inheritance/InheritanceBaseConfigBlueprint.java
  builder/tests/inheritance/src/main/java/io/helidon/builder/tests/inheritance/InheritanceConfigBlueprint.java
  builder/tests/inheritance/src/main/java/module-info.java
  builder/tests/inheritance/src/test/java/io/helidon/builder/tests/inheritance/InheritanceTest.java
  builder/tests/pom.xml
Labels: OCA Verified

#10365 Use common config instead of config with `Services.get`
  metrics/providers/micrometer/src/main/java/io/helidon/metrics/providers/micrometer/MicrometerMetricsFactory.java
Labels: OCA Verified

#10366 4.2.4: Read timeout deprecated in the ConnectionKey
  common/socket/src/main/java/io/helidon/common/socket/IdleInputStream.java
  webclient/api/src/main/java/io/helidon/webclient/api/ConnectionKey.java
  webclient/api/src/main/java/io/helidon/webclient/api/HttpClientRequest.java
  webclient/api/src/main/java/io/helidon/webclient/api/Proxy.java
  webclient/grpc/src/main/java/io/helidon/webclient/grpc/GrpcBaseClientCall.java
  webclient/http1/src/main/java/io/helidon/webclient/http1/Http1ConnectionCache.java
  webclient/http2/src/main/java/io/helidon/webclient/http2/Http2CallChainBase.java
  webclient/http2/src/main/java/io/helidon/webclient/http2/Http2ClientImpl.java
  webclient/tests/http1/src/test/java/io/helidon/webclient/http1/Http1ClientTest.java
  webserver/testing/junit5/http2/src/main/java/io/helidon/webserver/testing/junit5/http2/Http2TestConnection.java
  webserver/tests/http2/src/test/java/io/helidon/webserver/tests/http2/EmptyFrameCntTest.java
Labels: backport, 4.x, OCA Verified

#10367 4.x: Do now warn about setting a config to registry when using Config.global
  common/config/src/main/java/io/helidon/common/config/GlobalConfig.java
  config/config/src/main/java/io/helidon/config/Config.java
Labels: config, 4.x, OCA Verified

#10371 Update CHANGELOG for 4.2.4 release
  CHANGELOG.md
Labels: build, 4.x, OCA Verified

#10324 4.x: Update to ServiceRegistry API to add helper methods for qualified instances
  service/registry/src/main/java/io/helidon/service/registry/CoreServiceRegistry.java
  service/registry/src/main/java/io/helidon/service/registry/ServiceRegistry.java
  service/registry/src/main/java/io/helidon/service/registry/Services.java
  service/registry/src/main/java/io/helidon/service/registry/VirtualDescriptor.java
  service/tests/inject/src/test/java/io/helidon/service/tests/inject/LateBindingTest.java
Labels: 4.x, OCA Verified, inject

#10309 4.x: Removed unnecessary modifier protected of utility methods in SchemaGeneratorHelper
  microprofile/graphql/server/src/main/java/io/helidon/microprofile/graphql/server/SchemaGeneratorHelper.java
Labels: OCA Verified

#10331 Allow option for adding Iterable<String> header values
  http/http/src/main/java/io/helidon/http/HeaderValues.java
  http/http/src/test/java/io/helidon/http/HeaderValueIterableTest.java
Labels: OCA Verified

#10379 Add ability to exclude health checks by name; clarify doc
  docs/src/main/asciidoc/includes/health.adoc
  docs/src/main/asciidoc/mp/health.adoc
  docs/src/main/asciidoc/se/health.adoc
  webserver/observe/health/pom.xml
  webserver/observe/health/src/main/java/io/helidon/webserver/observe/health/HealthObserver.java
  webserver/observe/health/src/main/java/io/helidon/webserver/observe/health/HealthObserverConfigBlueprint.java
  webserver/observe/health/src/test/java/io/helidon/webserver/observe/health/TestExclude.java
Labels: OCA Verified

#10387 4.x commons lang 3.18.0
  config/etcd/pom.xml
  dependencies/pom.xml
  pom.xml
Labels: dependencies, 4.x, OCA Verified

#10378 4.x: Update Jakarta EL implementation to org.glassfish.expressly:expressly:5.0.0
  dependencies/pom.xml
  microprofile/bean-validation/pom.xml
  microprofile/tests/tck/tck-cdi-lang-model/pom.xml
  microprofile/tests/tck/tck-cdi/pom.xml
  security/abac/policy-el/pom.xml
  tests/integration/crac/pom.xml
  tests/integration/security/abac-policy/pom.xml
  tests/integration/security/gh1487/pom.xml
Labels: dependencies, bean validation, 4.x, OCA Verified

#10376 4.x: Fix issue with invalid registry if global registry is shutdown
  common/context/context/src/main/java/io/helidon/common/context/Context.java
  common/context/context/src/main/java/io/helidon/common/context/ListContext.java
  common/context/context/src/test/java/io/helidon/common/context/ContextsTest.java
  service/registry/src/main/java/io/helidon/service/registry/GlobalServiceRegistry.java
  service/registry/src/main/java/io/helidon/service/registry/ServiceRegistryManager.java
Labels: 4.x, OCA Verified, inject

#10388 4.x: Upgrade dependency check plugin to 12.1.3
  pom.xml
Labels: build, 4.x, OCA Verified

#10306 4.x: Docs describes interaction HelidonTest with MicroProfile Config profiles (#8849)
  docs/src/main/asciidoc/mp/testing/testing-common.adoc
Labels: OCA Verified

#10389 Adds documentation for new JSON-RPC client and server APIs
  docs/src/main/asciidoc/se/jsonrpc/client.adoc
  docs/src/main/asciidoc/se/jsonrpc/server.adoc
  docs/src/main/asciidoc/sitegen.yaml
  docs/src/main/java/io/helidon/docs/se/jsonrpc/ClientSnippets.java
  docs/src/main/java/io/helidon/docs/se/jsonrpc/ServerSnippets.java
Labels: 4.x, OCA Verified, jsonrpc

#10408 3.x: Upgrade gson to 2.13.1
  dependencies/pom.xml
Labels: dependencies, 3.x, OCA Verified

#10393 4.x: Update to documentation of internal features
  common/features/README.md
  docs-internal/config-api.md
  docs-internal/context.md
  docs-internal/datachunkinputstream.md
  docs-internal/db.md
  docs-internal/feature-catalog.md
  docs-internal/generic-type.md
  docs-internal/helidon-3.0.md
  docs-internal/multipartdecoder.md
Labels: task, 4.x, OCA Verified

#10412 Upgrades to gRPC 1.73.0 and removes reflection proto files
  dependencies/pom.xml
  webserver/grpc/pom.xml
  webserver/grpc/src/main/java/module-info.java
  webserver/grpc/src/main/proto/reflection.proto
  webserver/grpc/src/main/proto/reflectionv1alpha.proto
Labels: grpc, 4.x, OCA Verified

#10418 4.2.5: Upgrade gson to 2.13.1
  dependencies/pom.xml
Labels: dependencies, backport, OCA Verified

#10417 4.2.5: commons lang 3.18.0
  config/etcd/pom.xml
  dependencies/pom.xml
  pom.xml
Labels: dependencies, backport, OCA Verified

#10425 4.2.5: Suppress another grpc false positive
  etc/dependency-check-suppression.xml
Labels: build, 4.x, OCA Verified

#10419 Add Coherence Embedding Store Support
  all/pom.xml
  bom/pom.xml
  dependencies/pom.xml
  docs/src/main/asciidoc/se/integrations/langchain4j/coherence.adoc
  docs/src/main/asciidoc/se/integrations/langchain4j/core.adoc
  docs/src/main/asciidoc/se/integrations/langchain4j/langchain4j.adoc
  integrations/langchain4j/codegen/src/main/java/io/helidon/integrations/langchain4j/codegen/ConfigureMethodBuilder.java
  integrations/langchain4j/codegen/src/main/java/io/helidon/integrations/langchain4j/codegen/IntrospectionBlueprintBuilder.java
  integrations/langchain4j/langchain4j/src/main/java/io/helidon/integrations/langchain4j/EmbeddingStoreContentRetrieverConfigBlueprint.java
  integrations/langchain4j/langchain4j/src/main/java/io/helidon/integrations/langchain4j/EmbeddingStoreContentRetrieverFactory.java
  integrations/langchain4j/providers/coherence/pom.xml
  integrations/langchain4j/providers/coherence/src/main/java/io/helidon/integrations/langchain4j/providers/coherence/CoherenceFactoryMethods.java
  integrations/langchain4j/providers/coherence/src/main/java/io/helidon/integrations/langchain4j/providers/coherence/CoherenceLc4jProvider.java
  integrations/langchain4j/providers/coherence/src/main/java/io/helidon/integrations/langchain4j/providers/coherence/package-info.java
  integrations/langchain4j/providers/coherence/src/main/java/module-info.java
  integrations/langchain4j/providers/coherence/src/test/java/io/helidon/integrations/langchain4j/providers/coherence/CoherenceEmbeddingStoreIT.java
  integrations/langchain4j/providers/coherence/src/test/java/io/helidon/integrations/langchain4j/providers/coherence/CoherenceEmbeddingStorePropertiesTest.java
  integrations/langchain4j/providers/coherence/src/test/java/io/helidon/integrations/langchain4j/providers/coherence/MockEmbeddingModelFactory.java
  integrations/langchain4j/providers/coherence/src/test/resources/application.yaml
  integrations/langchain4j/providers/coherence/src/test/resources/logging-test.properties
  integrations/langchain4j/providers/pom.xml
Labels: dependencies, OCA Verified

#10424 Clarification of documentation of integration of security and webserver
  docs/se/security/03_containers-integration.adoc
  docs/shared/security/helidon-endpoints.adoc
Labels: docs, 2.x, OCA Verified

#10423 3.x: Docs update
  docs/includes/security/helidon-endpoints.adoc
  docs/se/security/containers-integration.adoc
Labels: 3.x, OCA Verified

#10436 4.x: Micro Upgrades to microprofile lra, reactive messaging, reactive operators
  dependencies/pom.xml
Labels: dependencies, 4.x, OCA Verified, microprofile

#10442 4.x: Upgrade typesafe-config to 1.4.4
  dependencies/pom.xml
Labels: config, dependencies, OCA Verified

#10445 Decrease log level severity when a stream timeout is retried
  webclient/grpc/src/main/java/io/helidon/webclient/grpc/GrpcBaseClientCall.java
Labels: grpc, 4.x, OCA Verified

#10443 4.x: Update to h2 database native image support
  dbclient/hikari/src/main/resources/META-INF/helidon/native-image/reflection-config.json
  dbclient/hikari/src/main/resources/META-INF/native-image/io.helidon.integrations.cdi/helidon-integrations-cdi-datasource-hikaricp/reflect-config.json
  integrations/db/h2/src/main/java/io/helidon/integrations/db/h2/EngineSubstitution.java
  integrations/db/h2/src/main/java/io/helidon/integrations/db/h2/SessionSubstitution.java
Labels: native-image, 4.x, OCA Verified

#10451 4.x Adopt Micrometer 1.15.2
  dependencies/pom.xml
  integrations/micrometer/cdi/src/main/java/io/helidon/integrations/micrometer/cdi/MicrometerCdiExtension.java
Labels: metrics, dependencies, OCA Verified

#10449 3.x: Updated version management
  dependencies/pom.xml
Labels: dependencies, OCA Verified

#10454 Update CHANGELOG for 3.2.13 release
  CHANGELOG.md
Labels: build, 3.x, OCA Verified

#10455 4.x: Early draft of 4.3 CHANGELOG
  CHANGELOG.md
Labels: build, 4.x, OCA Verified

#10444 4.2.x: Update to correctly handle global config without issuing a warning
  common/config/src/main/java/io/helidon/common/config/GlobalConfig.java
  common/context/src/main/java/io/helidon/common/context/Context.java
  common/context/src/main/java/io/helidon/common/context/ListContext.java
  config/config/src/main/java/io/helidon/config/Config.java
  config/config/src/main/java/io/helidon/config/ConfigProvider.java
  config/config/src/main/java/io/helidon/config/ConfigValues.java
  metadata/reflection/src/main/java/io/helidon/metadata/reflection/TypedElementFactory.java
  microprofile/cdi/src/main/java/io/helidon/microprofile/cdi/HelidonContainerImpl.java
  microprofile/cdi/src/main/java/io/helidon/microprofile/cdi/ServiceRegistryExtension.java
  microprofile/cdi/src/main/java/module-info.java
  microprofile/config/pom.xml
  microprofile/config/src/main/java/io/helidon/microprofile/config/ConfigCdiExtension.java
  microprofile/config/src/main/java/io/helidon/microprofile/config/MpConfigFactory.java
  microprofile/config/src/main/java/module-info.java
  microprofile/tests/tck/tck-lra/src/test/java/io/helidon/microprofile/lra/tck/CoordinatorAppService.java
  microprofile/tests/tck/tck-lra/src/test/java/io/helidon/microprofile/lra/tck/CoordinatorDeployer.java
  service/codegen/src/main/java/io/helidon/service/codegen/DescribedService.java
  service/registry/src/main/java/io/helidon/service/registry/CoreServiceDiscovery.java
  service/registry/src/main/java/io/helidon/service/registry/CoreServiceRegistry.java
  service/registry/src/main/java/io/helidon/service/registry/GlobalServiceRegistry.java
  service/registry/src/main/java/io/helidon/service/registry/ServiceRegistryManager.java
  testing/junit5/src/main/java/io/helidon/testing/junit5/TestJunitExtension.java
Labels: config, 4.x, OCA Verified

#10458 JwtAuthProvider correct errors reported now
  microprofile/jwt-auth/src/main/java/io/helidon/microprofile/jwt/auth/JwtAuthProvider.java
Labels: OCA Verified
