Repository helidon-io/helidon, pull requests merged in 2025-05, with the labels that each got.

#10076 Update MP OpenAPI to 3.1.2
  dependencies/pom.xml
Labels: dependencies, OCA Verified

#10071 4.x: Upgrade owasp-dependency-check to 12.1.1
  pom.xml
Labels: build, 4.x, OCA Verified

#10080 Update to Jandex 3.3.0
  dependencies/pom.xml
Labels: OCA Verified

#10091 4.2.2: Ensures SecretBundleNodeConfigSource can actually be polled (#9997)
  integrations/oci/secrets-config-source/src/main/java/io/helidon/integrations/oci/secrets/configsource/SecretBundleNodeConfigSource.java
Labels: bug, config, integration, OCI, backport, 4.x, OCA Verified

#10093 4.2.2: Use `SetUpFeatures` annotation
  docs/src/main/asciidoc/se/testing.adoc
  webserver/testing/junit5/junit5/src/main/java/io/helidon/webserver/testing/junit5/HelidonRoutingJunitExtension.java
  webserver/testing/junit5/junit5/src/main/java/io/helidon/webserver/testing/junit5/HelidonServerJunitExtension.java
  webserver/testing/junit5/junit5/src/main/java/io/helidon/webserver/testing/junit5/JunitExtensionBase.java
  webserver/testing/junit5/junit5/src/main/java/io/helidon/webserver/testing/junit5/SetUpFeatures.java
  webserver/testing/junit5/junit5/src/test/java/io/helidon/webserver/testing/junit5/TestRoutingTest.java
  webserver/testing/junit5/junit5/src/test/java/io/helidon/webserver/testing/junit5/TestServerTest.java
Labels: webserver, testing, backport, 4.x, OCA Verified

#10094 4.2.2: Adjusts OCI vault config sources to read only secret versions that are extant and in the Current rotation state
  integrations/oci/secrets-config-source/src/main/java/io/helidon/integrations/oci/secrets/configsource/SecretBundleLazyConfigSource.java
  integrations/oci/secrets-config-source/src/main/java/io/helidon/integrations/oci/secrets/configsource/SecretBundleNodeConfigSource.java
Labels: bug, SE, config, integration, OCI, backport, 4.x, OCA Verified

#10095 4.2.2: Update CHANGELOG for 4.2.2
  CHANGELOG.md
Labels: build, 4.x, OCA Verified

#9999 3.x: JWT module description changed (#9998)
  security/jwt/src/main/java/module-info.java
Labels: OCA Verified

#10083 3.x: Update path matchers to honor quantifiers in Regular expressions (#10082)
  webserver/webserver/src/main/java/io/helidon/webserver/PathPattern.java
  webserver/webserver/src/test/java/io/helidon/webserver/PathPatternTest.java
Labels: OCA Verified

#10062 3.x: Add docs about configuration ordering in tests (#9994)
  docs/mp/testing-ng.adoc
  docs/mp/testing.adoc
  microprofile/tests/junit5/src/main/java/io/helidon/microprofile/tests/junit5/Configuration.java
  microprofile/tests/testng/src/main/java/io/helidon/microprofile/tests/testng/Configuration.java
Labels: OCA Verified

#10098 Support for gRPC server metrics
  webserver/grpc/pom.xml
  webserver/grpc/src/main/java/io/helidon/webserver/grpc/GrpcConfigBlueprint.java
  webserver/grpc/src/main/java/io/helidon/webserver/grpc/GrpcProtocolHandler.java
  webserver/grpc/src/main/java/module-info.java
  webserver/tests/grpc/pom.xml
  webserver/tests/grpc/src/test/java/io/helidon/webserver/tests/grpc/GrpcBaseMetricsTest.java
  webserver/tests/grpc/src/test/java/io/helidon/webserver/tests/grpc/GrpcDisabledMetricsTest.java
  webserver/tests/grpc/src/test/java/io/helidon/webserver/tests/grpc/GrpcEnabledMetricsTest.java
Labels: metrics, webserver, grpc, 4.x, OCA Verified

#10101 Support for metrics in gRPC client
  webclient/grpc/pom.xml
  webclient/grpc/src/main/java/io/helidon/webclient/grpc/GrpcBaseClientCall.java
  webclient/grpc/src/main/java/io/helidon/webclient/grpc/GrpcChannel.java
  webclient/grpc/src/main/java/io/helidon/webclient/grpc/GrpcClientCall.java
  webclient/grpc/src/main/java/io/helidon/webclient/grpc/GrpcClientConfigBlueprint.java
  webclient/grpc/src/main/java/io/helidon/webclient/grpc/GrpcUnaryClientCall.java
  webclient/grpc/src/main/java/module-info.java
  webclient/tests/grpc/pom.xml
  webclient/tests/grpc/src/test/java/io/helidon/webclient/grpc/tests/GrpcBaseMetricsTest.java
  webclient/tests/grpc/src/test/java/io/helidon/webclient/grpc/tests/GrpcDisabledMetricsTest.java
  webclient/tests/grpc/src/test/java/io/helidon/webclient/grpc/tests/GrpcEnabledMetricsTest.java
Labels: metrics, grpc, webclient, 4.x, OCA Verified

#10088 4.x: http module updates (constants for annotations, dependency plugin, javadocs fail on warning)
  common/media-type/src/main/java/io/helidon/common/media/type/MediaTypes.java
  common/media-type/src/test/java/io/helidon/common/media/type/MediaTypesTest.java
  http/encoding/deflate/pom.xml
  http/encoding/deflate/src/main/java/io/helidon/http/encoding/deflate/DeflateEncodingProvider.java
  http/encoding/encoding/pom.xml
  http/encoding/encoding/src/main/java/module-info.java
  http/encoding/gzip/pom.xml
  http/encoding/gzip/src/main/java/io/helidon/http/encoding/gzip/GzipEncodingProvider.java
  http/http/pom.xml
  http/http/src/main/java/io/helidon/http/HeaderNameEnum.java
  http/http/src/main/java/io/helidon/http/HeaderNames.java
  http/http/src/main/java/io/helidon/http/HttpException.java
  http/http/src/main/java/io/helidon/http/HttpPrologue.java
  http/http/src/main/java/io/helidon/http/Method.java
  http/http/src/main/java/io/helidon/http/RequestException.java
  http/http/src/main/java/io/helidon/http/Status.java
  http/http/src/test/java/io/helidon/http/HeaderNamesTest.java
  http/http/src/test/java/io/helidon/http/HttpMethodTest.java
  http/http/src/test/java/io/helidon/http/HttpStatusTest.java
  http/http2/pom.xml
  http/http2/src/main/java/io/helidon/http/http2/ConnectionFlowControl.java
  http/http2/src/main/java/io/helidon/http/http2/Http2Exception.java
  http/http2/src/main/java/io/helidon/http/http2/WindowSize.java
  http/media/jackson/pom.xml
  http/media/jsonb/pom.xml
  http/media/jsonp/pom.xml
  http/media/media/pom.xml
  http/media/media/src/main/java/io/helidon/http/media/ReadableEntityBase.java
  http/media/multipart/pom.xml
  http/media/multipart/src/main/java/io/helidon/http/media/multipart/MultiPart.java
  http/pom.xml
  http/tests/pom.xml
Labels: 4.x, declarative, OCA Verified

#9682 4.x: Disable only the slowest test in FileSystemWatcherTest
  config/config/src/test/java/io/helidon/config/FileSystemWatcherTest.java
Labels: OCA Verified

#10054 Use ofNullable for matching pattern
  webserver/http2/src/main/java/io/helidon/webserver/http2/Http2ServerRequest.java
  webserver/tests/webserver/src/test/java/io/helidon/webserver/tests/MatchingPatternRoutingTest.java
  webserver/webserver/src/main/java/io/helidon/webserver/http1/Http1ServerRequest.java
Labels: OCA Verified

#9884 3.x: Refactoring and enabling tests io.helidon.microprofile.messaging.connector.ConnectorTest
  microprofile/messaging/core/src/test/java/io/helidon/microprofile/messaging/connector/ConnectorTest.java
Labels: OCA Verified

#9257 Update sampler type options in JaegerTracerBuilder.
  tracing/providers/jaeger/src/main/java/io/helidon/tracing/providers/jaeger/JaegerTracerBuilder.java
Labels: OCA Verified

#10112 Replaces TODOs with proper argument validation
  microprofile/grpc/client/src/main/java/io/helidon/microprofile/grpc/client/ClientServiceDescriptor.java
  webserver/grpc/src/main/java/io/helidon/webserver/grpc/GrpcServiceDescriptor.java
Labels: grpc, 4.x, OCA Verified

#10108 Updates to gRPC documentation
  docs/src/main/asciidoc/se/grpc/client.adoc
  docs/src/main/asciidoc/se/grpc/server.adoc
  docs/src/main/java/io/helidon/docs/se/grpc/ClientSnippets.java
  docs/src/main/java/io/helidon/docs/se/grpc/ServerSnippets.java
Labels: docs, grpc, OCA Verified

#10120 Simplify ready loop in WebClient proxy tests
  webclient/tests/http1/src/test/java/io/helidon/webclient/tests/HttpProxy.java
Labels: webclient, testing, 4.x, OCA Verified

#10116 Add header to metrics, health, OpenAPI, info, and config output to discourage browsers from sniffing data to infer the content type
  http/http/src/main/java/io/helidon/http/HeaderNameEnum.java
  http/http/src/main/java/io/helidon/http/HeaderNames.java
  http/http/src/main/java/io/helidon/http/HeaderValues.java
  openapi/openapi/src/main/java/io/helidon/openapi/OpenApiHttpFeature.java
  openapi/openapi/src/test/java/io/helidon/openapi/OpenApiFeatureTest.java
  webserver/observe/config/src/main/java/io/helidon/webserver/observe/config/ConfigService.java
  webserver/observe/health/src/main/java/io/helidon/webserver/observe/health/HealthHandler.java
  webserver/observe/health/src/test/java/io/helidon/webserver/observe/health/TestHeaders.java
  webserver/observe/info/src/main/java/io/helidon/webserver/observe/info/InfoService.java
  webserver/observe/metrics/pom.xml
  webserver/observe/metrics/src/main/java/io/helidon/webserver/observe/metrics/MetricsFeature.java
  webserver/observe/metrics/src/test/java/io/helidon/webserver/observe/metrics/TestNosniffHeader.java
Labels: OCA Verified

#10129 2.x: Add suppression for oracle xml db server false positive
  etc/dependency-check-suppression.xml
Labels: build, 2.x, OCA Verified

#10128 Fixes problems cancelling a client-streaming gRPC call
  webserver/grpc/src/main/java/io/helidon/webserver/grpc/GrpcProtocolHandler.java
  webserver/grpc/src/main/java/io/helidon/webserver/grpc/GrpcProtocolSelector.java
  webserver/grpc/src/test/java/io/helidon/webserver/grpc/GrpcProtocolHandlerTest.java
  webserver/http2/src/main/java/io/helidon/webserver/http2/Http2ServerStream.java
  webserver/tests/grpc/src/test/java/io/helidon/webserver/tests/grpc/CancelCallTest.java
Labels: grpc, server, 4.x, OCA Verified

#10145 Removed default header when abstain
  webserver/security/src/main/java/io/helidon/webserver/security/SecurityHandler.java
Labels: OCA Verified

#10143 Enhance MDC to allow mapping a key to a supplier of string; enhance tracing to add `trace_id`
  logging/common/pom.xml
  logging/common/src/main/java/io/helidon/logging/common/HelidonMdc.java
  logging/common/src/main/java/io/helidon/logging/common/MdcSupplierPropagator.java
  logging/common/src/main/java/module-info.java
  logging/jul/src/test/java/io/helidon/logging/jul/JulMdcTest.java
  logging/jul/src/test/resources/logging.properties
  tracing/provider-tests/pom.xml
  tracing/provider-tests/src/main/java/io/helidon/tracing/providers/tests/TestMdc.java
  tracing/provider-tests/src/main/java/module-info.java
  tracing/providers/opentelemetry/pom.xml
  tracing/providers/opentracing/pom.xml
  tracing/providers/zipkin/pom.xml
  tracing/tracing/src/main/java/io/helidon/tracing/TracerProviderHelper.java
  tracing/tracing/src/main/java/module-info.java
Labels: OCA Verified

#10162 4.x: Path pattern fix for WebServer
  docs/src/main/asciidoc/includes/security/helidon-endpoints.adoc
  docs/src/main/asciidoc/includes/security/providers/abac.adoc
  docs/src/main/asciidoc/se/security/containers-integration.adoc
  docs/src/main/asciidoc/se/webserver/webserver.adoc
  http/http/src/main/java/io/helidon/http/PathMatchers.java
  http/http/src/test/java/io/helidon/http/PathMatchersTest.java
  tests/integration/security/gh2297/src/main/resources/application.yaml
  webserver/security/src/main/java/io/helidon/webserver/security/SecurityHttpFeature.java
  webserver/security/src/main/java/io/helidon/webserver/security/package-info.java
  webserver/security/src/test/java/io/helidon/webserver/security/WebSecurityBuilderGateDefaultsTest.java
  webserver/security/src/test/java/io/helidon/webserver/security/WebSecurityProgrammaticTest.java
  webserver/security/src/test/resources/security-application.yaml
Labels: P1, 4.x, OCA Verified

#9892 Pipeline - Run build and test on latest stable java version
  .github/actions/common/action.yml
  .github/workflows/nightly.yaml
  health/health-checks/src/test/java/io/helidon/health/checks/MemoryHealthCheckTest.java
  integrations/microstream/cache/src/test/java/io/helidon/integrations/microstream/cache/CacheTest.java
  integrations/microstream/cdi/src/test/java/io/helidon/integrations/microstream/cdi/MicrostreamExtensionTest.java
  integrations/microstream/core/src/test/java/io/helidon/integrations/microstream/core/ConfigurationTest.java
Labels: build, 4.x, OCA Verified

#10170 4.x: Config.global()
  config/config/src/main/java/io/helidon/config/Config.java
Labels: 4.x, OCA Verified

#10166 3.x: Path pattern matching fix - backport for 3.x
  dependencies/pom.xml
  docs/se/security/containers-integration.adoc
  docs/se/webserver.adoc
  webserver/webserver/src/main/java/io/helidon/webserver/PathPattern.java
  webserver/webserver/src/test/java/io/helidon/webserver/PathPatternTest.java
Labels: OCA Verified

#10164 Runs gRPC metric enable/disable tests in separate VMs
  webserver/tests/grpc/pom.xml
Labels: grpc, testing, 4.x, OCA Verified

#10147 gRPC Improvements
  common/buffers/src/main/java/io/helidon/common/buffers/BufferData.java
  grpc/core/src/main/java/io/helidon/grpc/core/SafeStreamObserver.java
  webserver/grpc/src/main/java/io/helidon/webserver/grpc/GrpcConfigBlueprint.java
  webserver/grpc/src/main/java/io/helidon/webserver/grpc/GrpcProtocolHandler.java
  webserver/grpc/src/main/java/io/helidon/webserver/grpc/GrpcProtocolSelector.java
  webserver/grpc/src/test/java/io/helidon/webserver/grpc/GrpcProtocolHandlerTest.java
  webserver/http2/src/main/java/io/helidon/webserver/http2/spi/Http2SubProtocolSelector.java
  webserver/webserver/src/main/java/io/helidon/webserver/ConnectionHandler.java
Labels: enhancement, webserver, grpc, 4.x, OCA Verified

#10177 Add support for `metrics.rest-request.enabled` (with dot instead of hyphen) in SE metrics config
  metrics/api/pom.xml
  metrics/api/src/main/java/io/helidon/metrics/api/MetricsConfigBlueprint.java
  metrics/api/src/main/java/io/helidon/metrics/api/MetricsConfigSupport.java
  metrics/api/src/test/java/io/helidon/metrics/api/TestRestRequestConfig.java
Labels: OCA Verified

#10178 4.x: Update jandex-maven-plugin version to match that of jandex lib
  pom.xml
Labels: build, 4.x, OCA Verified

#10182 4.x: Add project names to langchain4j modules. Add urls to application poms.
  applications/parent/pom.xml
  integrations/langchain4j/codegen/pom.xml
  integrations/langchain4j/langchain4j/pom.xml
  integrations/langchain4j/providers/cohere/pom.xml
  integrations/langchain4j/providers/ollama/pom.xml
  integrations/langchain4j/providers/open-ai/pom.xml
  integrations/langchain4j/providers/oracle/pom.xml
  integrations/langchain4j/providers/pom.xml
Labels: build, 4.x, OCA Verified
