Repository helidon-io/helidon, pull requests merged in 2025-01, with the labels that each got.

#9619 Add metrics related to virtual threads
  docs/src/main/asciidoc/includes/guides/metrics.adoc
  docs/src/main/asciidoc/includes/metrics/metrics-config.adoc
  docs/src/main/asciidoc/mp/guides/metrics.adoc
  docs/src/main/asciidoc/se/guides/metrics.adoc
  metrics/api/src/main/java/io/helidon/metrics/api/MetricsConfigBlueprint.java
  metrics/system-meters/pom.xml
  metrics/system-meters/src/main/java/io/helidon/metrics/systemmeters/SystemMetersProvider.java
  metrics/system-meters/src/main/java/io/helidon/metrics/systemmeters/VThreadSystemMetersProvider.java
  metrics/system-meters/src/main/java/module-info.java
  metrics/system-meters/src/main/resources/META-INF/native-image/io.helidon.metrics/helidon-metrics-system-meters/native-image.properties
  metrics/system-meters/src/test/java/io/helidon/metrics/systemmeters/TestVirtualThreadsMetersBase.java
  metrics/system-meters/src/test/java/io/helidon/metrics/systemmeters/TestVirtualThreadsMetersWithCounts.java
  metrics/system-meters/src/test/java/io/helidon/metrics/systemmeters/TestVirtualThreadsMetersWithoutCounts.java
  tests/integration/packaging/mp-1/src/main/java/io/helidon/tests/integration/packaging/mp1/Mp1Main.java
Labels: OCA Verified

#9629 4.x: Document ServerLifecycle beforeStart and afterStop
  docs/src/main/asciidoc/se/guides/upgrade_4x.adoc
  docs/src/main/asciidoc/se/webserver.adoc
  docs/src/main/java/io/helidon/docs/se/guides/Upgrade4xSnippets.java
Labels: docs, webserver, 4.x, OCA Verified

#9631 Fix warning message; add test
  microprofile/telemetry/pom.xml
  microprofile/telemetry/src/main/java/io/helidon/microprofile/telemetry/HelidonTelemetryContainerFilter.java
  microprofile/telemetry/src/test/java/io/helidon/microprofile/telemetry/MemoryLogHandler.java
  microprofile/telemetry/src/test/java/io/helidon/microprofile/telemetry/WithSpanUsingLegacySpanNameTest.java
  microprofile/telemetry/src/test/resources/logging-test.properties
Labels: OCA Verified

#9630 Update copyright year in NOTICE
  NOTICE.txt
Labels: 4.x, OCA Verified

#9613 4.x silence jersey warnings
  archetypes/archetypes/src/main/archetype/mp/common/files/src/main/resources/logging.properties.mustache
  microprofile/server/src/main/java/io/helidon/microprofile/server/JaxRsService.java
  microprofile/tests/tck/tck-restful/tck-restful-test/pom.xml
  microprofile/tests/tck/tck-restful/tck-restful-test/src/test/resources/META-INF/microprofile-config.properties
Labels: 4.x, OCA Verified, jersey

#9641 4.x: Upgrade Jersey to 3.1.10
  dependencies/pom.xml
Labels: 4.x, OCA Verified

#9647 WebClient optional reason phrase #9646
  webclient/http1/src/main/java/io/helidon/webclient/http1/Http1CallChainBase.java
  webclient/tests/webclient/pom.xml
  webclient/tests/webclient/src/test/java/io/helidon/webclient/tests/ReasonPhraseTest.java
Labels: webclient, OCA Verified

#7227 Windows Github Action
  .github/actions/common/action.yml
  .github/workflows/validate.yml
  builder/tests/builder/src/test/java/io/helidon/builder/test/CustomNamedTest.java
  integrations/oci/sdk/runtime/src/main/java/io/helidon/integrations/oci/sdk/runtime/OciAuthenticationDetailsProvider.java
  microprofile/telemetry/src/test/java/io/helidon/microprofile/telemetry/TestTracerAtStartup.java
  microprofile/testing/testng/src/main/java/io/helidon/microprofile/testing/testng/HelidonTestNgListener.java
  microprofile/tests/telemetry/src/test/java/io/helidon/microprofile/telemetry/InMemorySpanExporter.java
  microprofile/tests/telemetry/src/test/java/io/helidon/microprofile/telemetry/InMemorySpanExporterProvider.java
  microprofile/tests/telemetry/src/test/java/io/helidon/microprofile/telemetry/RestSpanHierarchyTest.java
  microprofile/tests/telemetry/src/test/java/io/helidon/microprofile/telemetry/TestFullUrlName.java
  tests/integration/harness/src/main/java/io/helidon/tests/integration/harness/ProcessRunner.java
  tests/integration/jms/src/test/java/io/helidon/messaging/connectors/jms/AckMpTest.java
  tests/integration/oidc/src/test/java/io/helidon/tests/integration/oidc/CommonLoginBase.java
  tests/integration/oidc/src/test/java/io/helidon/tests/integration/oidc/CookieBasedLoginIT.java
  tests/integration/oidc/src/test/java/io/helidon/tests/integration/oidc/IdTokenIT.java
  tests/integration/oidc/src/test/java/io/helidon/tests/integration/oidc/QueryBasedLoginIT.java
  tests/integration/oidc/src/test/java/io/helidon/tests/integration/oidc/RefreshTokenIT.java
  tests/integration/packaging/mp-1/src/main/resources/META-INF/native-image/io.helidon.tests.integration.packaging/helidon-tests-integration-packaging-mp1/native-image.properties
  tests/integration/packaging/mp-1/src/test/java/io/helidon/tests/integration/packaging/mp1/Mp1NativeTestIT.java
  tests/integration/packaging/mp-3/src/test/java/io/helidon/tests/integration/packaging/mp3/Mp3NativeTestIT.java
  webclient/tests/grpc/src/test/java/io/helidon/webclient/grpc/tests/GrpcClientUriTest.java
  webserver/static-content/src/main/java/io/helidon/webserver/staticcontent/FileSystemContentHandler.java
  webserver/tests/http2/src/test/java/io/helidon/webserver/tests/http2/EmptyFrameCntTest.java
  webserver/tests/webserver/src/test/java/io/helidon/webserver/tests/WebServerStopIdleTest.java
  webserver/tests/websocket/src/main/java/io/helidon/webserver/tests/websocket/WsConversationClient.java
Labels: build, OCA Verified

#9653 Add ability for users to configure settings related to virtual threads meters
  docs/src/main/asciidoc/includes/guides/metrics.adoc
  metrics/api/src/main/java/io/helidon/metrics/api/MetricsConfigBlueprint.java
  metrics/system-meters/src/main/java/io/helidon/metrics/systemmeters/VThreadSystemMetersProvider.java
  metrics/system-meters/src/test/java/io/helidon/metrics/systemmeters/TestVirtualThreadsMetersConfigs.java
Labels: OCA Verified

#9654 Metrics support for FT SE
  docs/src/main/asciidoc/se/fault-tolerance.adoc
  docs/src/main/java/io/helidon/docs/se/FaultToleranceSnippets.java
  fault-tolerance/fault-tolerance/pom.xml
  fault-tolerance/fault-tolerance/src/main/java/io/helidon/faulttolerance/Bulkhead.java
  fault-tolerance/fault-tolerance/src/main/java/io/helidon/faulttolerance/BulkheadConfigBlueprint.java
  fault-tolerance/fault-tolerance/src/main/java/io/helidon/faulttolerance/BulkheadImpl.java
  fault-tolerance/fault-tolerance/src/main/java/io/helidon/faulttolerance/CircuitBreaker.java
  fault-tolerance/fault-tolerance/src/main/java/io/helidon/faulttolerance/CircuitBreakerConfigBlueprint.java
  fault-tolerance/fault-tolerance/src/main/java/io/helidon/faulttolerance/CircuitBreakerImpl.java
  fault-tolerance/fault-tolerance/src/main/java/io/helidon/faulttolerance/FaultTolerance.java
  fault-tolerance/fault-tolerance/src/main/java/io/helidon/faulttolerance/MetricsUtils.java
  fault-tolerance/fault-tolerance/src/main/java/io/helidon/faulttolerance/Retry.java
  fault-tolerance/fault-tolerance/src/main/java/io/helidon/faulttolerance/RetryConfigBlueprint.java
  fault-tolerance/fault-tolerance/src/main/java/io/helidon/faulttolerance/RetryImpl.java
  fault-tolerance/fault-tolerance/src/main/java/io/helidon/faulttolerance/Timeout.java
  fault-tolerance/fault-tolerance/src/main/java/io/helidon/faulttolerance/TimeoutConfigBlueprint.java
  fault-tolerance/fault-tolerance/src/main/java/io/helidon/faulttolerance/TimeoutImpl.java
  fault-tolerance/fault-tolerance/src/main/java/module-info.java
  fault-tolerance/fault-tolerance/src/test/java/io/helidon/faulttolerance/BulkheadBaseTest.java
  fault-tolerance/fault-tolerance/src/test/java/io/helidon/faulttolerance/BulkheadMetricsTest.java
  fault-tolerance/fault-tolerance/src/test/java/io/helidon/faulttolerance/BulkheadTest.java
  fault-tolerance/fault-tolerance/src/test/java/io/helidon/faulttolerance/CircuitBreakerBaseTest.java
  fault-tolerance/fault-tolerance/src/test/java/io/helidon/faulttolerance/CircuitBreakerMetricsTest.java
  fault-tolerance/fault-tolerance/src/test/java/io/helidon/faulttolerance/CircuitBreakerTest.java
  fault-tolerance/fault-tolerance/src/test/java/io/helidon/faulttolerance/MetricsEnableTest.java
  fault-tolerance/fault-tolerance/src/test/java/io/helidon/faulttolerance/RetryMetricsTest.java
  fault-tolerance/fault-tolerance/src/test/java/io/helidon/faulttolerance/TimeoutMetricsTest.java
  fault-tolerance/fault-tolerance/src/test/resources/application.yaml
Labels: SE, metrics, fault-tolerance, OCA Verified

#9649 4.x: Don't manage logback version. Use slf4j-bom.
  dependencies/pom.xml
Labels: dependencies, 4.x, OCA Verified

#9635 Enhance metrics doc and Javadoc on Helidon metrics API types
  applications/parent/pom.xml
  docs/src/main/asciidoc/includes/attributes.adoc
  docs/src/main/asciidoc/includes/metrics/metrics-shared.adoc
  docs/src/main/asciidoc/mp/metrics/metrics.adoc
  docs/src/main/asciidoc/se/metrics/metrics.adoc
  metrics/api/src/main/java/io/helidon/metrics/api/Counter.java
  metrics/api/src/main/java/io/helidon/metrics/api/DistributionSummary.java
  metrics/api/src/main/java/io/helidon/metrics/api/Gauge.java
  metrics/api/src/main/java/io/helidon/metrics/api/Timer.java
  parent/pom.xml
  pom.xml
Labels: OCA Verified

#9659 Disable others tests on windows
  .github/workflows/validate.yml
Labels: OCA Verified

#9637 Fixes a link in MP Config documentation
  docs/src/main/asciidoc/mp/config/introduction.adoc
Labels: OCA Verified

#9660 Rename MAVEN_ARGS to MVN_ARGS
  .github/actions/common/action.yml
  .github/workflows/release.yaml
  .github/workflows/snapshot.yaml
  .github/workflows/validate.yml
  etc/scripts/build-examples.sh
  etc/scripts/checkstyle.sh
  etc/scripts/copyright.sh
  etc/scripts/smoketest.sh
  etc/scripts/test-quickstarts.sh
Labels: 4.x, OCA Verified

#9662 4.x: Use 3 startup attempts for Oracle Testcontainer
  tests/integration/dbclient/oracle/src/test/java/io/helidon/tests/integration/dbclient/oracle/OracleTestContainer.java
Labels: testing, 4.x, OCA Verified

#9608 4.x: Remove unused code from EncryptionUtil
  config/encryption/src/main/java/io/helidon/config/encryption/EncryptionUtil.java
Labels: OCA Verified

#9611 4.x: Remove unused code from ClasspathSourceHelper
  config/config/src/main/java/io/helidon/config/ClasspathSourceHelper.java
Labels: OCA Verified

#9617 4.x: Remove unused code from ConfigAsciidocGenerator
  config/config/src/test/java/io/helidon/config/ConfigAsciidocGenerator.java
Labels: OCA Verified

#9622 4.x: Remove unused method ConfigMapperManager.mapper
  config/config/src/main/java/io/helidon/config/ConfigMapperManager.java
Labels: OCA Verified

#9623 4.x: Remove unused code from io.helidon.http.Utils
  http/http/src/main/java/io/helidon/http/Utils.java
Labels: OCA Verified

#9632 4.x: Fix typo @Provided -> @Provider in jaxrs-applications.adoc
  docs/src/main/asciidoc/mp/jaxrs/jaxrs-applications.adoc
Labels: OCA Verified

#9633 3.x: Fix typo @Provided -> @Provider in jaxrs-applications.adoc
  docs/mp/jaxrs/jaxrs-applications.adoc
Labels: OCA Verified

#9634 2.x: Fix typo @Provided -> @Provider in 05_jaxrs-applications.adoc
  docs/mp/jaxrs/05_jaxrs-applications.adoc
Labels: OCA Verified

#9458 4.x: Replace deprecated method Scheduling.fixedRateBuilder() on Scheduling.fixedRate() in CoordinatorService
  lra/coordinator/server/src/main/java/io/helidon/lra/coordinator/CoordinatorService.java
Labels: OCA Verified

#9671 Restore setting of no-cache header in health HTTP responses; add test
  webserver/observe/health/src/main/java/io/helidon/webserver/observe/health/HealthHandler.java
  webserver/observe/health/src/test/java/io/helidon/webserver/observe/health/TestNoCacheHeaders.java
Labels: OCA Verified

#9666 3.x: Remove unused code from ClasspathSourceHelper
  config/config/src/main/java/io/helidon/config/ClasspathSourceHelper.java
Labels: OCA Verified

#9667 3.x: Remove unused code from ConfigAsciidocGenerator
  config/config/src/test/java/io/helidon/config/ConfigAsciidocGenerator.java
Labels: OCA Verified

#9674 Use Helidon gRPC client in Config Etcd module
  config/etcd/pom.xml
  config/etcd/src/main/java/io/helidon/config/etcd/internal/client/v2/EtcdV2Client.java
  config/etcd/src/main/java/io/helidon/config/etcd/internal/client/v3/EtcdV3Client.java
  config/etcd/src/main/java/module-info.java
  config/etcd/src/test/java/io/helidon/config/etcd/EtcdConfigSourceIT.java
  config/etcd/src/test/java/io/helidon/config/etcd/client/EtcdClientIT.java
Labels: OCA Verified

#9677 4.x: Add documentation for server.base-path
  docs/src/main/asciidoc/mp/jaxrs/jaxrs-applications.adoc
  docs/src/main/asciidoc/mp/server.adoc
Labels: docs, 4.x, OCA Verified

#9688 3.x: Add graalvm suppression
  etc/dependency-check-suppression.xml
Labels: OCA Verified

#9689 Allow colon in Prometheus meter name; add test
  metrics/providers/micrometer/src/main/java/io/helidon/metrics/providers/micrometer/MicrometerPrometheusFormatter.java
  metrics/providers/micrometer/src/test/java/io/helidon/metrics/providers/micrometer/TestPrometheusFormatting.java
Labels: OCA Verified

#9692 Replace ${helidon.version} with ${project.version} in service/tests poms
  service/tests/config/pom.xml
  service/tests/events/pom.xml
  service/tests/inject/pom.xml
  service/tests/interception/pom.xml
  service/tests/lookup/pom.xml
  service/tests/qualified-providers/pom.xml
  service/tests/registry/pom.xml
  service/tests/scopes/pom.xml
  service/tests/service-lifecycle/pom.xml
  service/tests/stacking/pom.xml
  service/tests/toolbox/pom.xml
Labels: build, 4.x, OCA Verified

#9668 3.x: Remove unused method ConfigMapperManager.mapper
  config/config/src/main/java/io/helidon/config/ConfigMapperManager.java
Labels: OCA Verified

#9684 Support for application/json-patch+json media type
  common/media-type/src/main/java/io/helidon/common/media/type/MediaTypeEnum.java
  common/media-type/src/main/java/io/helidon/common/media/type/MediaTypes.java
  http/media/jsonp/src/main/java/io/helidon/http/media/jsonp/JsonpSupport.java
Labels: media-support, 4.x, OCA Verified

#9694 4.x fix status from deadlock health check if invoking the MBean fails
  health/health-checks/src/main/java/io/helidon/health/checks/DeadlockHealthCheck.java
  health/health-checks/src/test/java/io/helidon/health/checks/DeadlockHealthCheckTest.java
Labels: OCA Verified

#9701 Change virtual threads metrics default to disabled; remove count-leve enable/disable; update tests and doc
  docs/src/main/asciidoc/includes/guides/metrics.adoc
  docs/src/main/asciidoc/includes/metrics/metrics-config.adoc
  metrics/api/src/main/java/io/helidon/metrics/api/MetricsConfigBlueprint.java
  metrics/system-meters/pom.xml
  metrics/system-meters/src/main/java/io/helidon/metrics/systemmeters/VThreadSystemMetersProvider.java
  metrics/system-meters/src/test/java/io/helidon/metrics/systemmeters/TestVirtualThreadsMetersConfigs.java
  metrics/system-meters/src/test/java/io/helidon/metrics/systemmeters/TestVirtualThreadsMetersWithoutCounts.java
  tests/integration/packaging/mp-1/src/main/java/io/helidon/tests/integration/packaging/mp1/Mp1Main.java
Labels: OCA Verified

#9705 Close recording stream on shutdown
  metrics/system-meters/src/main/java/io/helidon/metrics/systemmeters/VThreadSystemMetersProvider.java
  metrics/system-meters/src/main/java/module-info.java
Labels: OCA Verified

#9703 4.x: Update issue template to work with latest issues update
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/config.yml
Labels: 4.x, OCA Verified

#9708 Add enhancement request template
  .github/ISSUE_TEMPLATE/enhancement_request.md
Labels: 4.x, OCA Verified

#9709 Deprecation of old config options now replaced by SocketOptions
  docs/src/main/asciidoc/includes/guides/performance-tuning.adoc
  webserver/webserver/src/main/java/io/helidon/webserver/ConnectionConfigBlueprint.java
  webserver/webserver/src/main/java/io/helidon/webserver/ListenerConfigBlueprint.java
Labels: OCA Verified

#9693 2.x: Fix error in OpenAPI handling of default values' types (#7642)
  openapi/src/main/java/io/helidon/openapi/ExpandedTypeDescription.java
  openapi/src/main/java/io/helidon/openapi/OpenAPISupport.java
  openapi/src/test/java/io/helidon/openapi/ParserTest.java
  openapi/src/test/resources/petstore-with-fake-endpoints-models-for-testing.yml
Labels: open-api, OCA Verified
