Repository helidon-io/helidon, pull requests merged in 2025-10, with the labels that each got.

#10740 Include the JSON-RPC ID in all error responses when available
  webserver/jsonrpc/src/main/java/io/helidon/webserver/jsonrpc/JsonRpcRouting.java
  webserver/tests/jsonrpc/src/test/java/io/helidon/webserver/tests/jsonrpc/JsonRpcExceptionTest.java
Labels: bug, 4.x, OCA Verified, jsonrpc

#10745 2.x: Upgrade macos runners to 14
  .github/workflows/validate.yml
Labels: build, 2.x, OCA Verified

#10744 Use requires transitive for service.registry
  config/config/src/main/java/module-info.java
Labels: 4.x, OCA Verified

#10746 Bump lc4j to 1.6.0
  dependencies/pom.xml
  integrations/langchain4j/langchain4j/pom.xml
  integrations/langchain4j/langchain4j/src/main/java/io/helidon/integrations/langchain4j/MetricsChatModelListener.java
  integrations/langchain4j/langchain4j/src/test/java/io/helidon/integrations/langchain4j/MetricsTest.java
Labels: OCA Verified

#10737 4.x: Remove unused plugin declaration for helidon-service-maven-plugin
  transaction/narayana/pom.xml
Labels: build, 4.x, OCA Verified
