Repository helidon-io/helidon, pull requests merged in 2025-06, with the labels that each got.

#10185 4.2.3: Add project names to langchain4j modules. Add urls to application poms
  applications/parent/pom.xml
  integrations/langchain4j/codegen/pom.xml
  integrations/langchain4j/langchain4j/pom.xml
  integrations/langchain4j/providers/cohere/pom.xml
  integrations/langchain4j/providers/ollama/pom.xml
  integrations/langchain4j/providers/open-ai/pom.xml
  integrations/langchain4j/providers/oracle/pom.xml
  integrations/langchain4j/providers/pom.xml
Labels: build, backport, 4.x, OCA Verified

#10186 3.x: Suppress graal-sdk fp
  etc/dependency-check-suppression.xml
Labels: build, 3.x, OCA Verified

#10188 4.2.3: migrate release workflow to use Central Publishing Portal
  .github/actions/common/action.yml
  .github/workflows/release.yaml
  .github/workflows/snapshot.yaml
  etc/scripts/setup-central-settings.sh
  etc/scripts/smoketest.sh
  etc/scripts/upload.sh
  parent/pom.xml
Labels: build, backport, 4.x, OCA Verified

#10191 4.x: Fix content type handling in server request headers.
  http/http/src/main/java/io/helidon/http/ServerRequestHeadersImpl.java
  webserver/tests/webserver/src/test/java/io/helidon/webserver/tests/HeadersServerTest.java
Labels: bug, webserver, 4.x, OCA Verified

#10205 4.2.3: Upgrade jgit to 7.2.1
  config/git/src/test/java/io/helidon/config/git/GitConfigSourceBuilderTest.java
  dependencies/pom.xml
Labels: config, dependencies, backport, 4.x, OCA Verified

#10209 4.2.3: Fix content type handling in server request headers.
  http/http/src/main/java/io/helidon/http/ServerRequestHeadersImpl.java
  webserver/tests/webserver/src/test/java/io/helidon/webserver/tests/HeadersServerTest.java
Labels: bug, webserver, backport, 4.x, OCA Verified

#10202 2.x: Fix accept header handling in server request headers
  webserver/test-support/src/test/java/io/helidon/webserver/testsupport/ClassPathContentHandlerTest.java
  webserver/webserver/src/main/java/io/helidon/webserver/HashRequestHeaders.java
Labels: bug, 2.x, OCA Verified

#10211 4.x: Fix 10124 UnknownFormatConversionException in log statement
  webserver/webserver/src/main/java/io/helidon/webserver/http/ErrorHandlers.java
Labels: webserver, 4.x, OCA Verified

#10210 #8333 - Update doc for removal of RequestPredicate in 4.x
  docs/src/main/asciidoc/se/guides/upgrade_4x.adoc
  docs/src/main/asciidoc/se/webserver/webserver.adoc
  docs/src/main/java/io/helidon/docs/se/guides/Upgrade4xSnippets.java
Labels: OCA Verified

#10198 Manage REST request metrics for resource methods on a superclass
  microprofile/metrics/pom.xml
  microprofile/metrics/src/main/java/io/helidon/microprofile/metrics/MetricsCdiExtension.java
  microprofile/metrics/src/test/java/io/helidon/microprofile/metrics/HelloWorldAsyncResponseTest.java
  microprofile/metrics/src/test/java/io/helidon/microprofile/metrics/HelloWorldAsyncResponseWithRestRequestTest.java
  microprofile/metrics/src/test/java/io/helidon/microprofile/metrics/HelloWorldTest.java
  microprofile/metrics/src/test/java/io/helidon/microprofile/metrics/TestRestServiceInheritance.java
  microprofile/metrics/src/test/java/io/helidon/microprofile/metrics/TestVetoedResource.java
Labels: OCA Verified

#10216 4.2.3: Manage REST request metrics for resource methods on a superclass
  microprofile/metrics/pom.xml
  microprofile/metrics/src/main/java/io/helidon/microprofile/metrics/MetricsCdiExtension.java
  microprofile/metrics/src/test/java/io/helidon/microprofile/metrics/HelloWorldAsyncResponseTest.java
  microprofile/metrics/src/test/java/io/helidon/microprofile/metrics/HelloWorldAsyncResponseWithRestRequestTest.java
  microprofile/metrics/src/test/java/io/helidon/microprofile/metrics/HelloWorldTest.java
  microprofile/metrics/src/test/java/io/helidon/microprofile/metrics/TestRestServiceInheritance.java
  microprofile/metrics/src/test/java/io/helidon/microprofile/metrics/TestVetoedResource.java
Labels: backport, OCA Verified

#10213 SecurityEnvironment query propagation
  webclient/security/src/main/java/io/helidon/webclient/security/WebClientSecurity.java
  webserver/security/src/main/java/io/helidon/webserver/security/SecurityContextFilter.java
Labels: OCA Verified

#10217 4.2.3: update snapshot timeout
  .github/workflows/snapshot.yaml
  etc/scripts/upload.sh
Labels: build, backport, 4.x, OCA Verified

#10220 4.2.3: Docs dependency fix for GraphQL server.
  docs/src/main/asciidoc/se/graphql.adoc
Labels: docs, graphql, backport, 4.x, OCA Verified

#10222 4.2.3: SecurityEnvironment query propagation
  webclient/security/src/main/java/io/helidon/webclient/security/WebClientSecurity.java
  webserver/security/src/main/java/io/helidon/webserver/security/SecurityContextFilter.java
Labels: backport, OCA Verified

#10221 4.2.3: Removed default header when abstain
  webserver/security/src/main/java/io/helidon/webserver/security/SecurityHandler.java
Labels: backport, OCA Verified

#10225 Update RELEASE.md
  etc/scripts/RELEASE.md
Labels: build, 4.x, OCA Verified

#10228 4.x: Support for varargs in common types
  builder/tests/builder/src/main/java/io/helidon/builder/test/testsubjects/VarargConfigBlueprint.java
  builder/tests/builder/src/main/java/io/helidon/builder/test/testsubjects/VarargSupport.java
  builder/tests/builder/src/test/java/io/helidon/builder/test/VarargTest.java
  builder/tests/common-types/src/main/java/io/helidon/common/types/TypeNameBlueprint.java
  builder/tests/common-types/src/main/java/io/helidon/common/types/TypeNameSupport.java
  codegen/apt/src/main/java/io/helidon/codegen/apt/AptTypeInfoFactory.java
  codegen/class-model/src/main/java/io/helidon/codegen/classmodel/Parameter.java
  codegen/class-model/src/main/java/io/helidon/codegen/classmodel/TypeArgument.java
  codegen/class-model/src/test/java/io/helidon/codegen/classmodel/ClassModelTest.java
  common/processor/class-model/src/main/java/io/helidon/common/processor/classmodel/TypeArgument.java
  common/types/src/main/java/io/helidon/common/types/TypeName.java
  common/types/src/main/java/io/helidon/common/types/TypeNameBlueprint.java
  common/types/src/main/java/io/helidon/common/types/TypeNameSupport.java
  common/types/src/test/java/io/helidon/common/types/TypeNameTest.java
Labels: 4.x, OCA Verified, codegen

#10233 [helidon-data] Removed workaround after varargs in blueprints were fixed.
  data/data/src/main/java/io/helidon/data/SortSupport.java
Labels: OCA Verified

#10232 3.x: Backport releasing to Central Publishing Portal
  .github/workflows/release.yaml
  applications/parent/pom.xml
  etc/scripts/release.sh
  etc/scripts/upload.sh
  microprofile/weld/weld-core-impl/pom.xml
  microprofile/weld/weld-se-core/pom.xml
  parent/pom.xml
  service-common/rest-cdi/pom.xml
  service-common/rest/pom.xml
Labels: build, 3.x, OCA Verified

#10253 2.x: Backport releasing to Central Publishing Portal
  .github/workflows/release.yaml
  applications/parent/pom.xml
  etc/scripts/release.sh
  etc/scripts/upload.sh
  microprofile/weld/weld-core-impl/pom.xml
  microprofile/weld/weld-se-core/pom.xml
  parent/pom.xml
  service-common/rest-cdi/pom.xml
  service-common/rest/pom.xml
Labels: build, 2.x, OCA Verified

#10256 3.x: Removed default header when abstain (#10255)
  security/integration/webserver/src/main/java/io/helidon/security/integration/webserver/SecurityHandler.java
Labels: OCA Verified

#10260 3.x: Fixes typo in REST.request configuration option (#10259)
  docs/includes/metrics/metrics-config.adoc
Labels: OCA Verified

#10266 4.x: Clarify javadoc of io.helidon.microprofile.server.Server start/stop (#8275)
  microprofile/server/src/main/java/io/helidon/microprofile/server/Server.java
Labels: OCA Verified

#10270 4.x: Fix Jackson when charset is used for Accept header.
  http/media/jackson/src/main/java/io/helidon/http/media/jackson/JacksonWriter.java
  http/media/jackson/src/test/java/io/helidon/http/media/jackson/JacksonMediaTest.java
  http/tests/media/jackson/pom.xml
  http/tests/media/jackson/src/test/java/io/helidon/http/tests/integration/media/jackson/JacksonTest.java
  http/tests/media/jackson/src/test/resources/logging.properties
  http/tests/media/pom.xml
Labels: bug, 4.x, OCA Verified

#10281 4.x: Remove unused code from io.helidon.metrics.providers.micrometer.MMeter
  metrics/providers/micrometer/src/main/java/io/helidon/metrics/providers/micrometer/MMeter.java
Labels: OCA Verified

#10272 3.x: Clarify javadoc of io.helidon.microprofile.server.Server start/stop (#10271)
  microprofile/server/src/main/java/io/helidon/microprofile/server/Server.java
Labels: OCA Verified

#10282 4.x: Upgrade kafka-clients to 3.9.1
  dependencies/pom.xml
Labels: dependencies, messaging, 4.x, OCA Verified

#10296 4.x: Builder fix for not-configured providers
  builder/api/src/main/java/io/helidon/builder/api/BuilderSupport.java
  builder/api/src/main/java/io/helidon/builder/api/Option.java
  builder/codegen/src/main/java/io/helidon/builder/codegen/GenerateAbstractBuilder.java
  builder/codegen/src/main/java/io/helidon/builder/codegen/Types.java
  builder/tests/builder/src/main/java/io/helidon/builder/test/testsubjects/WithProviderBlueprint.java
  builder/tests/builder/src/main/java/io/helidon/builder/test/testsubjects/WithProviderRegistryBlueprint.java
  builder/tests/codegen/src/test/java/io/helidon/builder/codegen/TypesTest.java
  common/config/src/main/java/io/helidon/common/config/ConfigBuilderSupport.java
  common/config/src/main/java/io/helidon/common/config/ProvidedUtil.java
  service/registry/src/main/java/io/helidon/service/registry/CoreServiceDiscovery.java
Labels: bug, 4.x, OCA Verified, builder
