Repository helidon-io/helidon, pull requests merged in 2025-03, with the labels that each got.

#9864 Accepts colon ':' as a valid character in a URI as mandated by RFC 3986
  common/uri/src/main/java/io/helidon/common/uri/UriValidator.java
  common/uri/src/test/java/io/helidon/common/uri/UriValidatorTest.java
Labels: webserver, 4.x, OCA Verified

#9865 4.x: Update all module to be compilable and testable with Java 24.
  builder/tests/common-types/src/main/java/io/helidon/common/types/TypeNameSupport.java
  common/types/src/main/java/io/helidon/common/types/TypeNameSupport.java
  common/types/src/test/java/io/helidon/common/types/TypeNameTest.java
  config/encryption/pom.xml
  integrations/micronaut/data/pom.xml
  integrations/micronaut/data/src/main/java/io/helidon/integrations/micronaut/cdi/data/MicronautDataCdiExtension.java
  integrations/microstream/cache/pom.xml
  integrations/microstream/cdi/pom.xml
  integrations/microstream/core/pom.xml
  microprofile/tests/testing/junit5/src/test/java/io/helidon/microprofile/tests/testing/junit5/TestPinnedThread.java
  microprofile/tests/testing/testng/src/test/java/io/helidon/microprofile/tests/testing/testng/TestPinnedThread.java
  tests/integration/tls-revocation-config/src/test/java/io/helidon/examples/webserver/mtls/RevocationConfigTest.java
  webclient/tests/webclient/src/test/java/io/helidon/webclient/tests/MutualTlsTest.java
  webserver/testing/junit5/junit5/src/test/java/io/helidon/webserver/testing/junit5/TestPinnedThread.java
  webserver/tests/http2/src/test/java/io/helidon/webserver/tests/http2/HeadersServerTest.java
  webserver/tests/webserver/src/test/java/io/helidon/webserver/tests/CipherSuiteTest.java
  webserver/tests/webserver/src/test/resources/cipherSuiteConfig.yaml
Labels: build, 4.x, OCA Verified

#9868 4.x: Use runtime dependencies in Service Maven Plugin
  docs/src/main/asciidoc/se/injection.adoc
  service/maven-plugin/src/main/java/io/helidon/service/maven/plugin/CreateApplicationAbstractMojo.java
  service/maven-plugin/src/main/java/io/helidon/service/maven/plugin/CreateApplicationMojo.java
  service/maven-plugin/src/main/java/io/helidon/service/maven/plugin/CreateTestApplicationMojo.java
Labels: 4.x, declarative, OCA Verified

#9871 4.x: Deprecation of Microstream modules.
  integrations/microstream/README.md
  integrations/microstream/cache/src/main/java/io/helidon/integrations/microstream/cache/CacheBuilder.java
  integrations/microstream/cache/src/main/java/io/helidon/integrations/microstream/cache/ConfigException.java
  integrations/microstream/cache/src/main/java/io/helidon/integrations/microstream/cache/MicrostreamCacheConfigurationBuilder.java
  integrations/microstream/cache/src/main/java/module-info.java
  integrations/microstream/cdi/src/main/java/io/helidon/integrations/microstream/cdi/CacheExtension.java
  integrations/microstream/cdi/src/main/java/io/helidon/integrations/microstream/cdi/EmbeddedStorageManagerExtension.java
  integrations/microstream/cdi/src/main/java/io/helidon/integrations/microstream/cdi/MicrostreamCache.java
  integrations/microstream/cdi/src/main/java/io/helidon/integrations/microstream/cdi/MicrostreamStorage.java
  integrations/microstream/cdi/src/main/java/module-info.java
  integrations/microstream/core/src/main/java/io/helidon/integrations/microstream/core/EmbeddedStorageManagerBuilder.java
  integrations/microstream/core/src/main/java/module-info.java
  integrations/microstream/health/src/main/java/io/helidon/integrations/microstream/health/MicrostreamHealthCheck.java
  integrations/microstream/health/src/main/java/module-info.java
  integrations/microstream/metrics/src/main/java/io/helidon/integrations/microstream/metrics/MicrostreamMetricsSupport.java
  integrations/microstream/metrics/src/main/java/module-info.java
Labels: OCA Verified

#9878 Documentation: Add Note for Preview features
  docs/src/main/asciidoc/includes/guides/crac.adoc
  docs/src/main/asciidoc/mp/guides/crac.adoc
  docs/src/main/asciidoc/se/guides/crac.adoc
  docs/src/main/asciidoc/se/injection.adoc
  docs/src/main/asciidoc/se/integrations/langchain4j/langchain4j.adoc
Labels: docs, 4.x, OCA Verified

#9876 4.x: Make sure Config.asMap() returns all nodes with values
  config/config/src/main/java/io/helidon/config/ConfigMappers.java
  config/config/src/test/java/io/helidon/config/ConfigTest.java
Labels: config, 4.x, OCA Verified

#9877 3.x: Make sure Config.asMap() returns all nodes with values
  config/config/src/main/java/io/helidon/config/ConfigMappers.java
  config/config/src/test/java/io/helidon/config/ConfigTest.java
  examples/README.md
Labels: config, 3.x, OCA Verified

#9882 3.x: Update suppression for open-api-ui
  etc/dependency-check-suppression.xml
Labels: 3.x, OCA Verified

#9880 New gRPC test that uses the repeated keyword
  webserver/tests/grpc/src/main/java/io/helidon/webserver/tests/grpc/CourseService.java
  webserver/tests/grpc/src/main/proto/courses.proto
  webserver/tests/grpc/src/test/java/io/helidon/webserver/tests/grpc/CourseServiceTest.java
  webserver/tests/grpc/src/test/java/io/helidon/webserver/tests/grpc/EventServiceTest.java
  webserver/tests/grpc/src/test/java/io/helidon/webserver/tests/grpc/TestObserver.java
Labels: grpc, 4.x, OCA Verified

#9896 3.x: Upgrade neo4j driver to 5.28.3
  dependencies/pom.xml
Labels: dependencies, 3.x, OCA Verified

#9895 4.x: Upgrade neo4j driver to 5.28.3
  dependencies/pom.xml
Labels: dependencies, 4.x, OCA Verified

#9898 3.x: Suppress FP for neo4j-bolt
  etc/dependency-check-suppression.xml
Labels: 3.x, OCA Verified

#9897 4.x: Suppress FP for neo4j-bolt
  etc/dependency-check-suppression.xml
Labels: 4.x, OCA Verified

#9890 3.x: Fix empty config values propagation (#9888)
  microprofile/messaging/core/src/main/java/io/helidon/microprofile/messaging/AdHocConfigBuilder.java
  microprofile/messaging/core/src/test/java/io/helidon/microprofile/messaging/AdHocConfigBuilderTest.java
  microprofile/messaging/core/src/test/java/io/helidon/microprofile/messaging/connector/ConnectorConfigTest.java
Labels: OCA Verified

#9807 4.x: Clarify docs about built-in healthchecks and Graal VM (#9021)
  docs/src/main/asciidoc/se/health.adoc
Labels: OCA Verified

#9803 4.x: Remove unnecessary check in BiConsumerChain
  common/reactive/src/main/java/io/helidon/common/reactive/BiConsumerChain.java
Labels: OCA Verified

#9917 Clarifies configuration of concurrency limits
  docs/src/main/asciidoc/se/webserver/concurrency-limits.adoc
Labels: docs, webserver, 4.x, OCA Verified

#9916 Clarifies that FT metrics can only be enabled programmatically
  docs/src/main/asciidoc/se/fault-tolerance.adoc
Labels: docs, fault-tolerance, 4.x, OCA Verified

#9924 Fix problems in tracing with headers that appear multiple times in an incoming request
  microprofile/telemetry/pom.xml
  microprofile/telemetry/src/main/java/io/helidon/microprofile/telemetry/HelidonTelemetryContainerFilter.java
  microprofile/telemetry/src/main/java/io/helidon/microprofile/telemetry/RequestContextHeaderProvider.java
  microprofile/telemetry/src/test/java/io/helidon/microprofile/telemetry/BaggageCheckingResource.java
  microprofile/telemetry/src/test/java/io/helidon/microprofile/telemetry/TestMultipleBaggageHeaders.java
  tracing/providers/opentelemetry/src/main/java/io/helidon/tracing/providers/opentelemetry/OpenTelemetryTracer.java
  tracing/providers/opentelemetry/src/test/java/io/helidon/tracing/providers/opentelemetry/MapHeaderProvider.java
  tracing/providers/opentelemetry/src/test/java/io/helidon/tracing/providers/opentelemetry/TestSpanAndBaggage.java
Labels: OCA Verified

#9893 Adds configurable buffering support to TcpClientConnection
  common/buffers/src/main/java/io/helidon/common/buffers/DataWriter.java
  http/http2/src/main/java/io/helidon/http/http2/Http2ConnectionWriter.java
  webclient/api/src/main/java/io/helidon/webclient/api/HttpClientConfigBlueprint.java
  webclient/api/src/main/java/io/helidon/webclient/api/TcpClientConnection.java
  webclient/api/src/test/java/io/helidon/webclient/api/BufferedDataWriterTest.java
  webclient/http1/src/main/java/io/helidon/webclient/http1/Http1CallEntityChain.java
  webclient/http1/src/main/java/io/helidon/webclient/http1/Http1CallOutputStreamChain.java
  webserver/http2/src/main/java/io/helidon/webserver/http2/Http2Upgrader.java
  webserver/websocket/src/main/java/io/helidon/webserver/websocket/WsUpgrader.java
Labels: webclient, 4.x, OCA Verified

#9891 Connector configuration improvements
  docs/src/main/asciidoc/mp/jaxrs/helidon-connector.adoc
  jersey/connector/pom.xml
  jersey/connector/src/main/java/io/helidon/jersey/connector/HelidonConnector.java
  jersey/connector/src/main/java/module-info.java
  jersey/tests/connector/pom.xml
  jersey/tests/connector/src/test/java/io/helidon/jersey/connector/ConnectorConfigTest.java
  jersey/tests/connector/src/test/resources/application.yaml
  jersey/tests/connector/src/test/resources/custom.yaml
Labels: jax-rs, webclient, OCA Verified

#9941 3.x Describe adding dependency for built-in health checks
  docs/mp/guides/health.adoc
  docs/mp/guides/quickstart.adoc
Labels: OCA Verified

#9937 Broken doc link #9366
  docs/src/main/asciidoc/mp/reactivemessaging/weblogic.adoc
Labels: docs, OCA Verified

#9907 3.x: Clarify docs about built-in healthchecks and Graal VM (#9906)
  docs/se/health.adoc
Labels: OCA Verified

#9911 3.x: Fix deadlock health check if invoking the ThreadMXBean fails (#9910)
  health/health-checks/src/main/java/io/helidon/health/checks/DeadlockHealthCheck.java
  health/health-checks/src/test/java/io/helidon/health/checks/DeadlockHealthCheckTest.java
  health/health/src/main/java/io/helidon/health/HealthSupport.java
Labels: OCA Verified
